version: '2.1'
orbs:
  node: circleci/node@5.0.2
  serverless-framework: circleci/serverless-framework@2.0.1
  aws-cli: circleci/aws-cli@4.1.2
jobs:
    build-app:
        docker:
            - image: 'cimg/base:stable'
              environment:
                    APP_ENV: test
                    CRYPTOPASS: 'circleci oauth'
                    PROD_MODE: false
                    INSTANCE_NAME: 'dev'
                    MYSQL_ADDON_HOST: 'localhost'
                    MYSQL_ADDON_PORT: '3306'
                    MYSQL_ADDON_DB: 'alexa_oauth'
                    METRICS_HOST: 'no.host'
                    METRICS_PORT: 2003
                    METRICS_UDP_PORT: 8124
        steps:
            - checkout
            - node/install:
                install-yarn: true
                node-version: '14'
            - run: yarn install
            # run tests!
            - run: yarn test
    deploy-preprod:
        executor: serverless-framework/default
        environment:
            DEPLOY_FUNCTION
        steps:
            - checkout
            - aws-cli/setup:
                aws_access_key_id: AWS_ACCESS_KEY
                aws_secret_access_key: AWS_PREPROD_ACCESS_SECRET
                region: AWS_REGION_NAME
            - run:
                name: Deploy
                command: |
                    ./.circleci/deploy.sh echo

workflows:
    test_my_app:
        jobs:
            - build-app
            - hold-preprod:
                type: approval
            - deploy-preprod:
                requires:
                    - hold-preprod
