version: '2.1'
orbs:
  node: circleci/node@x.y
jobs:
    build-app:
        docker:
            - image: 'cimg/base:stable'
        steps:
            - checkout
            - node/install:
                install-yarn: true
                node-version: '16.13'
            - run: yarn install
            # run tests!
            - run: yarn test
workflows:
    test_my_app:
        jobs:
            - build-app