version: 2
jobs:
    build-app:
        steps:
            -
                run: yarn install
            # run tests!
            -
                run: yarn test

workflows:
    version: 2
    build-project:
        jobs:
            - build-app