exports.DOMOTICZ_GET_DEVICES = JSON.stringify(
{
   "ActTime" : 1680951657,
   "AstrTwilightEnd" : "22:07",
   "AstrTwilightStart" : "05:19",
   "CivTwilightEnd" : "20:50",
   "CivTwilightStart" : "06:36",
   "DayLength" : "13:12",
   "NautTwilightEnd" : "21:28",
   "NautTwilightStart" : "05:59",
   "ServerTime" : "2023-04-08 13:00:57",
   "SunAtSouth" : "13:43",
   "Sunrise" : "07:07",
   "Sunset" : "20:19",
   "app_version" : "2020.2 (build 12711)",
   "result" : 
   [
      {
         "Data" : "Mixed",
         "Description" : "",
         "Favorite" : 0,
         "Image" : "Push",
         "LastUpdate" : "2023-04-08 02:10:00",
         "Name" : "DROP >ON Tous",
         "PlanID" : "",
         "PlanIDs" : 
         [
            0
         ],
         "Protected" : false,
         "Status" : "Mixed",
         "Type" : "Scene",
         "TypeImg" : "scene",
         "UsedByCamera" : false,
         "XOffset" : 0,
         "YOffset" : 0,
         "idx" : "12"
      },
      {
         "Data" : "Mixed",
         "Description" : "Arr\u00eat hors gel chauffage TMA-DROP20\ndate de red\u00e9marrage + 1an\n(sauf SdB & SdD) \ncondensteur optium =22 nf mais relay7 razcond requis pour (+)",
         "Favorite" : 0,
         "Image" : "Push",
         "LastUpdate" : "2023-04-08 02:09:00",
         "Name" : "DROP >OFF H.Gel",
         "PlanID" : "",
         "PlanIDs" : 
         [
            0
         ],
         "Protected" : false,
         "Status" : "Mixed",
         "Type" : "Scene",
         "TypeImg" : "scene",
         "UsedByCamera" : false,
         "XOffset" : 0,
         "YOffset" : 0,
         "idx" : "6"
      },
      {
         "Data" : "Mixed",
         "Description" : "Arr\u00eat chauffage TMA-DROP20 \n(sauf SdB & SdD)",
         "Favorite" : 0,
         "Image" : "Push",
         "LastUpdate" : "2022-11-12 17:29:58",
         "Name" : "DROP >OFF  Complet",
         "PlanID" : "",
         "PlanIDs" : 
         [
            0
         ],
         "Protected" : false,
         "Status" : "Mixed",
         "Type" : "Scene",
         "TypeImg" : "scene",
         "UsedByCamera" : false,
         "XOffset" : 0,
         "YOffset" : 0,
         "idx" : "4"
      },
      {
         "Data" : "Mixed",
         "Description" : "chgt mode ECO<->CONF Z1 (salon) sur TMA-DROP20",
         "Favorite" : 0,
         "Image" : "Push",
         "LastUpdate" : "2023-04-07 11:57:10",
         "Name" : "DROP >ECO/\\CONF Z1 Salon",
         "PlanID" : "",
         "PlanIDs" : 
         [
            0
         ],
         "Protected" : false,
         "Status" : "Mixed",
         "Type" : "Scene",
         "TypeImg" : "scene",
         "UsedByCamera" : false,
         "XOffset" : 0,
         "YOffset" : 0,
         "idx" : "7"
      },
      {
         "Data" : "Mixed",
         "Description" : "chgt mode ECO<->CONF Z2 (Chambres) sur TMA-DROP20",
         "Favorite" : 0,
         "Image" : "Push",
         "LastUpdate" : "2023-04-08 05:02:01",
         "Name" : "DROP >ECO/\\CONF Z2 Chambres",
         "PlanID" : "",
         "PlanIDs" : 
         [
            0
         ],
         "Protected" : false,
         "Status" : "Mixed",
         "Type" : "Scene",
         "TypeImg" : "scene",
         "UsedByCamera" : false,
         "XOffset" : 0,
         "YOffset" : 0,
         "idx" : "8"
      },
      {
         "Data" : "Mixed",
         "Description" : "Chgt mode ECO<->CONF Z3 (Bureau, Couloir, Hall, Buanderie), sur TMA-DROP20",
         "Favorite" : 0,
         "Image" : "Push",
         "LastUpdate" : "2023-04-08 05:03:00",
         "Name" : "DROP >ECO/\\CONF Z3 Bureau",
         "PlanID" : "",
         "PlanIDs" : 
         [
            0
         ],
         "Protected" : false,
         "Status" : "Mixed",
         "Type" : "Scene",
         "TypeImg" : "scene",
         "UsedByCamera" : false,
         "XOffset" : 0,
         "YOffset" : 0,
         "idx" : "9"
      },
      {
         "Data" : "Mixed",
         "Description" : "Chgt mode ECO<->CONF de chacune des Zones\nsur TMA-DROP20\n(sauf SdB & SdD)",
         "Favorite" : 0,
         "Image" : "Push",
         "LastUpdate" : "2019-11-08 20:41:35",
         "Name" : "DROP >ECO/\\CONF ALL",
         "PlanID" : "",
         "PlanIDs" : 
         [
            0
         ],
         "Protected" : false,
         "Status" : "Mixed",
         "Type" : "Scene",
         "TypeImg" : "scene",
         "UsedByCamera" : false,
         "XOffset" : 0,
         "YOffset" : 0,
         "idx" : "10"
      },
      {
         "Data" : "Off",
         "Description" : "enchainement de scenes pur etre sur de l'etat marche",
         "Favorite" : 0,
         "Image" : "Push",
         "LastUpdate" : "2019-11-06 00:36:14",
         "Name" : "DROP >RAZ",
         "PlanID" : "",
         "PlanIDs" : 
         [
            0
         ],
         "Protected" : false,
         "Status" : "Off",
         "Type" : "Scene",
         "TypeImg" : "scene",
         "UsedByCamera" : false,
         "XOffset" : 0,
         "YOffset" : 0,
         "idx" : "11"
      },
      {
         "Data" : "Mixed",
         "Description" : "Alexa_Name:Coupure totale",
         "Favorite" : 0,
         "Image" : "Push",
         "LastUpdate" : "2023-04-06 22:56:15",
         "Name" : "Extinction g\u00e9n\u00e9rale (TV+ECL+ChfD)",
         "PlanID" : "6",
         "PlanIDs" : 
         [
            6
         ],
         "Protected" : false,
         "Status" : "Mixed",
         "Type" : "Scene",
         "TypeImg" : "scene",
         "UsedByCamera" : false,
         "XOffset" : 261,
         "YOffset" : 151,
         "idx" : "1"
      },
      {
         "Data" : "Mixed",
         "Description" : "",
         "Favorite" : 0,
         "Image" : "Push",
         "LastUpdate" : "2021-11-20 10:17:26",
         "Name" : "DROP CONFORT PARTOUT",
         "PlanID" : "9",
         "PlanIDs" : 
         [
            9
         ],
         "Protected" : false,
         "Status" : "Mixed",
         "Type" : "Scene",
         "TypeImg" : "scene",
         "UsedByCamera" : false,
         "XOffset" : 0,
         "YOffset" : 0,
         "idx" : "13"
      },
      {
         "Data" : "Mixed",
         "Description" : "",
         "Favorite" : 0,
         "Image" : "Push",
         "LastUpdate" : "2019-12-29 23:42:29",
         "Name" : "DROP ECO  PARTOUT",
         "PlanID" : "9",
         "PlanIDs" : 
         [
            9
         ],
         "Protected" : false,
         "Status" : "Mixed",
         "Type" : "Scene",
         "TypeImg" : "scene",
         "UsedByCamera" : false,
         "XOffset" : 0,
         "YOffset" : 0,
         "idx" : "14"
      },
      {
         "Data" : "Off",
         "Description" : "Alexa_Name:Petit Caf\u00e9",
         "Favorite" : 0,
         "Image" : "Push",
         "LastUpdate" : "2023-04-08 10:51:19",
         "Name" : "FAIS MOI UN CAFE",
         "PlanID" : "10",
         "PlanIDs" : 
         [
            10
         ],
         "Protected" : false,
         "Status" : "Off",
         "Type" : "Scene",
         "TypeImg" : "scene",
         "UsedByCamera" : false,
         "XOffset" : 169,
         "YOffset" : 13,
         "idx" : "15"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 100,
         "CustomImage" : 0,
         "Data" : "13.7 C, 74 %",
         "Description" : "Alexa_Name:jardin",
         "DewPoint" : "9.15",
         "Favorite" : 0,
         "HardwareDisabled" : false,
         "HardwareID" : 2,
         "HardwareName" : "RFXCOM",
         "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
         "HardwareTypeVal" : 1,
         "HaveTimeout" : false,
         "Humidity" : 74,
         "HumidityStatus" : "Wet",
         "ID" : "8C01",
         "LastUpdate" : "2023-04-08 13:00:49",
         "Name" : "T-H JARDIN",
         "Notifications" : "false",
         "PlanID" : "15",
         "PlanIDs" : 
         [
            15
         ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : 7,
         "SubType" : "THGN122/123/132, THGR122/228/238/268",
         "Temp" : 13.699999999999999,
         "Timers" : "false",
         "Type" : "Temp + Humidity",
         "TypeImg" : "temperature",
         "Unit" : 1,
         "Used" : 1,
         "XOffset" : "153",
         "YOffset" : "403",
         "idx" : "4747",
         "trend" : 2
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 100,
         "CustomImage" : 0,
         "Data" : "21.9 C, 55 %",
         "Description" : "Alexa_Name:grenier",
         "DewPoint" : "12.45",
         "Favorite" : 0,
         "HardwareDisabled" : false,
         "HardwareID" : 2,
         "HardwareName" : "RFXCOM",
         "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
         "HardwareTypeVal" : 1,
         "HaveTimeout" : false,
         "Humidity" : 55,
         "HumidityStatus" : "Comfortable",
         "ID" : "DC04",
         "LastUpdate" : "2023-04-08 13:00:37",
         "Name" : "T-H GRENIER",
         "Notifications" : "false",
         "PlanID" : "15",
         "PlanIDs" : 
         [
            15
         ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : 7,
         "SubType" : "THGN122/123/132, THGR122/228/238/268",
         "Temp" : 21.899999999999999,
         "Timers" : "false",
         "Type" : "Temp + Humidity",
         "TypeImg" : "temperature",
         "Unit" : 4,
         "Used" : 1,
         "XOffset" : "152",
         "YOffset" : "339",
         "idx" : "4704",
         "trend" : 2
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 100,
         "CustomImage" : 0,
         "Data" : "20.2 C, 42 %",
         "Description" : "Alexa_Name:chambre nord",
         "DewPoint" : "6.88",
         "Favorite" : 0,
         "HardwareDisabled" : false,
         "HardwareID" : 2,
         "HardwareName" : "RFXCOM",
         "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
         "HardwareTypeVal" : 1,
         "HaveTimeout" : false,
         "Humidity" : 42,
         "HumidityStatus" : "Comfortable",
         "ID" : "C501",
         "LastUpdate" : "2023-04-08 13:00:39",
         "Name" : "T-H C1",
         "Notifications" : "false",
         "PlanID" : "2",
         "PlanIDs" : 
         [
            2
         ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : 7,
         "SubType" : "THGR810, THGN800",
         "Temp" : 20.199999999999999,
         "Timers" : "false",
         "Type" : "Temp + Humidity",
         "TypeImg" : "temperature",
         "Unit" : 1,
         "Used" : 1,
         "XOffset" : "467",
         "YOffset" : "79",
         "idx" : "4710",
         "trend" : 2
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 100,
         "CustomImage" : 0,
         "Data" : "16.9 C, 46 %",
         "Description" : "Alexa_Name: Chambre Hest",
         "DewPoint" : "5.20",
         "Favorite" : 0,
         "HardwareDisabled" : false,
         "HardwareID" : 2,
         "HardwareName" : "RFXCOM",
         "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
         "HardwareTypeVal" : 1,
         "HaveTimeout" : false,
         "Humidity" : 46,
         "HumidityStatus" : "Normal",
         "ID" : "FE02",
         "LastUpdate" : "2023-04-08 13:00:33",
         "Name" : "T-H C2",
         "Notifications" : "false",
         "PlanID" : "3",
         "PlanIDs" : 
         [
            3
         ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : 7,
         "SubType" : "THGR810, THGN800",
         "Temp" : 16.899999999999999,
         "Timers" : "false",
         "Type" : "Temp + Humidity",
         "TypeImg" : "temperature",
         "Unit" : 2,
         "Used" : 1,
         "XOffset" : "467",
         "YOffset" : "190",
         "idx" : "4422",
         "trend" : 2
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 100,
         "CustomImage" : 0,
         "Data" : "20.0 C, 38 %",
         "Description" : "Alexa_Name:Chambre Sud",
         "DewPoint" : "5.25",
         "Favorite" : 0,
         "HardwareDisabled" : false,
         "HardwareID" : 2,
         "HardwareName" : "RFXCOM",
         "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
         "HardwareTypeVal" : 1,
         "HaveTimeout" : false,
         "Humidity" : 38,
         "HumidityStatus" : "Dry",
         "ID" : "3707",
         "LastUpdate" : "2023-04-08 12:59:43",
         "Name" : "T-H C3",
         "Notifications" : "false",
         "PlanID" : "4",
         "PlanIDs" : 
         [
            4
         ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : 7,
         "SubType" : "THGR810, THGN800",
         "Temp" : 20.0,
         "Timers" : "false",
         "Type" : "Temp + Humidity",
         "TypeImg" : "temperature",
         "Unit" : 7,
         "Used" : 1,
         "XOffset" : "467",
         "YOffset" : "334",
         "idx" : "4702",
         "trend" : 3
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 100,
         "CustomImage" : 0,
         "Data" : "21.6 C",
         "Description" : "Alexa_Name:bureau",
         "Favorite" : 0,
         "HardwareDisabled" : false,
         "HardwareID" : 4,
         "HardwareName" : "Z-Wave+",
         "HardwareType" : "OpenZWave USB",
         "HardwareTypeVal" : 21,
         "HaveTimeout" : false,
         "ID" : "2901",
         "LastUpdate" : "2023-04-08 06:40:35",
         "Name" : "MS C4-BUREAU Temperature",
         "Notifications" : "false",
         "PlanID" : "5",
         "PlanIDs" : 
         [
            5
         ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "LaCrosse TX3",
         "Temp" : 21.600000000000001,
         "Timers" : "false",
         "Type" : "Temp",
         "TypeImg" : "temperature",
         "Unit" : 1,
         "Used" : 1,
         "XOffset" : "370",
         "YOffset" : "430",
         "idx" : "3590",
         "trend" : 2
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 100,
         "CustomImage" : 0,
         "Data" : "21.0 C",
         "Description" : "Alexa_Name:Couloir",
         "Favorite" : 0,
         "HardwareDisabled" : false,
         "HardwareID" : 4,
         "HardwareName" : "Z-Wave+",
         "HardwareType" : "OpenZWave USB",
         "HardwareTypeVal" : 21,
         "HaveTimeout" : false,
         "ID" : "0301",
         "LastUpdate" : "2023-04-08 12:55:55",
         "Name" : "MS COULOIR Temperature",
         "Notifications" : "false",
         "PlanID" : "6",
         "PlanIDs" : 
         [
            6
         ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "LaCrosse TX3",
         "Temp" : 21.0,
         "Timers" : "false",
         "Type" : "Temp",
         "TypeImg" : "temperature",
         "Unit" : 1,
         "Used" : 1,
         "XOffset" : "421",
         "YOffset" : "122",
         "idx" : "28",
         "trend" : 3
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 100,
         "CustomImage" : 0,
         "Data" : "17.1 C",
         "Description" : "Alexa_Name: salon",
         "Favorite" : 0,
         "HardwareDisabled" : false,
         "HardwareID" : 4,
         "HardwareName" : "Z-Wave+",
         "HardwareType" : "OpenZWave USB",
         "HardwareTypeVal" : 21,
         "HaveTimeout" : false,
         "ID" : "0501",
         "LastUpdate" : "2023-04-08 12:48:08",
         "Name" : "MS SALON Temperature",
         "Notifications" : "false",
         "PlanID" : "16",
         "PlanIDs" : 
         [
            16
         ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "LaCrosse TX3",
         "Temp" : 17.100000000000001,
         "Timers" : "false",
         "Type" : "Temp",
         "TypeImg" : "temperature",
         "Unit" : 1,
         "Used" : 1,
         "XOffset" : "156",
         "YOffset" : "196",
         "idx" : "80",
         "trend" : 2
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 100,
         "CustomImage" : 0,
         "Data" : "17.4 C, 45 %",
         "Description" : "Alexa_Name:Cuisine",
         "DewPoint" : "5.34",
         "Favorite" : 0,
         "HardwareDisabled" : false,
         "HardwareID" : 2,
         "HardwareName" : "RFXCOM",
         "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
         "HardwareTypeVal" : 1,
         "HaveTimeout" : false,
         "Humidity" : 45,
         "HumidityStatus" : "Normal",
         "ID" : "3001",
         "LastUpdate" : "2023-04-08 13:00:46",
         "Name" : "T-H CUISINE",
         "Notifications" : "false",
         "PlanID" : "10",
         "PlanIDs" : 
         [
            10
         ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : 7,
         "SubType" : "THGR810, THGN800",
         "Temp" : 17.399999999999999,
         "Timers" : "false",
         "Type" : "Temp + Humidity",
         "TypeImg" : "temperature",
         "Unit" : 1,
         "Used" : 1,
         "XOffset" : "177",
         "YOffset" : "73",
         "idx" : "4717",
         "trend" : 2
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 78,
         "CustomImage" : 0,
         "Data" : "16.8 C",
         "Description" : "Alexa_Name: sol douche",
         "Favorite" : 0,
         "HardwareDisabled" : false,
         "HardwareID" : 4,
         "HardwareName" : "Z-Wave+",
         "HardwareType" : "OpenZWave USB",
         "HardwareTypeVal" : 21,
         "HaveTimeout" : false,
         "ID" : "2E01",
         "LastUpdate" : "2023-04-07 20:05:24",
         "Name" : "FS SdD Temp",
         "Notifications" : "false",
         "PlanID" : "7",
         "PlanIDs" : 
         [
            7
         ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "LaCrosse TX3",
         "Temp" : 16.800000000000001,
         "Timers" : "false",
         "Type" : "Temp",
         "TypeImg" : "temperature",
         "Unit" : 1,
         "Used" : 1,
         "XOffset" : "388",
         "YOffset" : "218",
         "idx" : "4447",
         "trend" : 2
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 100,
         "CustomImage" : 0,
         "Data" : "18.6 C, 48 %",
         "Description" : "Alexa_Name:Douche",
         "DewPoint" : "7.37",
         "Favorite" : 0,
         "HardwareDisabled" : false,
         "HardwareID" : 2,
         "HardwareName" : "RFXCOM",
         "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
         "HardwareTypeVal" : 1,
         "HaveTimeout" : false,
         "Humidity" : 48,
         "HumidityStatus" : "Normal",
         "ID" : "C305",
         "LastUpdate" : "2023-04-08 12:58:43",
         "Name" : "T-H SdD",
         "Notifications" : "false",
         "PlanID" : "7",
         "PlanIDs" : 
         [
            7
         ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : 7,
         "SubType" : "THGR810, THGN800",
         "Temp" : 18.600000000000001,
         "Timers" : "false",
         "Type" : "Temp + Humidity",
         "TypeImg" : "temperature",
         "Unit" : 5,
         "Used" : 1,
         "XOffset" : "309",
         "YOffset" : "244",
         "idx" : "4706",
         "trend" : 2
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 100,
         "CustomImage" : 0,
         "Data" : "17.0 C, 43 %",
         "Description" : "Alexa_Name:Salle de Bain",
         "DewPoint" : "4.33",
         "Favorite" : 0,
         "HardwareDisabled" : false,
         "HardwareID" : 2,
         "HardwareName" : "RFXCOM",
         "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
         "HardwareTypeVal" : 1,
         "HaveTimeout" : false,
         "Humidity" : 43,
         "HumidityStatus" : "Normal",
         "ID" : "6708",
         "LastUpdate" : "2023-04-08 12:59:44",
         "Name" : "T-H SdB",
         "Notifications" : "false",
         "PlanID" : "8",
         "PlanIDs" : 
         [
            8
         ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : 7,
         "SubType" : "THGR810, THGN800",
         "Temp" : 17.0,
         "Timers" : "false",
         "Type" : "Temp + Humidity",
         "TypeImg" : "temperature",
         "Unit" : 8,
         "Used" : 1,
         "XOffset" : "308",
         "YOffset" : "318",
         "idx" : "4703",
         "trend" : 2
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 79,
         "CustomImage" : 0,
         "Data" : "16.9 C",
         "Description" : "Alexa_Name: toilette",
         "Favorite" : 0,
         "HardwareDisabled" : false,
         "HardwareID" : 4,
         "HardwareName" : "Z-Wave+",
         "HardwareType" : "OpenZWave USB",
         "HardwareTypeVal" : 21,
         "HaveTimeout" : false,
         "ID" : "2D01",
         "LastUpdate" : "2023-04-08 10:52:50",
         "Name" : "FS WC temp",
         "Notifications" : "false",
         "PlanID" : "17",
         "PlanIDs" : 
         [
            17
         ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "LaCrosse TX3",
         "Temp" : 16.899999999999999,
         "Timers" : "false",
         "Type" : "Temp",
         "TypeImg" : "temperature",
         "Unit" : 1,
         "Used" : 1,
         "XOffset" : "386",
         "YOffset" : "190",
         "idx" : "4442",
         "trend" : 2
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 73,
         "CustomImage" : 0,
         "Data" : "14.0 C",
         "Description" : "Alexa_Name:buanderie",
         "Favorite" : 0,
         "HardwareDisabled" : false,
         "HardwareID" : 4,
         "HardwareName" : "Z-Wave+",
         "HardwareType" : "OpenZWave USB",
         "HardwareTypeVal" : 21,
         "HaveTimeout" : false,
         "ID" : "2C01",
         "LastUpdate" : "2023-04-08 10:26:56",
         "Name" : "FS BUANDERIE Temp",
         "Notifications" : "false",
         "PlanID" : "9",
         "PlanIDs" : 
         [
            9
         ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "LaCrosse TX3",
         "Temp" : 14.0,
         "Timers" : "false",
         "Type" : "Temp",
         "TypeImg" : "temperature",
         "Unit" : 1,
         "Used" : 1,
         "XOffset" : "359",
         "YOffset" : "11",
         "idx" : "4436",
         "trend" : 1
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 100,
         "CustomImage" : 0,
         "Data" : "5.8 C, 46 %",
         "Description" : "Alexa_Name:frigo",
         "DewPoint" : "-4.94",
         "Favorite" : 0,
         "HardwareDisabled" : false,
         "HardwareID" : 2,
         "HardwareName" : "RFXCOM",
         "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
         "HardwareTypeVal" : 1,
         "HaveTimeout" : false,
         "Humidity" : 46,
         "HumidityStatus" : "Normal",
         "ID" : "C506",
         "LastUpdate" : "2023-04-08 13:00:24",
         "Name" : "T-H FRIGO",
         "Notifications" : "false",
         "PlanID" : "10",
         "PlanIDs" : 
         [
            10
         ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : 6,
         "SubType" : "THGR810, THGN800",
         "Temp" : 5.7999999999999998,
         "Timers" : "false",
         "Type" : "Temp + Humidity",
         "TypeImg" : "temperature",
         "Unit" : 6,
         "Used" : 1,
         "XOffset" : "273",
         "YOffset" : "102",
         "idx" : "4380",
         "trend" : 2
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 100,
         "CustomImage" : 0,
         "Data" : "-5.7 C, 56 %",
         "Description" : "Alexa_Name:cong\u00e9lateur",
         "DewPoint" : "-13.09",
         "Favorite" : 0,
         "HardwareDisabled" : false,
         "HardwareID" : 2,
         "HardwareName" : "RFXCOM",
         "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
         "HardwareTypeVal" : 1,
         "HaveTimeout" : false,
         "Humidity" : 56,
         "HumidityStatus" : "Normal",
         "ID" : "1A03",
         "LastUpdate" : "2023-04-08 13:00:56",
         "Name" : "T-H CONGELATEUR",
         "Notifications" : "false",
         "PlanID" : "10",
         "PlanIDs" : 
         [
            10
         ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : 7,
         "SubType" : "THGR810, THGN800",
         "Temp" : -5.7000000000000002,
         "Timers" : "false",
         "Type" : "Temp + Humidity",
         "TypeImg" : "temperature",
         "Unit" : 3,
         "Used" : 1,
         "XOffset" : "274",
         "YOffset" : "77",
         "idx" : "4381",
         "trend" : 2
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 61,
         "CustomImage" : 0,
         "Data" : "14.3 C",
         "Description" : "Alexa_Name: sol atelier",
         "Favorite" : 0,
         "HardwareDisabled" : false,
         "HardwareID" : 4,
         "HardwareName" : "Z-Wave+",
         "HardwareType" : "OpenZWave USB",
         "HardwareTypeVal" : 21,
         "HaveTimeout" : false,
         "ID" : "0401",
         "LastUpdate" : "2023-04-08 08:23:37",
         "Name" : "FS ATELIER Temp",
         "Notifications" : "false",
         "PlanID" : "13",
         "PlanIDs" : 
         [
            13
         ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "LaCrosse TX3",
         "Temp" : 14.300000000000001,
         "Timers" : "false",
         "Type" : "Temp",
         "TypeImg" : "temperature",
         "Unit" : 1,
         "Used" : 1,
         "XOffset" : "410",
         "YOffset" : "316",
         "idx" : "48",
         "trend" : 1
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 90,
         "CustomImage" : 0,
         "Data" : "15.5 C",
         "Description" : "Alexa_Name: Plafond atelier",
         "Favorite" : 0,
         "HardwareDisabled" : false,
         "HardwareID" : 4,
         "HardwareName" : "Z-Wave+",
         "HardwareType" : "OpenZWave USB",
         "HardwareTypeVal" : 21,
         "HaveTimeout" : false,
         "ID" : "1C01",
         "LastUpdate" : "2023-04-07 13:08:52",
         "Name" : "SS   ATELIER Temperature",
         "Notifications" : "false",
         "PlanID" : "13",
         "PlanIDs" : 
         [
            13
         ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "LaCrosse TX3",
         "Temp" : 15.5,
         "Timers" : "false",
         "Type" : "Temp",
         "TypeImg" : "temperature",
         "Unit" : 1,
         "Used" : 1,
         "XOffset" : "334",
         "YOffset" : "334",
         "idx" : "1665",
         "trend" : 1
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 100,
         "CustomImage" : 0,
         "Data" : "14.8 C, 53 %",
         "Description" : "Alexa_Name:cellier",
         "DewPoint" : "5.31",
         "Favorite" : 0,
         "HardwareDisabled" : false,
         "HardwareID" : 2,
         "HardwareName" : "RFXCOM",
         "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
         "HardwareTypeVal" : 1,
         "HaveTimeout" : false,
         "Humidity" : 53,
         "HumidityStatus" : "Normal",
         "ID" : "8B02",
         "LastUpdate" : "2023-04-08 13:00:17",
         "Name" : "T-H CELLIER",
         "Notifications" : "false",
         "PlanID" : "14",
         "PlanIDs" : 
         [
            14
         ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : 7,
         "SubType" : "THGN122/123/132, THGR122/228/238/268",
         "Temp" : 14.800000000000001,
         "Timers" : "false",
         "Type" : "Temp + Humidity",
         "TypeImg" : "temperature",
         "Unit" : 2,
         "Used" : 1,
         "XOffset" : "365",
         "YOffset" : "166",
         "idx" : "4798",
         "trend" : 2
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 100,
         "CustomImage" : 0,
         "Data" : "15.3 C",
         "Description" : "Alexa_Name: plafond cellier",
         "Favorite" : 0,
         "HardwareDisabled" : false,
         "HardwareID" : 4,
         "HardwareName" : "Z-Wave+",
         "HardwareType" : "OpenZWave USB",
         "HardwareTypeVal" : 21,
         "HaveTimeout" : true,
         "ID" : "0901",
         "LastUpdate" : "2023-04-07 12:00:08",
         "Name" : "SS CELLIER Temperature",
         "Notifications" : "false",
         "PlanID" : "14",
         "PlanIDs" : 
         [
            14
         ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "LaCrosse TX3",
         "Temp" : 15.300000000000001,
         "Timers" : "false",
         "Type" : "Temp",
         "TypeImg" : "temperature",
         "Unit" : 1,
         "Used" : 1,
         "XOffset" : "319",
         "YOffset" : "146",
         "idx" : "107",
         "trend" : 1
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 9,
         "Data" : "Off",
         "Description" : "Alexa_Name:Prise Ordinateur",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareDisabled" : false,
         "HardwareID" : 5,
         "HardwareName" : "DUMMY_VIRTUAL",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "0001535D",
         "Image" : "Generic",
         "IsSubDevice" : false,
         "LastUpdate" : "2023-04-08 01:00:00",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 100,
         "Name" : "? CDE ORDINATEUR",
         "Notifications" : "false",
         "PlanID" : "5",
         "PlanIDs" : 
         [
            5
         ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Switch",
         "SwitchType" : "On/Off",
         "SwitchTypeVal" : 0,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "lightbulb",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "421",
         "YOffset" : "430",
         "idx" : "4877"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 9,
         "Data" : "Off",
         "Description" : "Alexa_Name:Prise HIFI",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareDisabled" : false,
         "HardwareID" : 5,
         "HardwareName" : "DUMMY_VIRTUAL",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "0001531C",
         "Image" : "Generic",
         "IsSubDevice" : false,
         "LastUpdate" : "2023-04-08 01:30:00",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 100,
         "Name" : "? CDE ALIM HIFI",
         "Notifications" : "false",
         "PlanID" : "16",
         "PlanIDs" : 
         [
            16
         ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Switch",
         "SwitchType" : "On/Off",
         "SwitchTypeVal" : 0,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "lightbulb",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "9",
         "YOffset" : "249",
         "idx" : "4812"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "On",
         "Description" : "Alexa_Name:coupure television",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareDisabled" : false,
         "HardwareID" : 8,
         "HardwareName" : "LOGITECH HARMONY",
         "HardwareType" : "Logitech Harmony Hub",
         "HardwareTypeVal" : 36,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "FFFFFFFF",
         "Image" : "Push",
         "InternalState" : "On",
         "IsSubDevice" : false,
         "LastUpdate" : "2023-04-08 01:30:00",
         "Level" : 100,
         "LevelInt" : 15,
         "MaxDimLevel" : 15,
         "Name" : "HARMONY STOP ALL_OFF",
         "Notifications" : "false",
         "PlanID" : "16",
         "PlanIDs" : 
         [
            16
         ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "AC",
         "SwitchType" : "Push On Button",
         "SwitchTypeVal" : 9,
         "Timers" : "false",
         "Type" : "Lighting 2",
         "TypeImg" : "push",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "83",
         "YOffset" : "248",
         "idx" : "1733"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 12,
         "Data" : "Off",
         "Description" : "Alexa_Name: Television",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareDisabled" : false,
         "HardwareID" : 8,
         "HardwareName" : "LOGITECH HARMONY",
         "HardwareType" : "Logitech Harmony Hub",
         "HardwareTypeVal" : 36,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "21069DA",
         "Image" : "Media",
         "IsSubDevice" : false,
         "LastUpdate" : "2023-02-25 18:01:32",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 15,
         "Name" : "HARMONY  TVAMP_ON",
         "Notifications" : "false",
         "PlanID" : "16",
         "PlanIDs" : 
         [
            16
         ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "AC",
         "SwitchType" : "On/Off",
         "SwitchTypeVal" : 0,
         "Timers" : "false",
         "Type" : "Lighting 2",
         "TypeImg" : "lightbulb",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "107",
         "YOffset" : "194",
         "idx" : "1735"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 12,
         "Data" : "Off",
         "Description" : "Alexa_Name: T\u00e9l\u00e9",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareDisabled" : false,
         "HardwareID" : 8,
         "HardwareName" : "LOGITECH HARMONY",
         "HardwareType" : "Logitech Harmony Hub",
         "HardwareTypeVal" : 36,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "2109A23",
         "Image" : "Media",
         "IsSubDevice" : false,
         "LastUpdate" : "2023-04-03 21:30:20",
         "Level" : 100,
         "LevelInt" : 15,
         "MaxDimLevel" : 15,
         "Name" : "HARMONY TV_slt_ON",
         "Notifications" : "false",
         "PlanID" : "16",
         "PlanIDs" : 
         [
            16
         ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "AC",
         "SwitchType" : "On/Off",
         "SwitchTypeVal" : 0,
         "Timers" : "false",
         "Type" : "Lighting 2",
         "TypeImg" : "lightbulb",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "107",
         "YOffset" : "169",
         "idx" : "1744"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 12,
         "Data" : "Off",
         "Description" : "Alexa_Name:Home Cinema",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareDisabled" : false,
         "HardwareID" : 8,
         "HardwareName" : "LOGITECH HARMONY",
         "HardwareType" : "Logitech Harmony Hub",
         "HardwareTypeVal" : 36,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "21062EB",
         "Image" : "Media",
         "IsSubDevice" : false,
         "LastUpdate" : "2023-03-18 22:10:36",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 15,
         "Name" : "HARMONY HCINEMA_ON",
         "Notifications" : "false",
         "PlanID" : "16",
         "PlanIDs" : 
         [
            16
         ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "AC",
         "SwitchType" : "On/Off",
         "SwitchTypeVal" : 0,
         "Timers" : "false",
         "Type" : "Lighting 2",
         "TypeImg" : "lightbulb",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "107",
         "YOffset" : "218",
         "idx" : "1734"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 3,
         "Data" : "Off",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareDisabled" : false,
         "HardwareID" : 8,
         "HardwareName" : "LOGITECH HARMONY",
         "HardwareType" : "Logitech Harmony Hub",
         "HardwareTypeVal" : 36,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "2106B32",
         "Image" : "Harddisk",
         "IsSubDevice" : false,
         "LastUpdate" : "2022-11-20 20:29:06",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 15,
         "Name" : "HARMONY FBOX_ENR_ ON",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : 
         [
            0
         ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "AC",
         "SwitchType" : "On/Off",
         "SwitchTypeVal" : 0,
         "Timers" : "false",
         "Type" : "Lighting 2",
         "TypeImg" : "lightbulb",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "1736"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 5,
         "Data" : "Off",
         "Description" : "Alexa_Name:St\u00e9r\u00e9o",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareDisabled" : false,
         "HardwareID" : 8,
         "HardwareName" : "LOGITECH HARMONY",
         "HardwareType" : "Logitech Harmony Hub",
         "HardwareTypeVal" : 36,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "210C2BB",
         "Image" : "Amplifier",
         "IsSubDevice" : false,
         "LastUpdate" : "2022-11-12 19:39:03",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 15,
         "Name" : "HARMONY STEREO_slt_ON",
         "Notifications" : "false",
         "PlanID" : "16",
         "PlanIDs" : 
         [
            16
         ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "AC",
         "SwitchType" : "On/Off",
         "SwitchTypeVal" : 0,
         "Timers" : "false",
         "Type" : "Lighting 2",
         "TypeImg" : "lightbulb",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "106",
         "YOffset" : "249",
         "idx" : "1751"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 1,
         "Data" : "Off",
         "Description" : "Alexa_Name:Chargeur",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareDisabled" : false,
         "HardwareID" : 2,
         "HardwareName" : "RFXCOM",
         "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
         "HardwareTypeVal" : 1,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "0ACB400",
         "Image" : "WallSocket",
         "IsSubDevice" : false,
         "LastUpdate" : "2023-04-08 01:00:03",
         "Level" : 100,
         "LevelInt" : 15,
         "MaxDimLevel" : 15,
         "Name" : "PC CHARGEUR HALL",
         "Notifications" : "false",
         "PlanID" : "6",
         "PlanIDs" : 
         [
            6
         ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "AC",
         "SwitchType" : "On/Off",
         "SwitchTypeVal" : 0,
         "Timers" : "true",
         "Type" : "Lighting 2",
         "TypeImg" : "lightbulb",
         "Unit" : 4,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "287",
         "YOffset" : "195",
         "idx" : "4828"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "Off",
         "Description" : "Alexa_Name: Petit Caf\u00e9",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareDisabled" : false,
         "HardwareID" : 5,
         "HardwareName" : "DUMMY_VIRTUAL",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "000153AC",
         "Image" : "Push",
         "InternalState" : "Off",
         "IsSubDevice" : false,
         "LastUpdate" : "2023-03-12 20:22:47",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 100,
         "Name" : "?  CDE SCEN PETIT CAFE",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : 
         [
            0
         ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Switch",
         "SwitchType" : "Push On Button",
         "SwitchTypeVal" : 9,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "push",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "4956"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 9,
         "Data" : "Off",
         "Description" : "Alexa_Name: commande Machine a Caf\u00e9",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareDisabled" : false,
         "HardwareID" : 5,
         "HardwareName" : "DUMMY_VIRTUAL",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "00015343",
         "Image" : "Generic",
         "IsSubDevice" : false,
         "LastUpdate" : "2023-04-08 10:53:22",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 100,
         "Name" : "? CDE MACH. A  CAFE",
         "Notifications" : "false",
         "PlanID" : "10",
         "PlanIDs" : 
         [
            10
         ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Switch",
         "SwitchType" : "On/Off",
         "SwitchTypeVal" : 0,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "lightbulb",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "268",
         "YOffset" : "22",
         "idx" : "4851"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "Off",
         "Description" : "Alexa_Name:Lampe Salon",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareDisabled" : false,
         "HardwareID" : 2,
         "HardwareName" : "RFXCOM",
         "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
         "HardwareTypeVal" : 1,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "1EDE000",
         "Image" : "Light",
         "IsSubDevice" : false,
         "LastUpdate" : "2023-04-07 21:01:25",
         "Level" : 100,
         "LevelInt" : 15,
         "MaxDimLevel" : 15,
         "Name" : "ECL SALON DIOc1",
         "Notifications" : "false",
         "PlanID" : "16",
         "PlanIDs" : 
         [
            16
         ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "AC",
         "SwitchType" : "On/Off",
         "SwitchTypeVal" : 0,
         "Timers" : "false",
         "Type" : "Lighting 2",
         "TypeImg" : "lightbulb",
         "Unit" : 2,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "125",
         "YOffset" : "16",
         "idx" : "4814"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "Off",
         "Description" : "Alexa_Name:Lampe S\u00e9jour",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareDisabled" : false,
         "HardwareID" : 2,
         "HardwareName" : "RFXCOM",
         "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
         "HardwareTypeVal" : 1,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "1EDE000",
         "Image" : "Light",
         "IsSubDevice" : false,
         "LastUpdate" : "2023-04-06 22:56:19",
         "Level" : 93,
         "LevelInt" : 14,
         "MaxDimLevel" : 15,
         "Name" : "ECL SEJOUR DIOc2",
         "Notifications" : "false",
         "PlanID" : "16",
         "PlanIDs" : 
         [
            16
         ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "AC",
         "SwitchType" : "On/Off",
         "SwitchTypeVal" : 0,
         "Timers" : "false",
         "Type" : "Lighting 2",
         "TypeImg" : "lightbulb",
         "Unit" : 3,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "202",
         "YOffset" : "141",
         "idx" : "4815"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "Off",
         "Description" : "Alexa_Name:Lampe Cuisine",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareDisabled" : false,
         "HardwareID" : 2,
         "HardwareName" : "RFXCOM",
         "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
         "HardwareTypeVal" : 1,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "0ACB400",
         "Image" : "Light",
         "IsSubDevice" : false,
         "LastUpdate" : "2023-04-08 11:11:20",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 15,
         "Name" : "ECL CUISINE DIOc1",
         "Notifications" : "false",
         "PlanID" : "10",
         "PlanIDs" : 
         [
            10
         ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "AC",
         "SwitchType" : "On/Off",
         "SwitchTypeVal" : 0,
         "Timers" : "false",
         "Type" : "Lighting 2",
         "TypeImg" : "lightbulb",
         "Unit" : 2,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "235",
         "YOffset" : "49",
         "idx" : "4822"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "Off",
         "Description" : "Alexa_Name:Lampe chambre sud",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareDisabled" : false,
         "HardwareID" : 2,
         "HardwareName" : "RFXCOM",
         "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
         "HardwareTypeVal" : 1,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "16F1800",
         "Image" : "Light",
         "IsSubDevice" : false,
         "LastUpdate" : "2023-04-06 22:56:30",
         "Level" : 93,
         "LevelInt" : 14,
         "MaxDimLevel" : 15,
         "Name" : "ECL C3 DIOc1",
         "Notifications" : "false",
         "PlanID" : "4",
         "PlanIDs" : 
         [
            4
         ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "AC",
         "SwitchType" : "On/Off",
         "SwitchTypeVal" : 0,
         "Timers" : "false",
         "Type" : "Lighting 2",
         "TypeImg" : "lightbulb",
         "Unit" : 2,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "544",
         "YOffset" : "331",
         "idx" : "4894"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "Off",
         "Description" : "Alexa_Name:Lampe Bureau",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareDisabled" : false,
         "HardwareID" : 2,
         "HardwareName" : "RFXCOM",
         "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
         "HardwareTypeVal" : 1,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "2018C00",
         "Image" : "Light",
         "IsSubDevice" : false,
         "LastUpdate" : "2023-04-08 09:19:07",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 15,
         "Name" : "ECL C4 DIOc2",
         "Notifications" : "false",
         "PlanID" : "5",
         "PlanIDs" : 
         [
            5
         ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "AC",
         "SwitchType" : "On/Off",
         "SwitchTypeVal" : 0,
         "Timers" : "false",
         "Type" : "Lighting 2",
         "TypeImg" : "lightbulb",
         "Unit" : 3,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "382",
         "YOffset" : "383",
         "idx" : "4820"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "On",
         "Description" : "Alexa_Name:Coupure Generale",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareDisabled" : false,
         "HardwareID" : 5,
         "HardwareName" : "DUMMY_VIRTUAL",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "000149BD",
         "Image" : "Push",
         "InternalState" : "On",
         "IsSubDevice" : false,
         "LastUpdate" : "2023-03-10 21:13:56",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 100,
         "Name" : "? EXTINCTION GENERALE",
         "Notifications" : "false",
         "PlanID" : "6",
         "PlanIDs" : 
         [
            6
         ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Switch",
         "SwitchType" : "Push On Button",
         "SwitchTypeVal" : 9,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "push",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "262",
         "YOffset" : "125",
         "idx" : "2413"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 124,
         "Data" : "Off",
         "Description" : "Alexa_Name:Pr\u00e9sence forc\u00e9",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareDisabled" : false,
         "HardwareID" : 5,
         "HardwareName" : "DUMMY_VIRTUAL",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "0001516B",
         "Image" : "PRES_DAY",
         "IsSubDevice" : false,
         "LastUpdate" : "2023-04-08 01:00:00",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 100,
         "Name" : "? PRESENCE FORCEE (Cde manu)",
         "Notifications" : "false",
         "PlanID" : "2",
         "PlanIDs" : 
         [
            2
         ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Switch",
         "SwitchType" : "On/Off",
         "SwitchTypeVal" : 0,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "lightbulb",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "540",
         "YOffset" : "49",
         "idx" : "4379"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 127,
         "Data" : "Off",
         "Description" : "Alexa_Name:T\u00e9l\u00e9travail",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareDisabled" : false,
         "HardwareID" : 5,
         "HardwareName" : "DUMMY_VIRTUAL",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "000152BB",
         "Image" : "PRES_NIGHT",
         "IsSubDevice" : false,
         "LastUpdate" : "2023-04-07 16:01:00",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 100,
         "Name" : "? TELETRAVAIL (cde manu)",
         "Notifications" : "false",
         "PlanID" : "5",
         "PlanIDs" : 
         [
            5
         ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Switch",
         "SwitchType" : "On/Off",
         "SwitchTypeVal" : 0,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "lightbulb",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "362",
         "YOffset" : "405",
         "idx" : "4715"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 1,
         "Data" : "Off",
         "Description" : "Alexa_Name:clim",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareDisabled" : false,
         "HardwareID" : 4,
         "HardwareName" : "Z-Wave+",
         "HardwareType" : "OpenZWave USB",
         "HardwareTypeVal" : 21,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "00001A01",
         "Image" : "WallSocket",
         "IsSubDevice" : false,
         "LastUpdate" : "2023-03-12 15:04:34",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 100,
         "Name" : "PC CLIM",
         "Notifications" : "false",
         "PlanID" : "5",
         "PlanIDs" : 
         [
            5,
            9
         ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Switch",
         "SwitchType" : "On/Off",
         "SwitchTypeVal" : 0,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "lightbulb",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "360",
         "YOffset" : "360",
         "idx" : "1575"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 9,
         "Data" : "Off",
         "Description" : "Alexa_Name:Chauffage douche",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareDisabled" : false,
         "HardwareID" : 5,
         "HardwareName" : "DUMMY_VIRTUAL",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "00015172",
         "Image" : "Generic",
         "IsSubDevice" : false,
         "LastUpdate" : "2023-04-06 22:56:15",
         "Level" : 99,
         "LevelInt" : 99,
         "MaxDimLevel" : 100,
         "Name" : "? CDE CHAUF SdD",
         "Notifications" : "false",
         "PlanID" : "7",
         "PlanIDs" : 
         [
            7
         ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Switch",
         "SwitchType" : "On/Off",
         "SwitchTypeVal" : 0,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "lightbulb",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "304",
         "YOffset" : "217",
         "idx" : "4386"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 9,
         "Data" : "On",
         "Description" : "Alexa_Name:Chauffage g\u00e9n\u00e9ral",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareDisabled" : false,
         "HardwareID" : 5,
         "HardwareName" : "DUMMY_VIRTUAL",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "00014D31",
         "Image" : "Generic",
         "IsSubDevice" : false,
         "LastUpdate" : "2023-04-07 21:01:18",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 100,
         "Name" : "? CDE DROP POWER ON",
         "Notifications" : "false",
         "PlanID" : "9",
         "PlanIDs" : 
         [
            9
         ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "On",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Switch",
         "SwitchType" : "On/Off",
         "SwitchTypeVal" : 0,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "lightbulb",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "390",
         "YOffset" : "11",
         "idx" : "3297"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 9,
         "Data" : "Off",
         "Description" : "Alexa_Name:Confort Salon",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareDisabled" : false,
         "HardwareID" : 5,
         "HardwareName" : "DUMMY_VIRTUAL",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "00014D2E",
         "Image" : "Generic",
         "IsSubDevice" : false,
         "LastUpdate" : "2023-04-07 11:57:10",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 100,
         "Name" : "? CDE DROP CONF Z1SAL",
         "Notifications" : "false",
         "PlanID" : "16",
         "PlanIDs" : 
         [
            16
         ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Switch",
         "SwitchType" : "On/Off",
         "SwitchTypeVal" : 0,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "lightbulb",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "9",
         "YOffset" : "13",
         "idx" : "3294"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 9,
         "Data" : "On",
         "Description" : "Alexa_Name:Confort Chambre",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareDisabled" : false,
         "HardwareID" : 5,
         "HardwareName" : "DUMMY_VIRTUAL",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "00014D2F",
         "Image" : "Generic",
         "IsSubDevice" : false,
         "LastUpdate" : "2023-04-08 05:02:00",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 100,
         "Name" : "? CDE DROP CONF Z2CHA",
         "Notifications" : "false",
         "PlanID" : "2",
         "PlanIDs" : 
         [
            2
         ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "On",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Switch",
         "SwitchType" : "On/Off",
         "SwitchTypeVal" : 0,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "lightbulb",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "441",
         "YOffset" : "10",
         "idx" : "3295"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 9,
         "Data" : "On",
         "Description" : "Alexa_Name:Confort bureau",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareDisabled" : false,
         "HardwareID" : 5,
         "HardwareName" : "DUMMY_VIRTUAL",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "00014D30",
         "Image" : "Generic",
         "IsSubDevice" : false,
         "LastUpdate" : "2023-04-08 05:03:00",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 100,
         "Name" : "? CDE DROP CONF Z3BUR",
         "Notifications" : "false",
         "PlanID" : "5",
         "PlanIDs" : 
         [
            5
         ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "On",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Switch",
         "SwitchType" : "On/Off",
         "SwitchTypeVal" : 0,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "lightbulb",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "306",
         "YOffset" : "358",
         "idx" : "3296"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 10,
         "Data" : "Off",
         "Description" : "inversion Reduit - confort de chacune des 3 que Zone\nBugg\u00e9 . les secanrio pusl semble envoy\u00e9qs simutlenement dans certains cas...",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareDisabled" : false,
         "HardwareID" : 5,
         "HardwareName" : "DUMMY_VIRTUAL",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "00014BAA",
         "Image" : "Fireplace",
         "IsSubDevice" : false,
         "LastUpdate" : "2019-11-08 20:41:36",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 100,
         "Name" : "? CDE DROP ECOCF ALL",
         "Notifications" : "false",
         "PlanID" : "9",
         "PlanIDs" : 
         [
            9
         ],
         "Protected" : true,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Switch",
         "SwitchType" : "On/Off",
         "SwitchTypeVal" : 0,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "lightbulb",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "420",
         "YOffset" : "92",
         "idx" : "2906"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 9,
         "Data" : "Off",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareDisabled" : false,
         "HardwareID" : 5,
         "HardwareName" : "DUMMY_VIRTUAL",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "00015291",
         "Image" : "Generic",
         "IsSubDevice" : false,
         "LastUpdate" : "2022-11-01 15:31:55",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 100,
         "Name" : "? CDE VMC GV SdD",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : 
         [
            0
         ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Switch",
         "SwitchType" : "On/Off",
         "SwitchTypeVal" : 0,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "lightbulb",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "4673"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 100,
         "CustomImage" : 0,
         "Data" : "14.1 C, 60 %",
         "Description" : "Alexa_Name:cave",
         "DewPoint" : "6.45",
         "Favorite" : 0,
         "HardwareDisabled" : false,
         "HardwareID" : 2,
         "HardwareName" : "RFXCOM",
         "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
         "HardwareTypeVal" : 1,
         "HaveTimeout" : false,
         "Humidity" : 60,
         "HumidityStatus" : "Normal",
         "ID" : "7801",
         "LastUpdate" : "2023-04-08 13:00:11",
         "Name" : "T-H CAVE",
         "Notifications" : "false",
         "PlanID" : "12",
         "PlanIDs" : 
         [
            12
         ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : 6,
         "SubType" : "THGR810, THGN800",
         "Temp" : 14.1,
         "Timers" : "false",
         "Type" : "Temp + Humidity",
         "TypeImg" : "temperature",
         "Unit" : 1,
         "Used" : 1,
         "XOffset" : "363",
         "YOffset" : "48",
         "idx" : "4714",
         "trend" : 2
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 100,
         "CustomImage" : 0,
         "Data" : "14.8 C",
         "Description" : "Alexa_Name:garage",
         "Favorite" : 0,
         "HardwareDisabled" : false,
         "HardwareID" : 4,
         "HardwareName" : "Z-Wave+",
         "HardwareType" : "OpenZWave USB",
         "HardwareTypeVal" : 21,
         "HaveTimeout" : false,
         "ID" : "2701",
         "LastUpdate" : "2023-04-08 12:40:08",
         "Name" : "MS GARAGE Temperature",
         "Notifications" : "false",
         "PlanID" : "12",
         "PlanIDs" : 
         [
            12,
            12
         ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "LaCrosse TX3",
         "Temp" : 14.800000000000001,
         "Timers" : "false",
         "Type" : "Temp",
         "TypeImg" : "temperature",
         "Unit" : 1,
         "Used" : 1,
         "XOffset" : "439",
         "YOffset" : "8",
         "idx" : "3325",
         "trend" : 2
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 57,
         "CustomImage" : 0,
         "Data" : "13.9 C",
         "Description" : "Alexa_Name: sol garage",
         "Favorite" : 0,
         "HardwareDisabled" : false,
         "HardwareID" : 4,
         "HardwareName" : "Z-Wave+",
         "HardwareType" : "OpenZWave USB",
         "HardwareTypeVal" : 21,
         "HaveTimeout" : false,
         "ID" : "2B01",
         "LastUpdate" : "2023-04-08 12:39:54",
         "Name" : "FS GARAGE  Temp",
         "Notifications" : "false",
         "PlanID" : "12",
         "PlanIDs" : 
         [
            12
         ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "LaCrosse TX3",
         "Temp" : 13.9,
         "Timers" : "false",
         "Type" : "Temp",
         "TypeImg" : "temperature",
         "Unit" : 1,
         "Used" : 1,
         "XOffset" : "333",
         "YOffset" : "111",
         "idx" : "4429",
         "trend" : 1
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "On",
         "Description" : "Alexa_Name:VENTILATION HIVERS",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareDisabled" : false,
         "HardwareID" : 5,
         "HardwareName" : "DUMMY_VIRTUAL",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "00015285",
         "Image" : "Push",
         "InternalState" : "On",
         "IsSubDevice" : false,
         "LastUpdate" : "2023-03-26 01:46:01",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 100,
         "Name" : "? CDE VMC HIVER(Auto)",
         "Notifications" : "false",
         "PlanID" : "10",
         "PlanIDs" : 
         [
            10
         ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Switch",
         "SwitchType" : "Push On Button",
         "SwitchTypeVal" : 9,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "push",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "235",
         "YOffset" : "22",
         "idx" : "4661"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "On",
         "Description" : "Alexa_Name:VENTILATION ETE",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareDisabled" : false,
         "HardwareID" : 5,
         "HardwareName" : "DUMMY_VIRTUAL",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "00015284",
         "Image" : "Push",
         "InternalState" : "On",
         "IsSubDevice" : false,
         "LastUpdate" : "2023-01-01 09:40:58",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 100,
         "Name" : "? CDE VMC ETE(Auto)",
         "Notifications" : "false",
         "PlanID" : "10",
         "PlanIDs" : 
         [
            10
         ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Switch",
         "SwitchType" : "Push On Button",
         "SwitchTypeVal" : 9,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "push",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "235",
         "YOffset" : "0",
         "idx" : "4660"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "On",
         "Description" : "Alexa_Name:VENTILATION MAXI",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareDisabled" : false,
         "HardwareID" : 5,
         "HardwareName" : "DUMMY_VIRTUAL",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "00015286",
         "Image" : "Push",
         "InternalState" : "On",
         "IsSubDevice" : false,
         "LastUpdate" : "2022-11-24 10:07:41",
         "Level" : 100,
         "LevelInt" : 100,
         "MaxDimLevel" : 100,
         "Name" : "? CDE VMC MAXI(Manu)",
         "Notifications" : "false",
         "PlanID" : "10",
         "PlanIDs" : 
         [
            10
         ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Switch",
         "SwitchType" : "Push On Button",
         "SwitchTypeVal" : 9,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "push",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "221",
         "YOffset" : "0",
         "idx" : "4662"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "On",
         "Description" : "Alexa_Name:VENTILATION MINI",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareDisabled" : false,
         "HardwareID" : 5,
         "HardwareName" : "DUMMY_VIRTUAL",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "00015287",
         "Image" : "Push",
         "InternalState" : "On",
         "IsSubDevice" : false,
         "LastUpdate" : "2023-03-17 12:51:08",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 100,
         "Name" : "? CDE VMC MINI(Manu)",
         "Notifications" : "false",
         "PlanID" : "10",
         "PlanIDs" : 
         [
            10
         ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Switch",
         "SwitchType" : "Push On Button",
         "SwitchTypeVal" : 9,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "push",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "222",
         "YOffset" : "22",
         "idx" : "4663"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 100,
         "CustomImage" : 0,
         "Data" : "15.7 C, 52 %",
         "Description" : "Alexa_Name: Atelier",
         "DewPoint" : "5.87",
         "Favorite" : 0,
         "HardwareDisabled" : false,
         "HardwareID" : 2,
         "HardwareName" : "RFXCOM",
         "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
         "HardwareTypeVal" : 1,
         "HaveTimeout" : false,
         "Humidity" : 52,
         "HumidityStatus" : "Normal",
         "ID" : "0104",
         "LastUpdate" : "2023-04-08 13:00:20",
         "Name" : "T-H ATELIER",
         "Notifications" : "false",
         "PlanID" : "13",
         "PlanIDs" : 
         [
            13
         ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : 6,
         "SubType" : "THGR810, THGN800",
         "Temp" : 15.699999999999999,
         "Timers" : "false",
         "Type" : "Temp + Humidity",
         "TypeImg" : "temperature",
         "Unit" : 4,
         "Used" : 1,
         "XOffset" : "374",
         "YOffset" : "369",
         "idx" : "4802",
         "trend" : 1
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 100,
         "CustomImage" : 0,
         "Data" : "20.8 C, 38 %",
         "Description" : "Alexa_Name: Dressing",
         "DewPoint" : "5.96",
         "Favorite" : 0,
         "HardwareDisabled" : false,
         "HardwareID" : 2,
         "HardwareName" : "RFXCOM",
         "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
         "HardwareTypeVal" : 1,
         "HaveTimeout" : false,
         "Humidity" : 38,
         "HumidityStatus" : "Dry",
         "ID" : "F801",
         "LastUpdate" : "2023-04-08 13:00:23",
         "Name" : "T-H DRESSING NAS",
         "Notifications" : "false",
         "PlanID" : "17",
         "PlanIDs" : 
         [
            17
         ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : 7,
         "SubType" : "THGN122/123/132, THGR122/228/238/268",
         "Temp" : 20.800000000000001,
         "Timers" : "false",
         "Type" : "Temp + Humidity",
         "TypeImg" : "temperature",
         "Unit" : 1,
         "Used" : 1,
         "XOffset" : "306",
         "YOffset" : "191",
         "idx" : "4829",
         "trend" : 2
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 9,
         "Data" : "On",
         "Description" : "Alexa_Name:Chauffage Sud",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareDisabled" : false,
         "HardwareID" : 5,
         "HardwareName" : "DUMMY_VIRTUAL",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "000153C5",
         "Image" : "Generic",
         "IsSubDevice" : false,
         "LastUpdate" : "2023-04-07 21:17:22",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 100,
         "Name" : "Chauffage sud",
         "Notifications" : "false",
         "PlanID" : "4",
         "PlanIDs" : 
         [
            4
         ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "On",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Switch",
         "SwitchType" : "On/Off",
         "SwitchTypeVal" : 0,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "lightbulb",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "459",
         "YOffset" : "429",
         "idx" : "4981"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "Off",
         "Description" : "Alexa_Name:Test",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareDisabled" : false,
         "HardwareID" : 5,
         "HardwareName" : "DUMMY_VIRTUAL",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "000153C6",
         "Image" : "Light",
         "IsSubDevice" : false,
         "LastUpdate" : "2023-04-01 22:26:08",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 100,
         "Name" : "Test",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : 
         [
            0
         ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Switch",
         "SwitchType" : "On/Off",
         "SwitchTypeVal" : 0,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "lightbulb",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "4982"
      }
   ],
   "status" : "OK",
   "title" : "Devices"
});