exports.DOMOTICZ_GET_DEVICES = JSON.stringify({
   "ActTime" : 1557822986,
   "AstrTwilightEnd" : "22:57",
   "AstrTwilightStart" : "04:12",
   "CivTwilightEnd" : "21:28",
   "CivTwilightStart" : "05:41",
   "DayLength" : "14:41",
   "NautTwilightEnd" : "22:10",
   "NautTwilightStart" : "04:60",
   "ServerTime" : "2019-05-14 10:36:26",
   "SunAtSouth" : "13:35",
   "Sunrise" : "06:14",
   "Sunset" : "20:55",
   "app_version" : "4.10717",
   "result" : [
      {
         "Data" : "Mixed",
         "Description" : "",
         "Favorite" : 1,
         "LastUpdate" : "2019-04-17 20:54:42",
         "Name" : "Invités à la maison",
         "PlanID" : "",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "Status" : "Mixed",
         "Type" : "Scene",
         "TypeImg" : "scene",
         "UsedByCamera" : false,
         "XOffset" : 0,
         "YOffset" : 0,
         "idx" : "2"
      },
      {
         "Data" : "Off",
         "Description" : "",
         "Favorite" : 1,
         "LastUpdate" : "2019-05-14 00:59:43",
         "Name" : "Au dodo",
         "PlanID" : "",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "Status" : "Off",
         "Type" : "Scene",
         "TypeImg" : "scene",
         "UsedByCamera" : false,
         "XOffset" : 0,
         "YOffset" : 0,
         "idx" : "3"
      },
      {
         "Data" : "Off",
         "Description" : "",
         "Favorite" : 1,
         "LastUpdate" : "2019-05-11 21:01:12",
         "Name" : "Lampe Escalier",
         "PlanID" : "",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "Status" : "Off",
         "Type" : "Group",
         "TypeImg" : "group",
         "UsedByCamera" : false,
         "XOffset" : 0,
         "YOffset" : 0,
         "idx" : "5"
      },
      {
         "Data" : "On",
         "Description" : "",
         "Favorite" : 1,
         "LastUpdate" : "2019-04-27 08:48:08",
         "Name" : "VMC",
         "PlanID" : "",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "Status" : "On",
         "Type" : "Scene",
         "TypeImg" : "scene",
         "UsedByCamera" : false,
         "XOffset" : 0,
         "YOffset" : 0,
         "idx" : "6"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 151,
         "Data" : "Set Level: 20 %",
         "Description" : "Désigne le mode de gestion des consignes aux thermostats de chauffage",
         "DimmerType" : "none",
         "Favorite" : 1,
         "HardwareID" : 3,
         "HardwareName" : "Periph Virtuels",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "00014069",
         "Image" : "Th-Chauffage",
         "IsSubDevice" : false,
         "LastUpdate" : "2019-05-11 10:13:15",
         "Level" : 20,
         "LevelActions" : "fHx8",
         "LevelInt" : 20,
         "LevelNames" : "T2ZmfEVjb3xDb25mb3J0fE51aXQ=",
         "LevelOffHidden" : false,
         "MaxDimLevel" : 100,
         "Name" : "Mode Chauffage",
         "Notifications" : "true",
         "PlanID" : "9",
         "PlanIDs" : [ 9 ],
         "Protected" : true,
         "SelectorStyle" : 0,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Set Level: 20 %",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Selector Switch",
         "SwitchType" : "Selector",
         "SwitchTypeVal" : 18,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "Light",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "25"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 146,
         "Data" : "Set Level: 20 %",
         "Description" : "Spécifie le mode de gestion de la VMC (OFF; pilotage par l'hygrométrie de la salle de bain; Automatique Hygro + gestion de la température; mode forcé)",
         "DimmerType" : "none",
         "Favorite" : 1,
         "HardwareID" : 3,
         "HardwareName" : "Periph Virtuels",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "00014057",
         "Image" : "Th-VMC",
         "IsSubDevice" : false,
         "LastUpdate" : "2019-05-14 08:43:18",
         "Level" : 20,
         "LevelActions" : "fHx8fA==",
         "LevelInt" : 20,
         "LevelNames" : "T2ZmfEh5Z3JvIFNEQnxBdXRvfDFIfEZvcmPDqQ==",
         "LevelOffHidden" : false,
         "MaxDimLevel" : 100,
         "Name" : "Mode VMC",
         "Notifications" : "false",
         "PlanID" : "9",
         "PlanIDs" : [ 9 ],
         "Protected" : false,
         "SelectorStyle" : 0,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Set Level: 20 %",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Selector Switch",
         "SwitchType" : "Selector",
         "SwitchTypeVal" : 18,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "Light",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "7"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 164,
         "Data" : "Off",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 1,
         "HardwareID" : 9,
         "HardwareName" : "Zwave plus",
         "HardwareType" : "OpenZWave USB",
         "HardwareTypeVal" : 21,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "00001A01",
         "Image" : "VMC",
         "IsSubDevice" : false,
         "LastUpdate" : "2019-05-14 07:13:54",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 100,
         "Name" : "VMC",
         "Notifications" : "false",
         "PlanID" : "14",
         "PlanIDs" : [ 14 ],
         "Protected" : true,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Switch",
         "SwitchType" : "On/Off",
         "SwitchTypeVal" : 0,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "lightbulb",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "211"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 160,
         "Data" : "Set Level: 10 %",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 1,
         "HardwareID" : 3,
         "HardwareName" : "Periph Virtuels",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "00014068",
         "Image" : "Tempo",
         "IsSubDevice" : false,
         "LastUpdate" : "2019-05-14 06:10:01",
         "Level" : 10,
         "LevelActions" : "fHx8",
         "LevelInt" : 10,
         "LevelNames" : "T2ZmfEJsZXV8QmxhbmN8Um91Z2U=",
         "LevelOffHidden" : true,
         "MaxDimLevel" : 100,
         "Name" : "InfoTempo",
         "Notifications" : "false",
         "PlanID" : "9",
         "PlanIDs" : [ 9 ],
         "Protected" : true,
         "SelectorStyle" : 0,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Set Level: 10 %",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Selector Switch",
         "SwitchType" : "Selector",
         "SwitchTypeVal" : 18,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "Light",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "24"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 161,
         "Data" : "Off",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 1,
         "HardwareID" : 3,
         "HardwareName" : "Periph Virtuels",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "00014070",
         "Image" : "Tempo-demain",
         "IsSubDevice" : false,
         "LastUpdate" : "2019-05-14 00:00:01",
         "Level" : 0,
         "LevelActions" : "fHx8",
         "LevelInt" : 0,
         "LevelNames" : "T2ZmfEJsZXV8QmxhbmN8Um91Z2U=",
         "LevelOffHidden" : false,
         "MaxDimLevel" : 100,
         "Name" : "DemainTempo",
         "Notifications" : "true",
         "PlanID" : "9",
         "PlanIDs" : [ 9 ],
         "Protected" : true,
         "SelectorStyle" : 1,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Selector Switch",
         "SwitchType" : "Selector",
         "SwitchTypeVal" : 18,
         "Timers" : "true",
         "Type" : "Light/Switch",
         "TypeImg" : "Light",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "32"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 159,
         "Data" : "Off",
         "Description" : "Indique le type de facturation Heure CREUSE ou Heure PLEINE",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareID" : 3,
         "HardwareName" : "Periph Virtuels",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "00014062",
         "Image" : "HP-HC",
         "IsSubDevice" : false,
         "LastUpdate" : "2019-05-14 06:00:36",
         "Level" : 100,
         "LevelInt" : 100,
         "MaxDimLevel" : 100,
         "Name" : "Heures Creuses",
         "Notifications" : "false",
         "PlanID" : "9",
         "PlanIDs" : [ 9 ],
         "Protected" : true,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Switch",
         "SwitchType" : "On/Off",
         "SwitchTypeVal" : 0,
         "Timers" : "true",
         "Type" : "Light/Switch",
         "TypeImg" : "lightbulb",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "18"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 167,
         "Data" : "Off",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareID" : 3,
         "HardwareName" : "Periph Virtuels",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "000140FB",
         "Image" : "Invites",
         "IsSubDevice" : false,
         "LastUpdate" : "2019-01-11 21:41:08",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 100,
         "Name" : "Invités",
         "Notifications" : "false",
         "PlanID" : "9",
         "PlanIDs" : [ 9 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Switch",
         "SwitchType" : "On/Off",
         "SwitchTypeVal" : 0,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "lightbulb",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "171"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 147,
         "Data" : "Off",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareID" : 3,
         "HardwareName" : "Periph Virtuels",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "0001406F",
         "Image" : "Absent2",
         "IsSubDevice" : true,
         "LastUpdate" : "2019-01-12 18:01:31",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 100,
         "Name" : "Mode Absence",
         "Notifications" : "true",
         "PlanID" : "9",
         "PlanIDs" : [ 9 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Switch",
         "SwitchType" : "On/Off",
         "SwitchTypeVal" : 0,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "lightbulb",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "31"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 104,
         "Data" : "Off",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareID" : 3,
         "HardwareName" : "Periph Virtuels",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "00014071",
         "Image" : "Vacances",
         "IsSubDevice" : false,
         "LastUpdate" : "2019-05-14 00:10:02",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 100,
         "Name" : "Weekend",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Selector Switch",
         "SwitchType" : "On/Off",
         "SwitchTypeVal" : 0,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "lightbulb",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "33"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 104,
         "Data" : "Off",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareID" : 3,
         "HardwareName" : "Periph Virtuels",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "000140D5",
         "Image" : "Vacances",
         "IsSubDevice" : false,
         "LastUpdate" : "2019-05-11 13:07:35",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 100,
         "Name" : "Congés",
         "Notifications" : "false",
         "PlanID" : "9",
         "PlanIDs" : [ 9 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "aHR0cDovLzE5Mi4xNjguMC4xMC8/bWVzc2FnZT1Nb2RlJTIwY29uZyVDMyVBOXMlMjBBY3RpdiVDMyVBOSZpbnRlbnNpdHk9MTAmc3BlZWQ9NTAmc3RhdGljPTA=",
         "StrParam2" : "aHR0cDovLzE5Mi4xNjguMC4xMC8/bWVzc2FnZT1Nb2RlJTIwY29uZyVDMyVBOXMlMjBEJUMzJUE5c2FjdGl2JUMzJUE5JmludGVuc2l0eT0xMCZzcGVlZD01MCZzdGF0aWM9MA==",
         "SubType" : "Switch",
         "SwitchType" : "On/Off",
         "SwitchTypeVal" : 0,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "lightbulb",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "133"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 163,
         "Data" : "Off",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareID" : 3,
         "HardwareName" : "Periph Virtuels",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "0001406E",
         "Image" : "VacS",
         "IsSubDevice" : false,
         "LastUpdate" : "2019-05-14 00:02:00",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 100,
         "Name" : "Vacances Scolaires",
         "Notifications" : "false",
         "PlanID" : "9",
         "PlanIDs" : [ 9 ],
         "Protected" : true,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Switch",
         "SwitchType" : "On/Off",
         "SwitchTypeVal" : 0,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "lightbulb",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "30"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 169,
         "Data" : "Closed",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareID" : 3,
         "HardwareName" : "Periph Virtuels",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "000140FE",
         "Image" : "Feu-Rouge",
         "InternalState" : "Closed",
         "IsSubDevice" : false,
         "LastUpdate" : "2019-05-14 08:27:54",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 100,
         "Name" : "Maison Fermée",
         "Notifications" : "false",
         "PlanID" : "9",
         "PlanIDs" : [ 9 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Closed",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Switch",
         "SwitchType" : "Door Contact",
         "SwitchTypeVal" : 11,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "door",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "174"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 171,
         "Data" : "On",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareID" : 3,
         "HardwareName" : "Periph Virtuels",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "000140A6",
         "Image" : "Saison2",
         "IsSubDevice" : false,
         "LastUpdate" : "2019-05-01 00:01:04",
         "Level" : 100,
         "LevelInt" : 100,
         "MaxDimLevel" : 100,
         "Name" : "Ete",
         "Notifications" : "false",
         "PlanID" : "9",
         "PlanIDs" : [ 9 ],
         "Protected" : true,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "On",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Switch",
         "SwitchType" : "On/Off",
         "SwitchTypeVal" : 0,
         "Timers" : "true",
         "Type" : "Light/Switch",
         "TypeImg" : "lightbulb",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "86"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 70.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "Off",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 1,
         "HardwareID" : 3,
         "HardwareName" : "Periph Virtuels",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "00014179",
         "Image" : "Light",
         "IsSubDevice" : false,
         "LastUpdate" : "2019-05-14 08:28:42",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 100,
         "Name" : "Mouvement Maison",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Switch",
         "SwitchType" : "Motion Sensor",
         "SwitchTypeVal" : 8,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "motion",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "297"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 166,
         "Data" : "Off",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareID" : 3,
         "HardwareName" : "Periph Virtuels",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "00014120",
         "Image" : "onoff",
         "IsSubDevice" : false,
         "LastUpdate" : "2019-05-14 10:36:00",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 100,
         "Name" : "Lumière garage AUTO",
         "Notifications" : "false",
         "PlanID" : "2",
         "PlanIDs" : [ 2 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Switch",
         "SwitchType" : "On/Off",
         "SwitchTypeVal" : 0,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "lightbulb",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "272",
         "YOffset" : "258",
         "idx" : "208"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 12,
         "CustomImage" : 102,
         "Data" : "Closed",
         "Description" : "Contacteur de porte d'entrée",
         "DimmerType" : "none",
         "Favorite" : 1,
         "HardwareID" : 9,
         "HardwareName" : "Zwave plus",
         "HardwareType" : "OpenZWave USB",
         "HardwareTypeVal" : 21,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "00000800",
         "Image" : "Entree",
         "InternalState" : "Closed",
         "IsSubDevice" : false,
         "LastUpdate" : "2019-05-14 08:27:54",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 100,
         "Name" : "Porte Entrée",
         "Notifications" : "false",
         "PlanID" : "3",
         "PlanIDs" : [ 3 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Closed",
         "StrParam1" : "aHR0cDovLzE5Mi4xNjguMC4xMC8/bWVzc2FnZT1Qb3J0ZSUyMGQlMjdlbnRyJUMzJUE5ZSUyMG91dmVydGUmaW50ZW5zaXR5PTEwJnNwZWVkPTUwJnN0YXRpYz0w",
         "StrParam2" : "aHR0cDovLzE5Mi4xNjguMC4xMC8/aW50ZW5zaXR5PTEmc3BlZWQ9NDAmbG9jYWw9MCZzdGF0aWM9MQ==",
         "SubType" : "Switch",
         "SwitchType" : "Door Contact",
         "SwitchTypeVal" : 11,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "door",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "57",
         "YOffset" : "346",
         "idx" : "76"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 100,
         "CustomImage" : 103,
         "Data" : "Closed",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 1,
         "HardwareID" : 9,
         "HardwareName" : "Zwave plus",
         "HardwareType" : "OpenZWave USB",
         "HardwareTypeVal" : 21,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "00000C34",
         "Image" : "Porte",
         "InternalState" : "Closed",
         "IsSubDevice" : false,
         "LastUpdate" : "2019-05-14 09:36:10",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 100,
         "Name" : "Porte Garage",
         "Notifications" : "false",
         "PlanID" : "2",
         "PlanIDs" : [ 2, 3 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Closed",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Switch",
         "SwitchType" : "Door Contact",
         "SwitchTypeVal" : 11,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "door",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "183",
         "YOffset" : "253",
         "idx" : "112"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 65,
         "CustomImage" : 118,
         "Data" : "Closed",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 1,
         "HardwareID" : 9,
         "HardwareName" : "Zwave plus",
         "HardwareType" : "OpenZWave USB",
         "HardwareTypeVal" : 21,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "00000D00",
         "Image" : "garage",
         "InternalState" : "Closed",
         "IsSubDevice" : false,
         "LastUpdate" : "2019-05-12 11:15:07",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 100,
         "Name" : "Portail Garage",
         "Notifications" : "false",
         "PlanID" : "2",
         "PlanIDs" : [ 2 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Closed",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Switch",
         "SwitchType" : "Door Contact",
         "SwitchTypeVal" : 11,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "door",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "120",
         "YOffset" : "142",
         "idx" : "121"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 153,
         "Data" : "Off",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 1,
         "HardwareID" : 9,
         "HardwareName" : "Zwave plus",
         "HardwareType" : "OpenZWave USB",
         "HardwareTypeVal" : 21,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "00000F01",
         "Image" : "Chevet-rouge",
         "IsSubDevice" : false,
         "LastUpdate" : "2019-05-14 01:01:13",
         "Level" : 99,
         "LevelInt" : 99,
         "MaxDimLevel" : 100,
         "Name" : "Lumière Oeuf",
         "Notifications" : "false",
         "PlanID" : "4",
         "PlanIDs" : [ 4 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Switch",
         "SwitchType" : "On/Off",
         "SwitchTypeVal" : 0,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "lightbulb",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "128"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 103,
         "Data" : "Open",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 1,
         "HardwareID" : 9,
         "HardwareName" : "Zwave plus",
         "HardwareType" : "OpenZWave USB",
         "HardwareTypeVal" : 21,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "00002100",
         "Image" : "Porte",
         "InternalState" : "Open",
         "IsSubDevice" : false,
         "LastUpdate" : "2019-05-14 08:15:57",
         "Level" : 255,
         "LevelInt" : 255,
         "MaxDimLevel" : 100,
         "Name" : "Porte Salle de Bain",
         "Notifications" : "false",
         "PlanID" : "14",
         "PlanIDs" : [ 14 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Open",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Switch",
         "SwitchType" : "Door Contact",
         "SwitchTypeVal" : 11,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "door",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "287"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 157,
         "Data" : "Off",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 1,
         "HardwareID" : 3,
         "HardwareName" : "Periph Virtuels",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "000140DC",
         "Image" : "seche-serviette2",
         "IsSubDevice" : false,
         "LastUpdate" : "2019-05-14 07:36:34",
         "Level" : 0,
         "LevelActions" : "fHx8fHw=",
         "LevelInt" : 0,
         "LevelNames" : "T2ZmfEhvcnMgR2VsfEVjb3xDb25mb3J0IC0ywrBjfENvbmZvcnQgLTHCsGN8Q29uZm9ydA==",
         "LevelOffHidden" : false,
         "MaxDimLevel" : 100,
         "Name" : "Radiateur Salle de Bain",
         "Notifications" : "false",
         "PlanID" : "12",
         "PlanIDs" : [ 12, 14 ],
         "Protected" : false,
         "SelectorStyle" : 1,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Selector Switch",
         "SwitchType" : "Selector",
         "SwitchTypeVal" : 18,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "Light",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "140"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 108,
         "Data" : "Off",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 1,
         "HardwareID" : 9,
         "HardwareName" : "Zwave plus",
         "HardwareType" : "OpenZWave USB",
         "HardwareTypeVal" : 21,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "00002702",
         "Image" : "neon",
         "IsSubDevice" : false,
         "LastUpdate" : "2019-05-14 10:36:00",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 100,
         "Name" : "Lumière Garage Circulation",
         "Notifications" : "false",
         "PlanID" : "2",
         "PlanIDs" : [ 2 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Switch",
         "SwitchType" : "On/Off",
         "SwitchTypeVal" : 0,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "lightbulb",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "342"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 109,
         "Data" : "Off",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 1,
         "HardwareID" : 9,
         "HardwareName" : "Zwave plus",
         "HardwareType" : "OpenZWave USB",
         "HardwareTypeVal" : 21,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "00002703",
         "Image" : "Neon2",
         "IsSubDevice" : false,
         "LastUpdate" : "2019-05-13 22:21:06",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 100,
         "Name" : "Lumière Garage Travail",
         "Notifications" : "false",
         "PlanID" : "2",
         "PlanIDs" : [ 2 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Switch",
         "SwitchType" : "On/Off",
         "SwitchTypeVal" : 0,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "lightbulb",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "343"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 174,
         "Data" : "Off",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 1,
         "HardwareID" : 9,
         "HardwareName" : "Zwave plus",
         "HardwareType" : "OpenZWave USB",
         "HardwareTypeVal" : 21,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "00001C01",
         "Image" : "Etablis",
         "IsSubDevice" : false,
         "LastUpdate" : "2019-05-14 10:36:00",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 100,
         "Name" : "Lumière Etablis",
         "Notifications" : "false",
         "PlanID" : "2",
         "PlanIDs" : [ 2 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Switch",
         "SwitchType" : "On/Off",
         "SwitchTypeVal" : 0,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "lightbulb",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "587",
         "YOffset" : "331",
         "idx" : "231"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 172,
         "Data" : "Off",
         "Description" : "S1 relais Compresseur",
         "DimmerType" : "none",
         "Favorite" : 1,
         "HardwareID" : 9,
         "HardwareName" : "Zwave plus",
         "HardwareType" : "OpenZWave USB",
         "HardwareTypeVal" : 21,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "00002001",
         "Image" : "Compresseur",
         "IsSubDevice" : false,
         "LastUpdate" : "2019-05-13 19:48:04",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 100,
         "Name" : "Compresseur",
         "Notifications" : "false",
         "PlanID" : "2",
         "PlanIDs" : [ 2 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Switch",
         "SwitchType" : "On/Off",
         "SwitchTypeVal" : 0,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "lightbulb",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "932",
         "YOffset" : "363",
         "idx" : "270"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 173,
         "Data" : "Off",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 1,
         "HardwareID" : 9,
         "HardwareName" : "Zwave plus",
         "HardwareType" : "OpenZWave USB",
         "HardwareTypeVal" : 21,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "00001401",
         "Image" : "PR3D",
         "IsSubDevice" : false,
         "LastUpdate" : "2019-02-25 12:09:28",
         "Level" : 100,
         "LevelInt" : 100,
         "MaxDimLevel" : 100,
         "Name" : "Imprimante 3D",
         "Notifications" : "false",
         "PlanID" : "2",
         "PlanIDs" : [ 2 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Switch",
         "SwitchType" : "On/Off",
         "SwitchTypeVal" : 0,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "lightbulb",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "662",
         "YOffset" : "30",
         "idx" : "149"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : -1.0,
         "AddjValue2" : 0.0,
         "Barometer" : 1018,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "16.8 C, 39 %, 1018 hPa",
         "Description" : "",
         "DewPoint" : "2.76",
         "Favorite" : 1,
         "Forecast" : 1,
         "ForecastStr" : "Sunny",
         "HardwareID" : 12,
         "HardwareName" : "Météo Villelaure",
         "HardwareType" : "DarkSky (Weather Lookup)",
         "HardwareTypeVal" : 25,
         "HaveTimeout" : false,
         "Humidity" : 39,
         "HumidityStatus" : "Comfortable",
         "ID" : "0001",
         "LastUpdate" : "2019-05-14 10:36:11",
         "Name" : "Temp/Baro Villelaure",
         "Notifications" : "false",
         "PlanID" : "10",
         "PlanIDs" : [ 10 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "THB1 - BTHR918, BTHGN129",
         "Temp" : 16.800000000000001,
         "Timers" : "false",
         "Type" : "Temp + Humidity + Baro",
         "TypeImg" : "temperature",
         "Unit" : 1,
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "198",
         "forecast_url" : "aHR0cHM6Ly9kYXJrc2t5Lm5ldC8jL2YvNDMuNzExNzMxJTJDJTIwNS40MjQwMDM=",
         "idx" : "298",
         "trend" : 2
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : -1.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "Chill" : 16.800000000000001,
         "CustomImage" : 0,
         "Data" : "310.00;NW;37;54;16.8;16.8",
         "Description" : "",
         "Direction" : 310.0,
         "DirectionStr" : "NW",
         "Favorite" : 1,
         "Gust" : "19.4",
         "HardwareID" : 12,
         "HardwareName" : "Météo Villelaure",
         "HardwareType" : "DarkSky (Weather Lookup)",
         "HardwareTypeVal" : 25,
         "HaveTimeout" : false,
         "ID" : "0001",
         "LastUpdate" : "2019-05-14 10:36:11",
         "Name" : "Vent Villelaure",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Speed" : "13.3",
         "SubType" : "TFA",
         "Temp" : 16.800000000000001,
         "Timers" : "false",
         "Type" : "Wind",
         "TypeImg" : "wind",
         "Unit" : 0,
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "forecast_url" : "aHR0cHM6Ly9kYXJrc2t5Lm5ldC8jL2YvNDMuNzExNzMxJTJDJTIwNS40MjQwMDM=",
         "idx" : "299",
         "trend" : 2
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "10.9 km",
         "Description" : "",
         "Favorite" : 1,
         "HardwareID" : 12,
         "HardwareName" : "Météo Villelaure",
         "HardwareType" : "DarkSky (Weather Lookup)",
         "HardwareTypeVal" : 25,
         "HaveTimeout" : false,
         "ID" : "0",
         "LastUpdate" : "2019-05-14 10:36:11",
         "Name" : "Visibilité Villelaure",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "Visibility",
         "SwitchTypeVal" : 0,
         "Timers" : "false",
         "Type" : "General",
         "TypeImg" : "visibility",
         "Unit" : 1,
         "Used" : 1,
         "Visibility" : 10.9,
         "XOffset" : "0",
         "YOffset" : "0",
         "forecast_url" : "aHR0cHM6Ly9kYXJrc2t5Lm5ldC8jL2YvNDMuNzExNzMxJTJDJTIwNS40MjQwMDM=",
         "idx" : "302"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 9,
         "Data" : "Off",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 1,
         "HardwareID" : 3,
         "HardwareName" : "Periph Virtuels",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "00014172",
         "Image" : "Generic",
         "IsSubDevice" : false,
         "LastUpdate" : "2018-12-31 16:22:44",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 100,
         "Name" : "Arrêt auto 3D",
         "Notifications" : "false",
         "PlanID" : "2",
         "PlanIDs" : [ 2 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Switch",
         "SwitchType" : "On/Off",
         "SwitchTypeVal" : 0,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "lightbulb",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "736",
         "YOffset" : "30",
         "idx" : "290"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 100,
         "CustomImage" : 0,
         "Data" : "Off",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareID" : 9,
         "HardwareName" : "Zwave plus",
         "HardwareType" : "OpenZWave USB",
         "HardwareTypeVal" : 21,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "00000C00",
         "Image" : "Light",
         "IsSubDevice" : false,
         "LastUpdate" : "2019-05-14 08:28:03",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 100,
         "Name" : "Détecteur de mouvement Entrée",
         "Notifications" : "true",
         "PlanID" : "3",
         "PlanIDs" : [ 3 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Switch",
         "SwitchType" : "Motion Sensor",
         "SwitchTypeVal" : 8,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "motion",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "230",
         "YOffset" : "415",
         "idx" : "111"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 100,
         "CustomImage" : 0,
         "Data" : "Off",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareID" : 9,
         "HardwareName" : "Zwave plus",
         "HardwareType" : "OpenZWave USB",
         "HardwareTypeVal" : 21,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "00001300",
         "Image" : "Light",
         "IsSubDevice" : false,
         "LastUpdate" : "2019-05-14 07:51:49",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 100,
         "Name" : "Détecteur de mouvement Garage",
         "Notifications" : "false",
         "PlanID" : "2",
         "PlanIDs" : [ 2 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Switch",
         "SwitchType" : "Motion Sensor",
         "SwitchTypeVal" : 8,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "motion",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "376",
         "YOffset" : "172",
         "idx" : "144"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 66,
         "CustomImage" : 0,
         "Data" : "Off",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareID" : 9,
         "HardwareName" : "Zwave plus",
         "HardwareType" : "OpenZWave USB",
         "HardwareTypeVal" : 21,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "00000900",
         "Image" : "Light",
         "IsSubDevice" : false,
         "LastUpdate" : "2019-05-14 08:27:10",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 100,
         "Name" : "Détecteur de mouvement Cuisine",
         "Notifications" : "false",
         "PlanID" : "4",
         "PlanIDs" : [ 4 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Switch",
         "SwitchType" : "Motion Sensor",
         "SwitchTypeVal" : 8,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "motion",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "89"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 158,
         "Data" : "Off",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareID" : 9,
         "HardwareName" : "Zwave plus",
         "HardwareType" : "OpenZWave USB",
         "HardwareTypeVal" : 21,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "0000152D",
         "Image" : "Inondation",
         "IsSubDevice" : false,
         "LastUpdate" : "2019-05-14 00:58:51",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 100,
         "Name" : "Inondation Garage",
         "Notifications" : "false",
         "PlanID" : "2",
         "PlanIDs" : [ 2 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Switch",
         "SwitchType" : "On/Off",
         "SwitchTypeVal" : 0,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "lightbulb",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "886",
         "YOffset" : "415",
         "idx" : "161"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "54 Lux",
         "Description" : "",
         "Favorite" : 1,
         "HardwareID" : 9,
         "HardwareName" : "Zwave plus",
         "HardwareType" : "OpenZWave USB",
         "HardwareTypeVal" : 21,
         "HaveTimeout" : false,
         "ID" : "0000903",
         "LastUpdate" : "2019-05-14 10:32:07",
         "Name" : "Luminosité Cuisine",
         "Notifications" : "false",
         "PlanID" : "4",
         "PlanIDs" : [ 4 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "Lux",
         "Timers" : "false",
         "Type" : "Lux",
         "TypeImg" : "lux",
         "Unit" : 255,
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "92"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 100,
         "CustomImage" : 0,
         "Data" : "80 Lux",
         "Description" : "",
         "Favorite" : 1,
         "HardwareID" : 9,
         "HardwareName" : "Zwave plus",
         "HardwareType" : "OpenZWave USB",
         "HardwareTypeVal" : 21,
         "HaveTimeout" : false,
         "ID" : "0000C03",
         "LastUpdate" : "2019-05-14 10:34:28",
         "Name" : "Luminosité Entrée",
         "Notifications" : "false",
         "PlanID" : "3",
         "PlanIDs" : [ 3 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "Lux",
         "Timers" : "false",
         "Type" : "Lux",
         "TypeImg" : "lux",
         "Unit" : 255,
         "Used" : 1,
         "XOffset" : "186",
         "YOffset" : "417",
         "idx" : "115"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 100,
         "CustomImage" : 0,
         "Data" : "0 Lux",
         "Description" : "",
         "Favorite" : 1,
         "HardwareID" : 9,
         "HardwareName" : "Zwave plus",
         "HardwareType" : "OpenZWave USB",
         "HardwareTypeVal" : 21,
         "HaveTimeout" : true,
         "ID" : "0001303",
         "LastUpdate" : "2019-05-14 07:57:49",
         "Name" : "Luminosité Garage",
         "Notifications" : "false",
         "PlanID" : "2",
         "PlanIDs" : [ 2 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "Lux",
         "Timers" : "false",
         "Type" : "Lux",
         "TypeImg" : "lux",
         "Unit" : 255,
         "Used" : 1,
         "XOffset" : "378",
         "YOffset" : "77",
         "idx" : "147"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "351.12 DU",
         "Description" : "",
         "Favorite" : 0,
         "HardwareID" : 12,
         "HardwareName" : "Météo Villelaure",
         "HardwareType" : "DarkSky (Weather Lookup)",
         "HardwareTypeVal" : 25,
         "HaveTimeout" : false,
         "ID" : "00000100",
         "Image" : "Custom",
         "LastUpdate" : "2019-05-14 10:36:11",
         "Name" : "Ozone Villelaure",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "SensorType" : 1,
         "SensorUnit" : "DU",
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "Custom Sensor",
         "Timers" : "false",
         "Type" : "General",
         "TypeImg" : "Custom",
         "Unit" : 1,
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "forecast_url" : "aHR0cHM6Ly9kYXJrc2t5Lm5ldC8jL2YvNDMuNzExNzMxJTJDJTIwNS40MjQwMDM=",
         "idx" : "303"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "10.0",
         "Description" : "",
         "Favorite" : 1,
         "HardwareID" : 3,
         "HardwareName" : "Periph Virtuels",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveTimeout" : true,
         "ID" : "0014076",
         "LastUpdate" : "2019-05-14 08:00:01",
         "Name" : "Thermostat Salle de Bain",
         "Notifications" : "false",
         "PlanID" : "12",
         "PlanIDs" : [ 12, 14 ],
         "Protected" : false,
         "SetPoint" : "10.0",
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "SetPoint",
         "Timers" : "false",
         "Type" : "Thermostat",
         "TypeImg" : "override_mini",
         "Unit" : 1,
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "38"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 120,
         "Data" : "Off",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 1,
         "HardwareID" : 5,
         "HardwareName" : "GPIO domoticz",
         "HardwareType" : "Raspberry's GPIO port",
         "HardwareTypeVal" : 32,
         "HaveDimmer" : false,
         "HaveGroupCmd" : false,
         "HaveTimeout" : false,
         "ID" : "0",
         "Image" : "led_blue",
         "IsSubDevice" : false,
         "LastUpdate" : "2019-01-12 18:01:31",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 0,
         "Name" : "Voyant Absent",
         "Notifications" : "false",
         "PlanID" : "15",
         "PlanIDs" : [ 15 ],
         "Protected" : true,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Impuls",
         "SwitchType" : "On/Off",
         "SwitchTypeVal" : 0,
         "Timers" : "false",
         "Type" : "Lighting 1",
         "TypeImg" : "lightbulb",
         "Unit" : 4,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "43"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 100,
         "CustomImage" : 0,
         "Data" : "18.9 C",
         "Description" : "",
         "Favorite" : 1,
         "HardwareID" : 9,
         "HardwareName" : "Zwave plus",
         "HardwareType" : "OpenZWave USB",
         "HardwareTypeVal" : 21,
         "HaveTimeout" : true,
         "ID" : "0C01",
         "LastUpdate" : "2019-05-14 08:27:32",
         "Name" : "Entrée",
         "Notifications" : "true",
         "PlanID" : "3",
         "PlanIDs" : [ 3, 9, 12 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "LaCrosse TX3",
         "Temp" : 18.899999999999999,
         "Timers" : "false",
         "Type" : "Temp",
         "TypeImg" : "temperature",
         "Unit" : 1,
         "Used" : 1,
         "XOffset" : "131",
         "YOffset" : "417",
         "idx" : "116",
         "trend" : 0
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "19.7 C",
         "Description" : "Température de la cuisine issue de l’œil de Chat",
         "Favorite" : 1,
         "HardwareID" : 9,
         "HardwareName" : "Zwave plus",
         "HardwareType" : "OpenZWave USB",
         "HardwareTypeVal" : 21,
         "HaveTimeout" : false,
         "ID" : "0901",
         "LastUpdate" : "2019-05-14 10:29:29",
         "Name" : "Cuisine",
         "Notifications" : "true",
         "PlanID" : "4",
         "PlanIDs" : [ 4, 9, 12 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "LaCrosse TX3",
         "Temp" : 19.699999999999999,
         "Timers" : "false",
         "Type" : "Temp",
         "TypeImg" : "temperature",
         "Unit" : 1,
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "118",
         "trend" : 2
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 44,
         "CustomImage" : 0,
         "Data" : "20.0 C, 58 %",
         "Description" : "Température et Hygrométrie du salon",
         "DewPoint" : "11.49",
         "Favorite" : 1,
         "HardwareID" : 9,
         "HardwareName" : "Zwave plus",
         "HardwareType" : "OpenZWave USB",
         "HardwareTypeVal" : 21,
         "HaveTimeout" : true,
         "Humidity" : 58,
         "HumidityStatus" : "Comfortable",
         "ID" : "0301",
         "LastUpdate" : "2019-05-14 08:52:12",
         "Name" : "Salon",
         "Notifications" : "true",
         "PlanID" : "6",
         "PlanIDs" : [ 6, 9, 12 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "WTGR800",
         "Temp" : 20.0,
         "Timers" : "false",
         "Type" : "Temp + Humidity",
         "TypeImg" : "temperature",
         "Unit" : 0,
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "64",
         "trend" : 0
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "19.9 C, 63 %",
         "Description" : "Température et Hygrométrie de la chambre d'Erynn",
         "DewPoint" : "12.65",
         "Favorite" : 1,
         "HardwareID" : 9,
         "HardwareName" : "Zwave plus",
         "HardwareType" : "OpenZWave USB",
         "HardwareTypeVal" : 21,
         "HaveTimeout" : false,
         "Humidity" : 63,
         "HumidityStatus" : "Wet",
         "ID" : "0601",
         "LastUpdate" : "2019-05-14 10:06:15",
         "Name" : "Chambre Erynn",
         "Notifications" : "true",
         "PlanID" : "7",
         "PlanIDs" : [ 7, 9, 12 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "WTGR800",
         "Temp" : 19.899999999999999,
         "Timers" : "false",
         "Type" : "Temp + Humidity",
         "TypeImg" : "temperature",
         "Unit" : 0,
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "66",
         "trend" : 1
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 122,
         "Data" : "Off",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 1,
         "HardwareID" : 5,
         "HardwareName" : "GPIO domoticz",
         "HardwareType" : "Raspberry's GPIO port",
         "HardwareTypeVal" : 32,
         "HaveDimmer" : false,
         "HaveGroupCmd" : false,
         "HaveTimeout" : false,
         "ID" : "0",
         "Image" : "led_red",
         "IsSubDevice" : false,
         "LastUpdate" : "2019-05-14 08:43:00",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 0,
         "Name" : "Mémoire Intrusion",
         "Notifications" : "false",
         "PlanID" : "15",
         "PlanIDs" : [ 15 ],
         "Protected" : true,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Impuls",
         "SwitchType" : "On/Off",
         "SwitchTypeVal" : 0,
         "Timers" : "false",
         "Type" : "Lighting 1",
         "TypeImg" : "lightbulb",
         "Unit" : 17,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "141"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "Off",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 1,
         "HardwareID" : 3,
         "HardwareName" : "Periph Virtuels",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "000140CE",
         "Image" : "Push",
         "IsSubDevice" : false,
         "LastUpdate" : "2019-05-14 08:43:00",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 100,
         "Name" : "Aquitter",
         "Notifications" : "false",
         "PlanID" : "15",
         "PlanIDs" : [ 15 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Switch",
         "SwitchType" : "Push Off Button",
         "SwitchTypeVal" : 10,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "pushoff",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "126"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 1.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "Off",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareID" : 3,
         "HardwareName" : "Periph Virtuels",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "00014133",
         "Image" : "Push",
         "InternalState" : "Off",
         "IsSubDevice" : false,
         "LastUpdate" : "2019-05-14 00:59:50",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 100,
         "Name" : "Test Portes",
         "Notifications" : "false",
         "PlanID" : "9",
         "PlanIDs" : [ 9 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Switch",
         "SwitchType" : "Push On Button",
         "SwitchTypeVal" : 9,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "push",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "227"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "20.0 C, 61 %",
         "Description" : "",
         "DewPoint" : "12.25",
         "Favorite" : 1,
         "HardwareID" : 9,
         "HardwareName" : "Zwave plus",
         "HardwareType" : "OpenZWave USB",
         "HardwareTypeVal" : 21,
         "HaveTimeout" : false,
         "Humidity" : 61,
         "HumidityStatus" : "Wet",
         "ID" : "1901",
         "LastUpdate" : "2019-05-14 09:58:34",
         "Name" : "Chambre Parentale",
         "Notifications" : "true",
         "PlanID" : "9",
         "PlanIDs" : [ 9, 12, 13 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "WTGR800",
         "Temp" : 20.0,
         "Timers" : "false",
         "Type" : "Temp + Humidity",
         "TypeImg" : "temperature",
         "Unit" : 0,
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "188",
         "trend" : 1
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "21.0 C, 73 %",
         "Description" : "",
         "DewPoint" : "15.98",
         "Favorite" : 1,
         "HardwareID" : 9,
         "HardwareName" : "Zwave plus",
         "HardwareType" : "OpenZWave USB",
         "HardwareTypeVal" : 21,
         "HaveTimeout" : true,
         "Humidity" : 73,
         "HumidityStatus" : "Wet",
         "ID" : "1801",
         "LastUpdate" : "2019-05-14 09:27:08",
         "Name" : "Salle de Bain",
         "Notifications" : "true",
         "PlanID" : "9",
         "PlanIDs" : [ 9, 12, 14 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "WTGR800",
         "Temp" : 21.0,
         "Timers" : "false",
         "Type" : "Temp + Humidity",
         "TypeImg" : "temperature",
         "Unit" : 0,
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "186",
         "trend" : 1
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "242.17 V",
         "Description" : "",
         "Favorite" : 1,
         "HardwareID" : 9,
         "HardwareName" : "Zwave plus",
         "HardwareType" : "OpenZWave USB",
         "HardwareTypeVal" : 21,
         "HaveTimeout" : false,
         "ID" : "00001401",
         "LastUpdate" : "2019-05-14 10:35:24",
         "Name" : "Voltage Prise Imprimante",
         "Notifications" : "false",
         "PlanID" : "2",
         "PlanIDs" : [ 2, 9 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "Voltage",
         "Timers" : "false",
         "Type" : "General",
         "TypeImg" : "current",
         "Unit" : 1,
         "Used" : 1,
         "Voltage" : 242.16999999999999,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "155"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "Counter" : "166952 Min",
         "CounterToday" : "434 Min",
         "CustomImage" : 0,
         "Data" : "166952 Min",
         "Description" : "",
         "Favorite" : 1,
         "HardwareID" : 3,
         "HardwareName" : "Periph Virtuels",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveTimeout" : false,
         "ID" : "82214",
         "LastUpdate" : "2019-05-14 10:36:00",
         "Name" : "Compteur VMC",
         "Notifications" : "false",
         "PlanID" : "14",
         "PlanIDs" : [ 14, 16 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "Counter Incremental",
         "SwitchTypeVal" : 3,
         "Timers" : "false",
         "Type" : "General",
         "TypeImg" : "counter",
         "Unit" : 1,
         "Used" : 1,
         "ValueQuantity" : "Durée Utilisation VMC",
         "ValueUnits" : "Min",
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "214"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "Counter" : "35442 Min",
         "CounterToday" : "39 Min",
         "CustomImage" : 0,
         "Data" : "35442 Min",
         "Description" : "Compteur d'heures de fonctionnement du chauffage de la salle de bain",
         "Favorite" : 1,
         "HardwareID" : 3,
         "HardwareName" : "Periph Virtuels",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveTimeout" : false,
         "ID" : "82197",
         "LastUpdate" : "2019-05-14 10:36:00",
         "Name" : "Compteur Radiateur Salle de Bain",
         "Notifications" : "false",
         "PlanID" : "12",
         "PlanIDs" : [ 12, 14 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "Counter Incremental",
         "SwitchTypeVal" : 3,
         "Timers" : "false",
         "Type" : "General",
         "TypeImg" : "counter",
         "Unit" : 1,
         "Used" : 1,
         "ValueQuantity" : "Durée de fonctionnement",
         "ValueUnits" : "Min",
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "197"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 131,
         "Data" : "On",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 1,
         "HardwareID" : 9,
         "HardwareName" : "Zwave plus",
         "HardwareType" : "OpenZWave USB",
         "HardwareTypeVal" : 21,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "00002301",
         "Image" : "Lave-linge",
         "IsSubDevice" : false,
         "LastUpdate" : "2019-05-13 09:50:43",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 100,
         "Name" : "Lave Linge",
         "Notifications" : "false",
         "PlanID" : "2",
         "PlanIDs" : [ 2 ],
         "Protected" : true,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "On",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Switch",
         "SwitchType" : "On/Off",
         "SwitchTypeVal" : 0,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "lightbulb",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "841",
         "YOffset" : "443",
         "idx" : "308"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "Off",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 1,
         "HardwareID" : 9,
         "HardwareName" : "Zwave plus",
         "HardwareType" : "OpenZWave USB",
         "HardwareTypeVal" : 21,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "00002002",
         "Image" : "Light",
         "IsSubDevice" : false,
         "LastUpdate" : "2019-05-14 10:36:00",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 100,
         "Name" : "Lumière Compresseur",
         "Notifications" : "false",
         "PlanID" : "2",
         "PlanIDs" : [ 2 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Switch",
         "SwitchType" : "On/Off",
         "SwitchTypeVal" : 0,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "lightbulb",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "856",
         "YOffset" : "368",
         "idx" : "273"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 70,
         "CustomImage" : 133,
         "Data" : "Closed",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 1,
         "HardwareID" : 9,
         "HardwareName" : "Zwave plus",
         "HardwareType" : "OpenZWave USB",
         "HardwareTypeVal" : 21,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "00001634",
         "Image" : "Coffre",
         "InternalState" : "Closed",
         "IsSubDevice" : false,
         "LastUpdate" : "2018-10-04 04:40:57",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 100,
         "Name" : "Coffre fort",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Closed",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Switch",
         "SwitchType" : "Door Contact",
         "SwitchTypeVal" : 11,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "door",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "166"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 165,
         "Data" : "Off",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 1,
         "HardwareID" : 3,
         "HardwareName" : "Periph Virtuels",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "0001412F",
         "Image" : "Present",
         "IsSubDevice" : false,
         "LastUpdate" : "2019-05-13 08:57:37",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 100,
         "Name" : "Présence Olivier",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Switch",
         "SwitchType" : "On/Off",
         "SwitchTypeVal" : 0,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "lightbulb",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "223"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 1,
         "Data" : "Off",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 1,
         "HardwareID" : 9,
         "HardwareName" : "Zwave plus",
         "HardwareType" : "OpenZWave USB",
         "HardwareTypeVal" : 21,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "00002401",
         "Image" : "WallSocket",
         "IsSubDevice" : false,
         "LastUpdate" : "2019-05-13 18:13:42",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 100,
         "Name" : "P3",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Switch",
         "SwitchType" : "On/Off",
         "SwitchTypeVal" : 0,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "lightbulb",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "317"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "0;0.0",
         "Description" : "",
         "Favorite" : 1,
         "HardwareID" : 12,
         "HardwareName" : "Météo Villelaure",
         "HardwareType" : "DarkSky (Weather Lookup)",
         "HardwareTypeVal" : 25,
         "HaveTimeout" : false,
         "ID" : "0001",
         "LastUpdate" : "2019-05-14 10:36:11",
         "Name" : "Pluie Villelaure new",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "Rain" : "0.0",
         "RainRate" : "0",
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "Unknown",
         "Timers" : "false",
         "Type" : "Rain",
         "TypeImg" : "rain",
         "Unit" : 0,
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "forecast_url" : "aHR0cHM6Ly9kYXJrc2t5Lm5ldC8jL2YvNDMuNzExNzMxJTJDJTIwNS40MjQwMDM=",
         "idx" : "337"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "17.3 C",
         "Description" : "",
         "Favorite" : 0,
         "HardwareID" : 9,
         "HardwareName" : "Zwave plus",
         "HardwareType" : "OpenZWave USB",
         "HardwareTypeVal" : 21,
         "HaveTimeout" : false,
         "ID" : "2701",
         "LastUpdate" : "2019-05-14 10:35:11",
         "Name" : "Garage",
         "Notifications" : "true",
         "PlanID" : "2",
         "PlanIDs" : [ 2, 9 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "LaCrosse TX3",
         "Temp" : 17.300000000000001,
         "Timers" : "false",
         "Type" : "Temp",
         "TypeImg" : "temperature",
         "Unit" : 1,
         "Used" : 1,
         "XOffset" : "607",
         "YOffset" : "120",
         "idx" : "351",
         "trend" : 1
      }
   ],
   "status" : "OK",
   "title" : "Devices"
});