exports.DOMOTICZ_GET_DEVICES = JSON.stringify({
   "ActTime" : 1546982461,
   "ServerTime" : "2019-01-08 22:21:01",
   "Sunrise" : "08:32",
   "Sunset" : "17:33",
   "result" : [
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 100,
         "CustomImage" : 0,
         "Data" : "6.7 C, 88 %",
         "Description" : "",
         "DewPoint" : "4.85",
         "Favorite" : 1,
         "HardwareID" : 2,
         "HardwareName" : "RfxCom",
         "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
         "HardwareTypeVal" : 1,
         "HaveTimeout" : false,
         "Humidity" : 88,
         "HumidityStatus" : "Wet",
         "ID" : "AB01",
         "LastUpdate" : "2019-01-08 22:19:36",
         "Name" : "Hr/T° Ext.",
         "Notifications" : "false",
         "PlanID" : "11",
         "PlanIDs" : [ 11, 16 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : 7,
         "SubType" : "THGR810, THGN800",
         "Temp" : 6.7000000000000002,
         "Timers" : "false",
         "Type" : "Temp + Humidity",
         "TypeImg" : "temperature",
         "Unit" : 1,
         "Used" : 1,
         "XOffset" : "2728",
         "YOffset" : "1550",
         "idx" : "1461"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 100,
         "CustomImage" : 0,
         "Data" : "20.0 C, 39 %",
         "Description" : "",
         "DewPoint" : "5.62",
         "Favorite" : 1,
         "HardwareID" : 2,
         "HardwareName" : "RfxCom",
         "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
         "HardwareTypeVal" : 1,
         "HaveTimeout" : false,
         "Humidity" : 39,
         "HumidityStatus" : "Dry",
         "ID" : "2103",
         "LastUpdate" : "2019-01-08 22:20:28",
         "Name" : "Hr/T° Salon",
         "Notifications" : "false",
         "PlanID" : "2",
         "PlanIDs" : [ 2, 16 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : 7,
         "SubType" : "Alecto WS1700",
         "Temp" : 20.0,
         "Timers" : "false",
         "Type" : "Temp + Humidity",
         "TypeImg" : "temperature",
         "Unit" : 3,
         "Used" : 1,
         "XOffset" : "1402",
         "YOffset" : "890",
         "idx" : "1075"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 100,
         "CustomImage" : 0,
         "Data" : "15.9 C, 54 %",
         "Description" : "",
         "DewPoint" : "6.60",
         "Favorite" : 1,
         "HardwareID" : 2,
         "HardwareName" : "RfxCom",
         "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
         "HardwareTypeVal" : 1,
         "HaveTimeout" : false,
         "Humidity" : 54,
         "HumidityStatus" : "Comfortable",
         "ID" : "7301",
         "LastUpdate" : "2019-01-08 22:20:55",
         "Name" : "Hr/T° Chambre 1",
         "Notifications" : "false",
         "PlanID" : "6",
         "PlanIDs" : [ 6, 16 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : 7,
         "SubType" : "Alecto WS1700",
         "Temp" : 15.9,
         "Timers" : "false",
         "Type" : "Temp + Humidity",
         "TypeImg" : "temperature",
         "Unit" : 1,
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "1100"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 100,
         "CustomImage" : 0,
         "Data" : "16.6 C, 50 %",
         "Description" : "",
         "DewPoint" : "6.13",
         "Favorite" : 1,
         "HardwareID" : 2,
         "HardwareName" : "RfxCom",
         "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
         "HardwareTypeVal" : 1,
         "HaveTimeout" : false,
         "Humidity" : 50,
         "HumidityStatus" : "Comfortable",
         "ID" : "2B01",
         "LastUpdate" : "2019-01-08 22:20:52",
         "Name" : "Hr/T° Chambre 2",
         "Notifications" : "false",
         "PlanID" : "7",
         "PlanIDs" : [ 7, 16 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : 7,
         "SubType" : "Alecto WS1700",
         "Temp" : 16.600000000000001,
         "Timers" : "false",
         "Type" : "Temp + Humidity",
         "TypeImg" : "temperature",
         "Unit" : 1,
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "1082"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 100,
         "CustomImage" : 0,
         "Data" : "16.3 C, 42 %",
         "Description" : "",
         "DewPoint" : "3.36",
         "Favorite" : 1,
         "HardwareID" : 2,
         "HardwareName" : "RfxCom",
         "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
         "HardwareTypeVal" : 1,
         "HaveTimeout" : false,
         "Humidity" : 42,
         "HumidityStatus" : "Comfortable",
         "ID" : "E101",
         "LastUpdate" : "2019-01-08 22:14:54",
         "Name" : "Hr/T° Ch. 3/Ssprt",
         "Notifications" : "false",
         "PlanID" : "8",
         "PlanIDs" : [ 8, 16 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : 7,
         "SubType" : "Alecto WS1700",
         "Temp" : 16.300000000000001,
         "Timers" : "false",
         "Type" : "Temp + Humidity",
         "TypeImg" : "temperature",
         "Unit" : 1,
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "1080"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 100,
         "CustomImage" : 0,
         "Data" : "20.1 C, 40 %",
         "Description" : "",
         "DewPoint" : "6.08",
         "Favorite" : 1,
         "HardwareID" : 2,
         "HardwareName" : "RfxCom",
         "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
         "HardwareTypeVal" : 1,
         "HaveTimeout" : false,
         "Humidity" : 40,
         "HumidityStatus" : "Comfortable",
         "ID" : "4602",
         "LastUpdate" : "2019-01-08 22:20:59",
         "Name" : "Hr/T° Salle de bain",
         "Notifications" : "false",
         "PlanID" : "9",
         "PlanIDs" : [ 9, 16 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : 7,
         "SubType" : "Alecto WS1700",
         "Temp" : 20.100000000000001,
         "Timers" : "false",
         "Type" : "Temp + Humidity",
         "TypeImg" : "temperature",
         "Unit" : 2,
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "1497"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 100,
         "CustomImage" : 0,
         "Data" : "11.4 C, 58 %",
         "Description" : "",
         "DewPoint" : "3.43",
         "Favorite" : 1,
         "HardwareID" : 2,
         "HardwareName" : "RfxCom",
         "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
         "HardwareTypeVal" : 1,
         "HaveTimeout" : true,
         "Humidity" : 58,
         "HumidityStatus" : "Comfortable",
         "ID" : "B601",
         "LastUpdate" : "2019-01-08 07:43:22",
         "Name" : "Hr/T° Cave",
         "Notifications" : "false",
         "PlanID" : "3",
         "PlanIDs" : [ 3, 16 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : 6,
         "SubType" : "Alecto WS1700",
         "Temp" : 11.4,
         "Timers" : "false",
         "Type" : "Temp + Humidity",
         "TypeImg" : "temperature",
         "Unit" : 1,
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "584"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 100,
         "CustomImage" : 0,
         "Data" : "13.7 C, 60 %",
         "Description" : "",
         "DewPoint" : "6.07",
         "Favorite" : 1,
         "HardwareID" : 2,
         "HardwareName" : "RfxCom",
         "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
         "HardwareTypeVal" : 1,
         "HaveTimeout" : false,
         "Humidity" : 60,
         "HumidityStatus" : "Comfortable",
         "ID" : "6303",
         "LastUpdate" : "2019-01-08 22:20:58",
         "Name" : "Hr/T° Garage",
         "Notifications" : "false",
         "PlanID" : "5",
         "PlanIDs" : [ 5, 16 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : 6,
         "SubType" : "Alecto WS1700",
         "Temp" : 13.699999999999999,
         "Timers" : "false",
         "Type" : "Temp + Humidity",
         "TypeImg" : "temperature",
         "Unit" : 3,
         "Used" : 1,
         "XOffset" : "2868",
         "YOffset" : "1120",
         "idx" : "921"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "Closed",
         "Description" : "",
         "Favorite" : 1,
         "HardwareID" : 2,
         "HardwareName" : "RfxCom",
         "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
         "HardwareTypeVal" : 1,
         "HaveDimmer" : false,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "010141",
         "Image" : "Light",
         "IsSubDevice" : false,
         "LastUpdate" : "2019-01-08 17:33:04",
         "Level" : 0,
         "LevelInt" : 19,
         "MaxDimLevel" : 0,
         "Name" : "Volet Roulant Cuisine",
         "Notifications" : "false",
         "PlanID" : "4",
         "PlanIDs" : [ 4, 16 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : 7,
         "Status" : "Closed",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Blyss",
         "SwitchType" : "Blinds Inverted",
         "SwitchTypeVal" : 6,
         "Timers" : "false",
         "Type" : "Lighting 6",
         "TypeImg" : "blinds",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "489",
         "YOffset" : "552",
         "idx" : "115"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 13,
         "Data" : "Off",
         "Description" : "",
         "Favorite" : 1,
         "HardwareID" : 2,
         "HardwareName" : "RfxCom",
         "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
         "HardwareTypeVal" : 1,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "0EB548E",
         "Image" : "Alarm",
         "IsSubDevice" : false,
         "LastUpdate" : "2019-01-03 09:21:27",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 15,
         "Name" : "Détecteur de Porte",
         "Notifications" : "false",
         "PlanID" : "13",
         "PlanIDs" : [ 13 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : 7,
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "AC",
         "SwitchType" : "On/Off",
         "SwitchTypeVal" : 0,
         "Timers" : "false",
         "Type" : "Lighting 2",
         "TypeImg" : "lightbulb",
         "Unit" : 10,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "1347",
         "YOffset" : "761",
         "idx" : "1488"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 18,
         "Data" : "On",
         "Description" : "",
         "Favorite" : 1,
         "HardwareID" : 6,
         "HardwareName" : "Iphone_5S",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveDimmer" : false,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "80",
         "Image" : "Phone",
         "IsSubDevice" : false,
         "LastUpdate" : "2019-01-08 19:49:25",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 0,
         "Name" : "Iphone_5s",
         "Notifications" : "false",
         "PlanID" : "4",
         "PlanIDs" : [ 4, 16 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "On",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "X10",
         "SwitchType" : "On/Off",
         "SwitchTypeVal" : 0,
         "Timers" : "false",
         "Type" : "Lighting 1",
         "TypeImg" : "lightbulb",
         "Unit" : 16,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "1463",
         "YOffset" : "1271",
         "idx" : "174"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 9,
         "Data" : "On",
         "Description" : "",
         "Favorite" : 1,
         "HardwareID" : 2,
         "HardwareName" : "RfxCom",
         "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
         "HardwareTypeVal" : 1,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "152D79E",
         "Image" : "Generic",
         "IsSubDevice" : false,
         "LastUpdate" : "2019-01-08 17:28:03",
         "Level" : 100,
         "LevelInt" : 15,
         "MaxDimLevel" : 15,
         "Name" : "Interrupeur Crépusculaire",
         "Notifications" : "false",
         "PlanID" : "11",
         "PlanIDs" : [ 11, 16 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : 6,
         "Status" : "On",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "AC",
         "SwitchType" : "On/Off",
         "SwitchTypeVal" : 0,
         "Timers" : "false",
         "Type" : "Lighting 2",
         "TypeImg" : "lightbulb",
         "Unit" : 10,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "2737",
         "YOffset" : "1296",
         "idx" : "114"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "Normal",
         "Description" : "",
         "Favorite" : 1,
         "HardwareID" : 2,
         "HardwareName" : "RfxCom",
         "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
         "HardwareTypeVal" : 1,
         "HaveDimmer" : false,
         "HaveGroupCmd" : false,
         "HaveTimeout" : false,
         "ID" : "1BFF00",
         "LastUpdate" : "2018-07-21 10:00:45",
         "MaxDimLevel" : 0,
         "Name" : "Détect. Fumée Chaufferie",
         "Notifications" : "true",
         "PlanID" : "5",
         "PlanIDs" : [ 5, 16 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : 7,
         "Status" : "Normal",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "KD101 smoke detector",
         "SwitchType" : "Smoke Detector",
         "SwitchTypeVal" : 5,
         "Timers" : "false",
         "Type" : "Security",
         "TypeImg" : "smoke",
         "Unit" : 0,
         "Used" : 1,
         "XOffset" : "2966",
         "YOffset" : "481",
         "idx" : "108"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "Normal",
         "Description" : "",
         "Favorite" : 1,
         "HardwareID" : 2,
         "HardwareName" : "RfxCom",
         "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
         "HardwareTypeVal" : 1,
         "HaveDimmer" : false,
         "HaveGroupCmd" : false,
         "HaveTimeout" : false,
         "ID" : "8A3600",
         "LastUpdate" : "2018-07-21 10:00:54",
         "MaxDimLevel" : 0,
         "Name" : "Détect. Fumée Palier R+1",
         "Notifications" : "true",
         "PlanID" : "15",
         "PlanIDs" : [ 15, 16 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Normal",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "KD101 smoke detector",
         "SwitchType" : "Smoke Detector",
         "SwitchTypeVal" : 5,
         "Timers" : "false",
         "Type" : "Security",
         "TypeImg" : "smoke",
         "Unit" : 0,
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "107"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "Normal",
         "Description" : "",
         "Favorite" : 1,
         "HardwareID" : 2,
         "HardwareName" : "RfxCom",
         "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
         "HardwareTypeVal" : 1,
         "HaveDimmer" : false,
         "HaveGroupCmd" : false,
         "HaveTimeout" : false,
         "ID" : "62CF00",
         "LastUpdate" : "2018-07-21 10:01:27",
         "MaxDimLevel" : 0,
         "Name" : "Détect. Fumée LT",
         "Notifications" : "true",
         "PlanID" : "14",
         "PlanIDs" : [ 14, 16 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : 7,
         "Status" : "Normal",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "KD101 smoke detector",
         "SwitchType" : "Smoke Detector",
         "SwitchTypeVal" : 5,
         "Timers" : "false",
         "Type" : "Security",
         "TypeImg" : "smoke",
         "Unit" : 0,
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "109"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "Normal",
         "Description" : "",
         "Favorite" : 1,
         "HardwareID" : 2,
         "HardwareName" : "RfxCom",
         "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
         "HardwareTypeVal" : 1,
         "HaveDimmer" : false,
         "HaveGroupCmd" : false,
         "HaveTimeout" : false,
         "ID" : "21C200",
         "LastUpdate" : "2018-07-21 10:01:08",
         "MaxDimLevel" : 0,
         "Name" : "Détect. Fumée Grenier",
         "Notifications" : "true",
         "PlanID" : "10",
         "PlanIDs" : [ 10, 16 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Normal",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "KD101 smoke detector",
         "SwitchType" : "Smoke Detector",
         "SwitchTypeVal" : 5,
         "Timers" : "false",
         "Type" : "Security",
         "TypeImg" : "smoke",
         "Unit" : 0,
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "110"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 3,
         "Data" : "On",
         "Description" : "",
         "Favorite" : 1,
         "HardwareID" : 8,
         "HardwareName" : "NAS",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "000145CB",
         "Image" : "Harddisk",
         "IsSubDevice" : false,
         "LastUpdate" : "2019-01-08 22:19:03",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 100,
         "Name" : "NAS",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "On",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Switch",
         "SwitchType" : "On/Off",
         "SwitchTypeVal" : 0,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "lightbulb",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "1403"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 17,
         "Data" : "On",
         "Description" : "",
         "Favorite" : 1,
         "HardwareID" : 8,
         "HardwareName" : "NAS",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "000145CA",
         "Image" : "ComputerPC",
         "IsSubDevice" : false,
         "LastUpdate" : "2019-01-08 22:19:03",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 100,
         "Name" : "LiveBox",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "On",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Switch",
         "SwitchType" : "On/Off",
         "SwitchTypeVal" : 0,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "lightbulb",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "1402"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 109,
         "Data" : "Off",
         "Description" : "",
         "Favorite" : 0,
         "HardwareID" : 2,
         "HardwareName" : "RfxCom",
         "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
         "HardwareTypeVal" : 1,
         "HaveDimmer" : false,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "020241",
         "Image" : "Lampadaire",
         "IsSubDevice" : false,
         "LastUpdate" : "2017-12-22 10:10:13",
         "Level" : 0,
         "LevelInt" : 14,
         "MaxDimLevel" : 0,
         "Name" : "Module Avidsen (En attente)",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : 7,
         "Status" : "Off",
         "StrParam1" : "aHR0cDovL3d3dy5yZnhjb20uY29tL2VwYWdlcy83ODE2NTQ2OS5zZi9lbl9HQi8/T2JqZWN0UGF0aD0vU2hvcHMvNzgxNjU0NjkvQ2F0ZWdvcmllcy9Eb3dubG9hZHM=",
         "StrParam2" : "",
         "SubType" : "Blyss",
         "SwitchType" : "On/Off",
         "SwitchTypeVal" : 0,
         "Timers" : "false",
         "Type" : "Lighting 6",
         "TypeImg" : "lightbulb",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "140"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "1.20%",
         "Description" : "",
         "Favorite" : 1,
         "HardwareID" : 11,
         "HardwareName" : "NAS",
         "HardwareType" : "Motherboard sensors",
         "HardwareTypeVal" : 23,
         "HaveTimeout" : false,
         "ID" : "0000044D",
         "Image" : "Computer",
         "LastUpdate" : "2019-01-08 22:20:52",
         "Name" : "NAS_CPU_Usage",
         "Notifications" : "false",
         "PlanID" : "11",
         "PlanIDs" : [ 11 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "Percentage",
         "Timers" : "false",
         "Type" : "General",
         "TypeImg" : "hardware",
         "Unit" : 1,
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "1405"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "25.78%",
         "Description" : "",
         "Favorite" : 1,
         "HardwareID" : 11,
         "HardwareName" : "NAS",
         "HardwareType" : "Motherboard sensors",
         "HardwareTypeVal" : 23,
         "HaveTimeout" : false,
         "ID" : "0000044C",
         "Image" : "Computer",
         "LastUpdate" : "2019-01-08 22:20:22",
         "Name" : "NAS_Memory Usage",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "Percentage",
         "Timers" : "false",
         "Type" : "General",
         "TypeImg" : "hardware",
         "Unit" : 1,
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "1406"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "48.10%",
         "Description" : "",
         "Favorite" : 1,
         "HardwareID" : 11,
         "HardwareName" : "NAS",
         "HardwareType" : "Motherboard sensors",
         "HardwareTypeVal" : 23,
         "HaveTimeout" : false,
         "ID" : "0000044F",
         "Image" : "Computer",
         "LastUpdate" : "2019-01-08 22:20:42",
         "Name" : "NAS_HDD /volume1",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "Percentage",
         "Timers" : "false",
         "Type" : "General",
         "TypeImg" : "hardware",
         "Unit" : 1,
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "1408"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "41.01%",
         "Description" : "",
         "Favorite" : 1,
         "HardwareID" : 11,
         "HardwareName" : "NAS",
         "HardwareType" : "Motherboard sensors",
         "HardwareTypeVal" : 23,
         "HaveTimeout" : false,
         "ID" : "0000044E",
         "Image" : "Computer",
         "LastUpdate" : "2019-01-08 22:20:42",
         "Name" : "NAS_HDD/",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "Percentage",
         "Timers" : "false",
         "Type" : "General",
         "TypeImg" : "hardware",
         "Unit" : 1,
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "1407"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 100,
         "CounterToday" : "18138.304 kWh",
         "CustomImage" : 0,
         "Data" : "18138.304 kWh",
         "Description" : "",
         "Favorite" : 1,
         "HardwareID" : 2,
         "HardwareName" : "RfxCom",
         "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
         "HardwareTypeVal" : 1,
         "HaveTimeout" : true,
         "ID" : "DE00",
         "LastUpdate" : "2019-01-07 19:33:40",
         "Name" : "Comptage Général",
         "Notifications" : "false",
         "Options" : "1",
         "PlanID" : "16",
         "PlanIDs" : [ 16 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : 6,
         "SubType" : "CM180",
         "SwitchTypeVal" : 0,
         "Timers" : "false",
         "Type" : "Energy",
         "TypeImg" : "current",
         "Unit" : 0,
         "Usage" : "7760 Watt",
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "179"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 100,
         "CustomImage" : 0,
         "Data" : "6520 Watt, 360 Watt, 880 Watt, Total: 18138.304 kWh",
         "Description" : "",
         "Favorite" : 1,
         "HardwareID" : 2,
         "HardwareName" : "RfxCom",
         "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
         "HardwareTypeVal" : 1,
         "HaveTimeout" : true,
         "ID" : "DE00",
         "LastUpdate" : "2019-01-07 19:33:40",
         "Name" : "Comptage Général TRI (Pu)",
         "Notifications" : "false",
         "PlanID" : "16",
         "PlanIDs" : [ 16 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : 6,
         "SubType" : "CM180i",
         "Timers" : "false",
         "Type" : "Current/Energy",
         "TypeImg" : "current",
         "Unit" : 0,
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "displaytype" : 1,
         "idx" : "178"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 100,
         "CounterToday" : "4.220 kWh",
         "CustomImage" : 0,
         "Data" : "2274.684 kWh",
         "Description" : "",
         "Favorite" : 1,
         "HardwareID" : 2,
         "HardwareName" : "RfxCom",
         "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
         "HardwareTypeVal" : 1,
         "HaveTimeout" : false,
         "ID" : "E800",
         "LastUpdate" : "2019-01-08 22:20:54",
         "Name" : "Totalisateur CE TRI (Pu)",
         "Notifications" : "false",
         "Options" : "1",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : 6,
         "SubType" : "CM180",
         "SwitchTypeVal" : 0,
         "Timers" : "false",
         "Type" : "Energy",
         "TypeImg" : "current",
         "Unit" : 0,
         "Usage" : "0 Watt",
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "190"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 100,
         "CounterToday" : "0.000 kWh",
         "CustomImage" : 0,
         "Data" : "251.079 kWh",
         "Description" : "",
         "Favorite" : 1,
         "HardwareID" : 2,
         "HardwareName" : "RfxCom",
         "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
         "HardwareTypeVal" : 1,
         "HaveTimeout" : false,
         "ID" : "C100",
         "LastUpdate" : "2019-01-08 22:20:35",
         "Name" : "Totalisateur Pac1, Pac2 et Spa",
         "Notifications" : "false",
         "Options" : "1",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : 7,
         "SubType" : "CM180",
         "SwitchTypeVal" : 0,
         "Timers" : "false",
         "Type" : "Energy",
         "TypeImg" : "current",
         "Unit" : 0,
         "Usage" : "0 Watt",
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "169"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 100,
         "CustomImage" : 0,
         "Data" : "0 Watt, 0 Watt, 0 Watt, Total: 2274.684 kWh",
         "Description" : "",
         "Favorite" : 1,
         "HardwareID" : 2,
         "HardwareName" : "RfxCom",
         "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
         "HardwareTypeVal" : 1,
         "HaveTimeout" : false,
         "ID" : "E800",
         "LastUpdate" : "2019-01-08 22:20:54",
         "Name" : "Unknown",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : 6,
         "SubType" : "CM180i",
         "Timers" : "false",
         "Type" : "Current/Energy",
         "TypeImg" : "current",
         "Unit" : 0,
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "displaytype" : 1,
         "idx" : "278"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "19 Jours",
         "Description" : "",
         "Favorite" : 1,
         "HardwareID" : 14,
         "HardwareName" : "EJP Restant",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveTimeout" : true,
         "ID" : "00083496",
         "Image" : "Custom",
         "LastUpdate" : "2018-11-21 16:01:02",
         "Name" : "EJP Restant",
         "Notifications" : "false",
         "PlanID" : "11",
         "PlanIDs" : [ 11 ],
         "Protected" : false,
         "SensorType" : 1,
         "SensorUnit" : "Jours",
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "Custom Sensor",
         "Timers" : "false",
         "Type" : "General",
         "TypeImg" : "Custom",
         "Unit" : 1,
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "1496"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 100,
         "CustomImage" : 0,
         "Data" : "16.8 C, 52 %",
         "Description" : "",
         "DewPoint" : "6.89",
         "Favorite" : 1,
         "HardwareID" : 2,
         "HardwareName" : "RfxCom",
         "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
         "HardwareTypeVal" : 1,
         "HaveTimeout" : false,
         "Humidity" : 52,
         "HumidityStatus" : "Comfortable",
         "ID" : "7401",
         "LastUpdate" : "2019-01-08 22:20:35",
         "Name" : "Hr/T° Grenier",
         "Notifications" : "false",
         "PlanID" : "10",
         "PlanIDs" : [ 10, 16 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : 7,
         "SubType" : "Alecto WS1700",
         "Temp" : 16.800000000000001,
         "Timers" : "false",
         "Type" : "Temp + Humidity",
         "TypeImg" : "temperature",
         "Unit" : 1,
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "1261"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 100,
         "CustomImage" : 0,
         "Data" : "259.00;WSW;0;0;0.0;0.0",
         "Description" : "",
         "Direction" : 259.0,
         "DirectionStr" : "WSW",
         "Favorite" : 1,
         "Gust" : "0.0",
         "HardwareID" : 2,
         "HardwareName" : "RfxCom",
         "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
         "HardwareTypeVal" : 1,
         "HaveTimeout" : false,
         "ID" : "7500",
         "LastUpdate" : "2019-01-08 22:18:04",
         "Name" : "Anémo-Girouette",
         "Notifications" : "false",
         "PlanID" : "11",
         "PlanIDs" : [ 11, 16 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : 7,
         "Speed" : "0.0",
         "SubType" : "WGR800",
         "Timers" : "false",
         "Type" : "Wind",
         "TypeImg" : "wind",
         "Unit" : 0,
         "Used" : 1,
         "XOffset" : "2742",
         "YOffset" : "1807",
         "idx" : "1471"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 100,
         "CustomImage" : 0,
         "Data" : "6.0 UVI",
         "Description" : "",
         "Favorite" : 1,
         "HardwareID" : 2,
         "HardwareName" : "RfxCom",
         "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
         "HardwareTypeVal" : 1,
         "HaveTimeout" : false,
         "ID" : "6000",
         "LastUpdate" : "2019-01-08 21:56:07",
         "Name" : "Sonde UV",
         "Notifications" : "false",
         "PlanID" : "11",
         "PlanIDs" : [ 11, 16 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : 7,
         "SubType" : "UVN800",
         "Timers" : "false",
         "Type" : "UV",
         "TypeImg" : "uv",
         "UVI" : "6.0",
         "Unit" : 0,
         "Used" : 1,
         "XOffset" : "2742",
         "YOffset" : "1031",
         "idx" : "1472"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 100,
         "CustomImage" : 0,
         "Data" : "90;212.1",
         "Description" : "",
         "Favorite" : 1,
         "HardwareID" : 2,
         "HardwareName" : "RfxCom",
         "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
         "HardwareTypeVal" : 1,
         "HaveTimeout" : false,
         "ID" : "3A00",
         "LastUpdate" : "2019-01-08 22:20:37",
         "Name" : "Pluviomètre",
         "Notifications" : "false",
         "PlanID" : "11",
         "PlanIDs" : [ 11, 16 ],
         "Protected" : false,
         "Rain" : "0.9",
         "RainRate" : "0.9",
         "ShowNotifications" : true,
         "SignalLevel" : 6,
         "SubType" : "PCR800",
         "Timers" : "false",
         "Type" : "Rain",
         "TypeImg" : "rain",
         "Unit" : 0,
         "Used" : 1,
         "XOffset" : "2755",
         "YOffset" : "2074",
         "idx" : "1485"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "NON_EJP",
         "Description" : "",
         "Favorite" : 1,
         "HardwareID" : 12,
         "HardwareName" : "EJP Aujourdhui",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveTimeout" : false,
         "ID" : "83494",
         "LastUpdate" : "2019-01-07 11:01:26",
         "Level" : 0,
         "Name" : "EJP Aujourdhui",
         "Notifications" : "false",
         "PlanID" : "11",
         "PlanIDs" : [ 11 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "Alert",
         "Timers" : "false",
         "Type" : "General",
         "TypeImg" : "Alert",
         "Unit" : 1,
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "1494"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "NON_EJP",
         "Description" : "",
         "Favorite" : 1,
         "HardwareID" : 13,
         "HardwareName" : "EJP Demain",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveTimeout" : false,
         "ID" : "83495",
         "LastUpdate" : "2019-01-08 16:00:03",
         "Level" : 0,
         "Name" : "EJP Demain",
         "Notifications" : "false",
         "PlanID" : "11",
         "PlanIDs" : [ 11 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "Alert",
         "Timers" : "false",
         "Type" : "General",
         "TypeImg" : "Alert",
         "Unit" : 1,
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "1495"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 100,
         "CustomImage" : 0,
         "Data" : "0 Watt, 0 Watt, 0 Watt, Total: 251.079 kWh",
         "Description" : "",
         "Favorite" : 1,
         "HardwareID" : 2,
         "HardwareName" : "RfxCom",
         "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
         "HardwareTypeVal" : 1,
         "HaveTimeout" : false,
         "ID" : "C100",
         "LastUpdate" : "2019-01-08 22:20:35",
         "Name" : "Unknown",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : 7,
         "SubType" : "CM180i",
         "Timers" : "false",
         "Type" : "Current/Energy",
         "TypeImg" : "current",
         "Unit" : 0,
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "displaytype" : 1,
         "idx" : "583"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 1,
         "Data" : "Off",
         "Description" : "PC_Couverture_Chauffante",
         "Favorite" : 1,
         "HardwareID" : 2,
         "HardwareName" : "RfxCom",
         "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
         "HardwareTypeVal" : 1,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "1A9176E",
         "Image" : "WallSocket",
         "IsSubDevice" : false,
         "LastUpdate" : "2019-01-08 00:53:27",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 15,
         "Name" : "PC1_DIO (Couverture Chauffante)",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : 7,
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "AC",
         "SwitchType" : "On/Off",
         "SwitchTypeVal" : 0,
         "Timers" : "false",
         "Type" : "Lighting 2",
         "TypeImg" : "lightbulb",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "1499"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 1,
         "Data" : "Off",
         "Description" : "",
         "Favorite" : 1,
         "HardwareID" : 2,
         "HardwareName" : "RfxCom",
         "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
         "HardwareTypeVal" : 1,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "1A9176E",
         "Image" : "WallSocket",
         "IsSubDevice" : false,
         "LastUpdate" : "2019-01-07 23:33:43",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 15,
         "Name" : "PC2_DIO (Ecl_2 Salon)",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : 7,
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "AC",
         "SwitchType" : "On/Off",
         "SwitchTypeVal" : 0,
         "Timers" : "false",
         "Type" : "Lighting 2",
         "TypeImg" : "lightbulb",
         "Unit" : 2,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "1501"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 1,
         "Data" : "Off",
         "Description" : "",
         "Favorite" : 1,
         "HardwareID" : 2,
         "HardwareName" : "RfxCom",
         "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
         "HardwareTypeVal" : 1,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "1A9176E",
         "Image" : "WallSocket",
         "IsSubDevice" : false,
         "LastUpdate" : "2019-01-07 23:38:41",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 15,
         "Name" : "PC3_DIO (Ventilateur)",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : 7,
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "AC",
         "SwitchType" : "On/Off",
         "SwitchTypeVal" : 0,
         "Timers" : "false",
         "Type" : "Lighting 2",
         "TypeImg" : "lightbulb",
         "Unit" : 3,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "1502"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 1,
         "Data" : "Set Level: 73 %",
         "Description" : "(PC Halogène TV)",
         "Favorite" : 1,
         "HardwareID" : 2,
         "HardwareName" : "RfxCom",
         "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
         "HardwareTypeVal" : 1,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "0050505",
         "Image" : "WallSocket",
         "IsSubDevice" : false,
         "LastUpdate" : "2019-01-08 21:04:46",
         "Level" : 73,
         "LevelInt" : 11,
         "MaxDimLevel" : 15,
         "Name" : "PC4_DIO_Var",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Set Level: 73 %",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "AC",
         "SwitchType" : "Dimmer",
         "SwitchTypeVal" : 7,
         "Timers" : "false",
         "Type" : "Lighting 2",
         "TypeImg" : "dimmer",
         "Unit" : 4,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "1503"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 1,
         "Data" : "On",
         "Description" : "",
         "Favorite" : 0,
         "HardwareID" : 2,
         "HardwareName" : "RfxCom",
         "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
         "HardwareTypeVal" : 1,
         "HaveDimmer" : false,
         "HaveGroupCmd" : false,
         "HaveTimeout" : false,
         "ID" : "145154",
         "Image" : "WallSocket",
         "IsSubDevice" : false,
         "LastUpdate" : "2019-01-08 12:00:13",
         "Level" : 0,
         "LevelInt" : 379,
         "MaxDimLevel" : 0,
         "Name" : "Phénix_Arrêt",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : 7,
         "Status" : "On",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "PT2262",
         "SwitchType" : "On/Off",
         "SwitchTypeVal" : 0,
         "Timers" : "false",
         "Type" : "Lighting 4",
         "TypeImg" : "lightbulb",
         "Unit" : 0,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "1505"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 1,
         "Data" : "On",
         "Description" : "",
         "Favorite" : 0,
         "HardwareID" : 2,
         "HardwareName" : "RfxCom",
         "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
         "HardwareTypeVal" : 1,
         "HaveDimmer" : false,
         "HaveGroupCmd" : false,
         "HaveTimeout" : false,
         "ID" : "145151",
         "Image" : "WallSocket",
         "IsSubDevice" : false,
         "LastUpdate" : "2019-01-08 11:40:49",
         "Level" : 0,
         "LevelInt" : 367,
         "MaxDimLevel" : 0,
         "Name" : "Phénix_Marche",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : 7,
         "Status" : "On",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "PT2262",
         "SwitchType" : "On/Off",
         "SwitchTypeVal" : 0,
         "Timers" : "false",
         "Type" : "Lighting 4",
         "TypeImg" : "lightbulb",
         "Unit" : 0,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "1506"
      }
   ],
   "status" : "OK",
   "title" : "Devices"
});