exports.DOMOTICZ_GET_DEVICES = JSON.stringify({ "ActTime" : 1547393302,
"AstrTwilightEnd" : "19:12",
"AstrTwilightStart" : "06:50",
"CivTwilightEnd" : "17:52",
"CivTwilightStart" : "08:09",
"DayLength" : "08:29",
"NautTwilightEnd" : "18:33",
"NautTwilightStart" : "07:28",
"ServerTime" : "2019-01-13 16:28:22",
"SunAtSouth" : "13:05",
"Sunrise" : "08:46",
"Sunset" : "17:15",
"app_version" : "4.10241",
"result" : [
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 0.0,
"AddjValue2" : 0.0,
"BatteryLevel" : 255,
"CustomImage" : 0,
"Data" : "Off",
"Description" : "",
"DimmerType" : "none",
"Favorite" : 1,
"HardwareID" : 2,
"HardwareName" : "Twincat",
"HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
"HardwareTypeVal" : 15,
"HaveDimmer" : true,
"HaveGroupCmd" : true,
"HaveTimeout" : false,
"ID" : "00014051",
"Image" : "Light",
"IsSubDevice" : false,
"LastUpdate" : "2019-01-06 17:37:37",
"Level" : 0,
"LevelInt" : 0,
"MaxDimLevel" : 100,
"Name" : "test swich",
"Notifications" : "false",
"PlanID" : "0",
"PlanIDs" : [ 0 ],
"Protected" : false,
"ShowNotifications" : true,
"SignalLevel" : "-",
"Status" : "Off",
"StrParam1" : "",
"StrParam2" : "",
"SubType" : "Switch",
"SwitchType" : "On/Off",
"SwitchTypeVal" : 0,
"Timers" : "false",
"Type" : "Light/Switch",
"TypeImg" : "lightbulb",
"Unit" : 1,
"Used" : 1,
"UsedByCamera" : false,
"XOffset" : "0",
"YOffset" : "0",
"idx" : "1"
},
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 0.0,
"AddjValue2" : 0.0,
"BatteryLevel" : 255,
"CustomImage" : 11,
"Data" : "Off",
"Description" : "",
"DimmerType" : "none",
"Favorite" : 0,
"HardwareID" : 2,
"HardwareName" : "Twincat",
"HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
"HardwareTypeVal" : 15,
"HaveDimmer" : true,
"HaveGroupCmd" : true,
"HaveTimeout" : false,
"ID" : "00014058",
"Image" : "Water",
"IsSubDevice" : false,
"LastUpdate" : "2019-01-13 16:28:16",
"Level" : 0,
"LevelInt" : 0,
"MaxDimLevel" : 100,
"Name" : "Chauffe Eau",
"Notifications" : "false",
"PlanID" : "0",
"PlanIDs" : [ 0 ],
"Protected" : false,
"ShowNotifications" : true,
"SignalLevel" : "-",
"Status" : "Off",
"StrParam1" : "",
"StrParam2" : "",
"SubType" : "Switch",
"SwitchType" : "On/Off",
"SwitchTypeVal" : 0,
"Timers" : "false",
"Type" : "Light/Switch",
"TypeImg" : "lightbulb",
"Unit" : 1,
"Used" : 1,
"UsedByCamera" : false,
"XOffset" : "0",
"YOffset" : "0",
"idx" : "8"
},
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 0.0,
"AddjValue2" : 0.0,
"BatteryLevel" : 255,
"Counter" : "332.935 kWh",
"CounterToday" : "15.369 kWh",
"CustomImage" : 0,
"Data" : "332.935 kWh",
"Description" : "",
"Favorite" : 0,
"HardwareID" : 2,
"HardwareName" : "Twincat",
"HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
"HardwareTypeVal" : 15,
"HaveTimeout" : false,
"ID" : "14059",
"LastUpdate" : "2019-01-13 16:28:18",
"Name" : "chauffage",
"Notifications" : "false",
"PlanID" : "0",
"PlanIDs" : [ 0 ],
"Protected" : false,
"ShowNotifications" : true,
"SignalLevel" : "-",
"SubType" : "RFXMeter counter",
"SwitchTypeVal" : 0,
"Timers" : "false",
"Type" : "RFXMeter",
"TypeImg" : "counter",
"Unit" : 1,
"Used" : 1,
"ValueQuantity" : "",
"ValueUnits" : "",
"XOffset" : "0",
"YOffset" : "0",
"idx" : "9"
},
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 0.0,
"AddjValue2" : 0.0,
"BatteryLevel" : 91,
"CustomImage" : 0,
"Data" : "Off",
"Description" : "",
"DimmerType" : "none",
"Favorite" : 0,
"HardwareID" : 3,
"HardwareName" : "zigate",
"HardwareType" : "Zigate plugin",
"HardwareTypeVal" : 94,
"HaveDimmer" : true,
"HaveGroupCmd" : true,
"HaveTimeout" : false,
"ID" : "00158d0002b72992",
"Image" : "Light",
"IsSubDevice" : false,
"LastUpdate" : "2019-01-13 15:56:53",
"Level" : 0,
"LevelInt" : 0,
"MaxDimLevel" : 100,
"Name" : "Entree",
"Notifications" : "false",
"PlanID" : "0",
"PlanIDs" : [ 0 ],
"Protected" : false,
"ShowNotifications" : true,
"SignalLevel" : 5,
"Status" : "Off",
"StrParam1" : "",
"StrParam2" : "",
"SubType" : "Switch",
"SwitchType" : "Motion Sensor",
"SwitchTypeVal" : 8,
"Timers" : "false",
"Type" : "Light/Switch",
"TypeImg" : "motion",
"Unit" : 1,
"Used" : 1,
"UsedByCamera" : false,
"XOffset" : "0",
"YOffset" : "0",
"idx" : "12"
},
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 0.0,
"AddjValue2" : 0.0,
"BatteryLevel" : 91,
"CustomImage" : 0,
"Data" : "0 Lux",
"Description" : "",
"Favorite" : 0,
"HardwareID" : 3,
"HardwareName" : "zigate",
"HardwareType" : "Zigate plugin",
"HardwareTypeVal" : 94,
"HaveTimeout" : false,
"ID" : "00158d0002b72992",
"LastUpdate" : "2019-01-13 15:56:23",
"Name" : "Lux-entree",
"Notifications" : "false",
"PlanID" : "0",
"PlanIDs" : [ 0 ],
"Protected" : false,
"ShowNotifications" : true,
"SignalLevel" : 5,
"SubType" : "Lux",
"Timers" : "false",
"Type" : "Lux",
"TypeImg" : "lux",
"Unit" : 2,
"Used" : 1,
"XOffset" : "0",
"YOffset" : "0",
"idx" : "13"
},
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 0.0,
"AddjValue2" : 0.0,
"BatteryLevel" : 95,
"CustomImage" : 0,
"Data" : "Off",
"Description" : "",
"DimmerType" : "none",
"Favorite" : 0,
"HardwareID" : 3,
"HardwareName" : "zigate",
"HardwareType" : "Zigate plugin",
"HardwareTypeVal" : 94,
"HaveDimmer" : true,
"HaveGroupCmd" : true,
"HaveTimeout" : false,
"ID" : "00158d00028ee773",
"Image" : "Light",
"IsSubDevice" : false,
"LastUpdate" : "2018-12-30 16:20:56",
"Level" : 0,
"LevelInt" : 0,
"MaxDimLevel" : 100,
"Name" : "Smoke salle manger",
"Notifications" : "false",
"PlanID" : "0",
"PlanIDs" : [ 0 ],
"Protected" : false,
"ShowNotifications" : true,
"SignalLevel" : 7,
"Status" : "Off",
"StrParam1" : "",
"StrParam2" : "",
"SubType" : "Switch",
"SwitchType" : "Smoke Detector",
"SwitchTypeVal" : 5,
"Timers" : "false",
"Type" : "Light/Switch",
"TypeImg" : "smoke",
"Unit" : 3,
"Used" : 1,
"UsedByCamera" : false,
"XOffset" : "0",
"YOffset" : "0",
"idx" : "14"
},
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 0.0,
"AddjValue2" : 0.0,
"BatteryLevel" : 255,
"CustomImage" : 0,
"Data" : "Off",
"Description" : "",
"DimmerType" : "none",
"Favorite" : 0,
"HardwareID" : 2,
"HardwareName" : "Twincat",
"HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
"HardwareTypeVal" : 15,
"HaveDimmer" : true,
"HaveGroupCmd" : true,
"HaveTimeout" : false,
"ID" : "0001405F",
"Image" : "Light",
"IsSubDevice" : false,
"LastUpdate" : "2019-01-12 13:53:34",
"Level" : 0,
"LevelInt" : 0,
"MaxDimLevel" : 100,
"Name" : "Julien_gps",
"Notifications" : "false",
"PlanID" : "0",
"PlanIDs" : [ 0 ],
"Protected" : false,
"ShowNotifications" : true,
"SignalLevel" : "-",
"Status" : "Off",
"StrParam1" : "",
"StrParam2" : "",
"SubType" : "Switch",
"SwitchType" : "On/Off",
"SwitchTypeVal" : 0,
"Timers" : "false",
"Type" : "Light/Switch",
"TypeImg" : "lightbulb",
"Unit" : 1,
"Used" : 1,
"UsedByCamera" : false,
"XOffset" : "0",
"YOffset" : "0",
"idx" : "15"
},
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 0.0,
"AddjValue2" : 0.0,
"Barometer" : 996,
"BatteryLevel" : 90,
"CustomImage" : 0,
"Data" : "19.1 C, 52 %, 996 hPa",
"Description" : "",
"DewPoint" : "9.01",
"Favorite" : 0,
"Forecast" : 4,
"ForecastStr" : "Rain",
"HardwareID" : 3,
"HardwareName" : "zigate",
"HardwareType" : "Zigate plugin",
"HardwareTypeVal" : 94,
"HaveTimeout" : false,
"Humidity" : 52,
"HumidityStatus" : "Comfortable",
"ID" : "00158d000272e7c6",
"LastUpdate" : "2019-01-13 15:55:06",
"Name" : "Temperature sejour",
"Notifications" : "false",
"PlanID" : "0",
"PlanIDs" : [ 0 ],
"Protected" : false,
"ShowNotifications" : true,
"SignalLevel" : 8,
"SubType" : "THB1 - BTHR918, BTHGN129",
"Temp" : 19.100000000000001,
"Timers" : "false",
"Type" : "Temp + Humidity + Baro",
"TypeImg" : "temperature",
"Unit" : 4,
"Used" : 1,
"XOffset" : "0",
"YOffset" : "0",
"idx" : "16",
"trend" : 0
},
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 0.0,
"AddjValue2" : 0.0,
"Barometer" : 996,
"BatteryLevel" : 91,
"CustomImage" : 0,
"Data" : "15.5 C, 58 %, 996 hPa",
"Description" : "Temperature chambre du bas",
"DewPoint" : "7.27",
"Favorite" : 0,
"Forecast" : 4,
"ForecastStr" : "Rain",
"HardwareID" : 3,
"HardwareName" : "zigate",
"HardwareType" : "Zigate plugin",
"HardwareTypeVal" : 94,
"HaveTimeout" : false,
"Humidity" : 58,
"HumidityStatus" : "Comfortable",
"ID" : "00158d0002726468",
"LastUpdate" : "2019-01-13 15:57:43",
"Name" : "Temperature chambre",
"Notifications" : "false",
"PlanID" : "2",
"PlanIDs" : [ 2 ],
"Protected" : false,
"ShowNotifications" : true,
"SignalLevel" : 5,
"SubType" : "THB1 - BTHR918, BTHGN129",
"Temp" : 15.5,
"Timers" : "false",
"Type" : "Temp + Humidity + Baro",
"TypeImg" : "temperature",
"Unit" : 9,
"Used" : 1,
"XOffset" : "0",
"YOffset" : "0",
"idx" : "21",
"trend" : 0
},
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 0.0,
"AddjValue2" : 0.0,
"BatteryLevel" : 255,
"Counter" : "170.630 kWh",
"CounterToday" : "0.000 kWh",
"CustomImage" : 0,
"Data" : "170.630 kWh",
"Description" : "",
"Favorite" : 0,
"HardwareID" : 2,
"HardwareName" : "Twincat",
"HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
"HardwareTypeVal" : 15,
"HaveTimeout" : false,
"ID" : "1406A",
"LastUpdate" : "2019-01-13 16:28:20",
"Name" : "voiture",
"Notifications" : "false",
"PlanID" : "0",
"PlanIDs" : [ 0 ],
"Protected" : false,
"ShowNotifications" : true,
"SignalLevel" : "-",
"SubType" : "RFXMeter counter",
"SwitchTypeVal" : 0,
"Timers" : "false",
"Type" : "RFXMeter",
"TypeImg" : "counter",
"Unit" : 1,
"Used" : 1,
"ValueQuantity" : "",
"ValueUnits" : "",
"XOffset" : "0",
"YOffset" : "0",
"idx" : "26"
},
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 0.0,
"AddjValue2" : 0.0,
"BatteryLevel" : 255,
"CustomImage" : 9,
"Data" : "Off",
"Description" : "",
"DimmerType" : "none",
"Favorite" : 1,
"HardwareID" : 2,
"HardwareName" : "Twincat",
"HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
"HardwareTypeVal" : 15,
"HaveDimmer" : true,
"HaveGroupCmd" : true,
"HaveTimeout" : false,
"ID" : "0001406B",
"Image" : "Generic",
"IsSubDevice" : false,
"LastUpdate" : "2019-01-06 17:37:42",
"Level" : 0,
"LevelInt" : 0,
"MaxDimLevel" : 100,
"Name" : "power_button",
"Notifications" : "false",
"PlanID" : "0",
"PlanIDs" : [ 0 ],
"Protected" : false,
"ShowNotifications" : true,
"SignalLevel" : "-",
"Status" : "Off",
"StrParam1" : "",
"StrParam2" : "",
"SubType" : "Switch",
"SwitchType" : "On/Off",
"SwitchTypeVal" : 0,
"Timers" : "false",
"Type" : "Light/Switch",
"TypeImg" : "lightbulb",
"Unit" : 1,
"Used" : 1,
"UsedByCamera" : false,
"XOffset" : "0",
"YOffset" : "0",
"idx" : "27"
},
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 0.0,
"AddjValue2" : 0.0,
"BatteryLevel" : 255,
"CustomImage" : 0,
"Data" : "Off",
"Description" : "",
"DimmerType" : "none",
"Favorite" : 0,
"HardwareID" : 2,
"HardwareName" : "Twincat",
"HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
"HardwareTypeVal" : 15,
"HaveDimmer" : true,
"HaveGroupCmd" : true,
"HaveTimeout" : false,
"ID" : "0001406C",
"Image" : "Light",
"IsSubDevice" : false,
"LastUpdate" : "2019-01-12 19:19:49",
"Level" : 0,
"LevelInt" : 0,
"MaxDimLevel" : 100,
"Name" : "Solène gps",
"Notifications" : "false",
"PlanID" : "0",
"PlanIDs" : [ 0 ],
"Protected" : false,
"ShowNotifications" : true,
"SignalLevel" : "-",
"Status" : "Off",
"StrParam1" : "",
"StrParam2" : "",
"SubType" : "Switch",
"SwitchType" : "On/Off",
"SwitchTypeVal" : 0,
"Timers" : "false",
"Type" : "Light/Switch",
"TypeImg" : "lightbulb",
"Unit" : 1,
"Used" : 1,
"UsedByCamera" : false,
"XOffset" : "0",
"YOffset" : "0",
"idx" : "28"
},
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 0.0,
"AddjValue2" : 0.0,
"BatteryLevel" : 255,
"CustomImage" : 0,
"Data" : "Off",
"Description" : "",
"DimmerType" : "abs",
"Favorite" : 0,
"HardwareID" : 3,
"HardwareName" : "zigate",
"HardwareType" : "Zigate plugin",
"HardwareTypeVal" : 94,
"HaveDimmer" : true,
"HaveGroupCmd" : true,
"HaveTimeout" : false,
"ID" : "000b57fffe94ffe0",
"Image" : "Light",
"IsSubDevice" : false,
"LastUpdate" : "2018-12-28 16:40:52",
"Level" : 100,
"LevelInt" : 100,
"MaxDimLevel" : 100,
"Name" : "lumiere 1 sallon",
"Notifications" : "false",
"PlanID" : "0",
"PlanIDs" : [ 0 ],
"Protected" : false,
"ShowNotifications" : true,
"SignalLevel" : "-",
"Status" : "Off",
"StrParam1" : "",
"StrParam2" : "",
"SubType" : "Switch",
"SwitchType" : "Dimmer",
"SwitchTypeVal" : 7,
"Timers" : "false",
"Type" : "Light/Switch",
"TypeImg" : "dimmer",
"Unit" : 14,
"Used" : 1,
"UsedByCamera" : false,
"XOffset" : "0",
"YOffset" : "0",
"idx" : "29"
},
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 0.0,
"AddjValue2" : 0.0,
"BatteryLevel" : 255,
"CustomImage" : 0,
"Data" : "On",
"Description" : "",
"DimmerType" : "abs",
"Favorite" : 0,
"HardwareID" : 3,
"HardwareName" : "zigate",
"HardwareType" : "Zigate plugin",
"HardwareTypeVal" : 94,
"HaveDimmer" : true,
"HaveGroupCmd" : true,
"HaveTimeout" : false,
"ID" : "000b57fffe8e8b2e",
"Image" : "Light",
"IsSubDevice" : false,
"LastUpdate" : "2018-12-30 22:15:09",
"Level" : 17,
"LevelInt" : 17,
"MaxDimLevel" : 100,
"Name" : "lumiere 2 sallon",
"Notifications" : "false",
"PlanID" : "0",
"PlanIDs" : [ 0 ],
"Protected" : false,
"ShowNotifications" : true,
"SignalLevel" : "-",
"Status" : "On",
"StrParam1" : "",
"StrParam2" : "",
"SubType" : "Switch",
"SwitchType" : "Dimmer",
"SwitchTypeVal" : 7,
"Timers" : "false",
"Type" : "Light/Switch",
"TypeImg" : "dimmer",
"Unit" : 15,
"Used" : 1,
"UsedByCamera" : false,
"XOffset" : "0",
"YOffset" : "0",
"idx" : "30"
},
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 0.0,
"AddjValue2" : 0.0,
"BatteryLevel" : 255,
"CustomImage" : 0,
"Data" : "Off",
"Description" : "",
"DimmerType" : "abs",
"Favorite" : 0,
"HardwareID" : 3,
"HardwareName" : "zigate",
"HardwareType" : "Zigate plugin",
"HardwareTypeVal" : 94,
"HaveDimmer" : true,
"HaveGroupCmd" : true,
"HaveTimeout" : false,
"ID" : "90fd9ffffe13678a",
"Image" : "Light",
"IsSubDevice" : false,
"LastUpdate" : "2019-01-13 16:26:40",
"Level" : 95,
"LevelInt" : 95,
"MaxDimLevel" : 100,
"Name" : "chambre rue",
"Notifications" : "false",
"PlanID" : "0",
"PlanIDs" : [ 0 ],
"Protected" : false,
"ShowNotifications" : true,
"SignalLevel" : "-",
"Status" : "Off",
"StrParam1" : "",
"StrParam2" : "",
"SubType" : "Switch",
"SwitchType" : "Dimmer",
"SwitchTypeVal" : 7,
"Timers" : "false",
"Type" : "Light/Switch",
"TypeImg" : "dimmer",
"Unit" : 16,
"Used" : 1,
"UsedByCamera" : false,
"XOffset" : "0",
"YOffset" : "0",
"idx" : "31"
},
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 0.0,
"AddjValue2" : 0.0,
"BatteryLevel" : 255,
"CustomImage" : 0,
"Data" : "On",
"Description" : "",
"DimmerType" : "abs",
"Favorite" : 0,
"HardwareID" : 3,
"HardwareName" : "zigate",
"HardwareType" : "Zigate plugin",
"HardwareTypeVal" : 94,
"HaveDimmer" : true,
"HaveGroupCmd" : true,
"HaveTimeout" : false,
"ID" : "d0cf5efffe0df2c0",
"Image" : "Light",
"IsSubDevice" : false,
"LastUpdate" : "2018-12-28 16:32:04",
"Level" : 100,
"LevelInt" : 100,
"MaxDimLevel" : 100,
"Name" : "interupteur sallon",
"Notifications" : "false",
"PlanID" : "0",
"PlanIDs" : [ 0 ],
"Protected" : false,
"ShowNotifications" : true,
"SignalLevel" : "-",
"Status" : "On",
"StrParam1" : "",
"StrParam2" : "",
"SubType" : "Switch",
"SwitchType" : "Dimmer",
"SwitchTypeVal" : 7,
"Timers" : "false",
"Type" : "Light/Switch",
"TypeImg" : "dimmer",
"Unit" : 17,
"Used" : 1,
"UsedByCamera" : false,
"XOffset" : "0",
"YOffset" : "0",
"idx" : "32"
},
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 0.0,
"AddjValue2" : 0.0,
"Barometer" : 996,
"BatteryLevel" : 90,
"CustomImage" : 0,
"Data" : "15.6 C, 62 %, 996 hPa",
"Description" : "",
"DewPoint" : "8.34",
"Favorite" : 0,
"Forecast" : 4,
"ForecastStr" : "Rain",
"HardwareID" : 3,
"HardwareName" : "zigate",
"HardwareType" : "Zigate plugin",
"HardwareTypeVal" : 94,
"HaveTimeout" : false,
"Humidity" : 62,
"HumidityStatus" : "Comfortable",
"ID" : "00158d0002b6ccaf",
"LastUpdate" : "2019-01-13 16:11:03",
"Name" : "Temperature salle de bain",
"Notifications" : "false",
"PlanID" : "0",
"PlanIDs" : [ 0 ],
"Protected" : false,
"ShowNotifications" : true,
"SignalLevel" : 2,
"SubType" : "THB1 - BTHR918, BTHGN129",
"Temp" : 15.6,
"Timers" : "false",
"Type" : "Temp + Humidity + Baro",
"TypeImg" : "temperature",
"Unit" : 18,
"Used" : 1,
"XOffset" : "0",
"YOffset" : "0",
"idx" : "33",
"trend" : 0
}
],
"status" : "OK",
"title" : "Devices"
});