exports.DOMOTICZ_GET_DEVICES = JSON.stringify({
	"ActTime" : 1575919850,
	"AstrTwilightEnd" : "18:45",
	"AstrTwilightStart" : "06:37",
	"CivTwilightEnd" : "17:24",
	"CivTwilightStart" : "07:58",
	"DayLength" : "08:09",
	"NautTwilightEnd" : "18:05",
	"NautTwilightStart" : "07:16",
	"ServerTime" : "2019-12-09 20:30:50",
	"SunAtSouth" : "12:41",
	"Sunrise" : "08:36",
	"Sunset" : "16:45",
	"app_version" : "4.10717",
	"result" : [
	{
	"AddjMulti" : 1.0,
	"AddjMulti2" : 1.0,
	"AddjValue" : 0.0,
	"AddjValue2" : 0.0,
	"BatteryLevel" : 255,
	"CustomImage" : 0,
	"Data" : "On",
	"Description" : "",
	"DimmerType" : "none",
	"Favorite" : 1,
	"HardwareID" : 2,
	"HardwareName" : "RFLink",
	"HardwareType" : "RFLink Gateway USB",
	"HardwareTypeVal" : 46,
	"HaveDimmer" : true,
	"HaveGroupCmd" : true,
	"HaveTimeout" : false,
	"ID" : "02AF4000",
	"Image" : "Light",
	"IsSubDevice" : false,
	"LastUpdate" : "2019-12-09 19:52:28",
	"Level" : 0,
	"LevelInt" : 0,
	"MaxDimLevel" : 100,
	"Name" : "Lumiere Salon",
	"Notifications" : "false",
	"PlanID" : "0",
	"PlanIDs" : [ 0 ],
	"Protected" : false,
	"ShowNotifications" : true,
	"SignalLevel" : "-",
	"Status" : "On",
	"StrParam1" : "",
	"StrParam2" : "",
	"SubType" : "AC",
	"SwitchType" : "On/Off",
	"SwitchTypeVal" : 0,
	"Timers" : "false",
	"Type" : "Light/Switch",
	"TypeImg" : "lightbulb",
	"Unit" : 2,
	"Used" : 1,
	"UsedByCamera" : false,
	"XOffset" : "0",
	"YOffset" : "0",
	"idx" : "1"
	},
	{
	"AddjMulti" : 1.0,
	"AddjMulti2" : 1.0,
	"AddjValue" : 2700.0,
	"AddjValue2" : 0.0,
	"BatteryLevel" : 255,
	"CustomImage" : 0,
	"Data" : "Off",
	"Description" : "",
	"DimmerType" : "none",
	"Favorite" : 1,
	"HardwareID" : 2,
	"HardwareName" : "RFLink",
	"HardwareType" : "RFLink Gateway USB",
	"HardwareTypeVal" : 46,
	"HaveDimmer" : true,
	"HaveGroupCmd" : true,
	"HaveTimeout" : false,
	"ID" : "02AF4000",
	"Image" : "Light",
	"IsSubDevice" : false,
	"LastUpdate" : "2019-12-09 19:52:18",
	"Level" : 0,
	"LevelInt" : 0,
	"MaxDimLevel" : 100,
	"Name" : "Cafetiere",
	"Notifications" : "false",
	"PlanID" : "0",
	"PlanIDs" : [ 0 ],
	"Protected" : false,
	"ShowNotifications" : true,
	"SignalLevel" : "-",
	"Status" : "Off",
	"StrParam1" : "",
	"StrParam2" : "",
	"SubType" : "AC",
	"SwitchType" : "On/Off",
	"SwitchTypeVal" : 0,
	"Timers" : "false",
	"Type" : "Light/Switch",
	"TypeImg" : "lightbulb",
	"Unit" : 4,
	"Used" : 1,
	"UsedByCamera" : false,
	"XOffset" : "0",
	"YOffset" : "0",
	"idx" : "3"
	},
	{
	"AddjMulti" : 1.0,
	"AddjMulti2" : 1.0,
	"AddjValue" : 0.0,
	"AddjValue2" : 0.0,
	"BatteryLevel" : 255,
	"CustomImage" : 0,
	"Data" : "Closed",
	"Description" : "",
	"DimmerType" : "none",
	"Favorite" : 0,
	"HardwareID" : 2,
	"HardwareName" : "RFLink",
	"HardwareType" : "RFLink Gateway USB",
	"HardwareTypeVal" : 46,
	"HaveDimmer" : true,
	"HaveGroupCmd" : true,
	"HaveTimeout" : false,
	"ID" : "01D103E6",
	"Image" : "Light",
	"IsSubDevice" : false,
	"LastUpdate" : "2019-12-09 17:05:02",
	"Level" : 0,
	"LevelInt" : 0,
	"MaxDimLevel" : 100,
	"Name" : "Volet Salle a manger",
	"Notifications" : "false",
	"PlanID" : "0",
	"PlanIDs" : [ 0 ],
	"Protected" : false,
	"ShowNotifications" : true,
	"SignalLevel" : "-",
	"Status" : "Closed",
	"StrParam1" : "",
	"StrParam2" : "",
	"SubType" : "AC",
	"SwitchType" : "Blinds",
	"SwitchTypeVal" : 3,
	"Timers" : "true",
	"Type" : "Light/Switch",
	"TypeImg" : "blinds",
	"Unit" : 1,
	"Used" : 1,
	"UsedByCamera" : false,
	"XOffset" : "0",
	"YOffset" : "0",
	"idx" : "10"
	},
	{
	"AddjMulti" : 1.0,
	"AddjMulti2" : 1.0,
	"AddjValue" : 0.0,
	"AddjValue2" : 0.0,
	"BatteryLevel" : 255,
	"CustomImage" : 0,
	"Data" : "Closed",
	"Description" : "",
	"DimmerType" : "none",
	"Favorite" : 0,
	"HardwareID" : 2,
	"HardwareName" : "RFLink",
	"HardwareType" : "RFLink Gateway USB",
	"HardwareTypeVal" : 46,
	"HaveDimmer" : true,
	"HaveGroupCmd" : true,
	"HaveTimeout" : false,
	"ID" : "01D112CA",
	"Image" : "Light",
	"IsSubDevice" : false,
	"LastUpdate" : "2019-12-09 17:05:03",
	"Level" : 0,
	"LevelInt" : 0,
	"MaxDimLevel" : 100,
	"Name" : "Volet Cuisine",
	"Notifications" : "false",
	"PlanID" : "0",
	"PlanIDs" : [ 0 ],
	"Protected" : false,
	"ShowNotifications" : true,
	"SignalLevel" : "-",
	"Status" : "Closed",
	"StrParam1" : "",
	"StrParam2" : "",
	"SubType" : "AC",
	"SwitchType" : "Blinds",
	"SwitchTypeVal" : 3,
	"Timers" : "true",
	"Type" : "Light/Switch",
	"TypeImg" : "blinds",
	"Unit" : 1,
	"Used" : 1,
	"UsedByCamera" : false,
	"XOffset" : "0",
	"YOffset" : "0",
	"idx" : "11"
	},
	{
	"AddjMulti" : 1.0,
	"AddjMulti2" : 1.0,
	"AddjValue" : 0.0,
	"AddjValue2" : 0.0,
	"BatteryLevel" : 255,
	"CustomImage" : 0,
	"Data" : "Closed",
	"Description" : "",
	"DimmerType" : "none",
	"Favorite" : 0,
	"HardwareID" : 2,
	"HardwareName" : "RFLink",
	"HardwareType" : "RFLink Gateway USB",
	"HardwareTypeVal" : 46,
	"HaveDimmer" : true,
	"HaveGroupCmd" : true,
	"HaveTimeout" : false,
	"ID" : "01BAEFF2",
	"Image" : "Light",
	"IsSubDevice" : false,
	"LastUpdate" : "2019-12-09 19:44:31",
	"Level" : 0,
	"LevelInt" : 0,
	"MaxDimLevel" : 100,
	"Name" : "Volet Chambre Filles",
	"Notifications" : "false",
	"PlanID" : "0",
	"PlanIDs" : [ 0 ],
	"Protected" : false,
	"ShowNotifications" : true,
	"SignalLevel" : "-",
	"Status" : "Closed",
	"StrParam1" : "",
	"StrParam2" : "",
	"SubType" : "AC",
	"SwitchType" : "Blinds",
	"SwitchTypeVal" : 3,
	"Timers" : "true",
	"Type" : "Light/Switch",
	"TypeImg" : "blinds",
	"Unit" : 1,
	"Used" : 1,
	"UsedByCamera" : false,
	"XOffset" : "0",
	"YOffset" : "0",
	"idx" : "12"
	},
	{
	"AddjMulti" : 1.0,
	"AddjMulti2" : 1.0,
	"AddjValue" : 0.0,
	"AddjValue2" : 0.0,
	"BatteryLevel" : 255,
	"CustomImage" : 0,
	"Data" : "Open",
	"Description" : "",
	"DimmerType" : "none",
	"Favorite" : 0,
	"HardwareID" : 2,
	"HardwareName" : "RFLink",
	"HardwareType" : "RFLink Gateway USB",
	"HardwareTypeVal" : 46,
	"HaveDimmer" : true,
	"HaveGroupCmd" : true,
	"HaveTimeout" : false,
	"ID" : "01BAD3EE",
	"Image" : "Light",
	"IsSubDevice" : false,
	"LastUpdate" : "2019-12-09 06:36:12",
	"Level" : 0,
	"LevelInt" : 0,
	"MaxDimLevel" : 100,
	"Name" : "Volet Chambre",
	"Notifications" : "false",
	"PlanID" : "0",
	"PlanIDs" : [ 0 ],
	"Protected" : false,
	"ShowNotifications" : true,
	"SignalLevel" : "-",
	"Status" : "Open",
	"StrParam1" : "",
	"StrParam2" : "",
	"SubType" : "AC",
	"SwitchType" : "Blinds",
	"SwitchTypeVal" : 3,
	"Timers" : "false",
	"Type" : "Light/Switch",
	"TypeImg" : "blinds",
	"Unit" : 1,
	"Used" : 1,
	"UsedByCamera" : false,
	"XOffset" : "0",
	"YOffset" : "0",
	"idx" : "13"
	},
	{
	"AddjMulti" : 1.0,
	"AddjMulti2" : 1.0,
	"AddjValue" : 0.0,
	"AddjValue2" : 0.0,
	"BatteryLevel" : 255,
	"CustomImage" : 0,
	"Data" : "Closed",
	"Description" : "",
	"DimmerType" : "none",
	"Favorite" : 0,
	"HardwareID" : 2,
	"HardwareName" : "RFLink",
	"HardwareType" : "RFLink Gateway USB",
	"HardwareTypeVal" : 46,
	"HaveDimmer" : true,
	"HaveGroupCmd" : true,
	"HaveTimeout" : false,
	"ID" : "01BAC522",
	"Image" : "Light",
	"IsSubDevice" : false,
	"LastUpdate" : "2019-12-09 17:05:04",
	"Level" : 0,
	"LevelInt" : 0,
	"MaxDimLevel" : 100,
	"Name" : "Volet Salon",
	"Notifications" : "false",
	"PlanID" : "0",
	"PlanIDs" : [ 0 ],
	"Protected" : false,
	"ShowNotifications" : true,
	"SignalLevel" : "-",
	"Status" : "Closed",
	"StrParam1" : "",
	"StrParam2" : "",
	"SubType" : "AC",
	"SwitchType" : "Blinds",
	"SwitchTypeVal" : 3,
	"Timers" : "true",
	"Type" : "Light/Switch",
	"TypeImg" : "blinds",
	"Unit" : 1,
	"Used" : 1,
	"UsedByCamera" : false,
	"XOffset" : "0",
	"YOffset" : "0",
	"idx" : "16"
	}
	],
	"status" : "OK",
	"title" : "Devices"
});