exports.DOMOTICZ_GET_DEVICES = JSON.stringify(
	{
	ActTime: 1546028276,
	AstrTwilightEnd: "18:55",
	AstrTwilightStart: "06:45",
	CivTwilightEnd: "17:37",
	CivTwilightStart: "08:03",
	DayLength: "08:21",
	NautTwilightEnd: "18:17",
	NautTwilightStart: "07:23",
	ServerTime: "2018-12-28 21:17:56",
	SunAtSouth: "12:05",
	Sunrise: "08:40",
	Sunset: "17:01",
	app_version: "4.9700",
	result: [
	{
	Data: "On",
	Description: "",
	Favorite: 0,
	LastUpdate: "2018-12-22 15:39:39",
	Name: "Chien",
	PlanID: "",
	PlanIDs: [
	0
	],
	Protected: false,
	Status: "On",
	Type: "Scene",
	TypeImg: "scene",
	UsedByCamera: false,
	XOffset: 0,
	YOffset: 0,
	idx: "1"
	},
	{
	AddjMulti: 1,
	AddjMulti2: 1,
	AddjValue: 0,
	AddjValue2: 0,
	BatteryLevel: 100,
	CustomImage: 0,
	Data: "22.5 C, 36 %",
	Description: "",
	DewPoint: "6.68",
	Favorite: 1,
	HardwareID: 2,
	HardwareName: "rfxcom",
	HardwareType: "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
	HardwareTypeVal: 1,
	HaveTimeout: false,
	Humidity: 36,
	HumidityStatus: "Dry",
	ID: "1C31",
	LastUpdate: "2018-12-28 21:17:11",
	Name: "temperature maison",
	Notifications: "false",
	PlanID: "2",
	PlanIDs: [
	2
	],
	Protected: false,
	ShowNotifications: true,
	SignalLevel: 6,
	SubType: "Alecto WS1700",
	Temp: 22.5,
	Timers: "false",
	Type: "Temp + Humidity",
	TypeImg: "temperature",
	Unit: 49,
	Used: 1,
	XOffset: "0",
	YOffset: "0",
	idx: "1"
	},
	{
	AddjMulti: 1,
	AddjMulti2: 1,
	AddjValue: 0,
	AddjValue2: 0,
	BatteryLevel: 255,
	CustomImage: 0,
	Data: "Off",
	Description: "",
	DimmerType: "none",
	Favorite: 1,
	HardwareID: 2,
	HardwareName: "rfxcom",
	HardwareType: "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
	HardwareTypeVal: 1,
	HaveDimmer: false,
	HaveGroupCmd: true,
	HaveTimeout: false,
	ID: "CAA9",
	Image: "Light",
	IsSubDevice: false,
	LastUpdate: "2018-12-28 21:00:01",
	Level: 0,
	LevelInt: 0,
	MaxDimLevel: 0,
	Name: "lumiere sapin",
	Notifications: "false",
	PlanID: "2",
	PlanIDs: [
	2
	],
	Protected: false,
	ShowNotifications: true,
	SignalLevel: "-",
	Status: "Off",
	StrParam1: "",
	StrParam2: "",
	SubType: "Kangtai / Cotech",
	SwitchType: "On/Off",
	SwitchTypeVal: 0,
	Timers: "true",
	Type: "Lighting 5",
	TypeImg: "lightbulb",
	Unit: 1,
	Used: 1,
	UsedByCamera: false,
	XOffset: "0",
	YOffset: "0",
	idx: "3"
	},
	{
	AddjMulti: 1,
	AddjMulti2: 1,
	AddjValue: 0,
	AddjValue2: 0,
	BatteryLevel: 255,
	CustomImage: 0,
	Data: "On",
	Description: "",
	DimmerType: "none",
	Favorite: 0,
	HardwareID: 2,
	HardwareName: "rfxcom",
	HardwareType: "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
	HardwareTypeVal: 1,
	HaveDimmer: false,
	HaveGroupCmd: true,
	HaveTimeout: false,
	ID: "0D1747",
	Image: "Light",
	IsSubDevice: false,
	LastUpdate: "2018-12-27 22:06:38",
	Level: 0,
	LevelInt: 0,
	MaxDimLevel: 0,
	Name: "Vmc",
	Notifications: "false",
	PlanID: "2",
	PlanIDs: [
	2
	],
	Protected: false,
	ShowNotifications: true,
	SignalLevel: "-",
	Status: "On",
	StrParam1: "",
	StrParam2: "",
	SubType: "Blyss",
	SwitchType: "On/Off",
	SwitchTypeVal: 0,
	Timers: "false",
	Type: "Lighting 6",
	TypeImg: "lightbulb",
	Unit: 1,
	Used: 1,
	UsedByCamera: false,
	XOffset: "0",
	YOffset: "0",
	idx: "5"
	},
	{
	AddjMulti: 1,
	AddjMulti2: 1,
	AddjValue: 0,
	AddjValue2: 0,
	BatteryLevel: 255,
	CustomImage: 0,
	Data: "Off",
	Description: "",
	DimmerType: "none",
	Favorite: 1,
	HardwareID: 2,
	HardwareName: "rfxcom",
	HardwareType: "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
	HardwareTypeVal: 1,
	HaveDimmer: false,
	HaveGroupCmd: true,
	HaveTimeout: false,
	ID: "CAA9",
	Image: "Light",
	IsSubDevice: false,
	LastUpdate: "2018-12-28 21:00:01",
	Level: 0,
	LevelInt: 0,
	MaxDimLevel: 0,
	Name: "Chien",
	Notifications: "false",
	PlanID: "0",
	PlanIDs: [
	0
	],
	Protected: false,
	ShowNotifications: true,
	SignalLevel: "-",
	Status: "Off",
	StrParam1: "",
	StrParam2: "",
	SubType: "Kangtai / Cotech",
	SwitchType: "On/Off",
	SwitchTypeVal: 0,
	Timers: "false",
	Type: "Lighting 5",
	TypeImg: "lightbulb",
	Unit: 2,
	Used: 1,
	UsedByCamera: false,
	XOffset: "0",
	YOffset: "0",
	idx: "4"
	},
	{
	AddjMulti: 1,
	AddjMulti2: 1,
	AddjValue: 0,
	AddjValue2: 0,
	BatteryLevel: 255,
	CustomImage: 0,
	Data: "Closed",
	Description: "",
	DimmerType: "none",
	Favorite: 1,
	HardwareID: 2,
	HardwareName: "rfxcom",
	HardwareType: "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
	HardwareTypeVal: 1,
	HaveDimmer: false,
	HaveGroupCmd: false,
	HaveTimeout: false,
	ID: "010101",
	Image: "Light",
	IsSubDevice: false,
	LastUpdate: "2018-12-28 17:15:01",
	Level: 0,
	LevelInt: 0,
	MaxDimLevel: 0,
	Name: "volet cuisine",
	Notifications: "false",
	PlanID: "2",
	PlanIDs: [
	2
	],
	Protected: false,
	ShowNotifications: true,
	SignalLevel: "-",
	Status: "Closed",
	StrParam1: "",
	StrParam2: "",
	SubType: "ASA",
	SwitchType: "Blinds",
	SwitchTypeVal: 3,
	Timers: "true",
	Type: "RFY",
	TypeImg: "blinds",
	Unit: 1,
	Used: 1,
	UsedByCamera: false,
	XOffset: "0",
	YOffset: "0",
	idx: "2"
	},
	{
	AddjMulti: 1,
	AddjMulti2: 1,
	AddjValue: 0,
	AddjValue2: 0,
	BatteryLevel: 255,
	CustomImage: 0,
	Data: "On",
	Description: "",
	DimmerType: "none",
	Favorite: 0,
	HardwareID: 2,
	HardwareName: "rfxcom",
	HardwareType: "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
	HardwareTypeVal: 1,
	HaveDimmer: false,
	HaveGroupCmd: true,
	HaveTimeout: false,
	ID: "CAA9",
	Image: "Light",
	IsSubDevice: false,
	LastUpdate: "2018-12-28 16:00:01",
	Level: 0,
	LevelInt: 0,
	MaxDimLevel: 0,
	Name: "pere noël",
	Notifications: "false",
	PlanID: "0",
	PlanIDs: [
	0
	],
	Protected: false,
	ShowNotifications: true,
	SignalLevel: "-",
	Status: "On",
	StrParam1: "",
	StrParam2: "",
	SubType: "Kangtai / Cotech",
	SwitchType: "On/Off",
	SwitchTypeVal: 0,
	Timers: "true",
	Type: "Lighting 5",
	TypeImg: "lightbulb",
	Unit: 3,
	Used: 1,
	UsedByCamera: false,
	XOffset: "0",
	YOffset: "0",
	idx: "28"
	},
	{
	AddjMulti: 1,
	AddjMulti2: 1,
	AddjValue: 0,
	AddjValue2: 0,
	BatteryLevel: 255,
	CustomImage: 5,
	Data: "",
	Description: "",
	DimmerType: "none",
	Favorite: 0,
	HardwareID: 3,
	HardwareName: "Yamaha",
	HardwareType: "Yamaha AV Receiver with Kodi Remote",
	HardwareTypeVal: 94,
	HaveDimmer: true,
	HaveGroupCmd: true,
	HaveTimeout: false,
	ID: "0003000A",
	Image: "Amplifier",
	IsSubDevice: false,
	LastUpdate: "2018-12-27 22:29:42",
	Level: 0,
	LevelInt: 0,
	MaxDimLevel: 15,
	Name: "Yamaha - Main",
	Notifications: "false",
	PlanID: "0",
	PlanIDs: [
	0
	],
	Protected: false,
	ShowNotifications: true,
	SignalLevel: "-",
	Status: "Off",
	StrParam1: "",
	StrParam2: "",
	SubType: "AC",
	SwitchType: "Media Player",
	SwitchTypeVal: 17,
	Timers: "false",
	Type: "Lighting 2",
	TypeImg: "Media",
	Unit: 10,
	Used: 1,
	UsedByCamera: false,
	XOffset: "0",
	YOffset: "0",
	idx: "31"
	},
	{
	AddjMulti: 1,
	AddjMulti2: 1,
	AddjValue: 0,
	AddjValue2: 0,
	BatteryLevel: 255,
	CustomImage: 8,
	Data: "On",
	Description: "",
	DimmerType: "abs",
	Favorite: 0,
	HardwareID: 3,
	HardwareName: "Yamaha",
	HardwareType: "Yamaha AV Receiver with Kodi Remote",
	HardwareTypeVal: 94,
	HaveDimmer: true,
	HaveGroupCmd: true,
	HaveTimeout: false,
	ID: "0003000B",
	Image: "Speaker",
	IsSubDevice: false,
	LastUpdate: "2018-12-27 21:28:20",
	Level: 40,
	LevelInt: 40,
	MaxDimLevel: 100,
	Name: "Yamaha - Volume Main",
	Notifications: "false",
	PlanID: "0",
	PlanIDs: [
	0
	],
	Protected: false,
	ShowNotifications: true,
	SignalLevel: "-",
	Status: "On",
	StrParam1: "",
	StrParam2: "",
	SubType: "Switch",
	SwitchType: "Dimmer",
	SwitchTypeVal: 7,
	Timers: "false",
	Type: "Light/Switch",
	TypeImg: "dimmer",
	Unit: 11,
	Used: 1,
	UsedByCamera: false,
	XOffset: "0",
	YOffset: "0",
	idx: "32"
	},
	{
	AddjMulti: 1,
	AddjMulti2: 1,
	AddjValue: 0,
	AddjValue2: 0,
	BatteryLevel: 255,
	CustomImage: 101,
	Data: "On",
	Description: "",
	DimmerType: "none",
	Favorite: 0,
	HardwareID: 3,
	HardwareName: "Yamaha",
	HardwareType: "Yamaha AV Receiver with Kodi Remote",
	HardwareTypeVal: 94,
	HaveDimmer: true,
	HaveGroupCmd: true,
	HaveTimeout: false,
	ID: "0003000C",
	Image: "Yamaha",
	IsSubDevice: false,
	LastUpdate: "2018-12-28 21:14:57",
	Level: 60,
	LevelActions: "",
	LevelInt: 60,
	LevelNames: "T2ZmfFNJUklVU3xUVU5FUnxIRHxIRE1JMXxIRE1JMnxIRE1JM3xIRE1JNHxIRE1JNXxIRE1JNnxIRE1JN3xBVjF8QVYyfEFWM3xBVjR8QVY1fEFWNnxWLUFVWHxBVURJTzF8QVVESU8yfERPQ0t8aVBvZHxCbHVldG9vdGh8VUFXfE5FVHxSaGFwc29keXxTSVJJVVMgSW50ZXJuZXRSYWRpb3xQYW5kb3JhfE5hcHN0ZXJ8UEN8TkVUIFJBRElPfFVTQnxpUG9kIChVU0Ip",
	LevelOffHidden: true,
	MaxDimLevel: 100,
	Name: "Yamaha - Input Main",
	Notifications: "false",
	PlanID: "0",
	PlanIDs: [
	0
	],
	Protected: false,
	SelectorStyle: 1,
	ShowNotifications: true,
	SignalLevel: "-",
	Status: "On",
	StrParam1: "",
	StrParam2: "",
	SubType: "Selector Switch",
	SwitchType: "Selector",
	SwitchTypeVal: 18,
	Timers: "false",
	Type: "Light/Switch",
	TypeImg: "Light",
	Unit: 12,
	Used: 1,
	UsedByCamera: false,
	XOffset: "0",
	YOffset: "0",
	idx: "33"
	},
	{
	AddjMulti: 1,
	AddjMulti2: 1,
	AddjValue: 0,
	AddjValue2: 0,
	BatteryLevel: 255,
	CustomImage: 101,
	Data: "On",
	Description: "",
	DimmerType: "none",
	Favorite: 0,
	HardwareID: 3,
	HardwareName: "Yamaha",
	HardwareType: "Yamaha AV Receiver with Kodi Remote",
	HardwareTypeVal: 94,
	HaveDimmer: true,
	HaveGroupCmd: true,
	HaveTimeout: false,
	ID: "0003000D",
	Image: "Yamaha",
	IsSubDevice: false,
	LastUpdate: "2018-12-25 21:03:55",
	Level: 200,
	LevelActions: "",
	LevelInt: 200,
	LevelNames: "T2ZmfEhhbGwgaW4gTXVuaWNofEhhbGwgaW4gVmllbm5hfENoYW1iZXJ8Q2VsbGFyIENsdWJ8VGhlIFJveHkgVGhlYXRyZXxUaGUgQm90dG9tIExpbmV8U3BvcnRzfFNwb3RpZnl8QWN0aW9uIEdhbWV8Um9sZXBsYXlpbmcgR2FtZXxNdXNpYyBWaWRlb3xTdGFuZGFyZHxTcGVjdGFjbGV8U2NpLUZpfEFkdmVudHVyZXxEcmFtYXxNb25vIE1vdmllfDJjaCBTdGVyZW98N2NoIFN0ZXJlb3xTdXJyb3VuZCBEZWNvZGVy",
	LevelOffHidden: false,
	MaxDimLevel: 100,
	Name: "Yamaha - DSP Program Main",
	Notifications: "false",
	PlanID: "0",
	PlanIDs: [
	0
	],
	Protected: false,
	SelectorStyle: 1,
	ShowNotifications: true,
	SignalLevel: "-",
	Status: "On",
	StrParam1: "",
	StrParam2: "",
	SubType: "Selector Switch",
	SwitchType: "Selector",
	SwitchTypeVal: 18,
	Timers: "false",
	Type: "Light/Switch",
	TypeImg: "Light",
	Unit: 13,
	Used: 1,
	UsedByCamera: false,
	XOffset: "0",
	YOffset: "0",
	idx: "34"
	},
	{
	AddjMulti: 1,
	AddjMulti2: 1,
	AddjValue: 0,
	AddjValue2: 0,
	BatteryLevel: 255,
	CustomImage: 101,
	Data: "Off",
	Description: "",
	DimmerType: "none",
	Favorite: 0,
	HardwareID: 3,
	HardwareName: "Yamaha",
	HardwareType: "Yamaha AV Receiver with Kodi Remote",
	HardwareTypeVal: 94,
	HaveDimmer: true,
	HaveGroupCmd: true,
	HaveTimeout: false,
	ID: "0003000E",
	Image: "Yamaha",
	IsSubDevice: false,
	LastUpdate: "2018-12-25 10:55:09",
	Level: 0,
	LevelActions: "",
	LevelInt: 0,
	LevelNames: "T2ZmfERWRC9CRHxUVnxORVR8UkFESU8=",
	LevelOffHidden: true,
	MaxDimLevel: 100,
	Name: "Yamaha - Scene Main",
	Notifications: "false",
	PlanID: "0",
	PlanIDs: [
	0
	],
	Protected: false,
	SelectorStyle: 0,
	ShowNotifications: true,
	SignalLevel: "-",
	Status: "Off",
	StrParam1: "",
	StrParam2: "",
	SubType: "Selector Switch",
	SwitchType: "Selector",
	SwitchTypeVal: 18,
	Timers: "false",
	Type: "Light/Switch",
	TypeImg: "Light",
	Unit: 14,
	Used: 1,
	UsedByCamera: false,
	XOffset: "0",
	YOffset: "0",
	idx: "35"
	},
	{
	AddjMulti: 1,
	AddjMulti2: 1,
	AddjValue: 1,
	AddjValue2: 0,
	BatteryLevel: 255,
	CustomImage: 5,
	Data: "Off",
	Description: "",
	DimmerType: "none",
	Favorite: 1,
	HardwareID: 2,
	HardwareName: "rfxcom",
	HardwareType: "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
	HardwareTypeVal: 1,
	HaveDimmer: false,
	HaveGroupCmd: true,
	HaveTimeout: false,
	ID: "65",
	Image: "Amplifier",
	InternalState: "Off",
	IsSubDevice: false,
	LastUpdate: "2018-12-28 07:22:30",
	Level: 0,
	LevelInt: 0,
	MaxDimLevel: 0,
	Name: "salle à mange",
	Notifications: "false",
	PlanID: "2",
	PlanIDs: [
	2
	],
	Protected: false,
	ShowNotifications: true,
	SignalLevel: "-",
	Status: "",
	StrParam1: "",
	StrParam2: "",
	SubType: "ARC",
	SwitchType: "Push On Button",
	SwitchTypeVal: 9,
	Timers: "false",
	Type: "Lighting 1",
	TypeImg: "push",
	Unit: 6,
	Used: 1,
	UsedByCamera: false,
	XOffset: "0",
	YOffset: "0",
	idx: "36"
	}
	],
	status: "OK",
	title: "Devices"
	}
);