exports.DOMOTICZ_GET_DEVICES = JSON.stringify({
	"ActTime" : 1575744473,
	"AstrTwilightEnd" : "19:10",
	"AstrTwilightStart" : "04:33",
	"CivTwilightEnd" : "18:17",
	"CivTwilightStart" : "05:25",
	"DayLength" : "12:07",
	"NautTwilightEnd" : "18:43",
	"NautTwilightStart" : "04:59",
	"ServerTime" : "2019-12-07 18:47:53",
	"SunAtSouth" : "11:51",
	"Sunrise" : "05:48",
	"Sunset" : "17:55",
	"app_version" : "4.11553",
	"result" :
	[
	{
	"AddjMulti" : 1.0,
	"AddjMulti2" : 1.0,
	"AddjValue" : 0.0,
	"AddjValue2" : 0.0,
	"BatteryLevel" : 255,
	"CustomImage" : 0,
	"Data" : "Closed",
	"Description" : "",
	"DimmerType" : "none",
	"Favorite" : 1,
	"HardwareID" : 5,
	"HardwareName" : "RFXCOM",
	"HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
	"HardwareTypeVal" : 1,
	"HaveDimmer" : false,
	"HaveGroupCmd" : false,
	"HaveTimeout" : false,
	"ID" : "010102",
	"Image" : "Light",
	"IsSubDevice" : false,
	"LastUpdate" : "2019-12-07 18:23:29",
	"Level" : 0,
	"LevelInt" : 0,
	"MaxDimLevel" : 0,
	"Name" : "GVsalon",
	"Notifications" : "false",
	"PlanID" : "0",
	"PlanIDs" :
	[
	0
	],
	"Protected" : false,
	"ShowNotifications" : true,
	"SignalLevel" : "-",
	"Status" : "Closed",
	"StrParam1" : "",
	"StrParam2" : "",
	"SubType" : "RFY",
	"SwitchType" : "Blinds",
	"SwitchTypeVal" : 3,
	"Timers" : "false",
	"Type" : "RFY",
	"TypeImg" : "blinds",
	"Unit" : 1,
	"Used" : 1,
	"UsedByCamera" : false,
	"XOffset" : "0",
	"YOffset" : "0",
	"idx" : "2"
	},
	{
	"AddjMulti" : 1.0,
	"AddjMulti2" : 1.0,
	"AddjValue" : 0.0,
	"AddjValue2" : 0.0,
	"BatteryLevel" : 255,
	"CustomImage" : 0,
	"Data" : "Closed",
	"Description" : "",
	"DimmerType" : "none",
	"Favorite" : 1,
	"HardwareID" : 5,
	"HardwareName" : "RFXCOM",
	"HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
	"HardwareTypeVal" : 1,
	"HaveDimmer" : false,
	"HaveGroupCmd" : false,
	"HaveTimeout" : false,
	"ID" : "010101",
	"Image" : "Light",
	"IsSubDevice" : false,
	"LastUpdate" : "2019-12-07 18:23:31",
	"Level" : 0,
	"LevelInt" : 0,
	"MaxDimLevel" : 0,
	"Name" : "Vsalon",
	"Notifications" : "false",
	"PlanID" : "0",
	"PlanIDs" :
	[
	0
	],
	"Protected" : false,
	"ShowNotifications" : true,
	"SignalLevel" : "-",
	"Status" : "Closed",
	"StrParam1" : "",
	"StrParam2" : "",
	"SubType" : "RFY",
	"SwitchType" : "Blinds",
	"SwitchTypeVal" : 3,
	"Timers" : "false",
	"Type" : "RFY",
	"TypeImg" : "blinds",
	"Unit" : 1,
	"Used" : 1,
	"UsedByCamera" : false,
	"XOffset" : "0",
	"YOffset" : "0",
	"idx" : "3"
	},
	{
	"AddjMulti" : 1.0,
	"AddjMulti2" : 1.0,
	"AddjValue" : 0.0,
	"AddjValue2" : 0.0,
	"BatteryLevel" : 255,
	"CustomImage" : 0,
	"Data" : "Closed",
	"Description" : "",
	"DimmerType" : "none",
	"Favorite" : 1,
	"HardwareID" : 5,
	"HardwareName" : "RFXCOM",
	"HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
	"HardwareTypeVal" : 1,
	"HaveDimmer" : false,
	"HaveGroupCmd" : false,
	"HaveTimeout" : false,
	"ID" : "010101",
	"Image" : "Light",
	"IsSubDevice" : false,
	"LastUpdate" : "2019-12-07 18:23:32",
	"Level" : 0,
	"LevelInt" : 0,
	"MaxDimLevel" : 0,
	"Name" : "VCuisine",
	"Notifications" : "false",
	"PlanID" : "0",
	"PlanIDs" :
	[
	0
	],
	"Protected" : false,
	"ShowNotifications" : true,
	"SignalLevel" : "-",
	"Status" : "Closed",
	"StrParam1" : "",
	"StrParam2" : "",
	"SubType" : "RFY",
	"SwitchType" : "Blinds",
	"SwitchTypeVal" : 3,
	"Timers" : "false",
	"Type" : "RFY",
	"TypeImg" : "blinds",
	"Unit" : 2,
	"Used" : 1,
	"UsedByCamera" : false,
	"XOffset" : "0",
	"YOffset" : "0",
	"idx" : "4"
	},
	{
	"AddjMulti" : 1.0,
	"AddjMulti2" : 1.0,
	"AddjValue" : 0.0,
	"AddjValue2" : 0.0,
	"BatteryLevel" : 255,
	"CustomImage" : 0,
	"Data" : "Closed",
	"Description" : "",
	"DimmerType" : "none",
	"Favorite" : 1,
	"HardwareID" : 5,
	"HardwareName" : "RFXCOM",
	"HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
	"HardwareTypeVal" : 1,
	"HaveDimmer" : false,
	"HaveGroupCmd" : false,
	"HaveTimeout" : false,
	"ID" : "010101",
	"Image" : "Light",
	"IsSubDevice" : false,
	"LastUpdate" : "2019-12-07 18:23:34",
	"Level" : 0,
	"LevelInt" : 0,
	"MaxDimLevel" : 0,
	"Name" : "VSalleamanger",
	"Notifications" : "false",
	"PlanID" : "0",
	"PlanIDs" :
	[
	0
	],
	"Protected" : false,
	"ShowNotifications" : true,
	"SignalLevel" : "-",
	"Status" : "Closed",
	"StrParam1" : "",
	"StrParam2" : "",
	"SubType" : "RFY",
	"SwitchType" : "Blinds",
	"SwitchTypeVal" : 3,
	"Timers" : "false",
	"Type" : "RFY",
	"TypeImg" : "blinds",
	"Unit" : 3,
	"Used" : 1,
	"UsedByCamera" : false,
	"XOffset" : "0",
	"YOffset" : "0",
	"idx" : "5"
	},
	{
	"AddjMulti" : 1.0,
	"AddjMulti2" : 1.0,
	"AddjValue" : 0.0,
	"AddjValue2" : 0.0,
	"BatteryLevel" : 255,
	"CustomImage" : 0,
	"Data" : "Closed",
	"Description" : "",
	"DimmerType" : "none",
	"Favorite" : 1,
	"HardwareID" : 5,
	"HardwareName" : "RFXCOM",
	"HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
	"HardwareTypeVal" : 1,
	"HaveDimmer" : false,
	"HaveGroupCmd" : false,
	"HaveTimeout" : false,
	"ID" : "010101",
	"Image" : "Light",
	"IsSubDevice" : false,
	"LastUpdate" : "2019-12-07 18:23:33",
	"Level" : 0,
	"LevelInt" : 0,
	"MaxDimLevel" : 0,
	"Name" : "VBureau",
	"Notifications" : "false",
	"PlanID" : "0",
	"PlanIDs" :
	[
	0
	],
	"Protected" : false,
	"ShowNotifications" : true,
	"SignalLevel" : "-",
	"Status" : "Closed",
	"StrParam1" : "",
	"StrParam2" : "",
	"SubType" : "RFY",
	"SwitchType" : "Blinds",
	"SwitchTypeVal" : 3,
	"Timers" : "false",
	"Type" : "RFY",
	"TypeImg" : "blinds",
	"Unit" : 4,
	"Used" : 1,
	"UsedByCamera" : false,
	"XOffset" : "0",
	"YOffset" : "0",
	"idx" : "6"
	}
	],
	"status" : "OK",
	"title" : "Devices"
});