exports.DOMOTICZ_GET_DEVICES = JSON.stringify({ 
	"ActTime" : 1544396229,
"AstrTwilightEnd" : "19:07",
"AstrTwilightStart" : "06:42",
"CivTwilightEnd" : "17:55",
"CivTwilightStart" : "07:54",
"DayLength" : "08:54",
"NautTwilightEnd" : "18:32",
"NautTwilightStart" : "07:17",
"ServerTime" : "2018-12-09 23:57:09",
"SunAtSouth" : "12:05",
"Sunrise" : "08:27",
"Sunset" : "17:22",
"app_version" : "4.10256",
"result" : [
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 0.0,
"AddjValue2" : 0.0,
"BatteryLevel" : 255,
"Color" : "{\"b\":0,\"cw\":94,\"g\":0,\"m\":2,\"r\":0,\"t\":161,\"ww\":161}",
"CustomImage" : 0,
"Data" : "Off",
"Description" : "",
"DimmerType" : "abs",
"Favorite" : 0,
"HardwareID" : 84,
"HardwareName" : "Zigate",
"HardwareType" : "Zigate plugin",
"HardwareTypeVal" : 94,
"HaveDimmer" : true,
"HaveGroupCmd" : false,
"HaveTimeout" : false,
"ID" : "000b57fffed48d91",
"Image" : "Light",
"IsSubDevice" : false,
"LastUpdate" : "2018-12-09 23:27:39",
"Level" : 99,
"LevelInt" : 99,
"MaxDimLevel" : 100,
"Name" : "Plafonnier Salon",
"Notifications" : "false",
"PlanID" : "0",
"PlanIDs" : [ 0 ],
"Protected" : false,
"ShowNotifications" : true,
"SignalLevel" : 5,
"Status" : "Off",
"StrParam1" : "",
"StrParam2" : "",
"SubType" : "WW",
"SwitchType" : "Dimmer",
"SwitchTypeVal" : 7,
"Timers" : "false",
"Type" : "Color Switch",
"TypeImg" : "dimmer",
"Unit" : 21,
"Used" : 1,
"UsedByCamera" : false,
"XOffset" : "0",
"YOffset" : "0",
"idx" : "7214"
}
],
"status" : "OK",
"title" : "Devices"
});