exports.DOMOTICZ_GET_DEVICES = JSON.stringify({
   "ActTime" : 1540113093,
   "AstrTwilightEnd" : "20:34",
   "AstrTwilightStart" : "06:34",
   "CivTwilightEnd" : "19:22",
   "CivTwilightStart" : "07:45",
   "DayLength" : "10:34",
   "NautTwilightEnd" : "19:58",
   "NautTwilightStart" : "07:10",
   "ServerTime" : "2018-10-21 11:11:33",
   "SunAtSouth" : "13:05",
   "Sunrise" : "08:17",
   "Sunset" : "18:51",
   "app_version" : "4.10078",
   "result" : [
      { 
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "Open",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareID" : 1,
         "HardwareName" : "RFXtrx",
         "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
         "HardwareTypeVal" : 1,
         "HaveDimmer" : false,
         "HaveGroupCmd" : false,
         "HaveTimeout" : false,
         "ID" : "010101",
         "Image" : "Light",
         "IsSubDevice" : false,
         "LastUpdate" : "2018-11-23 07:48:00",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 0,
         "Name" : "Store Tous",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Open",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "RFY",
         "SwitchType" : "Venetian Blinds US",
         "SwitchTypeVal" : 14,
         "Timers" : "false",
         "Type" : "RFY",
         "TypeImg" : "blinds",
         "Unit" : 5,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "73"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 1,
         "Data" : "Set Level: 73 %",
         "Description" : "(PC Halogène TV)",
         "Favorite" : 1,
         "HardwareID" : 2,
         "HardwareName" : "RfxCom",
         "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
         "HardwareTypeVal" : 1,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "0050505",
         "Image" : "WallSocket",
         "IsSubDevice" : false,
         "LastUpdate" : "2019-01-08 21:04:46",
         "Level" : 73,
         "LevelInt" : 11,
         "MaxDimLevel" : 15,
         "Name" : "PC4_DIO_Var",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Set Level: 73 %",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "AC",
         "SwitchType" : "Dimmer",
         "SwitchTypeVal" : 7,
         "Timers" : "false",
         "Type" : "Lighting 2",
         "TypeImg" : "dimmer",
         "Unit" : 4,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "1503"
      },
      { 
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "Set Level: 10 %",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareID" : 8,
         "HardwareName" : "Dummy",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "00000000",
         "Image" : "Light",
         "IsSubDevice" : false,
         "LastUpdate" : "2018-11-21 07:24:21",
         "Level" : 10,
         "LevelActions" : "fHNjcmlwdDovLy9ob21lL3BpL2RvbW90aWN6L3NjcmlwdHMvbHVhL2NvbnNpZ25lLnNoIDE0fHNjcmlwdDovLy9ob21lL3BpL2RvbW90aWN6L3NjcmlwdHMvbHVhL2NvbnNpZ25lLnNoIDE4fHNjcmlwdDovLy9ob21lL3BpL2RvbW90aWN6L3NjcmlwdHMvbHVhL2NvbnNpZ25lLnNoIDE5fHNjcmlwdDovLy9ob21lL3BpL2RvbW90aWN6L3NjcmlwdHMvbHVhL2NvbnNpZ25lLnNoIDIwfHNjcmlwdDovLy9ob21lL3BpL2RvbW90aWN6L3NjcmlwdHMvbHVhL2NvbnNpZ25lLnNoIDIxfHNjcmlwdDovLy9ob21lL3BpL2RvbW90aWN6L3NjcmlwdHMvbHVhL2NvbnNpZ25lLnNoIDIyfHNjcmlwdDovLy9ob21lL3BpL2RvbW90aWN6L3NjcmlwdHMvbHVhL2NvbnNpZ25lLnNoIDIzfHNjcmlwdDovLy9ob21lL3BpL2RvbW90aWN6L3NjcmlwdHMvbHVhL2NvbnNpZ25lLnNoIDI0fHNjcmlwdDovLy9ob21lL3BpL2RvbW90aWN6L3NjcmlwdHMvbHVhL2NvbnNpZ25lLnNoIDI1fHNjcmlwdDovLy9ob21lL3BpL2RvbW90aWN6L3NjcmlwdHMvbHVhL2NvbnNpZ25lLnNoIDI2",
         "LevelInt" : 10,
         "LevelNames" : "T2ZmfDE0fDE4fDE5fDIwfDIxfDIyfDIzfDI0fDI1fDI2",
         "LevelOffHidden" : false,
         "MaxDimLevel" : 100,
         "Name" : "Test avec des accents à l'abri des théodors et autre laïques \;?/27^",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "SelectorStyle" : 0,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Set Level: 10 %",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Selector Switch",
         "SwitchType" : "Selector",
         "SwitchTypeVal" : 18,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "Light",
         "Unit" : 2,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "118"
      }   
   ],
   "status" : "OK",
   "title" : "Devices"
});