exports.DOMOTICZ_GET_DEVICES = JSON.stringify({
	ActTime: 1577716544,
	AstrTwilightEnd: "18:53",
	AstrTwilightStart: "06:34",
	CivTwilightEnd: "17:38",
	CivTwilightStart: "07:48",
	DayLength: "08:41",
	NautTwilightEnd: "18:16",
	NautTwilightStart: "07:10",
	ServerTime: "2019-12-30 15:35:44",
	SunAtSouth: "12:43",
	Sunrise: "08:23",
	Sunset: "17:04",
	app_version: "4.10717",
	result: [
	{
	AddjMulti: 1,
	AddjMulti2: 1,
	AddjValue: 0,
	AddjValue2: 0,
	BatteryLevel: 255,
	CustomImage: 0,
	Data: "Closed",
	Description: "",
	DimmerType: "none",
	Favorite: 0,
	HardwareID: 4,
	HardwareName: "ESPeasy",
	HardwareType: "Dummy (Does nothing, use for virtual switches only)",
	HardwareTypeVal: 15,
	HaveDimmer: false,
	HaveGroupCmd: true,
	HaveTimeout: false,
	ID: "65",
	Image: "Light",
	IsSubDevice: false,
	LastUpdate: "2019-12-22 23:05:18",
	Level: 0,
	LevelInt: 0,
	MaxDimLevel: 0,
	Name: "Volet de letage",
	Notifications: "false",
	PlanID: "0",
	PlanIDs: [
	0
	],
	Protected: false,
	ShowNotifications: true,
	SignalLevel: 0,
	Status: "Closed",
	StrParam1: "",
	StrParam2: "",
	SubType: "ARC",
	SwitchType: "Blinds Inverted",
	SwitchTypeVal: 6,
	Timers: "false",
	Type: "Lighting 1",
	TypeImg: "blinds",
	Unit: 1,
	Used: 1,
	UsedByCamera: false,
	XOffset: "0",
	YOffset: "0",
	idx: "201"
	},
	{
	AddjMulti: 1,
	AddjMulti2: 1,
	AddjValue: 0,
	AddjValue2: 0,
	BatteryLevel: 255,
	CustomImage: 0,
	Data: "Open",
	Description: "",
	DimmerType: "none",
	Favorite: 0,
	HardwareID: 4,
	HardwareName: "ESPeasy",
	HardwareType: "Dummy (Does nothing, use for virtual switches only)",
	HardwareTypeVal: 15,
	HaveDimmer: false,
	HaveGroupCmd: true,
	HaveTimeout: false,
	ID: "65",
	Image: "Light",
	IsSubDevice: false,
	LastUpdate: "2019-12-22 23:09:12",
	Level: 0,
	LevelInt: 0,
	MaxDimLevel: 0,
	Name: "Volet den haut",
	Notifications: "false",
	PlanID: "0",
	PlanIDs: [
	0
	],
	Protected: false,
	ShowNotifications: true,
	SignalLevel: 0,
	Status: "Open",
	StrParam1: "",
	StrParam2: "",
	SubType: "ARC",
	SwitchType: "Blinds",
	SwitchTypeVal: 3,
	Timers: "false",
	Type: "Lighting 1",
	TypeImg: "blinds",
	Unit: 2,
	Used: 1,
	UsedByCamera: false,
	XOffset: "0",
	YOffset: "0",
	idx: "202"
	}
	],
	status: "OK",
	title: "Devices"
});
