exports.DOMOTICZ_GET_DEVICES = JSON.stringify({
   "ActTime" : 1544885296,
   "AstrTwilightEnd" : "18:42",
   "AstrTwilightStart" : "06:22",
   "CivTwilightEnd" : "17:28",
   "CivTwilightStart" : "07:35",
   "DayLength" : "08:46",
   "NautTwilightEnd" : "18:06",
   "NautTwilightStart" : "06:57",
   "ServerTime" : "2018-12-15 15:48:16",
   "SunAtSouth" : "12:05",
   "Sunrise" : "08:09",
   "Sunset" : "16:54",
   "app_version" : "4.9700",
   "result" : [
      {
         "Data" : "On",
         "Description" : "Groupe de VMC",
         "Favorite" : 0,
         "LastUpdate" : "2018-12-15 15:27:22",
         "Name" : "VMCs",
         "PlanID" : "",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "Status" : "On",
         "Type" : "Group",
         "TypeImg" : "group",
         "UsedByCamera" : false,
         "XOffset" : 0,
         "YOffset" : 0,
         "idx" : "1"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareID" : 3,
         "HardwareName" : "kodiServer",
         "HardwareType" : "Kodi Media Server",
         "HardwareTypeVal" : 55,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "0000001",
         "Image" : "Light",
         "IsSubDevice" : false,
         "LastUpdate" : "2017-10-15 21:08:34",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 15,
         "Name" : "kodiTv",
         "Notifications" : "false",
         "PlanID" : "9",
         "PlanIDs" : [ 9 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "AC",
         "SwitchType" : "Media Player",
         "SwitchTypeVal" : 17,
         "Timers" : "false",
         "Type" : "Lighting 2",
         "TypeImg" : "Media",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "850",
         "YOffset" : "1454",
         "idx" : "1"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "4.3%",
         "Description" : "",
         "Favorite" : 0,
         "HardwareID" : 4,
         "HardwareName" : "PI_sensor",
         "HardwareType" : "Motherboard sensors",
         "HardwareTypeVal" : 23,
         "HaveTimeout" : false,
         "ID" : "0000044D",
         "Image" : "Computer",
         "LastUpdate" : "2018-12-15 15:47:50",
         "Name" : "CPU_Usage",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "Percentage",
         "Timers" : "false",
         "Type" : "General",
         "TypeImg" : "hardware",
         "Unit" : 1,
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "6"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "47.6 C",
         "Description" : "",
         "Favorite" : 0,
         "HardwareID" : 4,
         "HardwareName" : "PI_sensor",
         "HardwareType" : "Motherboard sensors",
         "HardwareTypeVal" : 23,
         "HaveTimeout" : false,
         "ID" : "0001",
         "LastUpdate" : "2018-12-15 15:48:10",
         "Name" : "RPI - Internal Temperature",
         "Notifications" : "false",
         "PlanID" : "14",
         "PlanIDs" : [ 14 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "LaCrosse TX3",
         "Temp" : 47.600000000000001,
         "Timers" : "false",
         "Type" : "Temp",
         "TypeImg" : "temperature",
         "Unit" : 1,
         "Used" : 1,
         "XOffset" : "1106",
         "YOffset" : "529",
         "idx" : "5"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "Barometer" : 1021,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "4.2 C, 43 %, 1021 hPa",
         "Description" : "",
         "DewPoint" : "-7.28",
         "Favorite" : 1,
         "Forecast" : 2,
         "ForecastStr" : "Partly Cloudy",
         "HardwareID" : 10,
         "HardwareName" : "WeatherUnderground",
         "HardwareType" : "Weather Underground",
         "HardwareTypeVal" : 14,
         "HaveTimeout" : false,
         "Humidity" : 43,
         "HumidityStatus" : "Comfortable",
         "ID" : "0001",
         "LastUpdate" : "2018-12-15 15:40:56",
         "Name" : "WU_THB",
         "Notifications" : "false",
         "PlanID" : "2",
         "PlanIDs" : [ 2, 15 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "THB1 - BTHR918, BTHGN129",
         "Temp" : 4.2000000000000002,
         "Timers" : "false",
         "Type" : "Temp + Humidity + Baro",
         "TypeImg" : "temperature",
         "Unit" : 1,
         "Used" : 1,
         "XOffset" : "1915",
         "YOffset" : "1282",
         "forecast_url" : "aHR0cDovL3d3dy53dW5kZXJncm91bmQuY29tL2NnaS1iaW4vZmluZHdlYXRoZXIvZ2V0Rm9yZWNhc3Q/cXVlcnk9Y3JvbGxlcw==",
         "idx" : "11"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "Chill" : 4.0,
         "CustomImage" : 0,
         "Data" : "90.00;E;1;9;4.2;4.0",
         "Description" : "",
         "Direction" : 90.0,
         "DirectionStr" : "E",
         "Favorite" : 0,
         "Gust" : "0.9",
         "HardwareID" : 10,
         "HardwareName" : "WeatherUnderground",
         "HardwareType" : "Weather Underground",
         "HardwareTypeVal" : 14,
         "HaveTimeout" : false,
         "ID" : "0001",
         "LastUpdate" : "2018-12-15 15:40:57",
         "Name" : "WU_Temp",
         "Notifications" : "false",
         "PlanID" : "2",
         "PlanIDs" : [ 2, 15 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Speed" : "0.1",
         "SubType" : "TFA",
         "Temp" : 4.2000000000000002,
         "Timers" : "false",
         "Type" : "Wind",
         "TypeImg" : "wind",
         "Unit" : 0,
         "Used" : 1,
         "XOffset" : "1903",
         "YOffset" : "1184",
         "forecast_url" : "aHR0cDovL3d3dy53dW5kZXJncm91bmQuY29tL2NnaS1iaW4vZmluZHdlYXRoZXIvZ2V0Rm9yZWNhc3Q/cXVlcnk9Y3JvbGxlcw==",
         "idx" : "12"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "0;0.0",
         "Description" : "",
         "Favorite" : 0,
         "HardwareID" : 10,
         "HardwareName" : "WeatherUnderground",
         "HardwareType" : "Weather Underground",
         "HardwareTypeVal" : 14,
         "HaveTimeout" : false,
         "ID" : "0001",
         "LastUpdate" : "2018-12-15 15:40:57",
         "Name" : "WU_Rain",
         "Notifications" : "false",
         "PlanID" : "2",
         "PlanIDs" : [ 2 ],
         "Protected" : false,
         "Rain" : "0",
         "RainRate" : "0",
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "WWW",
         "Timers" : "false",
         "Type" : "Rain",
         "TypeImg" : "rain",
         "Unit" : 0,
         "Used" : 1,
         "XOffset" : "1903",
         "YOffset" : "1364",
         "forecast_url" : "aHR0cDovL3d3dy53dW5kZXJncm91bmQuY29tL2NnaS1iaW4vZmluZHdlYXRoZXIvZ2V0Rm9yZWNhc3Q/cXVlcnk9Y3JvbGxlcw==",
         "idx" : "14"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "4.6 C, 66 %",
         "Description" : "",
         "DewPoint" : "-1.21",
         "Favorite" : 1,
         "HardwareID" : 14,
         "HardwareName" : "rflink",
         "HardwareType" : "RFLink Gateway USB",
         "HardwareTypeVal" : 46,
         "HaveTimeout" : false,
         "Humidity" : 66,
         "HumidityStatus" : "Wet",
         "ID" : "0D04",
         "LastUpdate" : "2018-12-15 15:48:09",
         "Name" : "TH-GARAGE",
         "Notifications" : "false",
         "PlanID" : "10",
         "PlanIDs" : [ 10, 15 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "LaCrosse TX3",
         "Temp" : 4.5999999999999996,
         "Timers" : "false",
         "Type" : "Temp + Humidity",
         "TypeImg" : "temperature",
         "Unit" : 2,
         "Used" : 1,
         "XOffset" : "1827",
         "YOffset" : "800",
         "idx" : "25"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 7,
         "Data" : "On",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareID" : 5,
         "HardwareName" : "Fictif",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveDimmer" : false,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "65",
         "Image" : "Fan",
         "IsSubDevice" : false,
         "LastUpdate" : "2018-12-15 15:27:24",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 0,
         "Name" : "VMC-CUISINE",
         "Notifications" : "false",
         "PlanID" : "7",
         "PlanIDs" : [ 7 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "On",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "X10",
         "SwitchType" : "On/Off",
         "SwitchTypeVal" : 0,
         "Timers" : "false",
         "Type" : "Lighting 1",
         "TypeImg" : "lightbulb",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "906",
         "YOffset" : "625",
         "idx" : "40"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 7,
         "Data" : "On",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareID" : 5,
         "HardwareName" : "Fictif",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "00014079",
         "Image" : "Fan",
         "IsSubDevice" : false,
         "LastUpdate" : "2018-12-15 15:27:24",
         "Level" : 99,
         "LevelInt" : 99,
         "MaxDimLevel" : 100,
         "Name" : "VMC-TOILETTE",
         "Notifications" : "false",
         "PlanID" : "11",
         "PlanIDs" : [ 11 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "On",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Switch",
         "SwitchType" : "On/Off",
         "SwitchTypeVal" : 0,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "lightbulb",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "1178",
         "YOffset" : "613",
         "idx" : "41"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 7,
         "Data" : "On",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareID" : 5,
         "HardwareName" : "Fictif",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "0001407A",
         "Image" : "Fan",
         "IsSubDevice" : false,
         "LastUpdate" : "2018-12-15 15:27:24",
         "Level" : 99,
         "LevelInt" : 99,
         "MaxDimLevel" : 100,
         "Name" : "VMC-GARAGE",
         "Notifications" : "false",
         "PlanID" : "10",
         "PlanIDs" : [ 10 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "On",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Switch",
         "SwitchType" : "On/Off",
         "SwitchTypeVal" : 0,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "lightbulb",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "1699",
         "YOffset" : "721",
         "idx" : "42"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 7,
         "Data" : "On",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareID" : 5,
         "HardwareName" : "Fictif",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "0001407B",
         "Image" : "Fan",
         "IsSubDevice" : false,
         "LastUpdate" : "2018-12-15 15:27:24",
         "Level" : 99,
         "LevelInt" : 99,
         "MaxDimLevel" : 100,
         "Name" : "VMC-SALLEDEBAIN",
         "Notifications" : "false",
         "PlanID" : "6",
         "PlanIDs" : [ 6 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "On",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Switch",
         "SwitchType" : "On/Off",
         "SwitchTypeVal" : 0,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "lightbulb",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "604",
         "YOffset" : "646",
         "idx" : "43"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 7,
         "Data" : "On",
         "Description" : "Permet l'allumage et l'arret de la VMC",
         "DimmerType" : "none",
         "Favorite" : 1,
         "HardwareID" : 14,
         "HardwareName" : "rflink",
         "HardwareType" : "RFLink Gateway USB",
         "HardwareTypeVal" : 46,
         "HaveDimmer" : false,
         "HaveGroupCmd" : false,
         "HaveTimeout" : false,
         "ID" : "00000047",
         "Image" : "Fan",
         "IsSubDevice" : false,
         "LastUpdate" : "2018-12-15 15:27:24",
         "Level" : 99,
         "LevelInt" : 99,
         "MaxDimLevel" : 100,
         "Name" : "VMC-ALL",
         "Notifications" : "false",
         "PlanID" : "15",
         "PlanIDs" : [ 15 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "On",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "ELRO AB400",
         "SwitchType" : "On/Off",
         "SwitchTypeVal" : 0,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "lightbulb",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "45"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 11,
         "Data" : "Off",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 1,
         "HardwareID" : 14,
         "HardwareName" : "rflink",
         "HardwareType" : "RFLink Gateway USB",
         "HardwareTypeVal" : 46,
         "HaveDimmer" : false,
         "HaveGroupCmd" : false,
         "HaveTimeout" : false,
         "ID" : "00000047",
         "Image" : "Water",
         "IsSubDevice" : false,
         "LastUpdate" : "2018-12-14 22:00:01",
         "Level" : 99,
         "LevelInt" : 99,
         "MaxDimLevel" : 100,
         "Name" : "PriseConnecte-B",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "ELRO AB400",
         "SwitchType" : "On/Off",
         "SwitchTypeVal" : 0,
         "Timers" : "true",
         "Type" : "Light/Switch",
         "TypeImg" : "lightbulb",
         "Unit" : 2,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "46"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 15,
         "Data" : "Off",
         "Description" : "Radiateur du salon",
         "DimmerType" : "none",
         "Favorite" : 1,
         "HardwareID" : 5,
         "HardwareName" : "Fictif",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "000140B3",
         "Image" : "Heating",
         "IsSubDevice" : false,
         "LastUpdate" : "2018-12-15 15:36:17",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 100,
         "Name" : "RADIATEUR-SALON",
         "Notifications" : "false",
         "PlanID" : "9",
         "PlanIDs" : [ 9, 15 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Switch",
         "SwitchType" : "On/Off",
         "SwitchTypeVal" : 0,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "lightbulb",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "1581",
         "YOffset" : "1449",
         "idx" : "99"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 15,
         "Data" : "Off",
         "Description" : "Radiateur Couloir",
         "DimmerType" : "none",
         "Favorite" : 1,
         "HardwareID" : 5,
         "HardwareName" : "Fictif",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "000140B4",
         "Image" : "Heating",
         "IsSubDevice" : false,
         "LastUpdate" : "2018-12-15 12:13:00",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 100,
         "Name" : "RADIATEUR-COULOIR",
         "Notifications" : "false",
         "PlanID" : "14",
         "PlanIDs" : [ 14, 15 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Switch",
         "SwitchType" : "On/Off",
         "SwitchTypeVal" : 0,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "lightbulb",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "1231",
         "YOffset" : "493",
         "idx" : "100"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "20.0",
         "Description" : "",
         "Favorite" : 1,
         "HardwareID" : 5,
         "HardwareName" : "Fictif",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveTimeout" : true,
         "ID" : "00140B8",
         "LastUpdate" : "2018-12-15 06:00:07",
         "Name" : "Thermostat-SALON",
         "Notifications" : "false",
         "PlanID" : "9",
         "PlanIDs" : [ 9, 15 ],
         "Protected" : false,
         "SetPoint" : "20.0",
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "SetPoint",
         "Timers" : "true",
         "Type" : "Thermostat",
         "TypeImg" : "override_mini",
         "Unit" : 1,
         "Used" : 1,
         "XOffset" : "1560",
         "YOffset" : "1159",
         "idx" : "104"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "20.0",
         "Description" : "",
         "Favorite" : 1,
         "HardwareID" : 5,
         "HardwareName" : "Fictif",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveTimeout" : true,
         "ID" : "00140B9",
         "LastUpdate" : "2018-12-15 08:00:01",
         "Name" : "Thermostat-COULOIR",
         "Notifications" : "false",
         "PlanID" : "14",
         "PlanIDs" : [ 14, 15 ],
         "Protected" : false,
         "SetPoint" : "20.0",
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "SetPoint",
         "Timers" : "true",
         "Type" : "Thermostat",
         "TypeImg" : "override_mini",
         "Unit" : 1,
         "Used" : 1,
         "XOffset" : "1047",
         "YOffset" : "528",
         "idx" : "105"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 10,
         "Data" : "Set Level: 10 %",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 1,
         "HardwareID" : 5,
         "HardwareName" : "Fictif",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "0001415C",
         "Image" : "Fireplace",
         "IsSubDevice" : false,
         "LastUpdate" : "2018-11-25 08:36:26",
         "Level" : 10,
         "LevelActions" : "fHx8fHw=",
         "LevelInt" : 10,
         "LevelNames" : "T2ZmfEF1dG98V2Vla2VuZCBPZmZ8TWFudWVsfEhvcnNHZWx8Rm9yY2UtMTY=",
         "LevelOffHidden" : false,
         "MaxDimLevel" : 100,
         "Name" : "RADIATEUR-MODE",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "SelectorStyle" : 0,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Set Level: 10 %",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Selector Switch",
         "SwitchType" : "Selector",
         "SwitchTypeVal" : 18,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "Light",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "268"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 7,
         "Data" : "Set Level: 20 %",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareID" : 5,
         "HardwareName" : "Fictif",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "00000000",
         "Image" : "Fan",
         "IsSubDevice" : false,
         "LastUpdate" : "2018-11-02 11:03:38",
         "Level" : 20,
         "LevelActions" : "fHw=",
         "LevelInt" : 20,
         "LevelNames" : "T2ZmfE1BTlVFTHxBVVRP",
         "LevelOffHidden" : false,
         "MaxDimLevel" : 100,
         "Name" : "VMC-MODE",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "SelectorStyle" : 0,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Set Level: 20 %",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Selector Switch",
         "SwitchType" : "Selector",
         "SwitchTypeVal" : 18,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "Light",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "790"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.5,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "21.0 C, 48 %",
         "Description" : "",
         "DewPoint" : "9.57",
         "Favorite" : 1,
         "HardwareID" : 14,
         "HardwareName" : "rflink",
         "HardwareType" : "RFLink Gateway USB",
         "HardwareTypeVal" : 46,
         "HaveTimeout" : false,
         "Humidity" : 48,
         "HumidityStatus" : "Comfortable",
         "ID" : "5AA8",
         "LastUpdate" : "2018-12-15 14:40:55",
         "Name" : "TH-CHAMBREMATHIS",
         "Notifications" : "false",
         "PlanID" : "4",
         "PlanIDs" : [ 4, 15 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "WTGR800",
         "Temp" : 21.0,
         "Timers" : "false",
         "Type" : "Temp + Humidity",
         "TypeImg" : "temperature",
         "Unit" : 0,
         "Used" : 1,
         "XOffset" : "960",
         "YOffset" : "89",
         "idx" : "940"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "22.4 C, 79 %",
         "Description" : "",
         "DewPoint" : "18.58",
         "Favorite" : 1,
         "HardwareID" : 14,
         "HardwareName" : "rflink",
         "HardwareType" : "RFLink Gateway USB",
         "HardwareTypeVal" : 46,
         "HaveTimeout" : false,
         "Humidity" : 79,
         "HumidityStatus" : "Wet",
         "ID" : "59E9",
         "LastUpdate" : "2018-12-15 15:47:47",
         "Name" : "TH-SALLEDEBAIN",
         "Notifications" : "false",
         "PlanID" : "6",
         "PlanIDs" : [ 6, 15 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "WTGR800",
         "Temp" : 22.399999999999999,
         "Timers" : "false",
         "Type" : "Temp + Humidity",
         "TypeImg" : "temperature",
         "Unit" : 0,
         "Used" : 1,
         "XOffset" : "602",
         "YOffset" : "699",
         "idx" : "1060"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "20.9 C, 45 %",
         "Description" : "",
         "DewPoint" : "8.52",
         "Favorite" : 1,
         "HardwareID" : 14,
         "HardwareName" : "rflink",
         "HardwareType" : "RFLink Gateway USB",
         "HardwareTypeVal" : 46,
         "HaveTimeout" : false,
         "Humidity" : 45,
         "HumidityStatus" : "Comfortable",
         "ID" : "5CE8",
         "LastUpdate" : "2018-12-15 15:47:59",
         "Name" : "TH-SALON",
         "Notifications" : "false",
         "PlanID" : "9",
         "PlanIDs" : [ 9, 15 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "WTGR800",
         "Temp" : 20.899999999999999,
         "Timers" : "false",
         "Type" : "Temp + Humidity",
         "TypeImg" : "temperature",
         "Unit" : 0,
         "Used" : 1,
         "XOffset" : "1292",
         "YOffset" : "1443",
         "idx" : "1331"
      }
   ],
   "status" : "OK",
   "title" : "Devices"
});