exports.DOMOTICZ_GET_DEVICES = JSON.stringify({
   "ActTime" : 1645602914,
   "AstrTwilightEnd" : "19:40",
   "AstrTwilightStart" : "05:33",
   "CivTwilightEnd" : "18:31",
   "CivTwilightStart" : "06:42",
   "DayLength" : "10:49",
   "NautTwilightEnd" : "19:06",
   "NautTwilightStart" : "06:08",
   "ServerTime" : "2022-02-23 08:55:14",
   "SunAtSouth" : "12:37",
   "Sunrise" : "07:12",
   "Sunset" : "18:01",
   "app_version" : "2022.1 (build 14205)",
   "result" : 
   [
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "Set Level: 41 %",
         "Description" : "{\"topic\": \"tasmota_esp32\", \"blind\": 1}",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareDisabled" : false,
         "HardwareID" : 6,
         "HardwareName" : "dummy ",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "0001411C",
         "Image" : "Light",
         "IsSubDevice" : false,
         "LastUpdate" : "2022-02-20 14:51:04",
         "Level" : 41,
         "LevelInt" : 41,
         "MaxDimLevel" : 100,
         "Name" : "tap1_esp32_ip56",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : 
         [
            0
         ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Set Level: 41 %",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Switch",
         "SwitchType" : "Blinds Percentage Inverted",
         "SwitchTypeVal" : 16,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "blinds",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "204"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "Set Level: 59 %",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareDisabled" : false,
         "HardwareID" : 12,
         "HardwareName" : "MQTT client - For AD MQTT",
         "HardwareType" : "MQTT Auto Discovery Client Gateway with LAN interface",
         "HardwareTypeVal" : 125,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "FD311C_SHT_1",
         "Image" : "Light",
         "IsSubDevice" : false,
         "LastUpdate" : "2022-02-21 06:48:56",
         "Level" : 59,
         "LevelInt" : 59,
         "MaxDimLevel" : 100,
         "Name" : "Tasmota",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : 
         [
            0
         ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : 3,
         "Status" : "Set Level: 59 %",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Switch",
         "SwitchType" : "Blinds + Stop",
         "SwitchTypeVal" : 21,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "blinds",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "266"
      },
   ],
   "status" : "OK",
   "title" : "Devices"
});