exports.DOMOTICZ_GET_DEVICES = JSON.stringify(
{
   "ActTime" : 1548922541,
   "AstrTwilightEnd" : "19:39",
   "AstrTwilightStart" : "06:30",
   "CivTwilightEnd" : "18:31",
   "CivTwilightStart" : "07:38",
   "DayLength" : "09:52",
   "NautTwilightEnd" : "19:05",
   "NautTwilightStart" : "07:04",
   "ServerTime" : "2019-01-31 09:15:41",
   "SunAtSouth" : "13:05",
   "Sunrise" : "08:09",
   "Sunset" : "18:01",
   "app_version" : "4.9700",
   "result" : [
		{ 
		   	"AddjMulti" : 1.0,
			"AddjMulti2" : 1.0,
			"AddjValue" : 0.0,
			"AddjValue2" : 0.0,
			"BatteryLevel" : 255,
			"CustomImage" : 0,
			"Data" : "Open",
			"Description" : "",
			"DimmerType" : "none",
			"Favorite" : 0,
			"HardwareID" : 7,
			"HardwareName" : "RFXcom",
			"HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
			"HardwareTypeVal" : 1,
			"HaveDimmer" : false,
			"HaveGroupCmd" : false,
			"HaveTimeout" : false,
			"ID" : "0B0102",
			"Image" : "Light",
			"IsSubDevice" : false,
			"LastUpdate" : "2019-04-02 16:46:56",
			"Level" : 0,
			"LevelInt" : 0,
			"MaxDimLevel" : 0,
			"Name" : "Volet Chambre Paul",
			"Notifications" : "false",
			"PlanID" : "0",
			"PlanIDs" : [ 0 ],
			"Protected" : false,
			"ShowNotifications" : true,
			"SignalLevel" : "-",
			"Status" : "Open",
			"StrParam1" : "",
			"StrParam2" : "",
			"SubType" : "RFY",
			"SwitchType" : "Venetian Blinds EU",
			"SwitchTypeVal" : 15,
			"Timers" : "false",
			"Type" : "RFY",
			"TypeImg" : "blinds",
			"Unit" : 2,
			"Used" : 1,
			"UsedByCamera" : false,
			"XOffset" : "0",
			"YOffset" : "0",
			"idx" : "76"
			},
			{
			"AddjMulti" : 1.0,
			"AddjMulti2" : 1.0,
			"AddjValue" : 0.0,
			"AddjValue2" : 0.0,
			"BatteryLevel" : 255,
			"CustomImage" : 0,
			"Data" : "Open",
			"Description" : "",
			"DimmerType" : "none",
			"Favorite" : 0,
			"HardwareID" : 7,
			"HardwareName" : "RFXcom",
			"HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
			"HardwareTypeVal" : 1,
			"HaveDimmer" : false,
			"HaveGroupCmd" : false,
			"HaveTimeout" : false,
			"ID" : "0B0101",
			"Image" : "Light",
			"IsSubDevice" : false,
			"LastUpdate" : "2019-04-02 16:49:54",
			"Level" : 0,
			"LevelInt" : 0,
			"MaxDimLevel" : 0,
			"Name" : "Volet Chambre 3",
			"Notifications" : "false",
			"PlanID" : "0",
			"PlanIDs" : [ 0 ],
			"Protected" : false,
			"ShowNotifications" : true,
			"SignalLevel" : "-",
			"Status" : "Open",
			"StrParam1" : "",
			"StrParam2" : "",
			"SubType" : "RFY",
			"SwitchType" : "Venetian Blinds EU",
			"SwitchTypeVal" : 15,
			"Timers" : "false",
			"Type" : "RFY",
			"TypeImg" : "blinds",
			"Unit" : 1,
			"Used" : 1,
			"UsedByCamera" : false,
			"XOffset" : "0",
			"YOffset" : "0",
			"idx" : "77"
		}
	],
   "status" : "OK",
   "title" : "Devices"
});