exports.DOMOTICZ_GET_DEVICES = JSON.stringify({
 "ActTime" : 1543954662,
 "AstrTwilightEnd" : "18:58",
 "AstrTwilightStart" : "06:25",
 "CivTwilightEnd" : "17:47",
 "CivTwilightStart" : "07:35",
 "DayLength" : "09:08",
 "NautTwilightEnd" : "18:23",
 "NautTwilightStart" : "06:60",
 "ServerTime" : "2018-12-04 21:17:42",
 "SunAtSouth" : "12:05",
 "Sunrise" : "08:07",
 "Sunset" : "17:15",
 "app_version" : "4.9700",
 "result" : [
 {
 "Data" : "Off",
 "Description" : "",
 "Favorite" : 0,
 "LastUpdate" : "2018-10-16 13:48:17",
 "Name" : "LED Alarme Vert",
 "PlanID" : "",
 "PlanIDs" : [ 0 ],
 "Protected" : false,
 "Status" : "Off",
 "Type" : "Scene",
 "TypeImg" : "scene",
 "UsedByCamera" : false,
 "XOffset" : 0,
 "YOffset" : 0,
 "idx" : "11"
 },
 {
 "Data" : "Off",
 "Description" : "",
 "Favorite" : 0,
 "LastUpdate" : "2018-07-07 09:10:19",
 "Name" : "LED Alarme Jaune",
 "PlanID" : "",
 "PlanIDs" : [ 0 ],
 "Protected" : false,
 "Status" : "Off",
 "Type" : "Scene",
 "TypeImg" : "scene",
 "UsedByCamera" : false,
 "XOffset" : 0,
 "YOffset" : 0,
 "idx" : "12"
 },
 {
 "Data" : "Off",
 "Description" : "",
 "Favorite" : 0,
 "LastUpdate" : "2018-07-07 09:10:23",
 "Name" : "LED Alarme Rouge",
 "PlanID" : "",
 "PlanIDs" : [ 0 ],
 "Protected" : false,
 "Status" : "Off",
 "Type" : "Scene",
 "TypeImg" : "scene",
 "UsedByCamera" : false,
 "XOffset" : 0,
 "YOffset" : 0,
 "idx" : "13"
 },
 {
 "Data" : "Off",
 "Description" : "",
 "Favorite" : 0,
 "LastUpdate" : "2018-07-07 09:10:25",
 "Name" : "LED Alarme Defaut",
 "PlanID" : "",
 "PlanIDs" : [ 0 ],
 "Protected" : false,
 "Status" : "Off",
 "Type" : "Scene",
 "TypeImg" : "scene",
 "UsedByCamera" : false,
 "XOffset" : 0,
 "YOffset" : 0,
 "idx" : "14"
 },
 {
 "AddjMulti" : 1.0,
 "AddjMulti2" : 1.0,
 "AddjValue" : 1.3,
 "AddjValue2" : 0.0,
 "BatteryLevel" : 255,
 "CustomImage" : 0,
 "Data" : "20.6 C",
 "Description" : "",
 "Favorite" : 1,
 "HardwareID" : 9,
 "HardwareName" : "1-Wire",
 "HardwareType" : "1-Wire (System)",
 "HardwareTypeVal" : 12,
 "HaveTimeout" : false,
 "ID" : "0FEA",
 "LastUpdate" : "2018-12-04 21:17:22",
 "Name" : "Salon",
 "Notifications" : "false",
 "PlanID" : "0",
 "PlanIDs" : [ 0 ],
 "Protected" : false,
 "ShowNotifications" : true,
 "SignalLevel" : "-",
 "SubType" : "LaCrosse TX3",
 "Temp" : 20.600000000000001,
 "Timers" : "false",
 "Type" : "Temp",
 "TypeImg" : "temperature",
 "Unit" : 234,
 "Used" : 1,
 "XOffset" : "0",
 "YOffset" : "0",
 "idx" : "29"
 },
 {
 "AddjMulti" : 1.0,
 "AddjMulti2" : 1.0,
 "AddjValue" : 0.0,
 "AddjValue2" : 0.0,
 "BatteryLevel" : 255,
 "CustomImage" : 0,
 "Data" : "21.0 C",
 "Description" : "",
 "Favorite" : 1,
 "HardwareID" : 9,
 "HardwareName" : "1-Wire",
 "HardwareType" : "1-Wire (System)",
 "HardwareTypeVal" : 12,
 "HaveTimeout" : false,
 "ID" : "8058",
 "LastUpdate" : "2018-12-04 21:17:14",
 "Name" : "Hall entrée",
 "Notifications" : "false",
 "PlanID" : "4",
 "PlanIDs" : [ 4 ],
 "Protected" : false,
 "ShowNotifications" : true,
 "SignalLevel" : "-",
 "SubType" : "LaCrosse TX3",
 "Temp" : 21.0,
 "Timers" : "false",
 "Type" : "Temp",
 "TypeImg" : "temperature",
 "Unit" : 88,
 "Used" : 1,
 "XOffset" : "630",
 "YOffset" : "727",
 "idx" : "31"
 },
 {
 "AddjMulti" : 1.0,
 "AddjMulti2" : 1.0,
 "AddjValue" : 0.0,
 "AddjValue2" : 0.0,
 "BatteryLevel" : 100,
 "CustomImage" : 0,
 "Data" : "22.4 C, 73 %",
 "Description" : "Thermomètre C",
 "DewPoint" : "17.32",
 "Favorite" : 0,
 "HardwareID" : 11,
 "HardwareName" : "RFXTRX",
 "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
 "HardwareTypeVal" : 1,
 "HaveTimeout" : true,
 "Humidity" : 73,
 "HumidityStatus" : "Wet",
 "ID" : "F401",
 "LastUpdate" : "2018-05-28 07:52:41",
 "Name" : "Salle de bain",
 "Notifications" : "false",
 "PlanID" : "0",
 "PlanIDs" : [ 0 ],
 "Protected" : false,
 "ShowNotifications" : true,
 "SignalLevel" : 7,
 "SubType" : "Alecto WS1700",
 "Temp" : 22.399999999999999,
 "Timers" : "false",
 "Type" : "Temp + Humidity",
 "TypeImg" : "temperature",
 "Unit" : 1,
 "Used" : 1,
 "XOffset" : "0",
 "YOffset" : "0",
 "idx" : "589"
 },
 {
 "AddjMulti" : 1.0,
 "AddjMulti2" : 1.0,
 "AddjValue" : -1.5,
 "AddjValue2" : 0.0,
 "BatteryLevel" : 255,
 "CustomImage" : 0,
 "Data" : "17.9 C",
 "Description" : "",
 "Favorite" : 0,
 "HardwareID" : 9,
 "HardwareName" : "1-Wire",
 "HardwareType" : "1-Wire (System)",
 "HardwareTypeVal" : 12,
 "HaveTimeout" : false,
 "ID" : "7E04",
 "LastUpdate" : "2018-12-04 21:17:18",
 "Name" : "Chambre (Plafond)",
 "Notifications" : "false",
 "PlanID" : "0",
 "PlanIDs" : [ 0 ],
 "Protected" : false,
 "ShowNotifications" : true,
 "SignalLevel" : "-",
 "SubType" : "LaCrosse TX3",
 "Temp" : 17.899999999999999,
 "Timers" : "false",
 "Type" : "Temp",
 "TypeImg" : "temperature",
 "Unit" : 4,
 "Used" : 1,
 "XOffset" : "0",
 "YOffset" : "0",
 "idx" : "30"
 },
 {
 "AddjMulti" : 1.0,
 "AddjMulti2" : 1.0,
 "AddjValue" : 0.0,
 "AddjValue2" : 0.0,
 "BatteryLevel" : 100,
 "CustomImage" : 0,
 "Data" : "19.0 C, 73 %",
 "Description" : "",
 "DewPoint" : "14.05",
 "Favorite" : 0,
 "HardwareID" : 11,
 "HardwareName" : "RFXTRX",
 "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
 "HardwareTypeVal" : 1,
 "HaveTimeout" : false,
 "Humidity" : 73,
 "HumidityStatus" : "Wet",
 "ID" : "7501",
 "LastUpdate" : "2018-12-04 21:17:15",
 "Name" : "Chambre",
 "Notifications" : "false",
 "PlanID" : "2",
 "PlanIDs" : [ 2 ],
 "Protected" : false,
 "ShowNotifications" : true,
 "SignalLevel" : 7,
 "SubType" : "Alecto WS1700",
 "Temp" : 19.0,
 "Timers" : "false",
 "Type" : "Temp + Humidity",
 "TypeImg" : "temperature",
 "Unit" : 1,
 "Used" : 1,
 "XOffset" : "71",
 "YOffset" : "1030",
 "idx" : "710"
 },
 {
 "AddjMulti" : 1.0,
 "AddjMulti2" : 1.0,
 "AddjValue" : 0.0,
 "AddjValue2" : 0.0,
 "BatteryLevel" : 100,
 "CustomImage" : 0,
 "Data" : "17.5 C, 72 %",
 "Description" : "Thermomètre A",
 "DewPoint" : "12.40",
 "Favorite" : 0,
 "HardwareID" : 11,
 "HardwareName" : "RFXTRX",
 "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
 "HardwareTypeVal" : 1,
 "HaveTimeout" : true,
 "Humidity" : 72,
 "HumidityStatus" : "Wet",
 "ID" : "5301",
 "LastUpdate" : "2018-05-02 08:30:08",
 "Name" : "Chambre Tom",
 "Notifications" : "false",
 "PlanID" : "0",
 "PlanIDs" : [ 0 ],
 "Protected" : false,
 "ShowNotifications" : true,
 "SignalLevel" : 7,
 "SubType" : "Alecto WS1700",
 "Temp" : 17.5,
 "Timers" : "false",
 "Type" : "Temp + Humidity",
 "TypeImg" : "temperature",
 "Unit" : 1,
 "Used" : 1,
 "XOffset" : "0",
 "YOffset" : "0",
 "idx" : "435"
 },
 {
 "AddjMulti" : 1.0,
 "AddjMulti2" : 1.0,
 "AddjValue" : 0.0,
 "AddjValue2" : 0.0,
 "BatteryLevel" : 255,
 "CustomImage" : 0,
 "Data" : "17.5 C",
 "Description" : "",
 "Favorite" : 1,
 "HardwareID" : 9,
 "HardwareName" : "1-Wire",
 "HardwareType" : "1-Wire (System)",
 "HardwareTypeVal" : 12,
 "HaveTimeout" : false,
 "ID" : "EEF5",
 "LastUpdate" : "2018-12-04 21:17:40",
 "Name" : "Insert",
 "Notifications" : "true",
 "PlanID" : "5",
 "PlanIDs" : [ 5 ],
 "Protected" : false,
 "ShowNotifications" : true,
 "SignalLevel" : "-",
 "SubType" : "LaCrosse TX3",
 "Temp" : 17.5,
 "Timers" : "false",
 "Type" : "Temp",
 "TypeImg" : "temperature",
 "Unit" : 245,
 "Used" : 1,
 "XOffset" : "0",
 "YOffset" : "0",
 "idx" : "244"
 },
 {
 "AddjMulti" : 1.0,
 "AddjMulti2" : 1.0,
 "AddjValue" : 0.0,
 "AddjValue2" : 0.0,
 "BatteryLevel" : 255,
 "CustomImage" : 0,
 "Data" : "12.1 C",
 "Description" : "",
 "Favorite" : 0,
 "HardwareID" : 9,
 "HardwareName" : "1-Wire",
 "HardwareType" : "1-Wire (System)",
 "HardwareTypeVal" : 12,
 "HaveTimeout" : false,
 "ID" : "94D1",
 "LastUpdate" : "2018-12-04 21:17:30",
 "Name" : "Garage",
 "Notifications" : "true",
 "PlanID" : "0",
 "PlanIDs" : [ 0 ],
 "Protected" : false,
 "ShowNotifications" : true,
 "SignalLevel" : "-",
 "SubType" : "LaCrosse TX3",
 "Temp" : 12.1,
 "Timers" : "false",
 "Type" : "Temp",
 "TypeImg" : "temperature",
 "Unit" : 209,
 "Used" : 1,
 "XOffset" : "0",
 "YOffset" : "0",
 "idx" : "27"
 },
 {
 "AddjMulti" : 1.0,
 "AddjMulti2" : 1.0,
 "AddjValue" : 1.0,
 "AddjValue2" : 0.0,
 "BatteryLevel" : 255,
 "CustomImage" : 0,
 "Data" : "8.2 C",
 "Description" : "",
 "Favorite" : 0,
 "HardwareID" : 9,
 "HardwareName" : "1-Wire",
 "HardwareType" : "1-Wire (System)",
 "HardwareTypeVal" : 12,
 "HaveTimeout" : false,
 "ID" : "34E0",
 "LastUpdate" : "2018-12-04 21:17:26",
 "Name" : "Combles",
 "Notifications" : "false",
 "PlanID" : "0",
 "PlanIDs" : [ 0 ],
 "Protected" : false,
 "ShowNotifications" : true,
 "SignalLevel" : "-",
 "SubType" : "LaCrosse TX3",
 "Temp" : 8.1999999999999993,
 "Timers" : "false",
 "Type" : "Temp",
 "TypeImg" : "temperature",
 "Unit" : 224,
 "Used" : 1,
 "XOffset" : "0",
 "YOffset" : "0",
 "idx" : "28"
 },
 {
 "AddjMulti" : 1.0,
 "AddjMulti2" : 1.0,
 "AddjValue" : 0.0,
 "AddjValue2" : 0.0,
 "BatteryLevel" : 255,
 "CustomImage" : 0,
 "Data" : "9.1 C",
 "Description" : "",
 "Favorite" : 1,
 "HardwareID" : 9,
 "HardwareName" : "1-Wire",
 "HardwareType" : "1-Wire (System)",
 "HardwareTypeVal" : 12,
 "HaveTimeout" : false,
 "ID" : "FFA7",
 "LastUpdate" : "2018-12-04 21:17:36",
 "Name" : "Exterieur",
 "Notifications" : "false",
 "PlanID" : "0",
 "PlanIDs" : [ 0 ],
 "Protected" : false,
 "ShowNotifications" : true,
 "SignalLevel" : "-",
 "SubType" : "LaCrosse TX3",
 "Temp" : 9.0999999999999996,
 "Timers" : "false",
 "Type" : "Temp",
 "TypeImg" : "temperature",
 "Unit" : 167,
 "Used" : 1,
 "XOffset" : "0",
 "YOffset" : "0",
 "idx" : "32"
 },
 {
 "AddjMulti" : 1.0,
 "AddjMulti2" : 1.0,
 "AddjValue" : 0.0,
 "AddjValue2" : 0.0,
 "BatteryLevel" : 255,
 "CustomImage" : 115,
 "Data" : "On",
 "Description" : "Entre le couché et le levé du soleil",
 "DimmerType" : "none",
 "Favorite" : 0,
 "HardwareID" : 21,
 "HardwareName" : "Virtual",
 "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
 "HardwareTypeVal" : 15,
 "HaveDimmer" : true,
 "HaveGroupCmd" : true,
 "HaveTimeout" : false,
 "ID" : "000140F3",
 "Image" : "Sunset",
 "IsSubDevice" : false,
 "LastUpdate" : "2018-12-04 17:06:01",
 "Level" : 100,
 "LevelInt" : 100,
 "MaxDimLevel" : 100,
 "Name" : "Nuit",
 "Notifications" : "false",
 "PlanID" : "0",
 "PlanIDs" : [ 0 ],
 "Protected" : true,
 "ShowNotifications" : true,
 "SignalLevel" : "-",
 "Status" : "On",
 "StrParam1" : "",
 "StrParam2" : "",
 "SubType" : "Switch",
 "SwitchType" : "On/Off",
 "SwitchTypeVal" : 0,
 "Timers" : "true",
 "Type" : "Light/Switch",
 "TypeImg" : "lightbulb",
 "Unit" : 1,
 "Used" : 1,
 "UsedByCamera" : false,
 "XOffset" : "0",
 "YOffset" : "0",
 "idx" : "164"
 },
 {
 "AddjMulti" : 1.0,
 "AddjMulti2" : 1.0,
 "AddjValue" : 0.0,
 "AddjValue2" : 0.0,
 "BatteryLevel" : 255,
 "CustomImage" : 116,
 "Data" : "Off",
 "Description" : "",
 "DimmerType" : "none",
 "Favorite" : 0,
 "HardwareID" : 21,
 "HardwareName" : "Virtual",
 "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
 "HardwareTypeVal" : 15,
 "HaveDimmer" : true,
 "HaveGroupCmd" : true,
 "HaveTimeout" : false,
 "ID" : "000140F4",
 "Image" : "Bed",
 "IsSubDevice" : false,
 "LastUpdate" : "2018-12-04 06:51:18",
 "Level" : 0,
 "LevelInt" : 0,
 "MaxDimLevel" : 100,
 "Name" : "Mode dodo",
 "Notifications" : "false",
 "PlanID" : "0",
 "PlanIDs" : [ 0 ],
 "Protected" : true,
 "ShowNotifications" : true,
 "SignalLevel" : "-",
 "Status" : "Off",
 "StrParam1" : "",
 "StrParam2" : "",
 "SubType" : "Switch",
 "SwitchType" : "On/Off",
 "SwitchTypeVal" : 0,
 "Timers" : "false",
 "Type" : "Light/Switch",
 "TypeImg" : "lightbulb",
 "Unit" : 1,
 "Used" : 1,
 "UsedByCamera" : false,
 "XOffset" : "0",
 "YOffset" : "0",
 "idx" : "165"
 },
 {
 "AddjMulti" : 1.0,
 "AddjMulti2" : 1.0,
 "AddjValue" : 30.0,
 "AddjValue2" : 0.0,
 "BatteryLevel" : 255,
 "CustomImage" : 102,
 "Data" : "Off",
 "Description" : "",
 "DimmerType" : "none",
 "Favorite" : 0,
 "HardwareID" : 21,
 "HardwareName" : "Virtual",
 "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
 "HardwareTypeVal" : 15,
 "HaveDimmer" : true,
 "HaveGroupCmd" : true,
 "HaveTimeout" : false,
 "ID" : "00014221",
 "Image" : "Mdetect",
 "IsSubDevice" : false,
 "LastUpdate" : "2018-12-04 21:09:51",
 "Level" : 0,
 "LevelInt" : 0,
 "MaxDimLevel" : 100,
 "Name" : "Motion",
 "Notifications" : "false",
 "PlanID" : "0",
 "PlanIDs" : [ 0 ],
 "Protected" : true,
 "ShowNotifications" : true,
 "SignalLevel" : "-",
 "Status" : "Off",
 "StrParam1" : "",
 "StrParam2" : "",
 "SubType" : "Switch",
 "SwitchType" : "On/Off",
 "SwitchTypeVal" : 0,
 "Timers" : "true",
 "Type" : "Light/Switch",
 "TypeImg" : "lightbulb",
 "Unit" : 1,
 "Used" : 1,
 "UsedByCamera" : false,
 "XOffset" : "0",
 "YOffset" : "0",
 "idx" : "465"
 },
 {
 "AddjMulti" : 1.0,
 "AddjMulti2" : 1.0,
 "AddjValue" : 0.0,
 "AddjValue2" : 0.0,
 "BatteryLevel" : 255,
 "CustomImage" : 9,
 "Data" : "Off",
 "Description" : "Indique que personne n'est présent dans la maison",
 "DimmerType" : "none",
 "Favorite" : 0,
 "HardwareID" : 21,
 "HardwareName" : "Virtual",
 "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
 "HardwareTypeVal" : 15,
 "HaveDimmer" : true,
 "HaveGroupCmd" : true,
 "HaveTimeout" : false,
 "ID" : "00014313",
 "Image" : "Generic",
 "IsSubDevice" : false,
 "LastUpdate" : "2018-12-04 17:10:03",
 "Level" : 0,
 "LevelInt" : 0,
 "MaxDimLevel" : 100,
 "Name" : "Absence",
 "Notifications" : "false",
 "PlanID" : "0",
 "PlanIDs" : [ 0 ],
 "Protected" : true,
 "ShowNotifications" : true,
 "SignalLevel" : "-",
 "Status" : "Off",
 "StrParam1" : "",
 "StrParam2" : "",
 "SubType" : "Switch",
 "SwitchType" : "On/Off",
 "SwitchTypeVal" : 0,
 "Timers" : "false",
 "Type" : "Light/Switch",
 "TypeImg" : "lightbulb",
 "Unit" : 1,
 "Used" : 1,
 "UsedByCamera" : false,
 "XOffset" : "0",
 "YOffset" : "0",
 "idx" : "707"
 },
 {
 "AddjMulti" : 1.0,
 "AddjMulti2" : 1.0,
 "AddjValue" : 0.0,
 "AddjValue2" : 0.0,
 "BatteryLevel" : 255,
 "CustomImage" : 119,
 "Data" : "Off",
 "Description" : "Pas de mouvement dans la maison depuis 20 minutes (hors porte du garage).\nRemise a zero sur porte d'entrée ou mouvement",
 "DimmerType" : "none",
 "Favorite" : 1,
 "HardwareID" : 21,
 "HardwareName" : "Virtual",
 "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
 "HardwareTypeVal" : 15,
 "HaveDimmer" : true,
 "HaveGroupCmd" : true,
 "HaveTimeout" : false,
 "ID" : "000140EA",
 "Image" : "NoMove",
 "IsSubDevice" : false,
 "LastUpdate" : "2018-12-04 17:00:47",
 "Level" : 0,
 "LevelInt" : 0,
 "MaxDimLevel" : 100,
 "Name" : "NoMove",
 "Notifications" : "false",
 "PlanID" : "0",
 "PlanIDs" : [ 0 ],
 "Protected" : true,
 "ShowNotifications" : true,
 "SignalLevel" : "-",
 "Status" : "Off",
 "StrParam1" : "",
 "StrParam2" : "",
 "SubType" : "Switch",
 "SwitchType" : "On/Off",
 "SwitchTypeVal" : 0,
 "Timers" : "false",
 "Type" : "Light/Switch",
 "TypeImg" : "lightbulb",
 "Unit" : 1,
 "Used" : 1,
 "UsedByCamera" : false,
 "XOffset" : "0",
 "YOffset" : "0",
 "idx" : "155"
 },
 {
 "AddjMulti" : 1.0,
 "AddjMulti2" : 1.0,
 "AddjValue" : 0.0,
 "AddjValue2" : 0.0,
 "BatteryLevel" : 255,
 "CustomImage" : 119,
 "Data" : "Off",
 "Description" : "Pas de mouvement dans la maison et porte garage fermée depuis 20minutes.\nRemise a zéro sur mouvement dans la maison",
 "DimmerType" : "none",
 "Favorite" : 0,
 "HardwareID" : 21,
 "HardwareName" : "Virtual",
 "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
 "HardwareTypeVal" : 15,
 "HaveDimmer" : true,
 "HaveGroupCmd" : true,
 "HaveTimeout" : false,
 "ID" : "00014156",
 "Image" : "NoMove",
 "IsSubDevice" : false,
 "LastUpdate" : "2018-12-04 20:10:32",
 "Level" : 0,
 "LevelInt" : 0,
 "MaxDimLevel" : 100,
 "Name" : "NoMove2",
 "Notifications" : "false",
 "PlanID" : "0",
 "PlanIDs" : [ 0 ],
 "Protected" : true,
 "ShowNotifications" : true,
 "SignalLevel" : "-",
 "Status" : "Off",
 "StrParam1" : "",
 "StrParam2" : "",
 "SubType" : "Switch",
 "SwitchType" : "On/Off",
 "SwitchTypeVal" : 0,
 "Timers" : "false",
 "Type" : "Light/Switch",
 "TypeImg" : "lightbulb",
 "Unit" : 1,
 "Used" : 1,
 "UsedByCamera" : false,
 "XOffset" : "0",
 "YOffset" : "0",
 "idx" : "262"
 },
 {
 "AddjMulti" : 1.0,
 "AddjMulti2" : 1.0,
 "AddjValue" : 0.0,
 "AddjValue2" : 0.0,
 "BatteryLevel" : 255,
 "CustomImage" : 9,
 "Data" : "Off",
 "Description" : "Stephane\nPile remplacée le 8/11/2017",
 "DimmerType" : "none",
 "Favorite" : 0,
 "HardwareID" : 21,
 "HardwareName" : "Virtual",
 "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
 "HardwareTypeVal" : 15,
 "HaveDimmer" : true,
 "HaveGroupCmd" : true,
 "HaveTimeout" : false,
 "ID" : "000142B6",
 "Image" : "Generic",
 "IsSubDevice" : false,
 "LastUpdate" : "2018-05-28 07:24:01",
 "Level" : 0,
 "LevelInt" : 0,
 "MaxDimLevel" : 100,
 "Name" : "Inter_Beacon_Vert",
 "Notifications" : "false",
 "PlanID" : "0",
 "PlanIDs" : [ 0 ],
 "Protected" : true,
 "ShowNotifications" : true,
 "SignalLevel" : "-",
 "Status" : "Off",
 "StrParam1" : "",
 "StrParam2" : "",
 "SubType" : "Switch",
 "SwitchType" : "On/Off",
 "SwitchTypeVal" : 0,
 "Timers" : "false",
 "Type" : "Light/Switch",
 "TypeImg" : "lightbulb",
 "Unit" : 1,
 "Used" : 1,
 "UsedByCamera" : false,
 "XOffset" : "0",
 "YOffset" : "0",
 "idx" : "614"
 },
 {
 "AddjMulti" : 1.0,
 "AddjMulti2" : 1.0,
 "AddjValue" : 0.0,
 "AddjValue2" : 0.0,
 "BatteryLevel" : 255,
 "CustomImage" : 9,
 "Data" : "Off",
 "Description" : "Cecile\nPile remplacée le 12/11/2017",
 "DimmerType" : "none",
 "Favorite" : 0,
 "HardwareID" : 21,
 "HardwareName" : "Virtual",
 "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
 "HardwareTypeVal" : 15,
 "HaveDimmer" : true,
 "HaveGroupCmd" : true,
 "HaveTimeout" : false,
 "ID" : "000142B9",
 "Image" : "Generic",
 "IsSubDevice" : false,
 "LastUpdate" : "2018-06-29 07:35:01",
 "Level" : 0,
 "LevelInt" : 0,
 "MaxDimLevel" : 100,
 "Name" : "Inter_Beacon_Rose",
 "Notifications" : "false",
 "PlanID" : "0",
 "PlanIDs" : [ 0 ],
 "Protected" : true,
 "ShowNotifications" : true,
 "SignalLevel" : "-",
 "Status" : "Off",
 "StrParam1" : "",
 "StrParam2" : "",
 "SubType" : "Switch",
 "SwitchType" : "On/Off",
 "SwitchTypeVal" : 0,
 "Timers" : "false",
 "Type" : "Light/Switch",
 "TypeImg" : "lightbulb",
 "Unit" : 1,
 "Used" : 1,
 "UsedByCamera" : false,
 "XOffset" : "0",
 "YOffset" : "0",
 "idx" : "617"
 },
 {
 "AddjMulti" : 1.0,
 "AddjMulti2" : 1.0,
 "AddjValue" : 0.0,
 "AddjValue2" : 0.0,
 "BatteryLevel" : 255,
 "CustomImage" : 111,
 "Data" : "On",
 "Description" : "TV Salon allumée",
 "DimmerType" : "none",
 "Favorite" : 0,
 "HardwareID" : 22,
 "HardwareName" : "TVSamsung",
 "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
 "HardwareTypeVal" : 15,
 "HaveDimmer" : true,
 "HaveGroupCmd" : true,
 "HaveTimeout" : false,
 "ID" : "000140EE",
 "Image" : "TVSamsung",
 "IsSubDevice" : false,
 "LastUpdate" : "2018-12-04 17:20:00",
 "Level" : 0,
 "LevelInt" : 0,
 "MaxDimLevel" : 100,
 "Name" : "TVSamsung",
 "Notifications" : "false",
 "PlanID" : "0",
 "PlanIDs" : [ 0 ],
 "Protected" : true,
 "ShowNotifications" : true,
 "SignalLevel" : "-",
 "Status" : "On",
 "StrParam1" : "",
 "StrParam2" : "",
 "SubType" : "Switch",
 "SwitchType" : "On/Off",
 "SwitchTypeVal" : 0,
 "Timers" : "false",
 "Type" : "Light/Switch",
 "TypeImg" : "lightbulb",
 "Unit" : 1,
 "Used" : 1,
 "UsedByCamera" : false,
 "XOffset" : "0",
 "YOffset" : "0",
 "idx" : "159"
 },
 {
 "AddjMulti" : 1.0,
 "AddjMulti2" : 1.0,
 "AddjValue" : 0.0,
 "AddjValue2" : 0.0,
 "BatteryLevel" : 255,
 "CustomImage" : 0,
 "Data" : "Off",
 "Description" : "Module A voie 1",
 "DimmerType" : "none",
 "Favorite" : 1,
 "HardwareID" : 23,
 "HardwareName" : "Z-Stick Gen5",
 "HardwareType" : "OpenZWave USB",
 "HardwareTypeVal" : 21,
 "HaveDimmer" : true,
 "HaveGroupCmd" : true,
 "HaveTimeout" : false,
 "ID" : "00002801",
 "Image" : "Light",
 "IsSubDevice" : false,
 "LastUpdate" : "2018-12-04 20:58:48",
 "Level" : 100,
 "LevelInt" : 100,
 "MaxDimLevel" : 100,
 "Name" : "Cuisine",
 "Notifications" : "false",
 "PlanID" : "6",
 "PlanIDs" : [ 6 ],
 "Protected" : false,
 "ShowNotifications" : true,
 "SignalLevel" : "-",
 "Status" : "Off",
 "StrParam1" : "",
 "StrParam2" : "",
 "SubType" : "Switch",
 "SwitchType" : "On/Off",
 "SwitchTypeVal" : 0,
 "Timers" : "false",
 "Type" : "Light/Switch",
 "TypeImg" : "lightbulb",
 "Unit" : 1,
 "Used" : 1,
 "UsedByCamera" : false,
 "XOffset" : "0",
 "YOffset" : "0",
 "idx" : "268"
 },
 {
 "AddjMulti" : 1.0,
 "AddjMulti2" : 1.0,
 "AddjValue" : 0.0,
 "AddjValue2" : 0.0,
 "BatteryLevel" : 255,
 "CustomImage" : 127,
 "Data" : "On",
 "Description" : "Module A voie 2",
 "DimmerType" : "none",
 "Favorite" : 1,
 "HardwareID" : 23,
 "HardwareName" : "Z-Stick Gen5",
 "HardwareType" : "OpenZWave USB",
 "HardwareTypeVal" : 21,
 "HaveDimmer" : true,
 "HaveGroupCmd" : true,
 "HaveTimeout" : false,
 "ID" : "00002802",
 "Image" : "LedBar",
 "IsSubDevice" : false,
 "LastUpdate" : "2018-12-04 17:39:56",
 "Level" : 255,
 "LevelInt" : 255,
 "MaxDimLevel" : 100,
 "Name" : "Évier",
 "Notifications" : "false",
 "PlanID" : "6",
 "PlanIDs" : [ 6 ],
 "Protected" : false,
 "ShowNotifications" : true,
 "SignalLevel" : "-",
 "Status" : "On",
 "StrParam1" : "",
 "StrParam2" : "",
 "SubType" : "Switch",
 "SwitchType" : "On/Off",
 "SwitchTypeVal" : 0,
 "Timers" : "false",
 "Type" : "Light/Switch",
 "TypeImg" : "lightbulb",
 "Unit" : 1,
 "Used" : 1,
 "UsedByCamera" : false,
 "XOffset" : "0",
 "YOffset" : "0",
 "idx" : "269"
 },
 {
 "AddjMulti" : 1.0,
 "AddjMulti2" : 1.0,
 "AddjValue" : 0.0,
 "AddjValue2" : 0.0,
 "BatteryLevel" : 255,
 "CustomImage" : 123,
 "Data" : "On",
 "Description" : "Dimmer",
 "DimmerType" : "abs",
 "Favorite" : 1,
 "HardwareID" : 23,
 "HardwareName" : "Z-Stick Gen5",
 "HardwareType" : "OpenZWave USB",
 "HardwareTypeVal" : 21,
 "HaveDimmer" : true,
 "HaveGroupCmd" : true,
 "HaveTimeout" : false,
 "ID" : "00002A01",
 "Image" : "LedSpot",
 "IsSubDevice" : false,
 "LastUpdate" : "2018-12-04 17:39:57",
 "Level" : 100,
 "LevelInt" : 100,
 "MaxDimLevel" : 100,
 "Name" : "Salon",
 "Notifications" : "false",
 "PlanID" : "5",
 "PlanIDs" : [ 5 ],
 "Protected" : false,
 "ShowNotifications" : true,
 "SignalLevel" : "-",
 "Status" : "On",
 "StrParam1" : "",
 "StrParam2" : "",
 "SubType" : "Switch",
 "SwitchType" : "Dimmer",
 "SwitchTypeVal" : 7,
 "Timers" : "false",
 "Type" : "Light/Switch",
 "TypeImg" : "dimmer",
 "Unit" : 1,
 "Used" : 1,
 "UsedByCamera" : false,
 "XOffset" : "1172",
 "YOffset" : "267",
 "idx" : "271"
 },
 {
 "AddjMulti" : 1.0,
 "AddjMulti2" : 1.0,
 "AddjValue" : 0.0,
 "AddjValue2" : 0.0,
 "BatteryLevel" : 255,
 "Color" : "{\"b\":0,\"cw\":112,\"g\":0,\"m\":2,\"r\":0,\"t\":143,\"ww\":143}",
 "CustomImage" : 120,
 "Data" : "Off",
 "Description" : "",
 "DimmerType" : "abs",
 "Favorite" : 1,
 "HardwareID" : 28,
 "HardwareName" : "Milight V6",
 "HardwareType" : "Limitless/AppLamp/Mi Light with LAN/WiFi interface",
 "HardwareTypeVal" : 22,
 "HaveDimmer" : true,
 "HaveGroupCmd" : false,
 "HaveTimeout" : false,
 "ID" : "1",
 "Image" : "LED",
 "IsSubDevice" : false,
 "LastUpdate" : "2018-12-04 21:00:01",
 "Level" : 100,
 "LevelInt" : 100,
 "MaxDimLevel" : 100,
 "Name" : "Niche",
 "Notifications" : "false",
 "PlanID" : "5",
 "PlanIDs" : [ 5 ],
 "Protected" : false,
 "ShowNotifications" : true,
 "SignalLevel" : "-",
 "Status" : "Off",
 "StrParam1" : "",
 "StrParam2" : "",
 "SubType" : "RGBWW",
 "SwitchType" : "Dimmer",
 "SwitchTypeVal" : 7,
 "Timers" : "true",
 "Type" : "Color Switch",
 "TypeImg" : "dimmer",
 "Unit" : 1,
 "Used" : 1,
 "UsedByCamera" : false,
 "XOffset" : "1519",
 "YOffset" : "183",
 "idx" : "735"
 },
 {
 "AddjMulti" : 1.0,
 "AddjMulti2" : 1.0,
 "AddjValue" : 0.0,
 "AddjValue2" : 0.0,
 "BatteryLevel" : 255,
 "CustomImage" : 0,
 "Data" : "Off",
 "Description" : "Module B voie 1",
 "DimmerType" : "none",
 "Favorite" : 1,
 "HardwareID" : 23,
 "HardwareName" : "Z-Stick Gen5",
 "HardwareType" : "OpenZWave USB",
 "HardwareTypeVal" : 21,
 "HaveDimmer" : true,
 "HaveGroupCmd" : true,
 "HaveTimeout" : false,
 "ID" : "00004801",
 "Image" : "Light",
 "IsSubDevice" : false,
 "LastUpdate" : "2018-12-04 20:10:40",
 "Level" : 0,
 "LevelInt" : 0,
 "MaxDimLevel" : 100,
 "Name" : "Salle a manger",
 "Notifications" : "false",
 "PlanID" : "5",
 "PlanIDs" : [ 5 ],
 "Protected" : false,
 "ShowNotifications" : true,
 "SignalLevel" : "-",
 "Status" : "Off",
 "StrParam1" : "",
 "StrParam2" : "",
 "SubType" : "Switch",
 "SwitchType" : "On/Off",
 "SwitchTypeVal" : 0,
 "Timers" : "false",
 "Type" : "Light/Switch",
 "TypeImg" : "lightbulb",
 "Unit" : 1,
 "Used" : 1,
 "UsedByCamera" : false,
 "XOffset" : "992",
 "YOffset" : "780",
 "idx" : "467"
 },
 {
 "AddjMulti" : 1.0,
 "AddjMulti2" : 1.0,
 "AddjValue" : 0.0,
 "AddjValue2" : 0.0,
 "BatteryLevel" : 255,
 "CustomImage" : 101,
 "Data" : "On",
 "Description" : "Code télécommande : 11111 \nBP_A_ON\nPB_A_Off",
 "DimmerType" : "none",
 "Favorite" : 1,
 "HardwareID" : 21,
 "HardwareName" : "Virtual",
 "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
 "HardwareTypeVal" : 15,
 "HaveDimmer" : true,
 "HaveGroupCmd" : true,
 "HaveTimeout" : false,
 "ID" : "000141D9",
 "Image" : "Uplighter",
 "IsSubDevice" : false,
 "LastUpdate" : "2018-12-04 17:41:23",
 "Level" : 0,
 "LevelInt" : 0,
 "MaxDimLevel" : 100,
 "Name" : "Lampadaire Salon",
 "Notifications" : "false",
 "PlanID" : "5",
 "PlanIDs" : [ 5 ],
 "Protected" : false,
 "ShowNotifications" : true,
 "SignalLevel" : "-",
 "Status" : "On",
 "StrParam1" : "",
 "StrParam2" : "",
 "SubType" : "Switch",
 "SwitchType" : "On/Off",
 "SwitchTypeVal" : 0,
 "Timers" : "false",
 "Type" : "Light/Switch",
 "TypeImg" : "lightbulb",
 "Unit" : 1,
 "Used" : 1,
 "UsedByCamera" : false,
 "XOffset" : "1521",
 "YOffset" : "69",
 "idx" : "393"
 },
 {
 "AddjMulti" : 1.0,
 "AddjMulti2" : 1.0,
 "AddjValue" : 1800.0,
 "AddjValue2" : 0.0,
 "BatteryLevel" : 255,
 "CustomImage" : 122,
 "Data" : "Off",
 "Description" : "Module C voie 1",
 "DimmerType" : "none",
 "Favorite" : 1,
 "HardwareID" : 23,
 "HardwareName" : "Z-Stick Gen5",
 "HardwareType" : "OpenZWave USB",
 "HardwareTypeVal" : 21,
 "HaveDimmer" : true,
 "HaveGroupCmd" : true,
 "HaveTimeout" : false,
 "ID" : "00004701",
 "Image" : "Lightbulb",
 "IsSubDevice" : false,
 "LastUpdate" : "2018-11-28 19:23:08",
 "Level" : 0,
 "LevelInt" : 0,
 "MaxDimLevel" : 100,
 "Name" : "Terrasse",
 "Notifications" : "false",
 "PlanID" : "7",
 "PlanIDs" : [ 7 ],
 "Protected" : false,
 "ShowNotifications" : true,
 "SignalLevel" : "-",
 "Status" : "Off",
 "StrParam1" : "",
 "StrParam2" : "",
 "SubType" : "Switch",
 "SwitchType" : "On/Off",
 "SwitchTypeVal" : 0,
 "Timers" : "false",
 "Type" : "Light/Switch",
 "TypeImg" : "lightbulb",
 "Unit" : 1,
 "Used" : 1,
 "UsedByCamera" : false,
 "XOffset" : "0",
 "YOffset" : "0",
 "idx" : "430"
 },
 {
 "AddjMulti" : 1.0,
 "AddjMulti2" : 1.0,
 "AddjValue" : 0.0,
 "AddjValue2" : 0.0,
 "BatteryLevel" : 255,
 "CustomImage" : 128,
 "Data" : "Off",
 "Description" : "Réglages :\nLa Nuit(HC)=17.5°C < marche > 18°C \nLe jour(HP)=16°C <marche > 16.8°C(Insert <45°C)\nSi fenêtre chambre fermée et P Max 3kW",
 "DimmerType" : "none",
 "Favorite" : 0,
 "HardwareID" : 21,
 "HardwareName" : "Virtual",
 "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
 "HardwareTypeVal" : 15,
 "HaveDimmer" : true,
 "HaveGroupCmd" : true,
 "HaveTimeout" : false,
 "ID" : "0001421A",
 "Image" : "icone_chauffage",
 "IsSubDevice" : false,
 "LastUpdate" : "2018-11-07 21:56:50",
 "Level" : 0,
 "LevelInt" : 0,
 "MaxDimLevel" : 100,
 "Name" : "Radiateur Chambre",
 "Notifications" : "false",
 "PlanID" : "0",
 "PlanIDs" : [ 0 ],
 "Protected" : true,
 "ShowNotifications" : true,
 "SignalLevel" : "-",
 "Status" : "Off",
 "StrParam1" : "",
 "StrParam2" : "",
 "SubType" : "Switch",
 "SwitchType" : "On/Off",
 "SwitchTypeVal" : 0,
 "Timers" : "false",
 "Type" : "Light/Switch",
 "TypeImg" : "lightbulb",
 "Unit" : 1,
 "Used" : 1,
 "UsedByCamera" : false,
 "XOffset" : "0",
 "YOffset" : "0",
 "idx" : "458"
 },
 {
 "AddjMulti" : 1.0,
 "AddjMulti2" : 1.0,
 "AddjValue" : 0.0,
 "AddjValue2" : 0.0,
 "BatteryLevel" : 255,
 "CustomImage" : 7,
 "Data" : "Off",
 "Description" : "Ventilateur insert\nMode automatique : 95/90°C\nCode télécommande :11111 \nBP_C_ON\nPB_C_Off",
 "DimmerType" : "none",
 "Favorite" : 0,
 "HardwareID" : 21,
 "HardwareName" : "Virtual",
 "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
 "HardwareTypeVal" : 15,
 "HaveDimmer" : true,
 "HaveGroupCmd" : true,
 "HaveTimeout" : false,
 "ID" : "000141BE",
 "Image" : "Fan",
 "IsSubDevice" : false,
 "LastUpdate" : "2018-12-01 00:49:44",
 "Level" : 0,
 "LevelInt" : 0,
 "MaxDimLevel" : 100,
 "Name" : "Ventilateur Insert",
 "Notifications" : "false",
 "PlanID" : "0",
 "PlanIDs" : [ 0 ],
 "Protected" : true,
 "ShowNotifications" : true,
 "SignalLevel" : "-",
 "Status" : "Off",
 "StrParam1" : "",
 "StrParam2" : "",
 "SubType" : "Switch",
 "SwitchType" : "On/Off",
 "SwitchTypeVal" : 0,
 "Timers" : "false",
 "Type" : "Light/Switch",
 "TypeImg" : "lightbulb",
 "Unit" : 1,
 "Used" : 1,
 "UsedByCamera" : false,
 "XOffset" : "0",
 "YOffset" : "0",
 "idx" : "366"
 },
 {
 "AddjMulti" : 1.0,
 "AddjMulti2" : 1.0,
 "AddjValue" : 0.0,
 "AddjValue2" : 0.0,
 "BatteryLevel" : 255,
 "CustomImage" : 108,
 "Data" : "Off",
 "Description" : "VMC en vitesse mini (Mode Eco)\nCode télécommande : 11110\nBP_A_ON\nPB_A_Off",
 "DimmerType" : "none",
 "Favorite" : 0,
 "HardwareID" : 21,
 "HardwareName" : "Virtual",
 "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
 "HardwareTypeVal" : 15,
 "HaveDimmer" : true,
 "HaveGroupCmd" : true,
 "HaveTimeout" : false,
 "ID" : "00014311",
 "Image" : "Slider",
 "IsSubDevice" : false,
 "LastUpdate" : "2018-12-04 17:10:03",
 "Level" : 0,
 "LevelInt" : 0,
 "MaxDimLevel" : 100,
 "Name" : "VMC_Eco",
 "Notifications" : "false",
 "PlanID" : "0",
 "PlanIDs" : [ 0 ],
 "Protected" : true,
 "ShowNotifications" : true,
 "SignalLevel" : "-",
 "Status" : "Off",
 "StrParam1" : "",
 "StrParam2" : "",
 "SubType" : "Switch",
 "SwitchType" : "On/Off",
 "SwitchTypeVal" : 0,
 "Timers" : "false",
 "Type" : "Light/Switch",
 "TypeImg" : "lightbulb",
 "Unit" : 1,
 "Used" : 1,
 "UsedByCamera" : false,
 "XOffset" : "0",
 "YOffset" : "0",
 "idx" : "705"
 },
 {
 "AddjMulti" : 1.0,
 "AddjMulti2" : 1.0,
 "AddjValue" : 0.0,
 "AddjValue2" : 0.0,
 "BatteryLevel" : 255,
 "Color" : "{\"b\":85,\"cw\":0,\"g\":255,\"m\":3,\"r\":0,\"t\":0,\"ww\":0}",
 "CustomImage" : 121,
 "Data" : "Off",
 "Description" : "",
 "DimmerType" : "abs",
 "Favorite" : 0,
 "HardwareID" : 27,
 "HardwareName" : "Milight",
 "HardwareType" : "Limitless/AppLamp/Mi Light with LAN/WiFi interface",
 "HardwareTypeVal" : 22,
 "HaveDimmer" : true,
 "HaveGroupCmd" : false,
 "HaveTimeout" : false,
 "ID" : "1",
 "Image" : "RGB-LED",
 "IsSubDevice" : false,
 "LastUpdate" : "2018-10-24 19:16:04",
 "Level" : 69,
 "LevelInt" : 69,
 "MaxDimLevel" : 100,
 "Name" : "LED Alarme",
 "Notifications" : "false",
 "PlanID" : "0",
 "PlanIDs" : [ 0 ],
 "Protected" : false,
 "ShowNotifications" : true,
 "SignalLevel" : "-",
 "Status" : "Off",
 "StrParam1" : "",
 "StrParam2" : "",
 "SubType" : "RGBW",
 "SwitchType" : "Dimmer",
 "SwitchTypeVal" : 7,
 "Timers" : "false",
 "Type" : "Color Switch",
 "TypeImg" : "dimmer",
 "Unit" : 1,
 "Used" : 1,
 "UsedByCamera" : false,
 "XOffset" : "0",
 "YOffset" : "0",
 "idx" : "405"
 },
 {
 "AddjMulti" : 1.0,
 "AddjMulti2" : 1.0,
 "AddjValue" : 0.0,
 "AddjValue2" : 0.0,
 "BatteryLevel" : 255,
 "CustomImage" : 108,
 "Data" : "Off",
 "Description" : "",
 "DimmerType" : "none",
 "Favorite" : 0,
 "HardwareID" : 21,
 "HardwareName" : "Virtual",
 "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
 "HardwareTypeVal" : 15,
 "HaveDimmer" : true,
 "HaveGroupCmd" : true,
 "HaveTimeout" : false,
 "ID" : "000140EC",
 "Image" : "Slider",
 "IsSubDevice" : false,
 "LastUpdate" : "2018-12-04 15:28:01",
 "Level" : 100,
 "LevelInt" : 100,
 "MaxDimLevel" : 100,
 "Name" : "HC (EDF)",
 "Notifications" : "false",
 "PlanID" : "0",
 "PlanIDs" : [ 0 ],
 "Protected" : true,
 "ShowNotifications" : true,
 "SignalLevel" : "-",
 "Status" : "Off",
 "StrParam1" : "",
 "StrParam2" : "",
 "SubType" : "Switch",
 "SwitchType" : "On/Off",
 "SwitchTypeVal" : 0,
 "Timers" : "true",
 "Type" : "Light/Switch",
 "TypeImg" : "lightbulb",
 "Unit" : 1,
 "Used" : 1,
 "UsedByCamera" : false,
 "XOffset" : "0",
 "YOffset" : "0",
 "idx" : "157"
 },
 {
 "AddjMulti" : 1.0,
 "AddjMulti2" : 1.0,
 "AddjValue" : 0.0,
 "AddjValue2" : 0.0,
 "BatteryLevel" : 100,
 "CustomImage" : 0,
 "Data" : "Disarm",
 "Description" : "Telecommande l'alarme, info utilisé par le RFXTRX pour modifier l’étatde l'alarme",
 "Favorite" : 0,
 "HardwareID" : 11,
 "HardwareName" : "RFXTRX",
 "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
 "HardwareTypeVal" : 1,
 "HaveDimmer" : false,
 "HaveGroupCmd" : false,
 "HaveTimeout" : false,
 "ID" : "08C847",
 "LastUpdate" : "2018-11-13 18:46:47",
 "MaxDimLevel" : 0,
 "Name" : "Etat Alarme",
 "Notifications" : "false",
 "PlanID" : "0",
 "PlanIDs" : [ 0 ],
 "Protected" : true,
 "ShowNotifications" : true,
 "SignalLevel" : 6,
 "Status" : "Disarm",
 "StrParam1" : "",
 "StrParam2" : "",
 "SubType" : "Meiantech/Atlantic/Aidebao",
 "SwitchType" : "Security",
 "SwitchTypeVal" : 0,
 "Timers" : "false",
 "Type" : "Security",
 "TypeImg" : "security",
 "Unit" : 0,
 "Used" : 1,
 "XOffset" : "0",
 "YOffset" : "0",
 "idx" : "80"
 },
 {
 "AddjMulti" : 1.0,
 "AddjMulti2" : 1.0,
 "AddjValue" : 0.0,
 "AddjValue2" : 0.0,
 "BatteryLevel" : 100,
 "CustomImage" : 0,
 "Data" : "Disarm",
 "Description" : "Etat de \"Clavier Alarm\"",
 "Favorite" : 1,
 "HardwareID" : 11,
 "HardwareName" : "RFXTRX",
 "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
 "HardwareTypeVal" : 1,
 "HaveDimmer" : false,
 "HaveGroupCmd" : false,
 "HaveTimeout" : false,
 "ID" : "E0A080",
 "LastUpdate" : "2018-10-16 13:48:17",
 "MaxDimLevel" : 0,
 "Name" : "Clavier Alarme",
 "Notifications" : "false",
 "PlanID" : "0",
 "PlanIDs" : [ 0 ],
 "Protected" : true,
 "ShowNotifications" : true,
 "SignalLevel" : 5,
 "Status" : "Disarm",
 "StrParam1" : "",
 "StrParam2" : "",
 "SubType" : "Meiantech/Atlantic/Aidebao",
 "SwitchType" : "Security",
 "SwitchTypeVal" : 0,
 "Timers" : "false",
 "Type" : "Security",
 "TypeImg" : "security",
 "Unit" : 0,
 "Used" : 1,
 "XOffset" : "0",
 "YOffset" : "0",
 "idx" : "117"
 },
 {
 "AddjMulti" : 1.0,
 "AddjMulti2" : 1.0,
 "AddjValue" : 0.0,
 "AddjValue2" : 0.0,
 "BatteryLevel" : 255,
 "CustomImage" : 13,
 "Data" : "Off",
 "Description" : "",
 "DimmerType" : "none",
 "Favorite" : 1,
 "HardwareID" : 21,
 "HardwareName" : "Virtual",
 "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
 "HardwareTypeVal" : 15,
 "HaveDimmer" : true,
 "HaveGroupCmd" : true,
 "HaveTimeout" : false,
 "ID" : "0001422B",
 "Image" : "Alarm",
 "IsSubDevice" : false,
 "LastUpdate" : "2018-04-07 13:39:37",
 "Level" : 0,
 "LevelInt" : 0,
 "MaxDimLevel" : 100,
 "Name" : "ALARME",
 "Notifications" : "true",
 "PlanID" : "0",
 "PlanIDs" : [ 0 ],
 "Protected" : true,
 "ShowNotifications" : true,
 "SignalLevel" : "-",
 "Status" : "Off",
 "StrParam1" : "",
 "StrParam2" : "",
 "SubType" : "Switch",
 "SwitchType" : "On/Off",
 "SwitchTypeVal" : 0,
 "Timers" : "false",
 "Type" : "Light/Switch",
 "TypeImg" : "lightbulb",
 "Unit" : 1,
 "Used" : 1,
 "UsedByCamera" : false,
 "XOffset" : "0",
 "YOffset" : "0",
 "idx" : "475"
 },
 {
 "AddjMulti" : 1.0,
 "AddjMulti2" : 1.0,
 "AddjValue" : 0.0,
 "AddjValue2" : 0.0,
 "BatteryLevel" : 255,
 "CustomImage" : 117,
 "Data" : "Off",
 "Description" : "A activer pendant les vacances.\nPermet d'activer ou de désactiver les options \"réveils\"",
 "DimmerType" : "none",
 "Favorite" : 0,
 "HardwareID" : 21,
 "HardwareName" : "Virtual",
 "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
 "HardwareTypeVal" : 15,
 "HaveDimmer" : true,
 "HaveGroupCmd" : true,
 "HaveTimeout" : false,
 "ID" : "0001419E",
 "Image" : "Holiday",
 "IsSubDevice" : false,
 "LastUpdate" : "2018-10-10 17:25:12",
 "Level" : 0,
 "LevelInt" : 0,
 "MaxDimLevel" : 100,
 "Name" : "Mode Vacances",
 "Notifications" : "false",
 "PlanID" : "0",
 "PlanIDs" : [ 0 ],
 "Protected" : true,
 "ShowNotifications" : true,
 "SignalLevel" : "-",
 "Status" : "Off",
 "StrParam1" : "",
 "StrParam2" : "",
 "SubType" : "Switch",
 "SwitchType" : "On/Off",
 "SwitchTypeVal" : 0,
 "Timers" : "false",
 "Type" : "Light/Switch",
 "TypeImg" : "lightbulb",
 "Unit" : 1,
 "Used" : 1,
 "UsedByCamera" : false,
 "XOffset" : "0",
 "YOffset" : "0",
 "idx" : "334"
 },
 {
 "AddjMulti" : 1.0,
 "AddjMulti2" : 1.0,
 "AddjValue" : 0.0,
 "AddjValue2" : 0.0,
 "BatteryLevel" : 255,
 "CustomImage" : 1,
 "Data" : "Off",
 "Description" : "MiniC\nCode télécommande : 11111 \nBP_D_ON\nPB_D_Off",
 "DimmerType" : "none",
 "Favorite" : 0,
 "HardwareID" : 21,
 "HardwareName" : "Virtual",
 "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
 "HardwareTypeVal" : 15,
 "HaveDimmer" : true,
 "HaveGroupCmd" : true,
 "HaveTimeout" : false,
 "ID" : "00014214",
 "Image" : "WallSocket",
 "IsSubDevice" : false,
 "LastUpdate" : "2018-11-18 15:21:09",
 "Level" : 0,
 "LevelInt" : 0,
 "MaxDimLevel" : 100,
 "Name" : "PC4",
 "Notifications" : "false",
 "PlanID" : "0",
 "PlanIDs" : [ 0 ],
 "Protected" : true,
 "ShowNotifications" : true,
 "SignalLevel" : "-",
 "Status" : "Off",
 "StrParam1" : "",
 "StrParam2" : "",
 "SubType" : "Switch",
 "SwitchType" : "On/Off",
 "SwitchTypeVal" : 0,
 "Timers" : "false",
 "Type" : "Light/Switch",
 "TypeImg" : "lightbulb",
 "Unit" : 1,
 "Used" : 1,
 "UsedByCamera" : false,
 "XOffset" : "0",
 "YOffset" : "0",
 "idx" : "452"
 },
 {
 "AddjMulti" : 1.0,
 "AddjMulti2" : 1.0,
 "AddjValue" : 7200.0,
 "AddjValue2" : 0.0,
 "BatteryLevel" : 255,
 "CustomImage" : 10,
 "Data" : "Off",
 "Description" : "Code télécommande : 11111 \nBP_B_ON\nPB_B_Off",
 "DimmerType" : "none",
 "Favorite" : 1,
 "HardwareID" : 21,
 "HardwareName" : "Virtual",
 "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
 "HardwareTypeVal" : 15,
 "HaveDimmer" : true,
 "HaveGroupCmd" : true,
 "HaveTimeout" : false,
 "ID" : "00014215",
 "Image" : "Fireplace",
 "IsSubDevice" : false,
 "LastUpdate" : "2018-11-15 00:29:55",
 "Level" : 0,
 "LevelInt" : 0,
 "MaxDimLevel" : 100,
 "Name" : "Tue-mouche",
 "Notifications" : "false",
 "PlanID" : "6",
 "PlanIDs" : [ 6 ],
 "Protected" : false,
 "ShowNotifications" : true,
 "SignalLevel" : "-",
 "Status" : "Off",
 "StrParam1" : "",
 "StrParam2" : "",
 "SubType" : "Switch",
 "SwitchType" : "On/Off",
 "SwitchTypeVal" : 0,
 "Timers" : "false",
 "Type" : "Light/Switch",
 "TypeImg" : "lightbulb",
 "Unit" : 1,
 "Used" : 1,
 "UsedByCamera" : false,
 "XOffset" : "0",
 "YOffset" : "0",
 "idx" : "453"
 },
 {
 "AddjMulti" : 1.0,
 "AddjMulti2" : 1.0,
 "AddjValue" : 0.0,
 "AddjValue2" : 0.0,
 "BatteryLevel" : 100,
 "CustomImage" : 0,
 "Data" : "Normal",
 "Description" : "",
 "Favorite" : 0,
 "HardwareID" : 11,
 "HardwareName" : "RFXTRX",
 "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
 "HardwareTypeVal" : 1,
 "HaveDimmer" : false,
 "HaveGroupCmd" : false,
 "HaveTimeout" : false,
 "ID" : "DE24F8",
 "LastUpdate" : "2018-12-04 20:56:56",
 "MaxDimLevel" : 0,
 "Name" : "Capteur placard",
 "Notifications" : "false",
 "PlanID" : "0",
 "PlanIDs" : [ 0 ],
 "Protected" : false,
 "ShowNotifications" : true,
 "SignalLevel" : 7,
 "Status" : "Normal",
 "StrParam1" : "",
 "StrParam2" : "",
 "SubType" : "Meiantech/Atlantic/Aidebao",
 "SwitchType" : "Security",
 "SwitchTypeVal" : 3,
 "Timers" : "false",
 "Type" : "Security",
 "TypeImg" : "security",
 "Unit" : 0,
 "Used" : 1,
 "XOffset" : "0",
 "YOffset" : "0",
 "idx" : "751"
 },
 {
 "AddjMulti" : 1.0,
 "AddjMulti2" : 1.0,
 "AddjValue" : 90.0,
 "AddjValue2" : 0.0,
 "BatteryLevel" : 255,
 "CustomImage" : 126,
 "Data" : "Off",
 "Description" : "",
 "DimmerType" : "none",
 "Favorite" : 0,
 "HardwareID" : 28,
 "HardwareName" : "Milight V6",
 "HardwareType" : "Limitless/AppLamp/Mi Light with LAN/WiFi interface",
 "HardwareTypeVal" : 22,
 "HaveDimmer" : true,
 "HaveGroupCmd" : false,
 "HaveTimeout" : false,
 "ID" : "1",
 "Image" : "LedBarTurned",
 "IsSubDevice" : false,
 "LastUpdate" : "2018-12-04 20:58:11",
 "Level" : 0,
 "LevelInt" : 0,
 "MaxDimLevel" : 100,
 "Name" : "Placard",
 "Notifications" : "false",
 "PlanID" : "5",
 "PlanIDs" : [ 5 ],
 "Protected" : false,
 "ShowNotifications" : true,
 "SignalLevel" : "-",
 "Status" : "Off",
 "StrParam1" : "",
 "StrParam2" : "",
 "SubType" : "RGBWW",
 "SwitchType" : "On/Off",
 "SwitchTypeVal" : 0,
 "Timers" : "false",
 "Type" : "Color Switch",
 "TypeImg" : "lightbulb",
 "Unit" : 2,
 "Used" : 1,
 "UsedByCamera" : false,
 "XOffset" : "1521",
 "YOffset" : "258",
 "idx" : "736"
 },
 {
 "AddjMulti" : 1.0,
 "AddjMulti2" : 1.0,
 "AddjValue" : 0.0,
 "AddjValue2" : 0.0,
 "BatteryLevel" : 100,
 "CustomImage" : 0,
 "Data" : "Alarm",
 "Description" : "Portail Garage",
 "Favorite" : 0,
 "HardwareID" : 11,
 "HardwareName" : "RFXTRX",
 "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
 "HardwareTypeVal" : 1,
 "HaveDimmer" : false,
 "HaveGroupCmd" : false,
 "HaveTimeout" : false,
 "ID" : "486CB7",
 "LastUpdate" : "2018-12-04 17:05:23",
 "MaxDimLevel" : 0,
 "Name" : "Capteur 1",
 "Notifications" : "false",
 "PlanID" : "0",
 "PlanIDs" : [ 0 ],
 "Protected" : true,
 "ShowNotifications" : true,
 "SignalLevel" : 6,
 "Status" : "Alarm",
 "StrParam1" : "",
 "StrParam2" : "",
 "SubType" : "Meiantech/Atlantic/Aidebao",
 "SwitchType" : "Security",
 "SwitchTypeVal" : 0,
 "Timers" : "false",
 "Type" : "Security",
 "TypeImg" : "security",
 "Unit" : 0,
 "Used" : 1,
 "XOffset" : "0",
 "YOffset" : "0",
 "idx" : "108"
 },
 {
 "AddjMulti" : 1.0,
 "AddjMulti2" : 1.0,
 "AddjValue" : 0.0,
 "AddjValue2" : 0.0,
 "BatteryLevel" : 100,
 "CustomImage" : 0,
 "Data" : "Normal",
 "Description" : "Porte d'entrée",
 "Favorite" : 0,
 "HardwareID" : 11,
 "HardwareName" : "RFXTRX",
 "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
 "HardwareTypeVal" : 1,
 "HaveDimmer" : false,
 "HaveGroupCmd" : false,
 "HaveTimeout" : false,
 "ID" : "485CF1",
 "LastUpdate" : "2018-11-21 22:20:39",
 "MaxDimLevel" : 0,
 "Name" : "Capteur 2",
 "Notifications" : "false",
 "PlanID" : "0",
 "PlanIDs" : [ 0 ],
 "Protected" : true,
 "ShowNotifications" : true,
 "SignalLevel" : 7,
 "Status" : "Normal",
 "StrParam1" : "",
 "StrParam2" : "",
 "SubType" : "Meiantech/Atlantic/Aidebao",
 "SwitchType" : "Security",
 "SwitchTypeVal" : 0,
 "Timers" : "false",
 "Type" : "Security",
 "TypeImg" : "security",
 "Unit" : 0,
 "Used" : 1,
 "XOffset" : "0",
 "YOffset" : "0",
 "idx" : "109"
 },
 {
 "AddjMulti" : 1.0,
 "AddjMulti2" : 1.0,
 "AddjValue" : 0.0,
 "AddjValue2" : 0.0,
 "BatteryLevel" : 100,
 "CustomImage" : 0,
 "Data" : "Normal",
 "Description" : "Porte accés Garage",
 "Favorite" : 0,
 "HardwareID" : 11,
 "HardwareName" : "RFXTRX",
 "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
 "HardwareTypeVal" : 1,
 "HaveDimmer" : false,
 "HaveGroupCmd" : false,
 "HaveTimeout" : false,
 "ID" : "48EC28",
 "LastUpdate" : "2018-12-04 21:05:10",
 "MaxDimLevel" : 0,
 "Name" : "Capteur 3",
 "Notifications" : "false",
 "PlanID" : "0",
 "PlanIDs" : [ 0 ],
 "Protected" : true,
 "ShowNotifications" : true,
 "SignalLevel" : 6,
 "Status" : "Normal",
 "StrParam1" : "",
 "StrParam2" : "",
 "SubType" : "Meiantech/Atlantic/Aidebao",
 "SwitchType" : "Security",
 "SwitchTypeVal" : 0,
 "Timers" : "false",
 "Type" : "Security",
 "TypeImg" : "security",
 "Unit" : 0,
 "Used" : 1,
 "XOffset" : "0",
 "YOffset" : "0",
 "idx" : "110"
 },
 {
 "AddjMulti" : 1.0,
 "AddjMulti2" : 1.0,
 "AddjValue" : 0.0,
 "AddjValue2" : 0.0,
 "BatteryLevel" : 100,
 "CustomImage" : 0,
 "Data" : "Normal",
 "Description" : "Chambre Tom",
 "Favorite" : 0,
 "HardwareID" : 11,
 "HardwareName" : "RFXTRX",
 "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
 "HardwareTypeVal" : 1,
 "HaveDimmer" : false,
 "HaveGroupCmd" : false,
 "HaveTimeout" : false,
 "ID" : "486C6D",
 "LastUpdate" : "2018-12-02 17:53:00",
 "MaxDimLevel" : 0,
 "Name" : "Capteur 4",
 "Notifications" : "false",
 "PlanID" : "0",
 "PlanIDs" : [ 0 ],
 "Protected" : true,
 "ShowNotifications" : true,
 "SignalLevel" : 5,
 "Status" : "Normal",
 "StrParam1" : "",
 "StrParam2" : "",
 "SubType" : "Meiantech/Atlantic/Aidebao",
 "SwitchType" : "Security",
 "SwitchTypeVal" : 0,
 "Timers" : "false",
 "Type" : "Security",
 "TypeImg" : "security",
 "Unit" : 0,
 "Used" : 1,
 "XOffset" : "0",
 "YOffset" : "0",
 "idx" : "111"
 },
 {
 "AddjMulti" : 1.0,
 "AddjMulti2" : 1.0,
 "AddjValue" : 0.0,
 "AddjValue2" : 0.0,
 "BatteryLevel" : 100,
 "CustomImage" : 0,
 "Data" : "Normal",
 "Description" : "Chambre Toto",
 "Favorite" : 0,
 "HardwareID" : 11,
 "HardwareName" : "RFXTRX",
 "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
 "HardwareTypeVal" : 1,
 "HaveDimmer" : false,
 "HaveGroupCmd" : false,
 "HaveTimeout" : false,
 "ID" : "48DC18",
 "LastUpdate" : "2018-12-01 12:58:25",
 "MaxDimLevel" : 0,
 "Name" : "Capteur 5",
 "Notifications" : "false",
 "PlanID" : "0",
 "PlanIDs" : [ 0 ],
 "Protected" : true,
 "ShowNotifications" : true,
 "SignalLevel" : 6,
 "Status" : "Normal",
 "StrParam1" : "",
 "StrParam2" : "",
 "SubType" : "Meiantech/Atlantic/Aidebao",
 "SwitchType" : "Security",
 "SwitchTypeVal" : 0,
 "Timers" : "false",
 "Type" : "Security",
 "TypeImg" : "security",
 "Unit" : 0,
 "Used" : 1,
 "XOffset" : "0",
 "YOffset" : "0",
 "idx" : "112"
 },
 {
 "AddjMulti" : 1.0,
 "AddjMulti2" : 1.0,
 "AddjValue" : 0.0,
 "AddjValue2" : 0.0,
 "BatteryLevel" : 100,
 "CustomImage" : 0,
 "Data" : "Normal",
 "Description" : "Fentre salon coté nuit",
 "Favorite" : 0,
 "HardwareID" : 11,
 "HardwareName" : "RFXTRX",
 "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
 "HardwareTypeVal" : 1,
 "HaveDimmer" : false,
 "HaveGroupCmd" : false,
 "HaveTimeout" : false,
 "ID" : "48DCF2",
 "LastUpdate" : "2018-12-01 17:20:44",
 "MaxDimLevel" : 0,
 "Name" : "Capteur 6",
 "Notifications" : "false",
 "PlanID" : "0",
 "PlanIDs" : [ 0 ],
 "Protected" : true,
 "ShowNotifications" : true,
 "SignalLevel" : 7,
 "Status" : "Normal",
 "StrParam1" : "",
 "StrParam2" : "",
 "SubType" : "Meiantech/Atlantic/Aidebao",
 "SwitchType" : "Security",
 "SwitchTypeVal" : 0,
 "Timers" : "false",
 "Type" : "Security",
 "TypeImg" : "security",
 "Unit" : 0,
 "Used" : 1,
 "XOffset" : "0",
 "YOffset" : "0",
 "idx" : "113"
 },
 {
 "AddjMulti" : 1.0,
 "AddjMulti2" : 1.0,
 "AddjValue" : 0.0,
 "AddjValue2" : 0.0,
 "BatteryLevel" : 100,
 "CustomImage" : 0,
 "Data" : "Normal",
 "Description" : "Fenetre salon coté garage",
 "Favorite" : 0,
 "HardwareID" : 11,
 "HardwareName" : "RFXTRX",
 "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
 "HardwareTypeVal" : 1,
 "HaveDimmer" : false,
 "HaveGroupCmd" : false,
 "HaveTimeout" : false,
 "ID" : "481CE4",
 "LastUpdate" : "2018-12-02 12:23:19",
 "MaxDimLevel" : 0,
 "Name" : "Capteur 7",
 "Notifications" : "false",
 "PlanID" : "0",
 "PlanIDs" : [ 0 ],
 "Protected" : true,
 "ShowNotifications" : true,
 "SignalLevel" : 8,
 "Status" : "Normal",
 "StrParam1" : "",
 "StrParam2" : "",
 "SubType" : "Meiantech/Atlantic/Aidebao",
 "SwitchType" : "Security",
 "SwitchTypeVal" : 0,
 "Timers" : "false",
 "Type" : "Security",
 "TypeImg" : "security",
 "Unit" : 0,
 "Used" : 1,
 "XOffset" : "0",
 "YOffset" : "0",
 "idx" : "114"
 },
 {
 "AddjMulti" : 1.0,
 "AddjMulti2" : 1.0,
 "AddjValue" : 0.0,
 "AddjValue2" : 0.0,
 "BatteryLevel" : 100,
 "CustomImage" : 0,
 "Data" : "Motion",
 "Description" : "Volumétrique Hall nuit",
 "Favorite" : 0,
 "HardwareID" : 11,
 "HardwareName" : "RFXTRX",
 "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
 "HardwareTypeVal" : 1,
 "HaveDimmer" : false,
 "HaveGroupCmd" : false,
 "HaveTimeout" : false,
 "ID" : "800A92",
 "LastUpdate" : "2018-12-04 20:43:20",
 "MaxDimLevel" : 0,
 "Name" : "Capteur 8",
 "Notifications" : "false",
 "PlanID" : "0",
 "PlanIDs" : [ 0 ],
 "Protected" : true,
 "ShowNotifications" : true,
 "SignalLevel" : 8,
 "Status" : "Motion",
 "StrParam1" : "",
 "StrParam2" : "",
 "SubType" : "Meiantech/Atlantic/Aidebao",
 "SwitchType" : "Security",
 "SwitchTypeVal" : 0,
 "Timers" : "false",
 "Type" : "Security",
 "TypeImg" : "security",
 "Unit" : 0,
 "Used" : 1,
 "XOffset" : "0",
 "YOffset" : "0",
 "idx" : "104"
 },
 {
 "AddjMulti" : 1.0,
 "AddjMulti2" : 1.0,
 "AddjValue" : 0.0,
 "AddjValue2" : 0.0,
 "BatteryLevel" : 100,
 "CustomImage" : 0,
 "Data" : "Motion",
 "Description" : "Volumétrique Hall entrée",
 "Favorite" : 0,
 "HardwareID" : 11,
 "HardwareName" : "RFXTRX",
 "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
 "HardwareTypeVal" : 1,
 "HaveDimmer" : false,
 "HaveGroupCmd" : false,
 "HaveTimeout" : false,
 "ID" : "80CA09",
 "LastUpdate" : "2018-12-04 20:43:17",
 "MaxDimLevel" : 0,
 "Name" : "Capteur 9",
 "Notifications" : "false",
 "PlanID" : "0",
 "PlanIDs" : [ 0 ],
 "Protected" : true,
 "ShowNotifications" : true,
 "SignalLevel" : 8,
 "Status" : "Motion",
 "StrParam1" : "",
 "StrParam2" : "",
 "SubType" : "Meiantech/Atlantic/Aidebao",
 "SwitchType" : "Security",
 "SwitchTypeVal" : 0,
 "Timers" : "false",
 "Type" : "Security",
 "TypeImg" : "security",
 "Unit" : 0,
 "Used" : 1,
 "XOffset" : "0",
 "YOffset" : "0",
 "idx" : "105"
 },
 {
 "AddjMulti" : 1.0,
 "AddjMulti2" : 1.0,
 "AddjValue" : 0.0,
 "AddjValue2" : 0.0,
 "BatteryLevel" : 100,
 "CustomImage" : 0,
 "Data" : "Motion",
 "Description" : "Volumétrique Salon",
 "Favorite" : 0,
 "HardwareID" : 11,
 "HardwareName" : "RFXTRX",
 "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
 "HardwareTypeVal" : 1,
 "HaveDimmer" : false,
 "HaveGroupCmd" : false,
 "HaveTimeout" : false,
 "ID" : "807252",
 "LastUpdate" : "2018-12-04 21:09:21",
 "MaxDimLevel" : 0,
 "Name" : "Capteur 10",
 "Notifications" : "false",
 "PlanID" : "0",
 "PlanIDs" : [ 0 ],
 "Protected" : true,
 "ShowNotifications" : true,
 "SignalLevel" : 8,
 "Status" : "Motion",
 "StrParam1" : "",
 "StrParam2" : "",
 "SubType" : "Meiantech/Atlantic/Aidebao",
 "SwitchType" : "Security",
 "SwitchTypeVal" : 0,
 "Timers" : "false",
 "Type" : "Security",
 "TypeImg" : "security",
 "Unit" : 0,
 "Used" : 1,
 "XOffset" : "0",
 "YOffset" : "0",
 "idx" : "106"
 },
 {
 "AddjMulti" : 1.0,
 "AddjMulti2" : 1.0,
 "AddjValue" : 0.0,
 "AddjValue2" : 0.0,
 "BatteryLevel" : 100,
 "CustomImage" : 0,
 "Data" : "Motion",
 "Description" : "Volumétrique cuisine",
 "Favorite" : 0,
 "HardwareID" : 11,
 "HardwareName" : "RFXTRX",
 "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
 "HardwareTypeVal" : 1,
 "HaveDimmer" : false,
 "HaveGroupCmd" : false,
 "HaveTimeout" : false,
 "ID" : "8072AA",
 "LastUpdate" : "2018-12-04 21:04:47",
 "MaxDimLevel" : 0,
 "Name" : "Capteur 11",
 "Notifications" : "false",
 "PlanID" : "0",
 "PlanIDs" : [ 0 ],
 "Protected" : true,
 "ShowNotifications" : true,
 "SignalLevel" : 8,
 "Status" : "Motion",
 "StrParam1" : "",
 "StrParam2" : "",
 "SubType" : "Meiantech/Atlantic/Aidebao",
 "SwitchType" : "Security",
 "SwitchTypeVal" : 0,
 "Timers" : "false",
 "Type" : "Security",
 "TypeImg" : "security",
 "Unit" : 0,
 "Used" : 1,
 "XOffset" : "0",
 "YOffset" : "0",
 "idx" : "107"
 },
 {
 "AddjMulti" : 1.0,
 "AddjMulti2" : 1.0,
 "AddjValue" : 0.0,
 "AddjValue2" : 0.0,
 "BatteryLevel" : 100,
 "CustomImage" : 0,
 "Data" : "Normal",
 "Description" : "Fenetre garage",
 "Favorite" : 0,
 "HardwareID" : 11,
 "HardwareName" : "RFXTRX",
 "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
 "HardwareTypeVal" : 1,
 "HaveDimmer" : false,
 "HaveGroupCmd" : false,
 "HaveTimeout" : false,
 "ID" : "6EA615",
 "LastUpdate" : "2018-10-07 18:42:08",
 "MaxDimLevel" : 0,
 "Name" : "Capteur 12",
 "Notifications" : "false",
 "PlanID" : "0",
 "PlanIDs" : [ 0 ],
 "Protected" : true,
 "ShowNotifications" : true,
 "SignalLevel" : 6,
 "Status" : "Normal",
 "StrParam1" : "",
 "StrParam2" : "",
 "SubType" : "Meiantech/Atlantic/Aidebao",
 "SwitchType" : "Security",
 "SwitchTypeVal" : 0,
 "Timers" : "false",
 "Type" : "Security",
 "TypeImg" : "security",
 "Unit" : 0,
 "Used" : 1,
 "XOffset" : "0",
 "YOffset" : "0",
 "idx" : "115"
 },
 {
 "AddjMulti" : 1.0,
 "AddjMulti2" : 1.0,
 "AddjValue" : 0.0,
 "AddjValue2" : 0.0,
 "BatteryLevel" : 100,
 "CustomImage" : 0,
 "Data" : "Alarm",
 "Description" : "Porte garage",
 "Favorite" : 0,
 "HardwareID" : 11,
 "HardwareName" : "RFXTRX",
 "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
 "HardwareTypeVal" : 1,
 "HaveDimmer" : false,
 "HaveGroupCmd" : false,
 "HaveTimeout" : false,
 "ID" : "6E66FE",
 "LastUpdate" : "2018-12-04 20:35:47",
 "MaxDimLevel" : 0,
 "Name" : "Capteur 13",
 "Notifications" : "false",
 "PlanID" : "0",
 "PlanIDs" : [ 0 ],
 "Protected" : true,
 "ShowNotifications" : true,
 "SignalLevel" : 7,
 "Status" : "Alarm",
 "StrParam1" : "",
 "StrParam2" : "",
 "SubType" : "Meiantech/Atlantic/Aidebao",
 "SwitchType" : "Security",
 "SwitchTypeVal" : 0,
 "Timers" : "false",
 "Type" : "Security",
 "TypeImg" : "security",
 "Unit" : 0,
 "Used" : 1,
 "XOffset" : "0",
 "YOffset" : "0",
 "idx" : "116"
 },
 {
 "AddjMulti" : 1.0,
 "AddjMulti2" : 1.0,
 "AddjValue" : 0.0,
 "AddjValue2" : 0.0,
 "BatteryLevel" : 255,
 "CustomImage" : 0,
 "Data" : "3.48%",
 "Description" : "",
 "Favorite" : 0,
 "HardwareID" : 20,
 "HardwareName" : "Raspberry",
 "HardwareType" : "Motherboard sensors",
 "HardwareTypeVal" : 23,
 "HaveTimeout" : false,
 "ID" : "0000044D",
 "Image" : "Computer",
 "LastUpdate" : "2018-12-04 21:17:39",
 "Name" : "CPU_Usage",
 "Notifications" : "false",
 "PlanID" : "0",
 "PlanIDs" : [ 0 ],
 "Protected" : false,
 "ShowNotifications" : true,
 "SignalLevel" : "-",
 "SubType" : "Percentage",
 "Timers" : "false",
 "Type" : "General",
 "TypeImg" : "hardware",
 "Unit" : 1,
 "Used" : 1,
 "XOffset" : "0",
 "YOffset" : "0",
 "idx" : "152"
 },
 {
 "AddjMulti" : 1.0,
 "AddjMulti2" : 1.0,
 "AddjValue" : 0.0,
 "AddjValue2" : 0.0,
 "BatteryLevel" : 255,
 "CustomImage" : 0,
 "Data" : "17.87%",
 "Description" : "",
 "Favorite" : 0,
 "HardwareID" : 20,
 "HardwareName" : "Raspberry",
 "HardwareType" : "Motherboard sensors",
 "HardwareTypeVal" : 23,
 "HaveTimeout" : false,
 "ID" : "0000044C",
 "Image" : "Computer",
 "LastUpdate" : "2018-12-04 21:16:29",
 "Name" : "Memory Usage",
 "Notifications" : "true",
 "PlanID" : "0",
 "PlanIDs" : [ 0 ],
 "Protected" : false,
 "ShowNotifications" : true,
 "SignalLevel" : "-",
 "SubType" : "Percentage",
 "Timers" : "false",
 "Type" : "General",
 "TypeImg" : "hardware",
 "Unit" : 1,
 "Used" : 1,
 "XOffset" : "0",
 "YOffset" : "0",
 "idx" : "146"
 },
 {
 "AddjMulti" : 1.0,
 "AddjMulti2" : 1.0,
 "AddjValue" : 0.0,
 "AddjValue2" : 0.0,
 "BatteryLevel" : 255,
 "CustomImage" : 0,
 "Data" : "65.81%",
 "Description" : "",
 "Favorite" : 0,
 "HardwareID" : 20,
 "HardwareName" : "Raspberry",
 "HardwareType" : "Motherboard sensors",
 "HardwareTypeVal" : 23,
 "HaveTimeout" : false,
 "ID" : "00000451",
 "Image" : "Computer",
 "LastUpdate" : "2018-12-04 21:17:19",
 "Name" : "HDD /",
 "Notifications" : "false",
 "PlanID" : "0",
 "PlanIDs" : [ 0 ],
 "Protected" : false,
 "ShowNotifications" : true,
 "SignalLevel" : "-",
 "SubType" : "Percentage",
 "Timers" : "false",
 "Type" : "General",
 "TypeImg" : "hardware",
 "Unit" : 1,
 "Used" : 1,
 "XOffset" : "0",
 "YOffset" : "0",
 "idx" : "150"
 },
 {
 "AddjMulti" : 1.0,
 "AddjMulti2" : 1.0,
 "AddjValue" : 0.0,
 "AddjValue2" : 0.0,
 "BatteryLevel" : 255,
 "CustomImage" : 0,
 "Data" : "41.2 C",
 "Description" : "",
 "Favorite" : 0,
 "HardwareID" : 20,
 "HardwareName" : "Raspberry",
 "HardwareType" : "Motherboard sensors",
 "HardwareTypeVal" : 23,
 "HaveTimeout" : false,
 "ID" : "0001",
 "LastUpdate" : "2018-12-04 21:17:19",
 "Name" : "Internal Temperature",
 "Notifications" : "false",
 "PlanID" : "0",
 "PlanIDs" : [ 0 ],
 "Protected" : false,
 "ShowNotifications" : true,
 "SignalLevel" : "-",
 "SubType" : "LaCrosse TX3",
 "Temp" : 41.200000000000003,
 "Timers" : "false",
 "Type" : "Temp",
 "TypeImg" : "temperature",
 "Unit" : 1,
 "Used" : 1,
 "XOffset" : "0",
 "YOffset" : "0",
 "idx" : "151"
 },
 {
 "AddjMulti" : 1.0,
 "AddjMulti2" : 1.0,
 "AddjValue" : 0.0,
 "AddjValue2" : 0.0,
 "BatteryLevel" : 255,
 "CustomImage" : 105,
 "Data" : "0 Mbps",
 "Description" : "",
 "Favorite" : 0,
 "HardwareID" : 21,
 "HardwareName" : "Virtual",
 "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
 "HardwareTypeVal" : 15,
 "HaveTimeout" : true,
 "ID" : "00082568",
 "Image" : "RaspberryPi2",
 "LastUpdate" : "2018-11-13 15:55:03",
 "Name" : "DOWNLOAD",
 "Notifications" : "false",
 "PlanID" : "0",
 "PlanIDs" : [ 0 ],
 "Protected" : false,
 "SensorType" : 1,
 "SensorUnit" : "Mbps",
 "ShowNotifications" : true,
 "SignalLevel" : "-",
 "SubType" : "Custom Sensor",
 "Timers" : "false",
 "Type" : "General",
 "TypeImg" : "RaspberryPi2",
 "Unit" : 1,
 "Used" : 1,
 "XOffset" : "0",
 "YOffset" : "0",
 "idx" : "568"
 },
 {
 "AddjMulti" : 1.0,
 "AddjMulti2" : 1.0,
 "AddjValue" : 0.0,
 "AddjValue2" : 0.0,
 "BatteryLevel" : 255,
 "CustomImage" : 105,
 "Data" : "0 Mbps",
 "Description" : "",
 "Favorite" : 0,
 "HardwareID" : 21,
 "HardwareName" : "Virtual",
 "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
 "HardwareTypeVal" : 15,
 "HaveTimeout" : true,
 "ID" : "00082569",
 "Image" : "RaspberryPi2",
 "LastUpdate" : "2018-11-13 15:55:03",
 "Name" : "UPLOAD",
 "Notifications" : "false",
 "PlanID" : "0",
 "PlanIDs" : [ 0 ],
 "Protected" : false,
 "SensorType" : 1,
 "SensorUnit" : "Mbps",
 "ShowNotifications" : true,
 "SignalLevel" : "-",
 "SubType" : "Custom Sensor",
 "Timers" : "false",
 "Type" : "General",
 "TypeImg" : "RaspberryPi2",
 "Unit" : 1,
 "Used" : 1,
 "XOffset" : "0",
 "YOffset" : "0",
 "idx" : "569"
 },
 {
 "AddjMulti" : 1.0,
 "AddjMulti2" : 1.0,
 "AddjValue" : 0.0,
 "AddjValue2" : 0.0,
 "BatteryLevel" : 255,
 "Counter" : "82343.487",
 "CounterDeliv" : "0.000",
 "CounterDelivToday" : "0 kWh",
 "CounterToday" : "14.852 kWh",
 "CustomImage" : 0,
 "Data" : "32845589;49497898;0;0;900;0",
 "Description" : "",
 "Favorite" : 1,
 "HardwareID" : 26,
 "HardwareName" : "Teleinfo EDF",
 "HardwareType" : "Teleinfo EDF",
 "HardwareTypeVal" : 19,
 "HaveTimeout" : false,
 "ID" : "0001",
 "LastUpdate" : "2018-12-04 21:16:50",
 "Name" : "Teleinfo EDF",
 "Notifications" : "false",
 "PlanID" : "0",
 "PlanIDs" : [ 0 ],
 "Protected" : false,
 "ShowNotifications" : true,
 "SignalLevel" : "-",
 "SubType" : "Energy",
 "SwitchTypeVal" : 0,
 "Timers" : "false",
 "Type" : "P1 Smart Meter",
 "TypeImg" : "counter",
 "Unit" : 1,
 "Usage" : "900 Watt",
 "UsageDeliv" : "0 Watt",
 "Used" : 1,
 "XOffset" : "0",
 "YOffset" : "0",
 "idx" : "329"
 },
 {
 "AddjMulti" : 1.0,
 "AddjMulti2" : 1.0,
 "AddjValue" : 0.0,
 "AddjValue2" : 0.0,
 "BatteryLevel" : 100,
 "CustomImage" : 0,
 "Data" : "Normal",
 "Description" : "Fenetre salle a manger",
 "Favorite" : 0,
 "HardwareID" : 11,
 "HardwareName" : "RFXTRX",
 "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
 "HardwareTypeVal" : 1,
 "HaveDimmer" : false,
 "HaveGroupCmd" : false,
 "HaveTimeout" : false,
 "ID" : "DE7460",
 "LastUpdate" : "2018-11-23 18:23:29",
 "MaxDimLevel" : 0,
 "Name" : "Capteur 14",
 "Notifications" : "false",
 "PlanID" : "0",
 "PlanIDs" : [ 0 ],
 "Protected" : true,
 "ShowNotifications" : true,
 "SignalLevel" : 7,
 "Status" : "Normal",
 "StrParam1" : "",
 "StrParam2" : "",
 "SubType" : "Meiantech/Atlantic/Aidebao",
 "SwitchType" : "Security",
 "SwitchTypeVal" : 0,
 "Timers" : "false",
 "Type" : "Security",
 "TypeImg" : "security",
 "Unit" : 0,
 "Used" : 1,
 "XOffset" : "0",
 "YOffset" : "0",
 "idx" : "471"
 },
 {
 "AddjMulti" : 1.0,
 "AddjMulti2" : 1.0,
 "AddjValue" : 0.0,
 "AddjValue2" : 0.0,
 "BatteryLevel" : 100,
 "CustomImage" : 0,
 "Data" : "Normal",
 "Description" : "Fenetre Chambre parents",
 "Favorite" : 0,
 "HardwareID" : 11,
 "HardwareName" : "RFXTRX",
 "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
 "HardwareTypeVal" : 1,
 "HaveDimmer" : false,
 "HaveGroupCmd" : false,
 "HaveTimeout" : false,
 "ID" : "DE34D2",
 "LastUpdate" : "2018-11-28 17:05:05",
 "MaxDimLevel" : 0,
 "Name" : "Capteur 15",
 "Notifications" : "false",
 "PlanID" : "0",
 "PlanIDs" : [ 0 ],
 "Protected" : true,
 "ShowNotifications" : true,
 "SignalLevel" : 6,
 "Status" : "Normal",
 "StrParam1" : "",
 "StrParam2" : "",
 "SubType" : "Meiantech/Atlantic/Aidebao",
 "SwitchType" : "Security",
 "SwitchTypeVal" : 0,
 "Timers" : "false",
 "Type" : "Security",
 "TypeImg" : "security",
 "Unit" : 0,
 "Used" : 1,
 "XOffset" : "0",
 "YOffset" : "0",
 "idx" : "472"
 },
 {
 "AddjMulti" : 1.0,
 "AddjMulti2" : 1.0,
 "AddjValue" : 0.0,
 "AddjValue2" : 0.0,
 "BatteryLevel" : 100,
 "CustomImage" : 0,
 "Data" : "Motion",
 "Description" : "Bris de vitre fenêtre Cuisine 1/2",
 "Favorite" : 0,
 "HardwareID" : 11,
 "HardwareName" : "RFXTRX",
 "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
 "HardwareTypeVal" : 1,
 "HaveDimmer" : false,
 "HaveGroupCmd" : false,
 "HaveTimeout" : false,
 "ID" : "2281AA",
 "LastUpdate" : "2017-08-27 14:48:17",
 "MaxDimLevel" : 0,
 "Name" : "Capteur 20",
 "Notifications" : "false",
 "PlanID" : "0",
 "PlanIDs" : [ 0 ],
 "Protected" : true,
 "ShowNotifications" : true,
 "SignalLevel" : 5,
 "Status" : "Motion",
 "StrParam1" : "",
 "StrParam2" : "",
 "SubType" : "Meiantech/Atlantic/Aidebao",
 "SwitchType" : "Security",
 "SwitchTypeVal" : 0,
 "Timers" : "false",
 "Type" : "Security",
 "TypeImg" : "security",
 "Unit" : 0,
 "Used" : 1,
 "XOffset" : "0",
 "YOffset" : "0",
 "idx" : "473"
 },
 {
 "AddjMulti" : 1.0,
 "AddjMulti2" : 1.0,
 "AddjValue" : 0.0,
 "AddjValue2" : 0.0,
 "BatteryLevel" : 100,
 "CustomImage" : 0,
 "Data" : "Motion",
 "Description" : "Bris de vitre fenêtre Cuisine 2/2",
 "Favorite" : 0,
 "HardwareID" : 11,
 "HardwareName" : "RFXTRX",
 "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
 "HardwareTypeVal" : 1,
 "HaveDimmer" : false,
 "HaveGroupCmd" : false,
 "HaveTimeout" : false,
 "ID" : "1C81AA",
 "LastUpdate" : "2018-12-02 20:55:37",
 "MaxDimLevel" : 0,
 "Name" : "Capteur 21",
 "Notifications" : "false",
 "PlanID" : "0",
 "PlanIDs" : [ 0 ],
 "Protected" : true,
 "ShowNotifications" : true,
 "SignalLevel" : 6,
 "Status" : "Motion",
 "StrParam1" : "",
 "StrParam2" : "",
 "SubType" : "Meiantech/Atlantic/Aidebao",
 "SwitchType" : "Security",
 "SwitchTypeVal" : 0,
 "Timers" : "false",
 "Type" : "Security",
 "TypeImg" : "security",
 "Unit" : 0,
 "Used" : 1,
 "XOffset" : "0",
 "YOffset" : "0",
 "idx" : "474"
 },
 {
 "AddjMulti" : 1.0,
 "AddjMulti2" : 1.0,
 "AddjValue" : 0.0,
 "AddjValue2" : 0.0,
 "BatteryLevel" : 255,
 "CustomImage" : 0,
 "Data" : "Off",
 "Description" : "Donc un chmod +x mon_script.py résout le problème\nRegarder dans /opt",
 "DimmerType" : "none",
 "Favorite" : 0,
 "HardwareID" : 21,
 "HardwareName" : "Virtual",
 "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
 "HardwareTypeVal" : 15,
 "HaveDimmer" : true,
 "HaveGroupCmd" : true,
 "HaveTimeout" : false,
 "ID" : "00014230",
 "Image" : "Light",
 "IsSubDevice" : false,
 "LastUpdate" : "2017-01-16 20:31:15",
 "Level" : 0,
 "LevelInt" : 0,
 "MaxDimLevel" : 100,
 "Name" : "Police LED",
 "Notifications" : "false",
 "PlanID" : "0",
 "PlanIDs" : [ 0 ],
 "Protected" : true,
 "ShowNotifications" : true,
 "SignalLevel" : "-",
 "Status" : "Off",
 "StrParam1" : "c2NyaXB0Oi8vL2hvbWUvcGkvbGltaXRsZXNzbGVkLnB5",
 "StrParam2" : "",
 "SubType" : "Switch",
 "SwitchType" : "On/Off",
 "SwitchTypeVal" : 0,
 "Timers" : "false",
 "Type" : "Light/Switch",
 "TypeImg" : "lightbulb",
 "Unit" : 1,
 "Used" : 1,
 "UsedByCamera" : false,
 "XOffset" : "0",
 "YOffset" : "0",
 "idx" : "480"
 },
 {
 "AddjMulti" : 1.0,
 "AddjMulti2" : 1.0,
 "AddjValue" : 30.0,
 "AddjValue2" : 0.0,
 "BatteryLevel" : 255,
 "CustomImage" : 105,
 "Data" : "Off",
 "Description" : "",
 "DimmerType" : "none",
 "Favorite" : 0,
 "HardwareID" : 21,
 "HardwareName" : "Virtual",
 "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
 "HardwareTypeVal" : 15,
 "HaveDimmer" : true,
 "HaveGroupCmd" : true,
 "HaveTimeout" : false,
 "ID" : "0001428A",
 "Image" : "RaspberryPi2",
 "IsSubDevice" : false,
 "LastUpdate" : "2018-11-13 15:55:31",
 "Level" : 0,
 "LevelInt" : 0,
 "MaxDimLevel" : 100,
 "Name" : "Test Debit",
 "Notifications" : "false",
 "PlanID" : "0",
 "PlanIDs" : [ 0 ],
 "Protected" : true,
 "ShowNotifications" : true,
 "SignalLevel" : "-",
 "Status" : "Off",
 "StrParam1" : "c2NyaXB0Oi8vL2hvbWUvcGkvc3BlZWR0ZXN0LnNo",
 "StrParam2" : "",
 "SubType" : "Switch",
 "SwitchType" : "On/Off",
 "SwitchTypeVal" : 0,
 "Timers" : "false",
 "Type" : "Light/Switch",
 "TypeImg" : "lightbulb",
 "Unit" : 1,
 "Used" : 1,
 "UsedByCamera" : false,
 "XOffset" : "0",
 "YOffset" : "0",
 "idx" : "570"
 },
 {
 "AddjMulti" : 1.0,
 "AddjMulti2" : 1.0,
 "AddjValue" : 2.0,
 "AddjValue2" : 0.0,
 "BatteryLevel" : 255,
 "CustomImage" : 103,
 "Data" : "Off",
 "Description" : "Pour lancer un Backup complet sur le NAS",
 "DimmerType" : "none",
 "Favorite" : 0,
 "HardwareID" : 21,
 "HardwareName" : "Virtual",
 "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
 "HardwareTypeVal" : 15,
 "HaveDimmer" : true,
 "HaveGroupCmd" : true,
 "HaveTimeout" : false,
 "ID" : "000141A5",
 "Image" : "NAS_Synology",
 "IsSubDevice" : false,
 "LastUpdate" : "2018-12-03 05:40:39",
 "Level" : 0,
 "LevelInt" : 0,
 "MaxDimLevel" : 100,
 "Name" : "Backup Domoticz sur le NAS",
 "Notifications" : "false",
 "PlanID" : "0",
 "PlanIDs" : [ 0 ],
 "Protected" : true,
 "ShowNotifications" : true,
 "SignalLevel" : "-",
 "Status" : "Off",
 "StrParam1" : "c2NyaXB0Oi8vL2hvbWUvcGkvYmFja3VwX2ltYWdlLnNo",
 "StrParam2" : "",
 "SubType" : "Switch",
 "SwitchType" : "On/Off",
 "SwitchTypeVal" : 0,
 "Timers" : "true",
 "Type" : "Light/Switch",
 "TypeImg" : "lightbulb",
 "Unit" : 1,
 "Used" : 1,
 "UsedByCamera" : false,
 "XOffset" : "0",
 "YOffset" : "0",
 "idx" : "341"
 },
 {
 "AddjMulti" : 1.0,
 "AddjMulti2" : 1.0,
 "AddjValue" : 1.0,
 "AddjValue2" : 0.0,
 "BatteryLevel" : 255,
 "CustomImage" : 0,
 "Data" : "On",
 "Description" : "",
 "DimmerType" : "none",
 "Favorite" : 0,
 "HardwareID" : 21,
 "HardwareName" : "Virtual",
 "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
 "HardwareTypeVal" : 15,
 "HaveDimmer" : true,
 "HaveGroupCmd" : true,
 "HaveTimeout" : false,
 "ID" : "000142CF",
 "Image" : "Light",
 "InternalState" : "On",
 "IsSubDevice" : false,
 "LastUpdate" : "2018-11-29 17:29:10",
 "Level" : 0,
 "LevelInt" : 0,
 "MaxDimLevel" : 100,
 "Name" : "Reboot Pi",
 "Notifications" : "false",
 "PlanID" : "0",
 "PlanIDs" : [ 0 ],
 "Protected" : true,
 "ShowNotifications" : true,
 "SignalLevel" : "-",
 "Status" : "",
 "StrParam1" :
"aHR0cDovLzE5Mi4xNjguMS4yMDA6ODg4OC9qc29uLmh0bT90eXBlPWNvbW1hbmQmcGFyYW09c3lzdGVtX3JlYm9vdA==",
 "StrParam2" : "",
 "SubType" : "Switch",
 "SwitchType" : "Push On Button",
 "SwitchTypeVal" : 9,
 "Timers" : "false",
 "Type" : "Light/Switch",
 "TypeImg" : "push",
 "Unit" : 1,
 "Used" : 1,
 "UsedByCamera" : false,
 "XOffset" : "0",
 "YOffset" : "0",
 "idx" : "639"
 },
 {
 "AddjMulti" : 1.0,
 "AddjMulti2" : 1.0,
 "AddjValue" : 0.0,
 "AddjValue2" : 0.0,
 "BatteryLevel" : 255,
 "CounterToday" : "7.904 kWh",
 "CustomImage" : 0,
 "Data" : "49497.9 kWh",
 "Description" : "",
 "Favorite" : 0,
 "HardwareID" : 26,
 "HardwareName" : "Teleinfo EDF",
 "HardwareType" : "Teleinfo EDF",
 "HardwareTypeVal" : 19,
 "HaveTimeout" : false,
 "ID" : "00001A03",
 "LastUpdate" : "2018-12-04 21:16:50",
 "Name" : "Teleinfo HC",
 "Notifications" : "false",
 "Options" : "0",
 "PlanID" : "0",
 "PlanIDs" : [ 0 ],
 "Protected" : false,
 "ShowNotifications" : true,
 "SignalLevel" : "-",
 "SubType" : "kWh",
 "SwitchTypeVal" : 0,
 "Timers" : "false",
 "Type" : "General",
 "TypeImg" : "current",
 "Unit" : 1,
 "Usage" : "0 Watt",
 "Used" : 1,
 "XOffset" : "0",
 "YOffset" : "0",
 "idx" : "683"
 },
 {
 "AddjMulti" : 1.0,
 "AddjMulti2" : 1.0,
 "AddjValue" : 0.0,
 "AddjValue2" : 0.0,
 "BatteryLevel" : 255,
 "CounterToday" : "6.944 kWh",
 "CustomImage" : 0,
 "Data" : "32845.6 kWh",
 "Description" : "",
 "Favorite" : 0,
 "HardwareID" : 26,
 "HardwareName" : "Teleinfo EDF",
 "HardwareType" : "Teleinfo EDF",
 "HardwareTypeVal" : 19,
 "HaveTimeout" : false,
 "ID" : "00001A04",
 "LastUpdate" : "2018-12-04 21:16:50",
 "Name" : "Teleinfo HP",
 "Notifications" : "false",
 "Options" : "",
 "PlanID" : "0",
 "PlanIDs" : [ 0 ],
 "Protected" : false,
 "ShowNotifications" : true,
 "SignalLevel" : "-",
 "SubType" : "kWh",
 "SwitchTypeVal" : 0,
 "Timers" : "false",
 "Type" : "General",
 "TypeImg" : "current",
 "Unit" : 1,
 "Usage" : "900 Watt",
 "Used" : 1,
 "XOffset" : "0",
 "YOffset" : "0",
 "idx" : "684"
 },
 {
 "AddjMulti" : 1.0,
 "AddjMulti2" : 1.0,
 "AddjValue" : 0.0,
 "AddjValue2" : 0.0,
 "BatteryLevel" : 255,
 "CustomImage" : 0,
 "Data" : "(2) Heures Pleines",
 "Description" : "",
 "Favorite" : 0,
 "HardwareID" : 26,
 "HardwareName" : "Teleinfo EDF",
 "HardwareType" : "Teleinfo EDF",
 "HardwareTypeVal" : 19,
 "HaveTimeout" : false,
 "ID" : "1",
 "LastUpdate" : "2018-12-04 17:39:26",
 "Level" : 2,
 "Name" : "Teleinfo Tarif en cours",
 "Notifications" : "false",
 "PlanID" : "0",
 "PlanIDs" : [ 0 ],
 "Protected" : false,
 "ShowNotifications" : true,
 "SignalLevel" : "-",
 "SubType" : "Alert",
 "Timers" : "false",
 "Type" : "General",
 "TypeImg" : "Alert",
 "Unit" : 1,
 "Used" : 1,
 "XOffset" : "0",
 "YOffset" : "0",
 "idx" : "687"
 },
 {
 "AddjMulti" : 1.0,
 "AddjMulti2" : 1.0,
 "AddjValue" : 0.0,
 "AddjValue2" : 0.0,
 "BatteryLevel" : 92,
 "CustomImage" : 0,
 "Data" : "Off",
 "Description" : "",
 "DimmerType" : "none",
 "Favorite" : 0,
 "HardwareID" : 23,
 "HardwareName" : "Z-Stick Gen5",
 "HardwareType" : "OpenZWave USB",
 "HardwareTypeVal" : 21,
 "HaveDimmer" : true,
 "HaveGroupCmd" : true,
 "HaveTimeout" : false,
 "ID" : "00004900",
 "Image" : "Light",
 "IsSubDevice" : false,
 "LastUpdate" : "2018-12-04 21:05:39",
 "Level" : 0,
 "LevelInt" : 0,
 "MaxDimLevel" : 100,
 "Name" : "Motion FGMS001",
 "Notifications" : "false",
 "PlanID" : "0",
 "PlanIDs" : [ 0 ],
 "Protected" : false,
 "ShowNotifications" : true,
 "SignalLevel" : "-",
 "Status" : "Off",
 "StrParam1" : "",
 "StrParam2" : "",
 "SubType" : "Switch",
 "SwitchType" : "Motion Sensor",
 "SwitchTypeVal" : 8,
 "Timers" : "false",
 "Type" : "Light/Switch",
 "TypeImg" : "motion",
 "Unit" : 1,
 "Used" : 1,
 "UsedByCamera" : false,
 "XOffset" : "0",
 "YOffset" : "0",
 "idx" : "694"
 },
 {
 "AddjMulti" : 1.0,
 "AddjMulti2" : 1.0,
 "AddjValue" : 0.0,
 "AddjValue2" : 0.0,
 "BatteryLevel" : 92,
 "CustomImage" : 0,
 "Data" : "Closed",
 "Description" : "",
 "DimmerType" : "none",
 "Favorite" : 0,
 "HardwareID" : 23,
 "HardwareName" : "Z-Stick Gen5",
 "HardwareType" : "OpenZWave USB",
 "HardwareTypeVal" : 21,
 "HaveDimmer" : true,
 "HaveGroupCmd" : true,
 "HaveTimeout" : false,
 "ID" : "00004928",
 "Image" : "Light",
 "IsSubDevice" : false,
 "LastUpdate" : "2018-12-04 20:12:58",
 "Level" : 0,
 "LevelInt" : 0,
 "MaxDimLevel" : 100,
 "Name" : "Choc FGMS001",
 "Notifications" : "false",
 "PlanID" : "0",
 "PlanIDs" : [ 0 ],
 "Protected" : false,
 "ShowNotifications" : true,
 "SignalLevel" : "-",
 "Status" : "Closed",
 "StrParam1" : "",
 "StrParam2" : "",
 "SubType" : "Switch",
 "SwitchType" : "Contact",
 "SwitchTypeVal" : 2,
 "Timers" : "false",
 "Type" : "Light/Switch",
 "TypeImg" : "contact",
 "Unit" : 1,
 "Used" : 1,
 "UsedByCamera" : false,
 "XOffset" : "0",
 "YOffset" : "0",
 "idx" : "695"
 },
 {
 "AddjMulti" : 1.0,
 "AddjMulti2" : 1.0,
 "AddjValue" : 0.0,
 "AddjValue2" : 0.0,
 "BatteryLevel" : 255,
 "CustomImage" : 9,
 "Data" : "Off",
 "Description" : "",
 "DimmerType" : "none",
 "Favorite" : 0,
 "HardwareID" : 21,
 "HardwareName" : "Virtual",
 "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
 "HardwareTypeVal" : 15,
 "HaveDimmer" : true,
 "HaveGroupCmd" : true,
 "HaveTimeout" : false,
 "ID" : "000142B8",
 "Image" : "Generic",
 "IsSubDevice" : false,
 "LastUpdate" : "2017-11-12 21:20:21",
 "Level" : 0,
 "LevelInt" : 0,
 "MaxDimLevel" : 100,
 "Name" : "Inter_Beacon_Blanc",
 "Notifications" : "false",
 "PlanID" : "0",
 "PlanIDs" : [ 0 ],
 "Protected" : false,
 "ShowNotifications" : true,
 "SignalLevel" : "-",
 "Status" : "Off",
 "StrParam1" : "",
 "StrParam2" : "",
 "SubType" : "Switch",
 "SwitchType" : "On/Off",
 "SwitchTypeVal" : 0,
 "Timers" : "false",
 "Type" : "Light/Switch",
 "TypeImg" : "lightbulb",
 "Unit" : 1,
 "Used" : 1,
 "UsedByCamera" : false,
 "XOffset" : "0",
 "YOffset" : "0",
 "idx" : "616"
 },
 {
 "AddjMulti" : 1.0,
 "AddjMulti2" : 1.0,
 "AddjValue" : 0.0,
 "AddjValue2" : 0.0,
 "BatteryLevel" : 255,
 "CustomImage" : 9,
 "Data" : "Off",
 "Description" : "",
 "DimmerType" : "none",
 "Favorite" : 0,
 "HardwareID" : 21,
 "HardwareName" : "Virtual",
 "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
 "HardwareTypeVal" : 15,
 "HaveDimmer" : true,
 "HaveGroupCmd" : true,
 "HaveTimeout" : false,
 "ID" : "000142B7",
 "Image" : "Generic",
 "IsSubDevice" : false,
 "LastUpdate" : "2017-09-06 14:04:05",
 "Level" : 0,
 "LevelInt" : 0,
 "MaxDimLevel" : 100,
 "Name" : "Inter_Beacon_Noir",
 "Notifications" : "false",
 "PlanID" : "0",
 "PlanIDs" : [ 0 ],
 "Protected" : false,
 "ShowNotifications" : true,
 "SignalLevel" : "-",
 "Status" : "Off",
 "StrParam1" : "",
 "StrParam2" : "",
 "SubType" : "Switch",
 "SwitchType" : "On/Off",
 "SwitchTypeVal" : 0,
 "Timers" : "false",
 "Type" : "Light/Switch",
 "TypeImg" : "lightbulb",
 "Unit" : 1,
 "Used" : 1,
 "UsedByCamera" : false,
 "XOffset" : "0",
 "YOffset" : "0",
 "idx" : "615"
 },
 {
 "AddjMulti" : 1.0,
 "AddjMulti2" : 1.0,
 "AddjValue" : 0.0,
 "AddjValue2" : 0.0,
 "BatteryLevel" : 92,
 "CustomImage" : 0,
 "Data" : "5 Lux",
 "Description" : "",
 "Favorite" : 0,
 "HardwareID" : 23,
 "HardwareName" : "Z-Stick Gen5",
 "HardwareType" : "OpenZWave USB",
 "HardwareTypeVal" : 21,
 "HaveTimeout" : false,
 "ID" : "0004903",
 "LastUpdate" : "2018-12-04 21:08:49",
 "Name" : "Lux FGMS001",
 "Notifications" : "false",
 "PlanID" : "0",
 "PlanIDs" : [ 0 ],
 "Protected" : false,
 "ShowNotifications" : true,
 "SignalLevel" : "-",
 "SubType" : "Lux",
 "Timers" : "false",
 "Type" : "Lux",
 "TypeImg" : "lux",
 "Unit" : 255,
 "Used" : 1,
 "XOffset" : "0",
 "YOffset" : "0",
 "idx" : "696"
 },
 {
 "AddjMulti" : 1.0,
 "AddjMulti2" : 1.0,
 "AddjValue" : 0.0,
 "AddjValue2" : 0.0,
 "BatteryLevel" : 92,
 "CustomImage" : 0,
 "Data" : "21.7 C",
 "Description" : "",
 "Favorite" : 0,
 "HardwareID" : 23,
 "HardwareName" : "Z-Stick Gen5",
 "HardwareType" : "OpenZWave USB",
 "HardwareTypeVal" : 21,
 "HaveTimeout" : false,
 "ID" : "4901",
 "LastUpdate" : "2018-12-04 21:07:50",
 "Name" : "Temp FGMS001",
 "Notifications" : "false",
 "PlanID" : "0",
 "PlanIDs" : [ 0 ],
 "Protected" : false,
 "ShowNotifications" : true,
 "SignalLevel" : "-",
 "SubType" : "LaCrosse TX3",
 "Temp" : 21.699999999999999,
 "Timers" : "false",
 "Type" : "Temp",
 "TypeImg" : "temperature",
 "Unit" : 1,
 "Used" : 1,
 "XOffset" : "0",
 "YOffset" : "0",
 "idx" : "697"
 },
 {
 "AddjMulti" : 1.0,
 "AddjMulti2" : 1.0,
 "AddjValue" : 0.0,
 "AddjValue2" : 0.0,
 "BatteryLevel" : 255,
 "CustomImage" : 0,
 "Data" : "Off",
 "Description" : "script:///home/pi/domoticz/scripts/Blink_Salon.py",
 "DimmerType" : "none",
 "Favorite" : 0,
 "HardwareID" : 21,
 "HardwareName" : "Virtual",
 "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
 "HardwareTypeVal" : 15,
 "HaveDimmer" : true,
 "HaveGroupCmd" : true,
 "HaveTimeout" : false,
 "ID" : "00014315",
 "Image" : "Light",
 "IsSubDevice" : false,
 "LastUpdate" : "2018-02-13 13:05:53",
 "Level" : 0,
 "LevelInt" : 0,
 "MaxDimLevel" : 100,
 "Name" : "Test",
 "Notifications" : "false",
 "PlanID" : "0",
 "PlanIDs" : [ 0 ],
 "Protected" : false,
 "ShowNotifications" : true,
 "SignalLevel" : "-",
 "Status" : "Off",
 "StrParam1" : "c2NyaXB0Oi8vL0JsaW5rX1NhbG9u",
 "StrParam2" : "",
 "SubType" : "Switch",
 "SwitchType" : "On/Off",
 "SwitchTypeVal" : 0,
 "Timers" : "false",
 "Type" : "Light/Switch",
 "TypeImg" : "lightbulb",
 "Unit" : 1,
 "Used" : 1,
 "UsedByCamera" : false,
 "XOffset" : "0",
 "YOffset" : "0",
 "idx" : "709"
 },
 {
 "AddjMulti" : 1.0,
 "AddjMulti2" : 1.0,
 "AddjValue" : 0.0,
 "AddjValue2" : 0.0,
 "BatteryLevel" : 255,
 "CustomImage" : 0,
 "Data" : "Closed",
 "Description" : "",
 "DimmerType" : "none",
 "Favorite" : 0,
 "HardwareID" : 21,
 "HardwareName" : "Virtual",
 "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
 "HardwareTypeVal" : 15,
 "HaveDimmer" : true,
 "HaveGroupCmd" : true,
 "HaveTimeout" : false,
 "ID" : "00014341",
 "Image" : "Light",
 "IsSubDevice" : false,
 "LastUpdate" : "2018-08-29 07:52:23",
 "Level" : 100,
 "LevelInt" : 100,
 "MaxDimLevel" : 100,
 "Name" : "Coupure courant",
 "Notifications" : "false",
 "PlanID" : "0",
 "PlanIDs" : [ 0 ],
 "Protected" : false,
 "ShowNotifications" : true,
 "SignalLevel" : "-",
 "Status" : "Closed",
 "StrParam1" : "",
 "StrParam2" : "",
 "SubType" : "Switch",
 "SwitchType" : "Contact",
 "SwitchTypeVal" : 2,
 "Timers" : "false",
 "Type" : "Light/Switch",
 "TypeImg" : "contact",
 "Unit" : 1,
 "Used" : 1,
 "UsedByCamera" : false,
 "XOffset" : "0",
 "YOffset" : "0",
 "idx" : "753"
 },
 {
 "AddjMulti" : 1.0,
 "AddjMulti2" : 1.0,
 "AddjValue" : 2.0,
 "AddjValue2" : 0.0,
 "BatteryLevel" : 255,
 "CustomImage" : 0,
 "Data" : "Off",
 "Description" : "https://api.pilot.patrickferreira.com/#FIELD1/#SUBJECT/#MESSAGE",
 "DimmerType" : "none",
 "Favorite" : 0,
 "HardwareID" : 21,
 "HardwareName" : "Virtual",
 "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
 "HardwareTypeVal" : 15,
 "HaveDimmer" : true,
 "HaveGroupCmd" : true,
 "HaveTimeout" : false,
 "ID" : "00014342",
 "Image" : "Light",
 "IsSubDevice" : false,
 "LastUpdate" : "2018-11-26 12:48:41",
 "Level" : 0,
 "LevelInt" : 0,
 "MaxDimLevel" : 100,
 "Name" : "Télé",
 "Notifications" : "false",
 "PlanID" : "5",
 "PlanIDs" : [ 5 ],
 "Protected" : false,
 "ShowNotifications" : true,
 "SignalLevel" : "-",
 "Status" : "Off",
 "StrParam1" : "c2NyaXB0Oi8vL2hvbWUvcGkvVFZfU0FNU1VOR19QT1dFUi5zaA==",
 "StrParam2" : "",
 "SubType" : "Switch",
 "SwitchType" : "On/Off",
 "SwitchTypeVal" : 0,
 "Timers" : "false",
 "Type" : "Light/Switch",
 "TypeImg" : "lightbulb",
 "Unit" : 1,
 "Used" : 1,
 "UsedByCamera" : false,
 "XOffset" : "1187",
 "YOffset" : "107",
 "idx" : "754"
 },
 {
 "AddjMulti" : 1.0,
 "AddjMulti2" : 1.0,
 "AddjValue" : 0.0,
 "AddjValue2" : 0.0,
 "BatteryLevel" : 255,
 "CustomImage" : 2,
 "Data" : "Off",
 "Description" : "",
 "DimmerType" : "none",
 "Favorite" : 0,
 "HardwareID" : 21,
 "HardwareName" : "Virtual",
 "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
 "HardwareTypeVal" : 15,
 "HaveDimmer" : true,
 "HaveGroupCmd" : true,
 "HaveTimeout" : false,
 "ID" : "00014343",
 "Image" : "TV",
 "IsSubDevice" : false,
 "LastUpdate" : "2018-10-10 20:15:48",
 "Level" : 0,
 "LevelActions" :
"fGh0dHA6Ly8xOTIuMTY4LjEuMjAwOjg4ODgvanNvbi5odG0/dHlwZT1jb21tYW5kJnBhcmFtPXN3aXRjaGxpZ2h0JmlkeD03NDImc3dpdGNoY21kPU9ufHx8",
 "LevelInt" : 0,
 "LevelNames" : "T2ZmfDF8MnwzfDQ=",
 "LevelOffHidden" : false,
 "MaxDimLevel" : 100,
 "Name" : "Télévision",
 "Notifications" : "false",
 "PlanID" : "5",
 "PlanIDs" : [ 5 ],
 "Protected" : false,
 "SelectorStyle" : 1,
 "ShowNotifications" : true,
 "SignalLevel" : "-",
 "Status" : "Off",
 "StrParam1" : "",
 "StrParam2" : "",
 "SubType" : "Selector Switch",
 "SwitchType" : "Selector",
 "SwitchTypeVal" : 18,
 "Timers" : "false",
 "Type" : "Light/Switch",
 "TypeImg" : "Light",
 "Unit" : 1,
 "Used" : 1,
 "UsedByCamera" : false,
 "XOffset" : "1190",
 "YOffset" : "63",
 "idx" : "755"
 },
 {
 "AddjMulti" : 1.0,
 "AddjMulti2" : 1.0,
 "AddjValue" : 2.0,
 "AddjValue2" : 0.0,
 "BatteryLevel" : 255,
 "CustomImage" : 133,
 "Data" : "Off",
 "Description" : "",
 "DimmerType" : "none",
 "Favorite" : 0,
 "HardwareID" : 21,
 "HardwareName" : "Virtual",
 "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
 "HardwareTypeVal" : 15,
 "HaveDimmer" : true,
 "HaveGroupCmd" : true,
 "HaveTimeout" : false,
 "ID" : "00014344",
 "Image" : "RobotVacuum",
 "IsSubDevice" : false,
 "LastUpdate" : "2018-10-13 12:49:12",
 "Level" : 0,
 "LevelInt" : 0,
 "MaxDimLevel" : 100,
 "Name" : "Gégé",
 "Notifications" : "false",
 "PlanID" : "0",
 "PlanIDs" : [ 0 ],
 "Protected" : false,
 "ShowNotifications" : true,
 "SignalLevel" : "-",
 "Status" : "Off",
 "StrParam1" : "c2NyaXB0Oi8vL2hvbWUvcGkvSVJfTkFWSUJPVC5zaA==",
 "StrParam2" : "",
 "SubType" : "Switch",
 "SwitchType" : "On/Off",
 "SwitchTypeVal" : 0,
 "Timers" : "false",
 "Type" : "Light/Switch",
 "TypeImg" : "lightbulb",
 "Unit" : 1,
 "Used" : 1,
 "UsedByCamera" : false,
 "XOffset" : "0",
 "YOffset" : "0",
 "idx" : "756"
 }
 ],
 "status" : "OK",
 "title" : "Devices"
});