exports.DOMOTICZ_GET_DEVICES = JSON.stringify({
   "ActTime" : 1544893463,
   "AstrTwilightEnd" : "18:60",
   "AstrTwilightStart" : "06:52",
   "CivTwilightEnd" : "17:41",
   "CivTwilightStart" : "08:11",
   "DayLength" : "08:15",
   "NautTwilightEnd" : "18:21",
   "NautTwilightStart" : "07:31",
   "ServerTime" : "2018-12-15 18:04:23",
   "SunAtSouth" : "12:05",
   "Sunrise" : "08:49",
   "Sunset" : "17:03",
   "result" : [
      {
         "Data" : "On",
         "Description" : "",
         "Favorite" : 0,
         "LastUpdate" : "2018-12-15 17:37:09",
         "Name" : "lampe bleu",
         "PlanID" : "",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "Status" : "On",
         "Type" : "Scene",
         "TypeImg" : "scene",
         "UsedByCamera" : false,
         "XOffset" : 0,
         "YOffset" : 0,
         "idx" : "5"
      },
      {
         "Data" : "On",
         "Description" : "",
         "Favorite" : 0,
         "LastUpdate" : "2018-12-15 17:36:58",
         "Name" : "lampe blanc 100",
         "PlanID" : "",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "Status" : "On",
         "Type" : "Scene",
         "TypeImg" : "scene",
         "UsedByCamera" : false,
         "XOffset" : 0,
         "YOffset" : 0,
         "idx" : "6"
      },
      {
         "Data" : "On",
         "Description" : "",
         "Favorite" : 0,
         "LastUpdate" : "2018-12-15 17:36:41",
         "Name" : "lampe blanc 25",
         "PlanID" : "",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "Status" : "On",
         "Type" : "Scene",
         "TypeImg" : "scene",
         "UsedByCamera" : false,
         "XOffset" : 0,
         "YOffset" : 0,
         "idx" : "7"
      },
      {
         "Data" : "On",
         "Description" : "",
         "Favorite" : 0,
         "LastUpdate" : "2018-12-15 17:36:45",
         "Name" : "lampe blanc 50",
         "PlanID" : "",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "Status" : "On",
         "Type" : "Scene",
         "TypeImg" : "scene",
         "UsedByCamera" : false,
         "XOffset" : 0,
         "YOffset" : 0,
         "idx" : "8"
      },
      {
         "Data" : "On",
         "Description" : "",
         "Favorite" : 0,
         "LastUpdate" : "2018-12-06 20:12:15",
         "Name" : "lampe blanc 75",
         "PlanID" : "",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "Status" : "On",
         "Type" : "Scene",
         "TypeImg" : "scene",
         "UsedByCamera" : false,
         "XOffset" : 0,
         "YOffset" : 0,
         "idx" : "9"
      },
      {
         "Data" : "On",
         "Description" : "",
         "Favorite" : 0,
         "LastUpdate" : "2018-02-22 19:14:45",
         "Name" : "test",
         "PlanID" : "",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "Status" : "On",
         "Type" : "Scene",
         "TypeImg" : "scene",
         "UsedByCamera" : false,
         "XOffset" : 0,
         "YOffset" : 0,
         "idx" : "10"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "Color" : "",
         "CustomImage" : 0,
         "Data" : "Off",
         "Description" : "",
         "DimmerType" : "abs",
         "Favorite" : 0,
         "HardwareID" : 2,
         "HardwareName" : "gateway",
         "HardwareType" : "Xiaomi Gateway",
         "HardwareTypeVal" : 95,
         "HaveDimmer" : true,
         "HaveGroupCmd" : false,
         "HaveTimeout" : false,
         "ID" : "07F1C547",
         "Image" : "Light",
         "IsSubDevice" : false,
         "LastUpdate" : "2018-12-15 17:45:24",
         "Level" : 26,
         "LevelInt" : 26,
         "MaxDimLevel" : 100,
         "Name" : "Xiaomi RGB Gateway",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "RGBW",
         "SwitchType" : "Dimmer",
         "SwitchTypeVal" : 7,
         "Timers" : "false",
         "Type" : "Color Switch",
         "TypeImg" : "dimmer",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "1"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 8,
         "Data" : "Off",
         "Description" : "",
         "DimmerType" : "abs",
         "Favorite" : 0,
         "HardwareID" : 2,
         "HardwareName" : "gateway",
         "HardwareType" : "Xiaomi Gateway",
         "HardwareTypeVal" : 95,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "07F1C547",
         "Image" : "Speaker",
         "IsSubDevice" : false,
         "LastUpdate" : "2018-10-21 17:21:25",
         "Level" : 100,
         "LevelInt" : 100,
         "MaxDimLevel" : 100,
         "Name" : "Xiaomi Gateway MP3",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Switch",
         "SwitchType" : "Dimmer",
         "SwitchTypeVal" : 7,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "dimmer",
         "Unit" : 6,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "5"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 1.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 8,
         "Data" : "Off",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareID" : 2,
         "HardwareName" : "gateway",
         "HardwareType" : "Xiaomi Gateway",
         "HardwareTypeVal" : 95,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "07F1C547",
         "Image" : "Speaker",
         "IsSubDevice" : false,
         "LastUpdate" : "2018-02-05 15:39:05",
         "Level" : 0,
         "LevelActions" : "fHx8fHx8fHx8",
         "LevelInt" : 0,
         "LevelNames" : "T2ZmfFBvbGljZSBzaXJlbiAxfFBvbGljZSBzaXJlbiAyfEFjY2lkZW50IHRvbmV8TWlzc2xlIGNvdW50ZG93bnxHaG9zdHxTbmlwZXJ8V2FyfEFpciBTdHJpa2V8QmFya2luZyBkb2dz",
         "LevelOffHidden" : false,
         "MaxDimLevel" : 100,
         "Name" : "Xiaomi Gateway Alarm Ringtone",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "SelectorStyle" : 1,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Selector Switch",
         "SwitchType" : "Selector",
         "SwitchTypeVal" : 18,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "Light",
         "Unit" : 3,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "2"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 8,
         "Data" : "Off",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareID" : 2,
         "HardwareName" : "gateway",
         "HardwareType" : "Xiaomi Gateway",
         "HardwareTypeVal" : 95,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "07F1C547",
         "Image" : "Speaker",
         "IsSubDevice" : false,
         "LastUpdate" : "2018-12-14 16:22:59",
         "Level" : 0,
         "LevelActions" : "",
         "LevelInt" : 0,
         "LevelNames" : "T2ZmfERvb3JiZWxsIHJpbmcgdG9uZXxLbm9jayBvbiBkb29yfEhpbGFyaW91c3xBbGFybSBjbG9jaw==",
         "LevelOffHidden" : false,
         "MaxDimLevel" : 100,
         "Name" : "Xiaomi Gateway Doorbell",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "SelectorStyle" : 1,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Selector Switch",
         "SwitchType" : "Selector",
         "SwitchTypeVal" : 18,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "Light",
         "Unit" : 5,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "4"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 8,
         "Data" : "Off",
         "Description" : "",
         "DimmerType" : "abs",
         "Favorite" : 0,
         "HardwareID" : 2,
         "HardwareName" : "gateway",
         "HardwareType" : "Xiaomi Gateway",
         "HardwareTypeVal" : 95,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "07F1C547",
         "Image" : "Speaker",
         "IsSubDevice" : false,
         "LastUpdate" : "2018-12-14 16:22:59",
         "Level" : 100,
         "LevelInt" : 100,
         "MaxDimLevel" : 100,
         "Name" : "Xiaomi Gateway Volume",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Switch",
         "SwitchType" : "Dimmer",
         "SwitchTypeVal" : 7,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "dimmer",
         "Unit" : 7,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "6"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 80,
         "CustomImage" : 0,
         "Data" : "Closed",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareID" : 2,
         "HardwareName" : "gateway",
         "HardwareType" : "Xiaomi Gateway",
         "HardwareTypeVal" : 95,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "01AAB2AD",
         "Image" : "Light",
         "IsSubDevice" : false,
         "LastUpdate" : "2018-12-15 17:32:31",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 100,
         "Name" : "capteur porte entree",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Closed",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Switch",
         "SwitchType" : "Contact",
         "SwitchTypeVal" : 2,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "contact",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "9"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 82,
         "CustomImage" : 0,
         "Data" : "Closed",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareID" : 2,
         "HardwareName" : "gateway",
         "HardwareType" : "Xiaomi Gateway",
         "HardwareTypeVal" : 95,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "019D4FCF",
         "Image" : "Light",
         "IsSubDevice" : false,
         "LastUpdate" : "2018-12-15 17:45:25",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 100,
         "Name" : "capteur porte LT",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Closed",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Switch",
         "SwitchType" : "Contact",
         "SwitchTypeVal" : 2,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "contact",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "22"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 80,
         "CustomImage" : 0,
         "Data" : "Closed",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareID" : 2,
         "HardwareName" : "gateway",
         "HardwareType" : "Xiaomi Gateway",
         "HardwareTypeVal" : 95,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "01DE8E5E",
         "Image" : "Light",
         "IsSubDevice" : false,
         "LastUpdate" : "2018-12-14 08:33:59",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 100,
         "Name" : "capteur baie etage sp",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Closed",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Switch",
         "SwitchType" : "Contact",
         "SwitchTypeVal" : 2,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "contact",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "53"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 9,
         "Data" : "Off",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 1,
         "HardwareID" : 2,
         "HardwareName" : "gateway",
         "HardwareType" : "Xiaomi Gateway",
         "HardwareTypeVal" : 95,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "01AB682F",
         "Image" : "Generic",
         "IsSubDevice" : false,
         "LastUpdate" : "2018-12-15 17:37:09",
         "Level" : 0,
         "LevelActions" : "fHx8fA==",
         "LevelInt" : 0,
         "LevelNames" : "T2ZmfENsaWNrfERvdWJsZSBDbGlja3xMb25nIENsaWNrfExvbmcgQ2xpY2sgUmVsZWFzZQ==",
         "LevelOffHidden" : false,
         "MaxDimLevel" : 100,
         "Name" : "interrupteur salon",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "SelectorStyle" : 0,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Selector Switch",
         "SwitchType" : "Selector",
         "SwitchTypeVal" : 18,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "Light",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "11"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 1.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 70,
         "CustomImage" : 9,
         "Data" : "Off",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareID" : 2,
         "HardwareName" : "gateway",
         "HardwareType" : "Xiaomi Gateway",
         "HardwareTypeVal" : 95,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "01B199EB",
         "Image" : "Generic",
         "IsSubDevice" : false,
         "LastUpdate" : "2018-12-14 16:22:57",
         "Level" : 0,
         "LevelActions" : "fHx8fA==",
         "LevelInt" : 0,
         "LevelNames" : "T2ZmfENsaWNrfERvdWJsZSBDbGlja3xMb25nIENsaWNrfExvbmcgQ2xpY2sgUmVsZWFzZQ==",
         "LevelOffHidden" : false,
         "MaxDimLevel" : 100,
         "Name" : "Interrupteur entree",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "SelectorStyle" : 0,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Selector Switch",
         "SwitchType" : "Selector",
         "SwitchTypeVal" : 18,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "Light",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "27"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 83,
         "CustomImage" : 9,
         "Data" : "Off",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareID" : 2,
         "HardwareName" : "gateway",
         "HardwareType" : "Xiaomi Gateway",
         "HardwareTypeVal" : 95,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "01A1F5D4",
         "Image" : "Generic",
         "IsSubDevice" : false,
         "LastUpdate" : "2018-12-15 12:48:17",
         "Level" : 0,
         "LevelActions" : "",
         "LevelInt" : 0,
         "LevelNames" : "T2ZmfENsaWNrfERvdWJsZSBDbGlja3xMb25nIENsaWNrfExvbmcgQ2xpY2sgUmVsZWFzZQ==",
         "LevelOffHidden" : false,
         "MaxDimLevel" : 100,
         "Name" : "bouton poele",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "SelectorStyle" : 0,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Selector Switch",
         "SwitchType" : "Selector",
         "SwitchTypeVal" : 18,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "Light",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "57"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "Color" : "{\"b\":255,\"cw\":0,\"g\":24,\"m\":3,\"r\":0,\"t\":0,\"ww\":0}",
         "CustomImage" : 0,
         "Data" : "On",
         "Description" : "",
         "DimmerType" : "abs",
         "Favorite" : 0,
         "HardwareID" : 3,
         "HardwareName" : "yeelight",
         "HardwareType" : "YeeLight LED",
         "HardwareTypeVal" : 91,
         "HaveDimmer" : true,
         "HaveGroupCmd" : false,
         "HaveTimeout" : false,
         "ID" : "C0A8014B",
         "Image" : "Light",
         "IsSubDevice" : false,
         "LastUpdate" : "2018-12-15 17:38:31",
         "Level" : 100,
         "LevelInt" : 100,
         "MaxDimLevel" : 100,
         "Name" : "lampe salon",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "On",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "RGBWW",
         "SwitchType" : "Dimmer",
         "SwitchTypeVal" : 7,
         "Timers" : "false",
         "Type" : "Color Switch",
         "TypeImg" : "dimmer",
         "Unit" : 0,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "15"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "Off",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareID" : 2,
         "HardwareName" : "gateway",
         "HardwareType" : "Xiaomi Gateway",
         "HardwareTypeVal" : 95,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "01AE9AD6",
         "Image" : "Light",
         "IsSubDevice" : false,
         "LastUpdate" : "2018-11-23 13:38:45",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 100,
         "Name" : "detecteur bureau",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Switch",
         "SwitchType" : "Motion Sensor",
         "SwitchTypeVal" : 8,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "motion",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "13"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 5.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "Off",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareID" : 2,
         "HardwareName" : "gateway",
         "HardwareType" : "Xiaomi Gateway",
         "HardwareTypeVal" : 95,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "01A8E3DC",
         "Image" : "Light",
         "IsSubDevice" : false,
         "LastUpdate" : "2018-12-15 15:45:03",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 100,
         "Name" : "detecteur chambre rdc",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Switch",
         "SwitchType" : "Motion Sensor",
         "SwitchTypeVal" : 8,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "motion",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "25"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "Off",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareID" : 2,
         "HardwareName" : "gateway",
         "HardwareType" : "Xiaomi Gateway",
         "HardwareTypeVal" : 95,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "02250836",
         "Image" : "Light",
         "IsSubDevice" : false,
         "LastUpdate" : "2018-12-15 18:03:02",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 100,
         "Name" : "detecteur salon",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Switch",
         "SwitchType" : "Motion Sensor",
         "SwitchTypeVal" : 8,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "motion",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "56"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 5.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CameraIdx" : "1",
         "CustomImage" : 2,
         "Data" : "Off",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 1,
         "HardwareID" : 4,
         "HardwareName" : "bouton virtuel",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "00014062",
         "Image" : "TV",
         "IsSubDevice" : false,
         "LastUpdate" : "2018-02-22 22:14:41",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 100,
         "Name" : "camera ext",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Switch",
         "SwitchType" : "On/Off",
         "SwitchTypeVal" : 0,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "lightbulb",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : true,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "18"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 10.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CameraIdx" : "2",
         "CustomImage" : 2,
         "Data" : "Off",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 1,
         "HardwareID" : 4,
         "HardwareName" : "bouton virtuel",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "00014064",
         "Image" : "TV",
         "IsSubDevice" : false,
         "LastUpdate" : "2018-08-19 10:37:40",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 100,
         "Name" : "camera grange",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Switch",
         "SwitchType" : "On/Off",
         "SwitchTypeVal" : 0,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "lightbulb",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : true,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "20"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 5.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CameraIdx" : "3",
         "CustomImage" : 2,
         "Data" : "Off",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 1,
         "HardwareID" : 4,
         "HardwareName" : "bouton virtuel",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "00014063",
         "Image" : "TV",
         "IsSubDevice" : false,
         "LastUpdate" : "2018-01-27 12:09:19",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 100,
         "Name" : "camera salon",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Switch",
         "SwitchType" : "On/Off",
         "SwitchTypeVal" : 0,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "lightbulb",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : true,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "19"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 100,
         "CustomImage" : 0,
         "Data" : "21.0 C",
         "Description" : "",
         "Favorite" : 0,
         "HardwareID" : 2,
         "HardwareName" : "gateway",
         "HardwareType" : "Xiaomi Gateway",
         "HardwareTypeVal" : 95,
         "HaveTimeout" : false,
         "ID" : "3282",
         "LastUpdate" : "2018-12-15 17:59:48",
         "Name" : "Xiaomi Temperature",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "LaCrosse TX3",
         "Temp" : 21.0,
         "Timers" : "false",
         "Type" : "Temp",
         "TypeImg" : "temperature",
         "Unit" : 130,
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "29"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "Humidity 41 %",
         "Description" : "",
         "Favorite" : 0,
         "HardwareID" : 2,
         "HardwareName" : "gateway",
         "HardwareType" : "Xiaomi Gateway",
         "HardwareTypeVal" : 95,
         "HaveTimeout" : false,
         "Humidity" : 41,
         "HumidityStatus" : "Comfortable",
         "ID" : "3282",
         "LastUpdate" : "2018-12-15 17:59:48",
         "Name" : "Xiaomi Humidity",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "LaCrosse TX3",
         "Timers" : "false",
         "Type" : "Humidity",
         "TypeImg" : "temperature",
         "Unit" : 1,
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "30"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "1003.0 Bar",
         "Description" : "",
         "Favorite" : 0,
         "HardwareID" : 2,
         "HardwareName" : "gateway",
         "HardwareType" : "Xiaomi Gateway",
         "HardwareTypeVal" : 95,
         "HaveTimeout" : false,
         "ID" : "F5328201",
         "LastUpdate" : "2018-12-15 17:59:48",
         "Name" : "Xiaomi Humidity",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Pressure" : 1003.0,
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "Pressure",
         "Timers" : "false",
         "Type" : "General",
         "TypeImg" : "gauge",
         "Unit" : 1,
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "31"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "21.0 C, 41 %",
         "Description" : "",
         "DewPoint" : "7.24",
         "Favorite" : 1,
         "HardwareID" : 2,
         "HardwareName" : "gateway",
         "HardwareType" : "Xiaomi Gateway",
         "HardwareTypeVal" : 95,
         "HaveTimeout" : false,
         "Humidity" : 41,
         "HumidityStatus" : "Comfortable",
         "ID" : "3282",
         "LastUpdate" : "2018-12-15 17:59:48",
         "Name" : "Température intérieur",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "LaCrosse TX3",
         "Temp" : 21.0,
         "Timers" : "false",
         "Type" : "Temp + Humidity",
         "TypeImg" : "temperature",
         "Unit" : 2,
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "32"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 99,
         "CustomImage" : 0,
         "Data" : "Off",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareID" : 5,
         "HardwareName" : "cle zwave",
         "HardwareType" : "OpenZWave USB",
         "HardwareTypeVal" : 21,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "00000300",
         "Image" : "Light",
         "IsSubDevice" : false,
         "LastUpdate" : "2018-02-05 18:56:39",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 100,
         "Name" : "detecteur fumee detection",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Switch",
         "SwitchType" : "On/Off",
         "SwitchTypeVal" : 0,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "lightbulb",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "33"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 100,
         "CustomImage" : 0,
         "Data" : "On",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareID" : 5,
         "HardwareName" : "cle zwave",
         "HardwareType" : "OpenZWave USB",
         "HardwareTypeVal" : 21,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "00000329",
         "Image" : "Light",
         "IsSubDevice" : false,
         "LastUpdate" : "2018-12-02 22:02:30",
         "Level" : 255,
         "LevelInt" : 255,
         "MaxDimLevel" : 100,
         "Name" : "detecteur fumee etat",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "On",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Switch",
         "SwitchType" : "On/Off",
         "SwitchTypeVal" : 0,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "lightbulb",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "36"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 9,
         "Data" : "Off",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareID" : 4,
         "HardwareName" : "bouton virtuel",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "00014077",
         "Image" : "Generic",
         "IsSubDevice" : false,
         "LastUpdate" : "2018-12-15 11:00:01",
         "Level" : 100,
         "LevelInt" : 100,
         "MaxDimLevel" : 100,
         "Name" : "planning semaine",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Switch",
         "SwitchType" : "On/Off",
         "SwitchTypeVal" : 0,
         "Timers" : "true",
         "Type" : "Light/Switch",
         "TypeImg" : "lightbulb",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "39"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 9,
         "Data" : "Off",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareID" : 4,
         "HardwareName" : "bouton virtuel",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "00014078",
         "Image" : "Generic",
         "IsSubDevice" : false,
         "LastUpdate" : "2018-12-15 11:00:01",
         "Level" : 100,
         "LevelInt" : 100,
         "MaxDimLevel" : 100,
         "Name" : "planning jfv",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Switch",
         "SwitchType" : "On/Off",
         "SwitchTypeVal" : 0,
         "Timers" : "true",
         "Type" : "Light/Switch",
         "TypeImg" : "lightbulb",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "40"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 10,
         "Data" : "Set Level: 20 %",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 1,
         "HardwareID" : 4,
         "HardwareName" : "bouton virtuel",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "0001407C",
         "Image" : "Fireplace",
         "IsSubDevice" : false,
         "LastUpdate" : "2018-12-15 12:48:17",
         "Level" : 20,
         "LevelActions" : "fHx8fA==",
         "LevelInt" : 20,
         "LevelNames" : "T2ZmfE5vcm1hbHxNYXJjaGUgRm9yY2VlfFJlcG9zfEFycmV0",
         "LevelOffHidden" : true,
         "MaxDimLevel" : 100,
         "Name" : "Poele mode",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "SelectorStyle" : 0,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Set Level: 20 %",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Selector Switch",
         "SwitchType" : "Selector",
         "SwitchTypeVal" : 18,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "Light",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "44"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "On",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareID" : 5,
         "HardwareName" : "cle zwave",
         "HardwareType" : "OpenZWave USB",
         "HardwareTypeVal" : 21,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "00000401",
         "Image" : "Light",
         "IsSubDevice" : false,
         "LastUpdate" : "2018-12-15 12:48:17",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 100,
         "Name" : "Poele contact sec",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "On",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Switch",
         "SwitchType" : "On/Off",
         "SwitchTypeVal" : 0,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "lightbulb",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "45"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "Normal",
         "Description" : "",
         "Favorite" : 1,
         "HardwareID" : 1,
         "HardwareName" : "Domoticz Internal",
         "HardwareType" : "Domoticz Internal interface",
         "HardwareTypeVal" : 67,
         "HaveDimmer" : false,
         "HaveGroupCmd" : false,
         "HaveTimeout" : false,
         "ID" : "148702",
         "LastUpdate" : "2018-10-21 17:21:55",
         "MaxDimLevel" : 0,
         "Name" : "Alarme",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Normal",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Security Panel",
         "SwitchType" : "Security",
         "SwitchTypeVal" : 0,
         "Timers" : "false",
         "Type" : "Security",
         "TypeImg" : "security",
         "Unit" : 0,
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "21"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "Off",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareID" : 4,
         "HardwareName" : "bouton virtuel",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "0001406A",
         "Image" : "Light",
         "IsSubDevice" : false,
         "LastUpdate" : "2018-03-18 14:50:17",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 100,
         "Name" : "bouton test",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Switch",
         "SwitchType" : "On/Off",
         "SwitchTypeVal" : 0,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "lightbulb",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "26"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "Barometer" : 1007,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "2.7 C, 85 %, 1007 hPa",
         "Description" : "",
         "DewPoint" : "0.43",
         "Favorite" : 1,
         "Forecast" : 4,
         "ForecastStr" : "Rain",
         "HardwareID" : 6,
         "HardwareName" : "METEO",
         "HardwareType" : "Weather Underground",
         "HardwareTypeVal" : 14,
         "HaveTimeout" : false,
         "Humidity" : 85,
         "HumidityStatus" : "Wet",
         "ID" : "0001",
         "LastUpdate" : "2018-12-15 17:57:33",
         "Name" : "Météo température",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "THB1 - BTHR918, BTHGN129",
         "Temp" : 2.7000000000000002,
         "Timers" : "false",
         "Type" : "Temp + Humidity + Baro",
         "TypeImg" : "temperature",
         "Unit" : 1,
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "forecast_url" : "aHR0cDovL3d3dy53dW5kZXJncm91bmQuY29tL2NnaS1iaW4vZmluZHdlYXRoZXIvZ2V0Rm9yZWNhc3Q/cXVlcnk9cHdzJTNBSUJBU1NFTk80Nw==",
         "idx" : "48"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "Chill" : 1.0,
         "CustomImage" : 0,
         "Data" : "213.00;SSW;21;71;2.7;1.0",
         "Description" : "",
         "Direction" : 213.0,
         "DirectionStr" : "SSW",
         "Favorite" : 1,
         "Gust" : "25.6",
         "HardwareID" : 6,
         "HardwareName" : "METEO",
         "HardwareType" : "Weather Underground",
         "HardwareTypeVal" : 14,
         "HaveTimeout" : false,
         "ID" : "0001",
         "LastUpdate" : "2018-12-15 17:57:33",
         "Name" : "Météo vent",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Speed" : "7.6",
         "SubType" : "TFA",
         "Temp" : 2.7000000000000002,
         "Timers" : "false",
         "Type" : "Wind",
         "TypeImg" : "wind",
         "Unit" : 0,
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "forecast_url" : "aHR0cDovL3d3dy53dW5kZXJncm91bmQuY29tL2NnaS1iaW4vZmluZHdlYXRoZXIvZ2V0Rm9yZWNhc3Q/cXVlcnk9cHdzJTNBSUJBU1NFTk80Nw==",
         "idx" : "49"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "0.0 UVI",
         "Description" : "",
         "Favorite" : 0,
         "HardwareID" : 6,
         "HardwareName" : "METEO",
         "HardwareType" : "Weather Underground",
         "HardwareTypeVal" : 14,
         "HaveTimeout" : false,
         "ID" : "0001",
         "LastUpdate" : "2018-12-15 17:57:33",
         "Name" : "Météo indice UV",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "UVN128,UV138",
         "Timers" : "false",
         "Type" : "UV",
         "TypeImg" : "uv",
         "UVI" : "0.0",
         "Unit" : 0,
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "forecast_url" : "aHR0cDovL3d3dy53dW5kZXJncm91bmQuY29tL2NnaS1iaW4vZmluZHdlYXRoZXIvZ2V0Rm9yZWNhc3Q/cXVlcnk9cHdzJTNBSUJBU1NFTk80Nw==",
         "idx" : "50"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "0;7.0",
         "Description" : "",
         "Favorite" : 1,
         "HardwareID" : 6,
         "HardwareName" : "METEO",
         "HardwareType" : "Weather Underground",
         "HardwareTypeVal" : 14,
         "HaveTimeout" : false,
         "ID" : "0001",
         "LastUpdate" : "2018-12-15 17:57:33",
         "Name" : "Météo Pluie",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "Rain" : "7",
         "RainRate" : "0",
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "WWW",
         "Timers" : "false",
         "Type" : "Rain",
         "TypeImg" : "rain",
         "Unit" : 0,
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "forecast_url" : "aHR0cDovL3d3dy53dW5kZXJncm91bmQuY29tL2NnaS1iaW4vZmluZHdlYXRoZXIvZ2V0Rm9yZWNhc3Q/cXVlcnk9cHdzJTNBSUJBU1NFTk80Nw==",
         "idx" : "51"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "0 Lux",
         "Description" : "",
         "Favorite" : 0,
         "HardwareID" : 2,
         "HardwareName" : "gateway",
         "HardwareType" : "Xiaomi Gateway",
         "HardwareTypeVal" : 95,
         "HaveTimeout" : false,
         "ID" : "0000036",
         "LastUpdate" : "2018-12-15 18:01:02",
         "Name" : "capteur luminosite salon",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "Lux",
         "Timers" : "false",
         "Type" : "Lux",
         "TypeImg" : "lux",
         "Unit" : 54,
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "55"
      }
   ],
   "status" : "OK",
   "title" : "Devices"
});