exports.DOMOTICZ_GET_DEVICES = JSON.stringify({
   "ActTime" : 1591253518,
   "AstrTwilightEnd" : "23:49",
   "AstrTwilightStart" : "03:56",
   "CivTwilightEnd" : "22:06",
   "CivTwilightStart" : "05:38",
   "DayLength" : "15:18",
   "NautTwilightEnd" : "22:52",
   "NautTwilightStart" : "04:53",
   "ServerTime" : "2020-06-04 08:51:58",
   "SunAtSouth" : "13:05",
   "Sunrise" : "06:14",
   "Sunset" : "21:31",
   "app_version" : "4.9700",
   "result" : [
      {
         "Data" : "Off",
         "Description" : "",
         "Favorite" : 0,
         "LastUpdate" : "2020-06-03 10:36:18",
         "Name" : "Commande garage",
         "PlanID" : "",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "Status" : "Off",
         "Type" : "Scene",
         "TypeImg" : "scene",
         "UsedByCamera" : false,
         "XOffset" : 0,
         "YOffset" : 0,
         "idx" : "1"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 100,
         "CustomImage" : 0,
         "Data" : "23.0 C, 58 %",
         "Description" : "",
         "DewPoint" : "14.29",
         "Favorite" : 1,
         "HardwareID" : 10,
         "HardwareName" : "RFX",
         "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
         "HardwareTypeVal" : 1,
         "HaveTimeout" : false,
         "Humidity" : 58,
         "HumidityStatus" : "Comfortable",
         "ID" : "6D03",
         "LastUpdate" : "2020-06-04 08:51:35",
         "Name" : "Chambre Mily",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : 5,
         "SubType" : "Alecto WS1700",
         "Temp" : 23.0,
         "Timers" : "false",
         "Type" : "Temp + Humidity",
         "TypeImg" : "temperature",
         "Unit" : 3,
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "34"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 100,
         "CustomImage" : 0,
         "Data" : "23.1 C, 55 %",
         "Description" : "",
         "DewPoint" : "13.57",
         "Favorite" : 1,
         "HardwareID" : 10,
         "HardwareName" : "RFX",
         "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
         "HardwareTypeVal" : 1,
         "HaveTimeout" : false,
         "Humidity" : 55,
         "HumidityStatus" : "Comfortable",
         "ID" : "9F02",
         "LastUpdate" : "2020-06-04 08:51:33",
         "Name" : "Chambre Bébé",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : 6,
         "SubType" : "Alecto WS1700",
         "Temp" : 23.100000000000001,
         "Timers" : "false",
         "Type" : "Temp + Humidity",
         "TypeImg" : "temperature",
         "Unit" : 2,
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "35"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 100,
         "CustomImage" : 0,
         "Data" : "22.4 C, 57 %",
         "Description" : "",
         "DewPoint" : "13.47",
         "Favorite" : 1,
         "HardwareID" : 10,
         "HardwareName" : "RFX",
         "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
         "HardwareTypeVal" : 1,
         "HaveTimeout" : false,
         "Humidity" : 57,
         "HumidityStatus" : "Comfortable",
         "ID" : "CB01",
         "LastUpdate" : "2020-06-04 08:51:47",
         "Name" : "Chambre Kate",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : 5,
         "SubType" : "Alecto WS1700",
         "Temp" : 22.399999999999999,
         "Timers" : "false",
         "Type" : "Temp + Humidity",
         "TypeImg" : "temperature",
         "Unit" : 1,
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "36"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "Stopped",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareID" : 10,
         "HardwareName" : "RFX",
         "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
         "HardwareTypeVal" : 1,
         "HaveDimmer" : false,
         "HaveGroupCmd" : false,
         "HaveTimeout" : false,
         "ID" : "002810",
         "Image" : "Light",
         "IsSubDevice" : true,
         "LastUpdate" : "2020-06-03 10:36:18",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 0,
         "Name" : "Garage",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Stopped",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "RFY",
         "SwitchType" : "Blinds",
         "SwitchTypeVal" : 3,
         "Timers" : "false",
         "Type" : "RFY",
         "TypeImg" : "blinds",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "37"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 100,
         "CustomImage" : 0,
         "Data" : "23.4 C, 55 %",
         "Description" : "",
         "DewPoint" : "13.85",
         "Favorite" : 1,
         "HardwareID" : 10,
         "HardwareName" : "RFX",
         "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
         "HardwareTypeVal" : 1,
         "HaveTimeout" : false,
         "Humidity" : 55,
         "HumidityStatus" : "Comfortable",
         "ID" : "D301",
         "LastUpdate" : "2020-06-04 08:51:53",
         "Name" : "Chambre Parents",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : 5,
         "SubType" : "Alecto WS1700",
         "Temp" : 23.399999999999999,
         "Timers" : "false",
         "Type" : "Temp + Humidity",
         "TypeImg" : "temperature",
         "Unit" : 1,
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "38"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "Off",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareID" : 6,
         "HardwareName" : "Perifvirtuels",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveDimmer" : false,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "65",
         "Image" : "Light",
         "IsSubDevice" : false,
         "LastUpdate" : "2020-06-03 10:36:18",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 0,
         "Name" : "Cmd gagare",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "X10",
         "SwitchType" : "On/Off",
         "SwitchTypeVal" : 0,
         "Timers" : "false",
         "Type" : "Lighting 1",
         "TypeImg" : "lightbulb",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "59"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "Barometer" : 1004,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "15.1 C, 87 %, 1004 hPa",
         "Description" : "",
         "DewPoint" : "12.95",
         "Favorite" : 0,
         "Forecast" : 3,
         "ForecastStr" : "Cloudy",
         "HardwareID" : 12,
         "HardwareName" : "Meteo",
         "HardwareType" : "DarkSky (Weather Lookup)",
         "HardwareTypeVal" : 25,
         "HaveTimeout" : false,
         "Humidity" : 87,
         "HumidityStatus" : "Wet",
         "ID" : "0001",
         "LastUpdate" : "2020-06-04 08:49:25",
         "Name" : "THP",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "THB1 - BTHR918, BTHGN129",
         "Temp" : 15.1,
         "Timers" : "false",
         "Type" : "Temp + Humidity + Baro",
         "TypeImg" : "temperature",
         "Unit" : 1,
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "forecast_url" : "aHR0cHM6Ly9kYXJrc2t5Lm5ldC8jL2YvNDMuNjYlMkMxLjUxMg==",
         "idx" : "74"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "Chill" : 15.1,
         "CustomImage" : 0,
         "Data" : "333.00;NNW;44;75;15.1;15.1",
         "Description" : "",
         "Direction" : 333.0,
         "DirectionStr" : "NNW",
         "Favorite" : 0,
         "Gust" : "7.5",
         "HardwareID" : 12,
         "HardwareName" : "Meteo",
         "HardwareType" : "DarkSky (Weather Lookup)",
         "HardwareTypeVal" : 25,
         "HaveTimeout" : false,
         "ID" : "0001",
         "LastUpdate" : "2020-06-04 08:49:25",
         "Name" : "Vent",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Speed" : "4.4",
         "SubType" : "TFA",
         "Temp" : 15.1,
         "Timers" : "false",
         "Type" : "Wind",
         "TypeImg" : "wind",
         "Unit" : 0,
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "forecast_url" : "aHR0cHM6Ly9kYXJrc2t5Lm5ldC8jL2YvNDMuNjYlMkMxLjUxMg==",
         "idx" : "75"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "0;0.0",
         "Description" : "",
         "Favorite" : 0,
         "HardwareID" : 12,
         "HardwareName" : "Meteo",
         "HardwareType" : "DarkSky (Weather Lookup)",
         "HardwareTypeVal" : 25,
         "HaveTimeout" : false,
         "ID" : "0001",
         "LastUpdate" : "2020-06-04 08:49:25",
         "Name" : "Pluie",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "Rain" : "0",
         "RainRate" : "0",
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "WWW",
         "Timers" : "false",
         "Type" : "Rain",
         "TypeImg" : "rain",
         "Unit" : 0,
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "forecast_url" : "aHR0cHM6Ly9kYXJrc2t5Lm5ldC8jL2YvNDMuNjYlMkMxLjUxMg==",
         "idx" : "77"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 1.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "Off",
         "Description" : "Alexa_Name: Ouvre volets",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareID" : 13,
         "HardwareName" : "DongleZwave",
         "HardwareType" : "OpenZWave USB",
         "HardwareTypeVal" : 21,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "00000601",
         "Image" : "Light",
         "IsSubDevice" : false,
         "LastUpdate" : "2020-06-04 07:20:02",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 100,
         "Name" : "Volets RDC montée",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Switch",
         "SwitchType" : "On/Off",
         "SwitchTypeVal" : 0,
         "Timers" : "true",
         "Type" : "Light/Switch",
         "TypeImg" : "lightbulb",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "82"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 1.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "Off",
         "Description" : "Alexa_Name: Ferme volets",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareID" : 13,
         "HardwareName" : "DongleZwave",
         "HardwareType" : "OpenZWave USB",
         "HardwareTypeVal" : 21,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "00000602",
         "Image" : "Light",
         "IsSubDevice" : false,
         "LastUpdate" : "2020-06-03 21:50:02",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 100,
         "Name" : "Volets RDC descente",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Switch",
         "SwitchType" : "On/Off",
         "SwitchTypeVal" : 0,
         "Timers" : "true",
         "Type" : "Light/Switch",
         "TypeImg" : "lightbulb",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "83"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "16%",
         "Description" : "",
         "Favorite" : 0,
         "HardwareID" : 6,
         "HardwareName" : "Perifvirtuels",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveTimeout" : false,
         "ID" : "00082085",
         "Image" : "Computer",
         "LastUpdate" : "2020-06-04 08:30:01",
         "Name" : "Proba Pluie 1h",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "Percentage",
         "Timers" : "false",
         "Type" : "General",
         "TypeImg" : "hardware",
         "Unit" : 1,
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "85"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "14%",
         "Description" : "",
         "Favorite" : 0,
         "HardwareID" : 6,
         "HardwareName" : "Perifvirtuels",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveTimeout" : false,
         "ID" : "00082086",
         "Image" : "Computer",
         "LastUpdate" : "2020-06-04 08:30:01",
         "Name" : "Proba Pluie 2h",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "Percentage",
         "Timers" : "false",
         "Type" : "General",
         "TypeImg" : "hardware",
         "Unit" : 1,
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "86"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "16%",
         "Description" : "",
         "Favorite" : 0,
         "HardwareID" : 6,
         "HardwareName" : "Perifvirtuels",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveTimeout" : false,
         "ID" : "00082087",
         "Image" : "Computer",
         "LastUpdate" : "2020-06-04 08:30:01",
         "Name" : "Proba Pluie 4h",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "Percentage",
         "Timers" : "false",
         "Type" : "General",
         "TypeImg" : "hardware",
         "Unit" : 1,
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "87"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "40%",
         "Description" : "",
         "Favorite" : 0,
         "HardwareID" : 6,
         "HardwareName" : "Perifvirtuels",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveTimeout" : false,
         "ID" : "00082088",
         "Image" : "Computer",
         "LastUpdate" : "2020-06-04 08:30:01",
         "Name" : "Proba Pluie 6h",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "Percentage",
         "Timers" : "false",
         "Type" : "General",
         "TypeImg" : "hardware",
         "Unit" : 1,
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "88"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "59%",
         "Description" : "",
         "Favorite" : 0,
         "HardwareID" : 6,
         "HardwareName" : "Perifvirtuels",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveTimeout" : false,
         "ID" : "00082089",
         "Image" : "Computer",
         "LastUpdate" : "2020-06-04 08:30:01",
         "Name" : "Proba Pluie 12h",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "Percentage",
         "Timers" : "false",
         "Type" : "General",
         "TypeImg" : "hardware",
         "Unit" : 1,
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "89"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "28%",
         "Description" : "",
         "Favorite" : 0,
         "HardwareID" : 6,
         "HardwareName" : "Perifvirtuels",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveTimeout" : false,
         "ID" : "00082090",
         "Image" : "Computer",
         "LastUpdate" : "2020-06-04 08:30:01",
         "Name" : "Proba Pluie 24h",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "Percentage",
         "Timers" : "false",
         "Type" : "General",
         "TypeImg" : "hardware",
         "Unit" : 1,
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "90"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 50,
         "CustomImage" : 10,
         "Data" : "Off",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareID" : 13,
         "HardwareName" : "DongleZwave",
         "HardwareType" : "OpenZWave USB",
         "HardwareTypeVal" : 21,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "00000729",
         "Image" : "Fireplace",
         "IsSubDevice" : false,
         "LastUpdate" : "2020-04-30 21:54:48",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 100,
         "Name" : "Fumée 3D Printer",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Switch",
         "SwitchType" : "On/Off",
         "SwitchTypeVal" : 0,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "lightbulb",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "100"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 100,
         "CustomImage" : 0,
         "Data" : "17.4 C, 82 %",
         "Description" : "",
         "DewPoint" : "14.30",
         "Favorite" : 0,
         "HardwareID" : 10,
         "HardwareName" : "RFX",
         "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
         "HardwareTypeVal" : 1,
         "HaveTimeout" : false,
         "Humidity" : 82,
         "HumidityStatus" : "Wet",
         "ID" : "AC01",
         "LastUpdate" : "2020-06-04 08:51:39",
         "Name" : "Température extérieure",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : 5,
         "SubType" : "Alecto WS1700",
         "Temp" : 17.399999999999999,
         "Timers" : "false",
         "Type" : "Temp + Humidity",
         "TypeImg" : "temperature",
         "Unit" : 1,
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "111"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 100,
         "CustomImage" : 0,
         "Data" : "25.4 C",
         "Description" : "",
         "Favorite" : 0,
         "HardwareID" : 10,
         "HardwareName" : "RFX",
         "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
         "HardwareTypeVal" : 1,
         "HaveTimeout" : true,
         "ID" : "5D00",
         "LastUpdate" : "2020-05-31 23:29:21",
         "Name" : "Température piscine",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : 5,
         "SubType" : "THR128/138, THC138",
         "Temp" : 25.399999999999999,
         "Timers" : "false",
         "Type" : "Temp",
         "TypeImg" : "temperature",
         "Unit" : 0,
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "124"
      }
   ],
   "status" : "OK",
   "title" : "Devices"
});