exports.DOMOTICZ_GET_DEVICES = JSON.stringify(
{
ActTime: 1612121699,
AstrTwilightEnd: "19:38",
AstrTwilightStart: "06:35",
CivTwilightEnd: "18:24",
CivTwilightStart: "07:50",
DayLength: "09:27",
NautTwilightEnd: "19:02",
NautTwilightStart: "07:12",
ServerTime: "2021-01-31 20:34:59",
SunAtSouth: "13:07",
Sunrise: "08:24",
Sunset: "17:50",
app_version: "2020.2 (build 12728)",
result: [
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 92,
CustomImage: 0,
Data: "Off",
Description: "",
DimmerType: "none",
Favorite: 0,
HardwareDisabled: false,
HardwareID: 2,
HardwareName: "OpenZWave",
HardwareType: "OpenZWave USB",
HardwareTypeVal: 21,
HaveDimmer: true,
HaveGroupCmd: true,
HaveTimeout: false,
ID: "00000900",
Image: "Light",
IsSubDevice: false,
LastUpdate: "2021-01-26 11:56:26",
Level: 0,
LevelInt: 0,
MaxDimLevel: 100,
Name: "Detection IR Bas",
Notifications: "false",
PlanID: "0",
PlanIDs: [
0
],
Protected: false,
ShowNotifications: true,
SignalLevel: "-",
Status: "Off",
StrParam1: "",
StrParam2: "",
SubType: "Switch",
SwitchType: "Motion Sensor",
SwitchTypeVal: 8,
Timers: "false",
Type: "Light/Switch",
TypeImg: "motion",
Unit: 1,
Used: 1,
UsedByCamera: false,
XOffset: "0",
YOffset: "0",
idx: "159"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 100,
CustomImage: 0,
Data: "Off",
Description: "",
DimmerType: "none",
Favorite: 0,
HardwareDisabled: false,
HardwareID: 2,
HardwareName: "OpenZWave",
HardwareType: "OpenZWave USB",
HardwareTypeVal: 21,
HaveDimmer: true,
HaveGroupCmd: true,
HaveTimeout: false,
ID: "00000B00",
Image: "Light",
IsSubDevice: false,
LastUpdate: "2021-01-26 11:19:12",
Level: 0,
LevelInt: 0,
MaxDimLevel: 100,
Name: "Detection IR Haut",
Notifications: "false",
PlanID: "0",
PlanIDs: [
0
],
Protected: false,
ShowNotifications: true,
SignalLevel: "-",
Status: "Off",
StrParam1: "",
StrParam2: "",
SubType: "Switch",
SwitchType: "Motion Sensor",
SwitchTypeVal: 8,
Timers: "false",
Type: "Light/Switch",
TypeImg: "motion",
Unit: 1,
Used: 1,
UsedByCamera: false,
XOffset: "0",
YOffset: "0",
idx: "167"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 88,
CustomImage: 0,
Data: "Off",
Description: "",
DimmerType: "none",
Favorite: 0,
HardwareDisabled: false,
HardwareID: 2,
HardwareName: "OpenZWave",
HardwareType: "OpenZWave USB",
HardwareTypeVal: 21,
HaveDimmer: true,
HaveGroupCmd: true,
HaveTimeout: false,
ID: "00000D00",
Image: "Light",
IsSubDevice: false,
LastUpdate: "2021-01-26 11:52:41",
Level: 0,
LevelInt: 0,
MaxDimLevel: 100,
Name: "Détecteur IR Cellier",
Notifications: "false",
PlanID: "0",
PlanIDs: [
0
],
Protected: false,
ShowNotifications: true,
SignalLevel: "-",
Status: "Off",
StrParam1: "",
StrParam2: "",
SubType: "Switch",
SwitchType: "Motion Sensor",
SwitchTypeVal: 8,
Timers: "false",
Type: "Light/Switch",
TypeImg: "motion",
Unit: 1,
Used: 1,
UsedByCamera: false,
XOffset: "0",
YOffset: "0",
idx: "180"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 100,
CameraIdx: "3",
CustomImage: 0,
Data: "Closed",
Description: "",
DimmerType: "none",
Favorite: 0,
HardwareDisabled: false,
HardwareID: 2,
HardwareName: "OpenZWave",
HardwareType: "OpenZWave USB",
HardwareTypeVal: 21,
HaveDimmer: true,
HaveGroupCmd: true,
HaveTimeout: false,
ID: "00000600",
Image: "Door",
InternalState: "Closed",
IsSubDevice: false,
LastUpdate: "2021-01-26 12:02:28",
Level: 0,
LevelInt: 0,
MaxDimLevel: 100,
Name: "Porte Entrée",
Notifications: "true",
PlanID: "0",
PlanIDs: [
0
],
Protected: false,
ShowNotifications: true,
SignalLevel: "-",
Status: "Closed",
StrParam1: "",
StrParam2: "",
SubType: "Switch",
SwitchType: "Door Contact",
SwitchTypeVal: 11,
Timers: "false",
Type: "Light/Switch",
TypeImg: "door",
Unit: 1,
Used: 1,
UsedByCamera: true,
XOffset: "0",
YOffset: "0",
idx: "113"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 81,
CustomImage: 0,
Data: "Closed",
Description: "",
DimmerType: "none",
Favorite: 0,
HardwareDisabled: false,
HardwareID: 2,
HardwareName: "OpenZWave",
HardwareType: "OpenZWave USB",
HardwareTypeVal: 21,
HaveDimmer: true,
HaveGroupCmd: true,
HaveTimeout: false,
ID: "00000500",
Image: "Door",
InternalState: "Closed",
IsSubDevice: false,
LastUpdate: "2020-11-30 15:09:37",
Level: 0,
LevelInt: 0,
MaxDimLevel: 100,
Name: "Porte Service",
Notifications: "true",
PlanID: "0",
PlanIDs: [
0
],
Protected: false,
ShowNotifications: true,
SignalLevel: "-",
Status: "Closed",
StrParam1: "",
StrParam2: "",
SubType: "Switch",
SwitchType: "Door Contact",
SwitchTypeVal: 11,
Timers: "false",
Type: "Light/Switch",
TypeImg: "door",
Unit: 1,
Used: 1,
UsedByCamera: false,
XOffset: "0",
YOffset: "0",
idx: "45"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 100,
CustomImage: 0,
Data: "Closed",
Description: "",
DimmerType: "none",
Favorite: 0,
HardwareDisabled: false,
HardwareID: 2,
HardwareName: "OpenZWave",
HardwareType: "OpenZWave USB",
HardwareTypeVal: 21,
HaveDimmer: true,
HaveGroupCmd: true,
HaveTimeout: false,
ID: "00000400",
Image: "Door",
InternalState: "Closed",
IsSubDevice: false,
LastUpdate: "2021-01-26 11:50:45",
Level: 0,
LevelInt: 0,
MaxDimLevel: 100,
Name: "Porte Garage",
Notifications: "true",
PlanID: "0",
PlanIDs: [
0
],
Protected: false,
ShowNotifications: true,
SignalLevel: "-",
Status: "Closed",
StrParam1: "",
StrParam2: "",
SubType: "Switch",
SwitchType: "Door Contact",
SwitchTypeVal: 11,
Timers: "false",
Type: "Light/Switch",
TypeImg: "door",
Unit: 1,
Used: 1,
UsedByCamera: false,
XOffset: "0",
YOffset: "0",
idx: "6"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 86,
CustomImage: 0,
Data: "Closed",
Description: "",
DimmerType: "none",
Favorite: 0,
HardwareDisabled: false,
HardwareID: 2,
HardwareName: "OpenZWave",
HardwareType: "OpenZWave USB",
HardwareTypeVal: 21,
HaveDimmer: true,
HaveGroupCmd: true,
HaveTimeout: false,
ID: "00000E00",
Image: "Door",
InternalState: "Closed",
IsSubDevice: false,
LastUpdate: "2021-01-26 11:52:11",
Level: 0,
LevelInt: 0,
MaxDimLevel: 100,
Name: "Porte Cellier",
Notifications: "true",
PlanID: "0",
PlanIDs: [
0
],
Protected: false,
ShowNotifications: true,
SignalLevel: "-",
Status: "Closed",
StrParam1: "",
StrParam2: "",
SubType: "Switch",
SwitchType: "Door Contact",
SwitchTypeVal: 11,
Timers: "false",
Type: "Light/Switch",
TypeImg: "door",
Unit: 1,
Used: 1,
UsedByCamera: false,
XOffset: "0",
YOffset: "0",
idx: "188"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 255,
CustomImage: 1,
Data: "Off",
Description: "",
DimmerType: "none",
Favorite: 0,
HardwareDisabled: false,
HardwareID: 2,
HardwareName: "OpenZWave",
HardwareType: "OpenZWave USB",
HardwareTypeVal: 21,
HaveDimmer: true,
HaveGroupCmd: true,
HaveTimeout: false,
ID: "00000801",
Image: "WallSocket",
IsSubDevice: false,
LastUpdate: "2020-11-09 10:32:52",
Level: 0,
LevelInt: 0,
MaxDimLevel: 100,
Name: "Prise Piscine",
Notifications: "true",
PlanID: "0",
PlanIDs: [
0
],
Protected: false,
ShowNotifications: true,
SignalLevel: "-",
Status: "Off",
StrParam1: "",
StrParam2: "",
SubType: "Switch",
SwitchType: "On/Off",
SwitchTypeVal: 0,
Timers: "true",
Type: "Light/Switch",
TypeImg: "lightbulb",
Unit: 1,
Used: 1,
UsedByCamera: false,
XOffset: "0",
YOffset: "0",
idx: "151"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 255,
CustomImage: 0,
Data: "On",
Description: "",
DimmerType: "none",
Favorite: 0,
HardwareDisabled: false,
HardwareID: 2,
HardwareName: "OpenZWave",
HardwareType: "OpenZWave USB",
HardwareTypeVal: 21,
HaveDimmer: true,
HaveGroupCmd: true,
HaveTimeout: false,
ID: "00000701",
Image: "Light",
IsSubDevice: false,
LastUpdate: "2021-01-31 17:49:01",
Level: 0,
LevelInt: 0,
MaxDimLevel: 100,
Name: "Lampadaire Salon",
Notifications: "true",
PlanID: "0",
PlanIDs: [
0
],
Protected: false,
ShowNotifications: true,
SignalLevel: "-",
Status: "On",
StrParam1: "",
StrParam2: "",
SubType: "Switch",
SwitchType: "On/Off",
SwitchTypeVal: 0,
Timers: "true",
Type: "Light/Switch",
TypeImg: "lightbulb",
Unit: 1,
Used: 1,
UsedByCamera: false,
XOffset: "0",
YOffset: "0",
idx: "10"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 255,
CustomImage: 0,
Data: "364.5 Watt",
Description: "",
Favorite: 0,
HardwareDisabled: false,
HardwareID: 2,
HardwareName: "OpenZWave",
HardwareType: "OpenZWave USB",
HardwareTypeVal: 21,
HaveTimeout: false,
ID: "0000A01",
LastUpdate: "2021-01-31 20:34:57",
Name: "Maison",
Notifications: "false",
PlanID: "0",
PlanIDs: [
0
],
Protected: false,
ShowNotifications: true,
SignalLevel: "-",
SubType: "Electric",
Timers: "false",
Type: "Usage",
TypeImg: "current",
Unit: 2,
Used: 1,
XOffset: "0",
YOffset: "0",
idx: "12"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 255,
CounterToday: "28.140 kWh",
CustomImage: 0,
Data: "22065.128 kWh",
Description: "",
EnergyMeterMode: "",
Favorite: 0,
HardwareDisabled: false,
HardwareID: 2,
HardwareName: "OpenZWave",
HardwareType: "OpenZWave USB",
HardwareTypeVal: 21,
HaveTimeout: false,
ID: "00000A01",
LastUpdate: "2021-01-31 20:34:57",
Name: "Maison kWh Meter",
Notifications: "false",
PlanID: "0",
PlanIDs: [
0
],
Protected: false,
ShowNotifications: true,
SignalLevel: "-",
SubType: "kWh",
SwitchTypeVal: 0,
Timers: "false",
Type: "General",
TypeImg: "current",
Unit: 1,
Usage: "364.538 Watt",
Used: 1,
XOffset: "0",
YOffset: "0",
idx: "13"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 255,
CustomImage: 0,
Data: "238.311 V",
Description: "",
Favorite: 0,
HardwareDisabled: false,
HardwareID: 2,
HardwareName: "OpenZWave",
HardwareType: "OpenZWave USB",
HardwareTypeVal: 21,
HaveTimeout: false,
ID: "00000A01",
LastUpdate: "2021-01-31 20:34:56",
Name: "Maison Voltage",
Notifications: "false",
PlanID: "0",
PlanIDs: [
0
],
Protected: false,
ShowNotifications: true,
SignalLevel: "-",
SubType: "Voltage",
Timers: "false",
Type: "General",
TypeImg: "current",
Unit: 1,
Used: 1,
Voltage: 238.311,
XOffset: "0",
YOffset: "0",
idx: "14"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 255,
CustomImage: 0,
Data: "2.3 A",
Description: "",
Favorite: 0,
HardwareDisabled: false,
HardwareID: 2,
HardwareName: "OpenZWave",
HardwareType: "OpenZWave USB",
HardwareTypeVal: 21,
HaveTimeout: false,
ID: "0A01",
LastUpdate: "2021-01-31 20:34:57",
Name: "Maison Intensité",
Notifications: "false",
PlanID: "0",
PlanIDs: [
0
],
Protected: false,
ShowNotifications: true,
SignalLevel: "-",
SubType: "CM113, Electrisave",
Timers: "false",
Type: "Current",
TypeImg: "current",
Unit: 0,
Used: 1,
XOffset: "0",
YOffset: "0",
displaytype: 0,
idx: "15"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 255,
CounterToday: "10.276 kWh",
CustomImage: 0,
Data: "4443.043 kWh",
Description: "",
EnergyMeterMode: "",
Favorite: 0,
HardwareDisabled: false,
HardwareID: 5,
HardwareName: "EDF Heures Creuses",
HardwareType: "Dummy (Does nothing, use for virtual switches only)",
HardwareTypeVal: 15,
HaveTimeout: false,
ID: "00082051",
LastUpdate: "2021-01-31 20:34:57",
Name: "Compteur Electrique HC",
Notifications: "false",
PlanID: "0",
PlanIDs: [
0
],
Protected: false,
ShowNotifications: true,
SignalLevel: "-",
SubType: "kWh",
SwitchTypeVal: 0,
Timers: "false",
Type: "General",
TypeImg: "current",
Unit: 1,
Usage: "0 Watt",
Used: 1,
XOffset: "0",
YOffset: "0",
idx: "51"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 255,
CounterToday: "17.864 kWh",
CustomImage: 0,
Data: "8322.349 kWh",
Description: "",
EnergyMeterMode: "",
Favorite: 0,
HardwareDisabled: false,
HardwareID: 6,
HardwareName: "EDF Heures Pleines",
HardwareType: "Dummy (Does nothing, use for virtual switches only)",
HardwareTypeVal: 15,
HaveTimeout: false,
ID: "00082050",
LastUpdate: "2021-01-31 20:34:57",
Name: "Compteur Electrique HP",
Notifications: "false",
PlanID: "0",
PlanIDs: [
0
],
Protected: false,
ShowNotifications: true,
SignalLevel: "-",
SubType: "kWh",
SwitchTypeVal: 0,
Timers: "false",
Type: "General",
TypeImg: "current",
Unit: 1,
Usage: "364.538 Watt",
Used: 1,
XOffset: "0",
YOffset: "0",
idx: "50"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
Barometer: 988.3,
BatteryLevel: 255,
CustomImage: 0,
Data: "16.0 C, 60 %, 988.3 hPa",
Description: "",
DewPoint: "8.24",
Favorite: 0,
Forecast: 2,
ForecastStr: "Heavy Rain",
HardwareDisabled: false,
HardwareID: 3,
HardwareName: "Netatmo",
HardwareType: "Netatmo",
HardwareTypeVal: 54,
HaveTimeout: false,
Humidity: 60,
HumidityStatus: "Comfortable",
ID: "B25C",
LastUpdate: "2021-01-31 20:26:23",
Name: "Température Intérieure",
Notifications: "false",
PlanID: "0",
PlanIDs: [
0
],
Protected: false,
ShowNotifications: true,
SignalLevel: 7,
SubType: "Weather Station",
Temp: 16,
Timers: "false",
Type: "Temp + Humidity + Baro",
TypeImg: "temperature",
Unit: 92,
Used: 1,
XOffset: "0",
YOffset: "0",
idx: "30",
trend: 3
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 81,
CustomImage: 0,
Data: "9.6 C, 95 %",
Description: "",
DewPoint: "8.84",
Favorite: 0,
HardwareDisabled: false,
HardwareID: 3,
HardwareName: "Netatmo",
HardwareType: "Netatmo",
HardwareTypeVal: 54,
HaveTimeout: false,
Humidity: 95,
HumidityStatus: "Wet",
ID: "6721",
LastUpdate: "2021-01-31 20:26:23",
Name: "Température Extérieure",
Notifications: "false",
PlanID: "0",
PlanIDs: [
0
],
Protected: false,
ShowNotifications: true,
SignalLevel: 5,
SubType: "WTGR800",
Temp: 9.6,
Timers: "false",
Type: "Temp + Humidity",
TypeImg: "temperature",
Unit: 0,
Used: 1,
XOffset: "0",
YOffset: "0",
idx: "29",
trend: 3
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 255,
CustomImage: 0,
Data: "459 ppm",
Description: "",
Favorite: 0,
HardwareDisabled: false,
HardwareID: 3,
HardwareName: "Netatmo",
HardwareType: "Netatmo",
HardwareTypeVal: 54,
HaveTimeout: false,
ID: "00B2",
LastUpdate: "2021-01-31 20:26:23",
Name: "Qualité de l'Air Intérieur",
Notifications: "false",
PlanID: "0",
PlanIDs: [
0
],
Protected: false,
Quality: "Excellent",
ShowNotifications: true,
SignalLevel: "-",
SubType: "Voltcraft CO-20",
Timers: "false",
Type: "Air Quality",
TypeImg: "air",
Unit: 92,
Used: 1,
XOffset: "0",
YOffset: "0",
idx: "31"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 255,
CustomImage: 0,
Data: "35 dB",
Description: "",
Favorite: 0,
HardwareDisabled: false,
HardwareID: 3,
HardwareName: "Netatmo",
HardwareType: "Netatmo",
HardwareTypeVal: 54,
HaveTimeout: false,
ID: "A253B25C",
LastUpdate: "2021-01-31 20:26:23",
Name: "Bruit Intérieur",
Notifications: "false",
PlanID: "0",
PlanIDs: [
0
],
Protected: false,
ShowNotifications: true,
SignalLevel: "-",
SubType: "Sound Level",
Timers: "false",
Type: "General",
TypeImg: "Speaker",
Unit: 1,
Used: 1,
XOffset: "0",
YOffset: "0",
idx: "32"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 255,
CustomImage: 1,
Data: "Off",
Description: "",
DimmerType: "none",
Favorite: 0,
HardwareDisabled: false,
HardwareID: 5,
HardwareName: "EDF Heures Creuses",
HardwareType: "Dummy (Does nothing, use for virtual switches only)",
HardwareTypeVal: 15,
HaveDimmer: false,
HaveGroupCmd: true,
HaveTimeout: false,
ID: "65",
Image: "WallSocket",
IsSubDevice: false,
LastUpdate: "2021-01-31 07:00:26",
Level: 0,
LevelInt: 0,
MaxDimLevel: 0,
Name: "EDF Heures Creuses",
Notifications: "false",
PlanID: "0",
PlanIDs: [
0
],
Protected: false,
ShowNotifications: true,
SignalLevel: "-",
Status: "Off",
StrParam1: "",
StrParam2: "",
SubType: "X10",
SwitchType: "On/Off",
SwitchTypeVal: 0,
Timers: "true",
Type: "Lighting 1",
TypeImg: "lightbulb",
Unit: 1,
Used: 1,
UsedByCamera: false,
XOffset: "0",
YOffset: "0",
idx: "52"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 255,
CustomImage: 1,
Data: "On",
Description: "",
DimmerType: "none",
Favorite: 0,
HardwareDisabled: false,
HardwareID: 6,
HardwareName: "EDF Heures Pleines",
HardwareType: "Dummy (Does nothing, use for virtual switches only)",
HardwareTypeVal: 15,
HaveDimmer: false,
HaveGroupCmd: true,
HaveTimeout: false,
ID: "65",
Image: "WallSocket",
IsSubDevice: false,
LastUpdate: "2021-01-31 07:00:26",
Level: 0,
LevelInt: 0,
MaxDimLevel: 0,
Name: "EDF Heures Pleines",
Notifications: "false",
PlanID: "0",
PlanIDs: [
0
],
Protected: false,
ShowNotifications: true,
SignalLevel: "-",
Status: "On",
StrParam1: "",
StrParam2: "",
SubType: "X10",
SwitchType: "On/Off",
SwitchTypeVal: 0,
Timers: "true",
Type: "Lighting 1",
TypeImg: "lightbulb",
Unit: 1,
Used: 1,
UsedByCamera: false,
XOffset: "0",
YOffset: "0",
idx: "53"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 255,
CustomImage: 0,
Data: "1926.86 €",
Description: "",
Favorite: 0,
HardwareDisabled: false,
HardwareID: 7,
HardwareName: "EDF Montant",
HardwareType: "Dummy (Does nothing, use for virtual switches only)",
HardwareTypeVal: 15,
HaveTimeout: false,
ID: "00082054",
Image: "Custom",
LastUpdate: "2021-01-31 20:34:57",
Name: "EDF Montant",
Notifications: "false",
PlanID: "0",
PlanIDs: [
0
],
Protected: false,
SensorType: 1,
SensorUnit: "€",
ShowNotifications: true,
SignalLevel: "-",
SubType: "Custom Sensor",
Timers: "false",
Type: "General",
TypeImg: "Custom",
Unit: 1,
Used: 1,
XOffset: "0",
YOffset: "0",
idx: "54"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 1,
AddjValue2: 0,
BatteryLevel: 255,
CustomImage: 19,
Data: "Off",
Description: "",
DimmerType: "none",
Favorite: 0,
HardwareDisabled: false,
HardwareID: 8,
HardwareName: "Camera",
HardwareType: "Dummy (Does nothing, use for virtual switches only)",
HardwareTypeVal: 15,
HaveDimmer: false,
HaveGroupCmd: true,
HaveTimeout: false,
ID: "65",
Image: "Sun",
IsSubDevice: false,
LastUpdate: "2021-01-26 12:02:28",
Level: 0,
LevelInt: 0,
MaxDimLevel: 0,
Name: "Camera Entree",
Notifications: "false",
PlanID: "0",
PlanIDs: [
0
],
Protected: false,
ShowNotifications: true,
SignalLevel: "-",
Status: "Off",
StrParam1: "",
StrParam2: "",
SubType: "X10",
SwitchType: "On/Off",
SwitchTypeVal: 0,
Timers: "false",
Type: "Lighting 1",
TypeImg: "lightbulb",
Unit: 1,
Used: 1,
UsedByCamera: false,
XOffset: "0",
YOffset: "0",
idx: "66"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
Barometer: 991,
BatteryLevel: 255,
CustomImage: 0,
Data: "8.9 C, 94 %, 991 hPa",
Description: "",
DewPoint: "7.99",
Favorite: 0,
Forecast: 4,
ForecastStr: "Rain",
HardwareDisabled: false,
HardwareID: 9,
HardwareName: "Météo",
HardwareType: "DarkSky (Weather Lookup)",
HardwareTypeVal: 25,
HaveTimeout: false,
Humidity: 94,
HumidityStatus: "Wet",
ID: "0001",
LastUpdate: "2021-01-31 20:34:05",
Name: "THB",
Notifications: "false",
PlanID: "0",
PlanIDs: [
0
],
Protected: false,
ShowNotifications: true,
SignalLevel: "-",
SubType: "THB1 - BTHR918, BTHGN129",
Temp: 8.9,
Timers: "false",
Type: "Temp + Humidity + Baro",
TypeImg: "temperature",
Unit: 1,
Used: 1,
XOffset: "0",
YOffset: "0",
forecast_url: "aHR0cHM6Ly9kYXJrc2t5Lm5ldC8jL2YvNDguNjA3NTQ3JTJDMS42MzkwOTY=",
idx: "73",
trend: 2
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 255,
Chill: 6.4,
CustomImage: 0,
Data: "203.00;SSW;46;93;8.9;6.4",
Description: "",
Direction: 203,
DirectionStr: "SSW",
Favorite: 0,
Gust: "9.3",
HardwareDisabled: false,
HardwareID: 9,
HardwareName: "Météo",
HardwareType: "DarkSky (Weather Lookup)",
HardwareTypeVal: 25,
HaveTimeout: false,
ID: "0001",
LastUpdate: "2021-01-31 20:34:05",
Name: "Température",
Notifications: "false",
PlanID: "0",
PlanIDs: [
0
],
Protected: false,
ShowNotifications: true,
SignalLevel: "-",
Speed: "4.6",
SubType: "TFA",
Temp: 8.9,
Timers: "false",
Type: "Wind",
TypeImg: "wind",
Unit: 0,
Used: 1,
XOffset: "0",
YOffset: "0",
forecast_url: "aHR0cHM6Ly9kYXJrc2t5Lm5ldC8jL2YvNDguNjA3NTQ3JTJDMS42MzkwOTY=",
idx: "74",
trend: 2
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 255,
CustomImage: 0,
Data: "0.0 UVI",
Description: "",
Favorite: 0,
HardwareDisabled: false,
HardwareID: 9,
HardwareName: "Météo",
HardwareType: "DarkSky (Weather Lookup)",
HardwareTypeVal: 25,
HaveTimeout: false,
ID: "0001",
LastUpdate: "2021-01-31 20:34:05",
Name: "UV Index",
Notifications: "false",
PlanID: "0",
PlanIDs: [
0
],
Protected: false,
ShowNotifications: true,
SignalLevel: "-",
SubType: "UVN128,UV138",
Timers: "false",
Type: "UV",
TypeImg: "uv",
UVI: "0.0",
Unit: 0,
Used: 1,
XOffset: "0",
YOffset: "0",
forecast_url: "aHR0cHM6Ly9kYXJrc2t5Lm5ldC8jL2YvNDguNjA3NTQ3JTJDMS42MzkwOTY=",
idx: "75"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 255,
CustomImage: 0,
Data: "330 DU",
Description: "",
Favorite: 0,
HardwareDisabled: false,
HardwareID: 9,
HardwareName: "Météo",
HardwareType: "DarkSky (Weather Lookup)",
HardwareTypeVal: 25,
HaveTimeout: false,
ID: "00000100",
Image: "Custom",
LastUpdate: "2021-01-31 20:34:05",
Name: "Ozone Sensor",
Notifications: "false",
PlanID: "0",
PlanIDs: [
0
],
Protected: false,
SensorType: 1,
SensorUnit: "DU",
ShowNotifications: true,
SignalLevel: "-",
SubType: "Custom Sensor",
Timers: "false",
Type: "General",
TypeImg: "Custom",
Unit: 1,
Used: 1,
XOffset: "0",
YOffset: "0",
forecast_url: "aHR0cHM6Ly9kYXJrc2t5Lm5ldC8jL2YvNDguNjA3NTQ3JTJDMS42MzkwOTY=",
idx: "78"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 255,
CustomImage: 0,
Data: "10846;4.2",
Description: "",
Favorite: 0,
HardwareDisabled: false,
HardwareID: 9,
HardwareName: "Météo",
HardwareType: "DarkSky (Weather Lookup)",
HardwareTypeVal: 25,
HaveTimeout: false,
ID: "0001",
LastUpdate: "2021-01-31 20:34:05",
Name: "Pluie",
Notifications: "false",
PlanID: "0",
PlanIDs: [
0
],
Protected: false,
Rain: "4.1",
RainRate: "1.0795",
ShowNotifications: true,
SignalLevel: "-",
SubType: "RainByRate",
Timers: "false",
Type: "Rain",
TypeImg: "rain",
Unit: 0,
Used: 1,
XOffset: "0",
YOffset: "0",
forecast_url: "aHR0cHM6Ly9kYXJrc2t5Lm5ldC8jL2YvNDguNjA3NTQ3JTJDMS42MzkwOTY=",
idx: "79"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 90,
CustomImage: 0,
Data: "On",
Description: "",
DimmerType: "none",
Favorite: 0,
HardwareDisabled: false,
HardwareID: 2,
HardwareName: "OpenZWave",
HardwareType: "OpenZWave USB",
HardwareTypeVal: 21,
HaveDimmer: true,
HaveGroupCmd: true,
HaveTimeout: false,
ID: "00000300",
Image: "Light",
IsSubDevice: false,
LastUpdate: "2021-01-31 13:57:52",
Level: 255,
LevelInt: 255,
MaxDimLevel: 100,
Name: "Détecteur Inondation Piscine",
Notifications: "true",
PlanID: "0",
PlanIDs: [
0
],
Protected: false,
ShowNotifications: true,
SignalLevel: "-",
Status: "On",
StrParam1: "",
StrParam2: "",
SubType: "Switch",
SwitchType: "Smoke Detector",
SwitchTypeVal: 5,
Timers: "false",
Type: "Light/Switch",
TypeImg: "smoke",
Unit: 1,
Used: 1,
UsedByCamera: false,
XOffset: "0",
YOffset: "0",
idx: "123"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 255,
CounterToday: "0.090 kWh",
CustomImage: 0,
Data: "824.670 kWh",
Description: "",
EnergyMeterMode: "0",
Favorite: 0,
HardwareDisabled: false,
HardwareID: 2,
HardwareName: "OpenZWave",
HardwareType: "OpenZWave USB",
HardwareTypeVal: 21,
HaveTimeout: false,
ID: "00000701",
LastUpdate: "2021-01-31 20:34:34",
Name: "kWh Meter Lampadaire",
Notifications: "false",
PlanID: "0",
PlanIDs: [
0
],
Protected: false,
ShowNotifications: true,
SignalLevel: "-",
SubType: "kWh",
SwitchTypeVal: 0,
Timers: "false",
Type: "General",
TypeImg: "current",
Unit: 1,
Usage: "8.73 Watt",
Used: 1,
XOffset: "0",
YOffset: "0",
idx: "143"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 255,
CustomImage: 0,
Data: "8.7 Watt",
Description: "",
Favorite: 0,
HardwareDisabled: false,
HardwareID: 2,
HardwareName: "OpenZWave",
HardwareType: "OpenZWave USB",
HardwareTypeVal: 21,
HaveTimeout: false,
ID: "0000701",
LastUpdate: "2021-01-31 20:24:35",
Name: "Consommation Lampadaire",
Notifications: "false",
PlanID: "0",
PlanIDs: [
0
],
Protected: false,
ShowNotifications: true,
SignalLevel: "-",
SubType: "Electric",
Timers: "false",
Type: "Usage",
TypeImg: "current",
Unit: 2,
Used: 1,
XOffset: "0",
YOffset: "0",
idx: "144"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 255,
CustomImage: 0,
Data: "235.3 V",
Description: "",
Favorite: 0,
HardwareDisabled: false,
HardwareID: 2,
HardwareName: "OpenZWave",
HardwareType: "OpenZWave USB",
HardwareTypeVal: 21,
HaveTimeout: false,
ID: "00000701",
LastUpdate: "2021-01-31 20:29:35",
Name: "Voltage Lampadaire",
Notifications: "false",
PlanID: "0",
PlanIDs: [
0
],
Protected: false,
ShowNotifications: true,
SignalLevel: "-",
SubType: "Voltage",
Timers: "false",
Type: "General",
TypeImg: "current",
Unit: 1,
Used: 1,
Voltage: 235.3,
XOffset: "0",
YOffset: "0",
idx: "145"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 255,
CustomImage: 0,
Data: "0.1 A",
Description: "",
Favorite: 0,
HardwareDisabled: false,
HardwareID: 2,
HardwareName: "OpenZWave",
HardwareType: "OpenZWave USB",
HardwareTypeVal: 21,
HaveTimeout: false,
ID: "0701",
LastUpdate: "2021-01-31 20:24:36",
Name: "Intensité Lampadaire",
Notifications: "false",
PlanID: "0",
PlanIDs: [
0
],
Protected: false,
ShowNotifications: true,
SignalLevel: "-",
SubType: "CM113, Electrisave",
Timers: "false",
Type: "Current",
TypeImg: "current",
Unit: 0,
Used: 1,
XOffset: "0",
YOffset: "0",
displaytype: 0,
idx: "146"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 255,
CustomImage: 0,
Data: "0 Watt",
Description: "",
Favorite: 0,
HardwareDisabled: false,
HardwareID: 2,
HardwareName: "OpenZWave",
HardwareType: "OpenZWave USB",
HardwareTypeVal: 21,
HaveTimeout: false,
ID: "0000804",
LastUpdate: "2021-01-31 20:33:33",
Name: "Consommation Piscine",
Notifications: "false",
PlanID: "0",
PlanIDs: [
0
],
Protected: false,
ShowNotifications: true,
SignalLevel: "-",
SubType: "Electric",
Timers: "false",
Type: "Usage",
TypeImg: "current",
Unit: 2,
Used: 1,
XOffset: "0",
YOffset: "0",
idx: "154"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 255,
CounterToday: "0.000 kWh",
CustomImage: 0,
Data: "1176.050 kWh",
Description: "",
EnergyMeterMode: "",
Favorite: 0,
HardwareDisabled: false,
HardwareID: 2,
HardwareName: "OpenZWave",
HardwareType: "OpenZWave USB",
HardwareTypeVal: 21,
HaveTimeout: false,
ID: "00000801",
LastUpdate: "2021-01-31 20:33:33",
Name: "kWh Meter Piscine",
Notifications: "false",
PlanID: "0",
PlanIDs: [
0
],
Protected: false,
ShowNotifications: true,
SignalLevel: "-",
SubType: "kWh",
SwitchTypeVal: 0,
Timers: "false",
Type: "General",
TypeImg: "current",
Unit: 1,
Usage: "0 Watt",
Used: 1,
XOffset: "0",
YOffset: "0",
idx: "155"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 92,
CustomImage: 0,
Data: "0 Lux",
Description: "",
Favorite: 0,
HardwareDisabled: false,
HardwareID: 2,
HardwareName: "OpenZWave",
HardwareType: "OpenZWave USB",
HardwareTypeVal: 21,
HaveTimeout: true,
ID: "0000903",
LastUpdate: "2021-01-26 11:55:58",
Name: "Illuminance Bas",
Notifications: "false",
PlanID: "0",
PlanIDs: [
0
],
Protected: false,
ShowNotifications: true,
SignalLevel: "-",
SubType: "Lux",
Timers: "false",
Type: "Lux",
TypeImg: "lux",
Unit: 255,
Used: 1,
XOffset: "0",
YOffset: "0",
idx: "161"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 92,
CustomImage: 0,
Data: "16.2 C",
Description: "",
Favorite: 0,
HardwareDisabled: false,
HardwareID: 2,
HardwareName: "OpenZWave",
HardwareType: "OpenZWave USB",
HardwareTypeVal: 21,
HaveTimeout: true,
ID: "0901",
LastUpdate: "2021-01-29 08:16:40",
Name: "Temperature Bas IR",
Notifications: "false",
PlanID: "0",
PlanIDs: [
0
],
Protected: false,
ShowNotifications: true,
SignalLevel: "-",
SubType: "LaCrosse TX3",
Temp: 16.2,
Timers: "false",
Type: "Temp",
TypeImg: "temperature",
Unit: 1,
Used: 1,
XOffset: "0",
YOffset: "0",
idx: "162",
trend: 3
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 100,
CustomImage: 0,
Data: "0 Lux",
Description: "",
Favorite: 0,
HardwareDisabled: false,
HardwareID: 2,
HardwareName: "OpenZWave",
HardwareType: "OpenZWave USB",
HardwareTypeVal: 21,
HaveTimeout: true,
ID: "0000B03",
LastUpdate: "2021-01-18 23:32:51",
Name: "Illuminance Haut",
Notifications: "false",
PlanID: "0",
PlanIDs: [
0
],
Protected: false,
ShowNotifications: true,
SignalLevel: "-",
SubType: "Lux",
Timers: "false",
Type: "Lux",
TypeImg: "lux",
Unit: 255,
Used: 1,
XOffset: "0",
YOffset: "0",
idx: "169"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 100,
CustomImage: 0,
Data: "16.6 C",
Description: "",
Favorite: 0,
HardwareDisabled: false,
HardwareID: 2,
HardwareName: "OpenZWave",
HardwareType: "OpenZWave USB",
HardwareTypeVal: 21,
HaveTimeout: true,
ID: "0B01",
LastUpdate: "2021-01-31 16:30:12",
Name: "Temperature Haut",
Notifications: "false",
PlanID: "0",
PlanIDs: [
0
],
Protected: false,
ShowNotifications: true,
SignalLevel: "-",
SubType: "LaCrosse TX3",
Temp: 16.6,
Timers: "false",
Type: "Temp",
TypeImg: "temperature",
Unit: 1,
Used: 1,
XOffset: "0",
YOffset: "0",
idx: "171",
trend: 2
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 255,
CustomImage: 0,
Data: "Off",
Description: "",
DimmerType: "none",
Favorite: 0,
HardwareDisabled: false,
HardwareID: 2,
HardwareName: "OpenZWave",
HardwareType: "OpenZWave USB",
HardwareTypeVal: 21,
HaveDimmer: true,
HaveGroupCmd: true,
HaveTimeout: false,
ID: "00000C02",
Image: "Push",
InternalState: "Off",
IsSubDevice: false,
LastUpdate: "2020-12-21 09:27:08",
Level: 0,
LevelInt: 0,
MaxDimLevel: 100,
Name: "Portail",
Notifications: "true",
PlanID: "0",
PlanIDs: [
0
],
Protected: false,
ShowNotifications: true,
SignalLevel: "-",
Status: "",
StrParam1: "",
StrParam2: "",
SubType: "Switch",
SwitchType: "Push On Button",
SwitchTypeVal: 9,
Timers: "false",
Type: "Light/Switch",
TypeImg: "push",
Unit: 1,
Used: 1,
UsedByCamera: false,
XOffset: "0",
YOffset: "0",
idx: "176"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 88,
CustomImage: 0,
Data: "18.9 C, 52 %",
Description: "",
DewPoint: "8.83",
Favorite: 0,
HardwareDisabled: false,
HardwareID: 2,
HardwareName: "OpenZWave",
HardwareType: "OpenZWave USB",
HardwareTypeVal: 21,
HaveTimeout: false,
Humidity: 52,
HumidityStatus: "Comfortable",
ID: "0D01",
LastUpdate: "2021-01-31 20:18:30",
Name: "TempHum Cellier",
Notifications: "false",
PlanID: "0",
PlanIDs: [
0
],
Protected: false,
ShowNotifications: true,
SignalLevel: "-",
SubType: "WTGR800",
Temp: 18.9,
Timers: "false",
Type: "Temp + Humidity",
TypeImg: "temperature",
Unit: 0,
Used: 1,
XOffset: "0",
YOffset: "0",
idx: "185",
trend: 1
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 255,
CustomImage: 0,
Data: "On",
Description: "",
DimmerType: "none",
Favorite: 0,
HardwareDisabled: false,
HardwareID: 10,
HardwareName: "Dummy iPhone",
HardwareType: "Dummy (Does nothing, use for virtual switches only)",
HardwareTypeVal: 15,
HaveDimmer: false,
HaveGroupCmd: true,
HaveTimeout: false,
ID: "80",
Image: "Light",
IsSubDevice: false,
LastUpdate: "2021-01-24 18:48:26",
Level: 0,
LevelInt: 0,
MaxDimLevel: 0,
Name: "Mon iPhone",
Notifications: "true",
PlanID: "0",
PlanIDs: [
0
],
Protected: false,
ShowNotifications: true,
SignalLevel: "-",
Status: "On",
StrParam1: "",
StrParam2: "",
SubType: "X10",
SwitchType: "On/Off",
SwitchTypeVal: 0,
Timers: "false",
Type: "Lighting 1",
TypeImg: "lightbulb",
Unit: 16,
Used: 1,
UsedByCamera: false,
XOffset: "0",
YOffset: "0",
idx: "207"
}
],
status: "OK",
title: "Devices"
});