exports.DOMOTICZ_GET_DEVICES = JSON.stringify({
		ActTime: 1565604967,
		AstrTwilightEnd: "22:54",
		AstrTwilightStart: "04:37",
		CivTwilightEnd: "21:27",
		CivTwilightStart: "06:04",
		DayLength: "14:18",
		NautTwilightEnd: "22:08",
		NautTwilightStart: "05:23",
		ServerTime: "2019-08-12 12:16:07",
		SunAtSouth: "13:46",
		Sunrise: "06:37",
		Sunset: "20:55",
		app_version: "4.10717",
		result: [
		{
		AddjMulti: 1,
		AddjMulti2: 1,
		AddjValue: 0,
		AddjValue2: 0,
		BatteryLevel: 255,
		CustomImage: 0,
		Data: "Open",
		Description: "",
		DimmerType: "none",
		Favorite: 1,
		HardwareID: 4,
		HardwareName: "RFX",
		HardwareType: "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
		HardwareTypeVal: 1,
		HaveDimmer: false,
		HaveGroupCmd: false,
		HaveTimeout: false,
		ID: "000000",
		Image: "Light",
		IsSubDevice: false,
		LastUpdate: "2019-08-12 08:29:57",
		Level: 0,
		LevelInt: 0,
		MaxDimLevel: 0,
		Name: "Salon",
		Notifications: "false",
		PlanID: "2",
		PlanIDs: [
		2
		],
		Protected: false,
		ShowNotifications: true,
		SignalLevel: "-",
		Status: "Open",
		StrParam1: "",
		StrParam2: "",
		SubType: "RFY",
		SwitchType: "Blinds",
		SwitchTypeVal: 3,
		Timers: "false",
		Type: "RFY",
		TypeImg: "blinds",
		Unit: 1,
		Used: 1,
		UsedByCamera: false,
		XOffset: "0",
		YOffset: "0",
		idx: "8"
		},
		{
		AddjMulti: 1,
		AddjMulti2: 1,
		AddjValue: 0,
		AddjValue2: 0,
		BatteryLevel: 255,
		CustomImage: 0,
		Data: "Open",
		Description: "",
		DimmerType: "none",
		Favorite: 1,
		HardwareID: 4,
		HardwareName: "RFX",
		HardwareType: "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
		HardwareTypeVal: 1,
		HaveDimmer: false,
		HaveGroupCmd: false,
		HaveTimeout: false,
		ID: "010000",
		Image: "Light",
		IsSubDevice: false,
		LastUpdate: "2019-08-12 09:39:26",
		Level: 0,
		LevelInt: 0,
		MaxDimLevel: 0,
		Name: "Chambre",
		Notifications: "false",
		PlanID: "2",
		PlanIDs: [
		2
		],
		Protected: false,
		ShowNotifications: true,
		SignalLevel: "-",
		Status: "Open",
		StrParam1: "",
		StrParam2: "",
		SubType: "RFY",
		SwitchType: "Blinds",
		SwitchTypeVal: 3,
		Timers: "false",
		Type: "RFY",
		TypeImg: "blinds",
		Unit: 1,
		Used: 1,
		UsedByCamera: false,
		XOffset: "0",
		YOffset: "0",
		idx: "9"
		},
		{
		AddjMulti: 1,
		AddjMulti2: 1,
		AddjValue: 0,
		AddjValue2: 0,
		BatteryLevel: 255,
		CustomImage: 0,
		Data: "Open",
		Description: "",
		DimmerType: "none",
		Favorite: 1,
		HardwareID: 4,
		HardwareName: "RFX",
		HardwareType: "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
		HardwareTypeVal: 1,
		HaveDimmer: false,
		HaveGroupCmd: false,
		HaveTimeout: false,
		ID: "020000",
		Image: "Light",
		IsSubDevice: false,
		LastUpdate: "2019-08-12 09:05:15",
		Level: 0,
		LevelInt: 0,
		MaxDimLevel: 0,
		Name: "Chambre Mael",
		Notifications: "false",
		PlanID: "2",
		PlanIDs: [
		2
		],
		Protected: false,
		ShowNotifications: true,
		SignalLevel: "-",
		Status: "Open",
		StrParam1: "",
		StrParam2: "",
		SubType: "RFY",
		SwitchType: "Blinds",
		SwitchTypeVal: 3,
		Timers: "false",
		Type: "RFY",
		TypeImg: "blinds",
		Unit: 1,
		Used: 1,
		UsedByCamera: false,
		XOffset: "0",
		YOffset: "0",
		idx: "10"
		}
		],
		status: "OK",
		title: "Devices"
});