exports.DOMOTICZ_GET_DEVICES = JSON.stringify({
"ActTime" : 1546031508,
"AstrTwilightEnd" : "18:52",
"AstrTwilightStart" : "06:33",
"CivTwilightEnd" : "17:38",
"CivTwilightStart" : "07:47",
"DayLength" : "08:43",
"NautTwilightEnd" : "18:16",
"NautTwilightStart" : "07:09",
"ServerTime" : "2018-12-28 22:11:48",
"SunAtSouth" : "12:05",
"Sunrise" : "08:21",
"Sunset" : "17:04",
"app_version" : "4.9700",
"result" : [
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 0.0,
"AddjValue2" : 0.0,
"BatteryLevel" : 77,
"CustomImage" : 0,
"Data" : "Closed",
"Description" : "",
"DimmerType" : "none",
"Favorite" : 0,
"HardwareID" : 2,
"HardwareName" : "Xiaomi Gateway",
"HardwareType" : "Xiaomi Gateway",
"HardwareTypeVal" : 95,
"HaveDimmer" : true,
"HaveGroupCmd" : true,
"HaveTimeout" : false,
"ID" : "016C7A5A",
"Image" : "Light",
"InternalState" : "Closed",
"IsSubDevice" : false,
"LastUpdate" : "2018-08-19 02:10:38",
"Level" : 0,
"LevelInt" : 0,
"MaxDimLevel" : 100,
"Name" : "Salon",
"Notifications" : "false",
"PlanID" : "0",
"PlanIDs" : [ 0 ],
"Protected" : false,
"ShowNotifications" : true,
"SignalLevel" : "-",
"Status" : "Closed",
"StrParam1" : "",
"StrParam2" : "",
"SubType" : "Switch",
"SwitchType" : "Door Contact",
"SwitchTypeVal" : 11,
"Timers" : "false",
"Type" : "Light/Switch",
"TypeImg" : "door",
"Unit" : 1,
"Used" : 1,
"UsedByCamera" : false,
"XOffset" : "0",
"YOffset" : "0",
"idx" : "10"
},
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 0.0,
"AddjValue2" : 0.0,
"BatteryLevel" : 80,
"CustomImage" : 0,
"Data" : "Closed",
"Description" : "",
"DimmerType" : "none",
"Favorite" : 0,
"HardwareID" : 2,
"HardwareName" : "Xiaomi Gateway",
"HardwareType" : "Xiaomi Gateway",
"HardwareTypeVal" : 95,
"HaveDimmer" : true,
"HaveGroupCmd" : true,
"HaveTimeout" : false,
"ID" : "01DE883B",
"Image" : "Light",
"InternalState" : "Closed",
"IsSubDevice" : false,
"LastUpdate" : "2018-12-28 15:17:31",
"Level" : 0,
"LevelInt" : 0,
"MaxDimLevel" : 100,
"Name" : "Salon - fenêtre",
"Notifications" : "false",
"PlanID" : "0",
"PlanIDs" : [ 0 ],
"Protected" : false,
"ShowNotifications" : true,
"SignalLevel" : "-",
"Status" : "Closed",
"StrParam1" : "",
"StrParam2" : "",
"SubType" : "Switch",
"SwitchType" : "Door Contact",
"SwitchTypeVal" : 11,
"Timers" : "false",
"Type" : "Light/Switch",
"TypeImg" : "door",
"Unit" : 1,
"Used" : 1,
"UsedByCamera" : false,
"XOffset" : "0",
"YOffset" : "0",
"idx" : "78"
},
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 0.0,
"AddjValue2" : 0.0,
"BatteryLevel" : 81,
"CustomImage" : 0,
"Data" : "Closed",
"Description" : "",
"DimmerType" : "none",
"Favorite" : 0,
"HardwareID" : 2,
"HardwareName" : "Xiaomi Gateway",
"HardwareType" : "Xiaomi Gateway",
"HardwareTypeVal" : 95,
"HaveDimmer" : true,
"HaveGroupCmd" : true,
"HaveTimeout" : false,
"ID" : "016FF6A9",
"Image" : "Light",
"InternalState" : "Closed",
"IsSubDevice" : false,
"LastUpdate" : "2018-12-28 15:26:53",
"Level" : 0,
"LevelInt" : 0,
"MaxDimLevel" : 100,
"Name" : "Porte Fenetre cuisine",
"Notifications" : "false",
"PlanID" : "0",
"PlanIDs" : [ 0 ],
"Protected" : false,
"ShowNotifications" : true,
"SignalLevel" : "-",
"Status" : "Closed",
"StrParam1" : "",
"StrParam2" : "",
"SubType" : "Switch",
"SwitchType" : "Door Contact",
"SwitchTypeVal" : 11,
"Timers" : "false",
"Type" : "Light/Switch",
"TypeImg" : "door",
"Unit" : 1,
"Used" : 1,
"UsedByCamera" : false,
"XOffset" : "0",
"YOffset" : "0",
"idx" : "12"
},
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 0.0,
"AddjValue2" : 0.0,
"BatteryLevel" : 76,
"CustomImage" : 0,
"Data" : "Closed",
"Description" : "",
"DimmerType" : "none",
"Favorite" : 0,
"HardwareID" : 2,
"HardwareName" : "Xiaomi Gateway",
"HardwareType" : "Xiaomi Gateway",
"HardwareTypeVal" : 95,
"HaveDimmer" : true,
"HaveGroupCmd" : true,
"HaveTimeout" : false,
"ID" : "01D3AAE7",
"Image" : "Light",
"InternalState" : "Closed",
"IsSubDevice" : false,
"LastUpdate" : "2018-07-09 18:36:00",
"Level" : 0,
"LevelInt" : 0,
"MaxDimLevel" : 100,
"Name" : "Garage route",
"Notifications" : "false",
"PlanID" : "0",
"PlanIDs" : [ 0 ],
"Protected" : false,
"ShowNotifications" : true,
"SignalLevel" : "-",
"Status" : "Closed",
"StrParam1" : "",
"StrParam2" : "",
"SubType" : "Switch",
"SwitchType" : "Door Contact",
"SwitchTypeVal" : 11,
"Timers" : "false",
"Type" : "Light/Switch",
"TypeImg" : "door",
"Unit" : 1,
"Used" : 1,
"UsedByCamera" : false,
"XOffset" : "0",
"YOffset" : "0",
"idx" : "71"
},
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 0.0,
"AddjValue2" : 0.0,
"BatteryLevel" : 76,
"CustomImage" : 0,
"Data" : "Closed",
"Description" : "",
"DimmerType" : "none",
"Favorite" : 0,
"HardwareID" : 2,
"HardwareName" : "Xiaomi Gateway",
"HardwareType" : "Xiaomi Gateway",
"HardwareTypeVal" : 95,
"HaveDimmer" : true,
"HaveGroupCmd" : true,
"HaveTimeout" : false,
"ID" : "01D3AE2D",
"Image" : "Light",
"InternalState" : "Closed",
"IsSubDevice" : false,
"LastUpdate" : "2018-12-28 17:46:31",
"Level" : 0,
"LevelInt" : 0,
"MaxDimLevel" : 100,
"Name" : "Garage piscine",
"Notifications" : "false",
"PlanID" : "0",
"PlanIDs" : [ 0 ],
"Protected" : false,
"ShowNotifications" : true,
"SignalLevel" : "-",
"Status" : "Closed",
"StrParam1" : "",
"StrParam2" : "",
"SubType" : "Switch",
"SwitchType" : "Door Contact",
"SwitchTypeVal" : 11,
"Timers" : "false",
"Type" : "Light/Switch",
"TypeImg" : "door",
"Unit" : 1,
"Used" : 1,
"UsedByCamera" : false,
"XOffset" : "0",
"YOffset" : "0",
"idx" : "76"
},
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 0.0,
"AddjValue2" : 0.0,
"BatteryLevel" : 80,
"CustomImage" : 0,
"Data" : "Closed",
"Description" : "",
"DimmerType" : "none",
"Favorite" : 0,
"HardwareID" : 2,
"HardwareName" : "Xiaomi Gateway",
"HardwareType" : "Xiaomi Gateway",
"HardwareTypeVal" : 95,
"HaveDimmer" : true,
"HaveGroupCmd" : true,
"HaveTimeout" : false,
"ID" : "02019792",
"Image" : "Light",
"InternalState" : "Closed",
"IsSubDevice" : false,
"LastUpdate" : "2018-12-28 20:39:36",
"Level" : 0,
"LevelInt" : 0,
"MaxDimLevel" : 100,
"Name" : "Entréé",
"Notifications" : "false",
"PlanID" : "0",
"PlanIDs" : [ 0 ],
"Protected" : false,
"ShowNotifications" : true,
"SignalLevel" : "-",
"Status" : "Closed",
"StrParam1" : "",
"StrParam2" : "",
"SubType" : "Switch",
"SwitchType" : "Door Contact",
"SwitchTypeVal" : 11,
"Timers" : "false",
"Type" : "Light/Switch",
"TypeImg" : "door",
"Unit" : 1,
"Used" : 1,
"UsedByCamera" : false,
"XOffset" : "0",
"YOffset" : "0",
"idx" : "99"
},
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 0.0,
"AddjValue2" : 0.0,
"BatteryLevel" : 82,
"CustomImage" : 0,
"Data" : "Closed",
"Description" : "",
"DimmerType" : "none",
"Favorite" : 0,
"HardwareID" : 2,
"HardwareName" : "Xiaomi Gateway",
"HardwareType" : "Xiaomi Gateway",
"HardwareTypeVal" : 95,
"HaveDimmer" : true,
"HaveGroupCmd" : true,
"HaveTimeout" : false,
"ID" : "01FD7BFA",
"Image" : "Light",
"InternalState" : "Closed",
"IsSubDevice" : false,
"LastUpdate" : "2018-12-20 16:16:21",
"Level" : 0,
"LevelInt" : 0,
"MaxDimLevel" : 100,
"Name" : "Chambre Noé - Porte fenêtre",
"Notifications" : "false",
"PlanID" : "0",
"PlanIDs" : [ 0 ],
"Protected" : false,
"ShowNotifications" : true,
"SignalLevel" : "-",
"Status" : "Closed",
"StrParam1" : "",
"StrParam2" : "",
"SubType" : "Switch",
"SwitchType" : "Door Contact",
"SwitchTypeVal" : 11,
"Timers" : "false",
"Type" : "Light/Switch",
"TypeImg" : "door",
"Unit" : 1,
"Used" : 1,
"UsedByCamera" : false,
"XOffset" : "0",
"YOffset" : "0",
"idx" : "101"
},
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 0.0,
"AddjValue2" : 0.0,
"BatteryLevel" : 82,
"CustomImage" : 0,
"Data" : "Closed",
"Description" : "",
"DimmerType" : "none",
"Favorite" : 0,
"HardwareID" : 2,
"HardwareName" : "Xiaomi Gateway",
"HardwareType" : "Xiaomi Gateway",
"HardwareTypeVal" : 95,
"HaveDimmer" : true,
"HaveGroupCmd" : true,
"HaveTimeout" : false,
"ID" : "01FD7BE1",
"Image" : "Light",
"InternalState" : "Closed",
"IsSubDevice" : false,
"LastUpdate" : "2018-12-21 09:49:01",
"Level" : 0,
"LevelInt" : 0,
"MaxDimLevel" : 100,
"Name" : "Chambre bas - Fenêtre",
"Notifications" : "false",
"PlanID" : "0",
"PlanIDs" : [ 0 ],
"Protected" : false,
"ShowNotifications" : true,
"SignalLevel" : "-",
"Status" : "Closed",
"StrParam1" : "",
"StrParam2" : "",
"SubType" : "Switch",
"SwitchType" : "Door Contact",
"SwitchTypeVal" : 11,
"Timers" : "false",
"Type" : "Light/Switch",
"TypeImg" : "door",
"Unit" : 1,
"Used" : 1,
"UsedByCamera" : false,
"XOffset" : "0",
"YOffset" : "0",
"idx" : "103"
},
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 0.0,
"AddjValue2" : 0.0,
"BatteryLevel" : 255,
"Color" : "{\"b\":69,\"cw\":0,\"g\":104,\"m\":3,\"r\":255,\"t\":0,\"ww\":0}",
"CustomImage" : 0,
"Data" : "Off",
"Description" : "",
"DimmerType" : "abs",
"Favorite" : 0,
"HardwareID" : 2,
"HardwareName" : "Xiaomi Gateway",
"HardwareType" : "Xiaomi Gateway",
"HardwareTypeVal" : 95,
"HaveDimmer" : true,
"HaveGroupCmd" : false,
"HaveTimeout" : false,
"ID" : "008DCDFC",
"Image" : "Light",
"IsSubDevice" : false,
"LastUpdate" : "2018-12-14 20:57:49",
"Level" : 78,
"LevelInt" : 78,
"MaxDimLevel" : 100,
"Name" : "Xiaomi Gateway - RGB",
"Notifications" : "false",
"PlanID" : "0",
"PlanIDs" : [ 0 ],
"Protected" : false,
"ShowNotifications" : true,
"SignalLevel" : "-",
"Status" : "Off",
"StrParam1" : "",
"StrParam2" : "",
"SubType" : "RGBW",
"SwitchType" : "Dimmer",
"SwitchTypeVal" : 7,
"Timers" : "false",
"Type" : "Color Switch",
"TypeImg" : "dimmer",
"Unit" : 1,
"Used" : 1,
"UsedByCamera" : false,
"XOffset" : "0",
"YOffset" : "0",
"idx" : "1"
},
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 0.0,
"AddjValue2" : 0.0,
"BatteryLevel" : 255,
"CustomImage" : 8,
"Data" : "Off",
"Description" : "",
"DimmerType" : "abs",
"Favorite" : 0,
"HardwareID" : 2,
"HardwareName" : "Xiaomi Gateway",
"HardwareType" : "Xiaomi Gateway",
"HardwareTypeVal" : 95,
"HaveDimmer" : true,
"HaveGroupCmd" : true,
"HaveTimeout" : false,
"ID" : "008DCDFC",
"Image" : "Speaker",
"IsSubDevice" : false,
"LastUpdate" : "2018-10-24 19:51:00",
"Level" : 50,
"LevelInt" : 50,
"MaxDimLevel" : 100,
"Name" : "Xiaomi Gateway - Volume",
"Notifications" : "false",
"PlanID" : "0",
"PlanIDs" : [ 0 ],
"Protected" : false,
"ShowNotifications" : true,
"SignalLevel" : "-",
"Status" : "Off",
"StrParam1" : "",
"StrParam2" : "",
"SubType" : "Switch",
"SwitchType" : "Dimmer",
"SwitchTypeVal" : 7,
"Timers" : "false",
"Type" : "Light/Switch",
"TypeImg" : "dimmer",
"Unit" : 7,
"Used" : 1,
"UsedByCamera" : false,
"XOffset" : "0",
"YOffset" : "0",
"idx" : "6"
},
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 0.0,
"AddjValue2" : 0.0,
"BatteryLevel" : 255,
"CustomImage" : 9,
"Data" : "On",
"Description" : "",
"DimmerType" : "none",
"Favorite" : 0,
"HardwareID" : 2,
"HardwareName" : "Xiaomi Gateway",
"HardwareType" : "Xiaomi Gateway",
"HardwareTypeVal" : 95,
"HaveDimmer" : true,
"HaveGroupCmd" : true,
"HaveTimeout" : false,
"ID" : "0103A43A",
"Image" : "Generic",
"IsSubDevice" : false,
"LastUpdate" : "2018-12-28 17:19:58",
"Level" : 70,
"LevelActions" : "",
"LevelInt" : 70,
"LevelNames" : "T2ZmfGZsaXA5MHxmbGlwMTgwfG1vdmV8dGFwX3R3aWNlfHNoYWtlX2Fpcnxzd2luZ3xhbGVydHxmcmVlX2ZhbGx8Y2xvY2tfd2lzZXxhbnRpX2Nsb2NrX3dpc2U=",
"LevelOffHidden" : false,
"MaxDimLevel" : 100,
"Name" : "Xiaomi Cube",
"Notifications" : "false",
"PlanID" : "0",
"PlanIDs" : [ 0 ],
"Protected" : false,
"SelectorStyle" : 0,
"ShowNotifications" : true,
"SignalLevel" : "-",
"Status" : "On",
"StrParam1" : "",
"StrParam2" : "",
"SubType" : "Selector Switch",
"SwitchType" : "Selector",
"SwitchTypeVal" : 18,
"Timers" : "false",
"Type" : "Light/Switch",
"TypeImg" : "Light",
"Unit" : 1,
"Used" : 1,
"UsedByCamera" : false,
"XOffset" : "0",
"YOffset" : "0",
"idx" : "30"
},
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 0.0,
"AddjValue2" : 0.0,
"BatteryLevel" : 255,
"CustomImage" : 7,
"Data" : "Off",
"Description" : "",
"DimmerType" : "none",
"Favorite" : 1,
"HardwareID" : 4,
"HardwareName" : "KMTronic",
"HardwareType" : "KMTronic Gateway with LAN interface",
"HardwareTypeVal" : 48,
"HaveDimmer" : true,
"HaveGroupCmd" : true,
"HaveTimeout" : false,
"ID" : "0000001",
"Image" : "Fan",
"IsSubDevice" : false,
"LastUpdate" : "2018-12-28 22:00:10",
"Level" : 0,
"LevelInt" : 0,
"MaxDimLevel" : 15,
"Name" : "VMC",
"Notifications" : "false",
"PlanID" : "0",
"PlanIDs" : [ 0 ],
"Protected" : false,
"ShowNotifications" : true,
"SignalLevel" : "-",
"Status" : "Off",
"StrParam1" : "",
"StrParam2" : "",
"SubType" : "AC",
"SwitchType" : "On/Off",
"SwitchTypeVal" : 0,
"Timers" : "false",
"Type" : "Lighting 2",
"TypeImg" : "lightbulb",
"Unit" : 1,
"Used" : 1,
"UsedByCamera" : false,
"XOffset" : "0",
"YOffset" : "0",
"idx" : "16"
},
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 0.0,
"AddjValue2" : 0.0,
"BatteryLevel" : 255,
"CustomImage" : 16,
"Data" : "Off",
"Description" : "",
"DimmerType" : "none",
"Favorite" : 0,
"HardwareID" : 4,
"HardwareName" : "KMTronic",
"HardwareType" : "KMTronic Gateway with LAN interface",
"HardwareTypeVal" : 48,
"HaveDimmer" : true,
"HaveGroupCmd" : true,
"HaveTimeout" : false,
"ID" : "0000002",
"Image" : "Cooling",
"IsSubDevice" : false,
"LastUpdate" : "2018-09-26 00:17:51",
"Level" : 0,
"LevelInt" : 0,
"MaxDimLevel" : 15,
"Name" : "VMC - Bypass",
"Notifications" : "false",
"PlanID" : "0",
"PlanIDs" : [ 0 ],
"Protected" : false,
"ShowNotifications" : true,
"SignalLevel" : "-",
"Status" : "Off",
"StrParam1" : "",
"StrParam2" : "",
"SubType" : "AC",
"SwitchType" : "On/Off",
"SwitchTypeVal" : 0,
"Timers" : "false",
"Type" : "Lighting 2",
"TypeImg" : "lightbulb",
"Unit" : 1,
"Used" : 1,
"UsedByCamera" : false,
"XOffset" : "0",
"YOffset" : "0",
"idx" : "17"
},
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 0.0,
"AddjValue2" : 0.0,
"BatteryLevel" : 255,
"CustomImage" : 16,
"Data" : "Off",
"Description" : "",
"DimmerType" : "none",
"Favorite" : 0,
"HardwareID" : 5,
"HardwareName" : "Virtual switch 1",
"HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
"HardwareTypeVal" : 15,
"HaveDimmer" : true,
"HaveGroupCmd" : true,
"HaveTimeout" : false,
"ID" : "00014070",
"Image" : "Cooling",
"IsSubDevice" : false,
"LastUpdate" : "2018-09-23 07:57:59",
"Level" : 0,
"LevelInt" : 0,
"MaxDimLevel" : 100,
"Name" : "VMC - Mode été",
"Notifications" : "false",
"PlanID" : "0",
"PlanIDs" : [ 0 ],
"Protected" : false,
"ShowNotifications" : true,
"SignalLevel" : "-",
"Status" : "Off",
"StrParam1" : "",
"StrParam2" : "",
"SubType" : "Switch",
"SwitchType" : "On/Off",
"SwitchTypeVal" : 0,
"Timers" : "false",
"Type" : "Light/Switch",
"TypeImg" : "lightbulb",
"Unit" : 1,
"Used" : 1,
"UsedByCamera" : false,
"XOffset" : "0",
"YOffset" : "0",
"idx" : "32"
},
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 0.0,
"AddjValue2" : 0.0,
"BatteryLevel" : 77,
"CustomImage" : 9,
"Data" : "Off",
"Description" : "",
"DimmerType" : "none",
"Favorite" : 0,
"HardwareID" : 2,
"HardwareName" : "Xiaomi Gateway",
"HardwareType" : "Xiaomi Gateway",
"HardwareTypeVal" : 95,
"HaveDimmer" : true,
"HaveGroupCmd" : true,
"HaveTimeout" : false,
"ID" : "018B3B44",
"Image" : "Generic",
"IsSubDevice" : false,
"LastUpdate" : "2018-12-01 01:18:29",
"Level" : 0,
"LevelActions" : "",
"LevelInt" : 0,
"LevelNames" : "T2ZmfENsaWNrfERvdWJsZSBDbGlja3xMb25nIENsaWNrfExvbmcgQ2xpY2sgUmVsZWFzZQ==",
"LevelOffHidden" : false,
"MaxDimLevel" : 100,
"Name" : "Pool House - Wireless Switch",
"Notifications" : "false",
"PlanID" : "0",
"PlanIDs" : [ 0 ],
"Protected" : false,
"SelectorStyle" : 0,
"ShowNotifications" : true,
"SignalLevel" : "-",
"Status" : "Off",
"StrParam1" : "",
"StrParam2" : "",
"SubType" : "Selector Switch",
"SwitchType" : "Selector",
"SwitchTypeVal" : 18,
"Timers" : "false",
"Type" : "Light/Switch",
"TypeImg" : "Light",
"Unit" : 1,
"Used" : 1,
"UsedByCamera" : false,
"XOffset" : "0",
"YOffset" : "0",
"idx" : "8"
},
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 1.0,
"AddjValue2" : 0.0,
"BatteryLevel" : 255,
"CustomImage" : 0,
"Data" : "Off",
"Description" : "",
"DimmerType" : "none",
"Favorite" : 0,
"HardwareID" : 4,
"HardwareName" : "KMTronic",
"HardwareType" : "KMTronic Gateway with LAN interface",
"HardwareTypeVal" : 48,
"HaveDimmer" : true,
"HaveGroupCmd" : true,
"HaveTimeout" : false,
"ID" : "0000003",
"Image" : "Light",
"InternalState" : "Off",
"IsSubDevice" : false,
"LastUpdate" : "2017-11-22 00:02:54",
"Level" : 0,
"LevelInt" : 0,
"MaxDimLevel" : 15,
"Name" : "Lumière entrée",
"Notifications" : "false",
"PlanID" : "0",
"PlanIDs" : [ 0 ],
"Protected" : false,
"ShowNotifications" : true,
"SignalLevel" : "-",
"Status" : "",
"StrParam1" : "",
"StrParam2" : "",
"SubType" : "AC",
"SwitchType" : "Push On Button",
"SwitchTypeVal" : 9,
"Timers" : "false",
"Type" : "Lighting 2",
"TypeImg" : "push",
"Unit" : 1,
"Used" : 1,
"UsedByCamera" : false,
"XOffset" : "0",
"YOffset" : "0",
"idx" : "18"
},
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 0.0,
"AddjValue2" : 0.0,
"BatteryLevel" : 255,
"CustomImage" : 0,
"Data" : "Off",
"Description" : "",
"DimmerType" : "none",
"Favorite" : 0,
"HardwareID" : 4,
"HardwareName" : "KMTronic",
"HardwareType" : "KMTronic Gateway with LAN interface",
"HardwareTypeVal" : 48,
"HaveDimmer" : true,
"HaveGroupCmd" : true,
"HaveTimeout" : false,
"ID" : "0000005",
"Image" : "Light",
"IsSubDevice" : false,
"LastUpdate" : "2018-12-28 21:10:25",
"Level" : 0,
"LevelInt" : 0,
"MaxDimLevel" : 15,
"Name" : "Terrasse",
"Notifications" : "false",
"PlanID" : "0",
"PlanIDs" : [ 0 ],
"Protected" : false,
"ShowNotifications" : true,
"SignalLevel" : "-",
"Status" : "Off",
"StrParam1" : "",
"StrParam2" : "",
"SubType" : "AC",
"SwitchType" : "On/Off",
"SwitchTypeVal" : 0,
"Timers" : "false",
"Type" : "Lighting 2",
"TypeImg" : "lightbulb",
"Unit" : 1,
"Used" : 1,
"UsedByCamera" : false,
"XOffset" : "0",
"YOffset" : "0",
"idx" : "20"
},
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 0.0,
"AddjValue2" : 0.0,
"BatteryLevel" : 255,
"CustomImage" : 0,
"Data" : "Off",
"Description" : "",
"DimmerType" : "none",
"Favorite" : 0,
"HardwareID" : 4,
"HardwareName" : "KMTronic",
"HardwareType" : "KMTronic Gateway with LAN interface",
"HardwareTypeVal" : 48,
"HaveDimmer" : true,
"HaveGroupCmd" : true,
"HaveTimeout" : false,
"ID" : "0000006",
"Image" : "Light",
"IsSubDevice" : false,
"LastUpdate" : "2018-12-28 20:50:23",
"Level" : 0,
"LevelInt" : 0,
"MaxDimLevel" : 15,
"Name" : "Guirlande",
"Notifications" : "false",
"PlanID" : "0",
"PlanIDs" : [ 0 ],
"Protected" : false,
"ShowNotifications" : true,
"SignalLevel" : "-",
"Status" : "Off",
"StrParam1" : "",
"StrParam2" : "",
"SubType" : "AC",
"SwitchType" : "On/Off",
"SwitchTypeVal" : 0,
"Timers" : "false",
"Type" : "Lighting 2",
"TypeImg" : "lightbulb",
"Unit" : 1,
"Used" : 1,
"UsedByCamera" : false,
"XOffset" : "0",
"YOffset" : "0",
"idx" : "21"
},
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 0.0,
"AddjValue2" : 0.0,
"BatteryLevel" : 255,
"CustomImage" : 7,
"Data" : "Off",
"Description" : "",
"DimmerType" : "none",
"Favorite" : 0,
"HardwareID" : 4,
"HardwareName" : "KMTronic",
"HardwareType" : "KMTronic Gateway with LAN interface",
"HardwareTypeVal" : 48,
"HaveDimmer" : true,
"HaveGroupCmd" : true,
"HaveTimeout" : false,
"ID" : "0000007",
"Image" : "Fan",
"IsSubDevice" : false,
"LastUpdate" : "2018-09-30 11:38:10",
"Level" : 0,
"LevelInt" : 0,
"MaxDimLevel" : 15,
"Name" : "Piscine - Filtration",
"Notifications" : "false",
"PlanID" : "0",
"PlanIDs" : [ 0 ],
"Protected" : false,
"ShowNotifications" : true,
"SignalLevel" : "-",
"Status" : "Off",
"StrParam1" : "",
"StrParam2" : "",
"SubType" : "AC",
"SwitchType" : "On/Off",
"SwitchTypeVal" : 0,
"Timers" : "false",
"Type" : "Lighting 2",
"TypeImg" : "lightbulb",
"Unit" : 1,
"Used" : 1,
"UsedByCamera" : false,
"XOffset" : "0",
"YOffset" : "0",
"idx" : "22"
},
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 0.0,
"AddjValue2" : 0.0,
"BatteryLevel" : 255,
"CustomImage" : 0,
"Data" : "Off",
"Description" : "",
"DimmerType" : "none",
"Favorite" : 0,
"HardwareID" : 4,
"HardwareName" : "KMTronic",
"HardwareType" : "KMTronic Gateway with LAN interface",
"HardwareTypeVal" : 48,
"HaveDimmer" : true,
"HaveGroupCmd" : true,
"HaveTimeout" : false,
"ID" : "0000008",
"Image" : "Light",
"IsSubDevice" : false,
"LastUpdate" : "2018-12-28 14:20:05",
"Level" : 0,
"LevelInt" : 0,
"MaxDimLevel" : 15,
"Name" : "Piscine",
"Notifications" : "false",
"PlanID" : "0",
"PlanIDs" : [ 0 ],
"Protected" : false,
"ShowNotifications" : true,
"SignalLevel" : "-",
"Status" : "Off",
"StrParam1" : "",
"StrParam2" : "",
"SubType" : "AC",
"SwitchType" : "On/Off",
"SwitchTypeVal" : 0,
"Timers" : "false",
"Type" : "Lighting 2",
"TypeImg" : "lightbulb",
"Unit" : 1,
"Used" : 1,
"UsedByCamera" : false,
"XOffset" : "0",
"YOffset" : "0",
"idx" : "23"
},
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 0.0,
"AddjValue2" : 0.0,
"BatteryLevel" : 73,
"CustomImage" : 0,
"Data" : "1002.0 Bar",
"Description" : "",
"Favorite" : 0,
"HardwareID" : 2,
"HardwareName" : "Xiaomi Gateway",
"HardwareType" : "Xiaomi Gateway",
"HardwareTypeVal" : 95,
"HaveTimeout" : false,
"ID" : "AB3B3B01",
"LastUpdate" : "2018-12-28 21:58:17",
"Name" : "Pression exterieure",
"Notifications" : "false",
"PlanID" : "0",
"PlanIDs" : [ 0 ],
"Pressure" : 1002.0,
"Protected" : false,
"ShowNotifications" : true,
"SignalLevel" : "-",
"SubType" : "Pressure",
"Timers" : "false",
"Type" : "General",
"TypeImg" : "gauge",
"Unit" : 1,
"Used" : 1,
"XOffset" : "0",
"YOffset" : "0",
"idx" : "27"
},
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 0.0,
"AddjValue2" : 0.0,
"BatteryLevel" : 73,
"CustomImage" : 0,
"Data" : "6.0 C, 80 %",
"Description" : "",
"DewPoint" : "2.81",
"Favorite" : 1,
"HardwareID" : 2,
"HardwareName" : "Xiaomi Gateway",
"HardwareType" : "Xiaomi Gateway",
"HardwareTypeVal" : 95,
"HaveTimeout" : false,
"Humidity" : 80,
"HumidityStatus" : "Wet",
"ID" : "3B3B",
"LastUpdate" : "2018-12-28 21:58:17",
"Name" : "Exterieure",
"Notifications" : "false",
"PlanID" : "0",
"PlanIDs" : [ 0 ],
"Protected" : false,
"ShowNotifications" : true,
"SignalLevel" : "-",
"SubType" : "LaCrosse TX3",
"Temp" : 6.0,
"Timers" : "false",
"Type" : "Temp + Humidity",
"TypeImg" : "temperature",
"Unit" : 2,
"Used" : 1,
"XOffset" : "0",
"YOffset" : "0",
"idx" : "28"
},
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 0.0,
"AddjValue2" : 0.0,
"BatteryLevel" : 255,
"CustomImage" : 0,
"Data" : "Open",
"Description" : "",
"DimmerType" : "none",
"Favorite" : 0,
"HardwareID" : 6,
"HardwareName" : "Z-Stick",
"HardwareType" : "OpenZWave USB",
"HardwareTypeVal" : 21,
"HaveDimmer" : true,
"HaveGroupCmd" : true,
"HaveTimeout" : false,
"ID" : "00000201",
"Image" : "Light",
"IsSubDevice" : false,
"LastUpdate" : "2018-12-28 07:26:36",
"Level" : 0,
"LevelInt" : 0,
"MaxDimLevel" : 100,
"Name" : "Salon - Volet roulant",
"Notifications" : "false",
"PlanID" : "0",
"PlanIDs" : [ 0 ],
"Protected" : false,
"ShowNotifications" : true,
"SignalLevel" : "-",
"Status" : "Open",
"StrParam1" : "",
"StrParam2" : "",
"SubType" : "Switch",
"SwitchType" : "Blinds",
"SwitchTypeVal" : 3,
"Timers" : "false",
"Type" : "Light/Switch",
"TypeImg" : "blinds",
"Unit" : 1,
"Used" : 1,
"UsedByCamera" : false,
"XOffset" : "0",
"YOffset" : "0",
"idx" : "33"
},
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 0.0,
"AddjValue2" : 0.0,
"BatteryLevel" : 255,
"CustomImage" : 0,
"Data" : "Closed",
"Description" : "",
"DimmerType" : "none",
"Favorite" : 0,
"HardwareID" : 6,
"HardwareName" : "Z-Stick",
"HardwareType" : "OpenZWave USB",
"HardwareTypeVal" : 21,
"HaveDimmer" : true,
"HaveGroupCmd" : true,
"HaveTimeout" : false,
"ID" : "00000301",
"Image" : "Light",
"IsSubDevice" : false,
"LastUpdate" : "2018-12-28 17:29:57",
"Level" : 100,
"LevelInt" : 100,
"MaxDimLevel" : 100,
"Name" : "Terrasse - Volet roulant",
"Notifications" : "false",
"PlanID" : "0",
"PlanIDs" : [ 0 ],
"Protected" : false,
"ShowNotifications" : true,
"SignalLevel" : "-",
"Status" : "Closed",
"StrParam1" : "",
"StrParam2" : "",
"SubType" : "Switch",
"SwitchType" : "Blinds",
"SwitchTypeVal" : 3,
"Timers" : "false",
"Type" : "Light/Switch",
"TypeImg" : "blinds",
"Unit" : 1,
"Used" : 1,
"UsedByCamera" : false,
"XOffset" : "0",
"YOffset" : "0",
"idx" : "34"
},
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 0.0,
"AddjValue2" : 0.0,
"BatteryLevel" : 255,
"CustomImage" : 0,
"Data" : "Closed",
"Description" : "",
"DimmerType" : "none",
"Favorite" : 0,
"HardwareID" : 6,
"HardwareName" : "Z-Stick",
"HardwareType" : "OpenZWave USB",
"HardwareTypeVal" : 21,
"HaveDimmer" : true,
"HaveGroupCmd" : true,
"HaveTimeout" : false,
"ID" : "00000F01",
"Image" : "Light",
"IsSubDevice" : false,
"LastUpdate" : "2018-12-28 17:10:58",
"Level" : 100,
"LevelInt" : 100,
"MaxDimLevel" : 100,
"Name" : "Cuisine - Volet roulant",
"Notifications" : "false",
"PlanID" : "0",
"PlanIDs" : [ 0 ],
"Protected" : false,
"ShowNotifications" : true,
"SignalLevel" : "-",
"Status" : "Closed",
"StrParam1" : "",
"StrParam2" : "",
"SubType" : "Switch",
"SwitchType" : "Blinds",
"SwitchTypeVal" : 3,
"Timers" : "false",
"Type" : "Light/Switch",
"TypeImg" : "blinds",
"Unit" : 1,
"Used" : 1,
"UsedByCamera" : false,
"XOffset" : "0",
"YOffset" : "0",
"idx" : "39"
},
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 0.0,
"AddjValue2" : 0.0,
"BatteryLevel" : 255,
"CustomImage" : 0,
"Data" : "Open",
"Description" : "",
"DimmerType" : "none",
"Favorite" : 0,
"HardwareID" : 6,
"HardwareName" : "Z-Stick",
"HardwareType" : "OpenZWave USB",
"HardwareTypeVal" : 21,
"HaveDimmer" : true,
"HaveGroupCmd" : true,
"HaveTimeout" : false,
"ID" : "00000701",
"Image" : "Light",
"IsSubDevice" : false,
"LastUpdate" : "2018-12-28 07:26:38",
"Level" : 100,
"LevelInt" : 100,
"MaxDimLevel" : 100,
"Name" : "Salon - Volet roulant Fenêtre fixe",
"Notifications" : "false",
"PlanID" : "0",
"PlanIDs" : [ 0 ],
"Protected" : false,
"ShowNotifications" : true,
"SignalLevel" : "-",
"Status" : "Open",
"StrParam1" : "",
"StrParam2" : "",
"SubType" : "Switch",
"SwitchType" : "Blinds Inverted",
"SwitchTypeVal" : 6,
"Timers" : "false",
"Type" : "Light/Switch",
"TypeImg" : "blinds",
"Unit" : 1,
"Used" : 1,
"UsedByCamera" : false,
"XOffset" : "0",
"YOffset" : "0",
"idx" : "119"
},
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 0.0,
"AddjValue2" : 0.0,
"BatteryLevel" : 255,
"CustomImage" : 15,
"Data" : "Set Level: 20 %",
"Description" : "",
"DimmerType" : "abs",
"Favorite" : 0,
"HardwareID" : 6,
"HardwareName" : "Z-Stick",
"HardwareType" : "OpenZWave USB",
"HardwareTypeVal" : 21,
"HaveDimmer" : true,
"HaveGroupCmd" : true,
"HaveTimeout" : false,
"ID" : "00000601",
"Image" : "Heating",
"IsSubDevice" : false,
"LastUpdate" : "2018-10-06 00:21:30",
"Level" : 20,
"LevelInt" : 20,
"MaxDimLevel" : 100,
"Name" : "Seche serviette - Salle de bain parentale",
"Notifications" : "false",
"PlanID" : "0",
"PlanIDs" : [ 0 ],
"Protected" : false,
"ShowNotifications" : true,
"SignalLevel" : "-",
"Status" : "Set Level: 20 %",
"StrParam1" : "",
"StrParam2" : "",
"SubType" : "Switch",
"SwitchType" : "Dimmer",
"SwitchTypeVal" : 7,
"Timers" : "false",
"Type" : "Light/Switch",
"TypeImg" : "dimmer",
"Unit" : 1,
"Used" : 1,
"UsedByCamera" : false,
"XOffset" : "0",
"YOffset" : "0",
"idx" : "52"
},
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 1800.0,
"AddjValue2" : 0.0,
"BatteryLevel" : 255,
"CustomImage" : 15,
"Data" : "Off",
"Description" : "",
"DimmerType" : "none",
"Favorite" : 0,
"HardwareID" : 5,
"HardwareName" : "Virtual switch 1",
"HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
"HardwareTypeVal" : 15,
"HaveDimmer" : true,
"HaveGroupCmd" : true,
"HaveTimeout" : false,
"ID" : "0001408A",
"Image" : "Heating",
"IsSubDevice" : false,
"LastUpdate" : "2018-10-06 00:21:30",
"Level" : 0,
"LevelInt" : 0,
"MaxDimLevel" : 100,
"Name" : "SdB parentale - Chauffage 30min",
"Notifications" : "false",
"PlanID" : "0",
"PlanIDs" : [ 0 ],
"Protected" : false,
"ShowNotifications" : true,
"SignalLevel" : "-",
"Status" : "Off",
"StrParam1" : "",
"StrParam2" : "",
"SubType" : "Switch",
"SwitchType" : "On/Off",
"SwitchTypeVal" : 0,
"Timers" : "false",
"Type" : "Light/Switch",
"TypeImg" : "lightbulb",
"Unit" : 1,
"Used" : 1,
"UsedByCamera" : false,
"XOffset" : "0",
"YOffset" : "0",
"idx" : "58"
},
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 0.0,
"AddjValue2" : 0.0,
"BatteryLevel" : 74,
"CustomImage" : 0,
"Data" : "16.2 C, 75 %",
"Description" : "",
"DewPoint" : "11.76",
"Favorite" : 0,
"HardwareID" : 2,
"HardwareName" : "Xiaomi Gateway",
"HardwareType" : "Xiaomi Gateway",
"HardwareTypeVal" : 95,
"HaveTimeout" : false,
"Humidity" : 75,
"HumidityStatus" : "Wet",
"ID" : "4315",
"LastUpdate" : "2018-12-28 22:03:51",
"Name" : "Sous-sol",
"Notifications" : "false",
"PlanID" : "0",
"PlanIDs" : [ 0 ],
"Protected" : false,
"ShowNotifications" : true,
"SignalLevel" : "-",
"SubType" : "LaCrosse TX3",
"Temp" : 16.199999999999999,
"Timers" : "false",
"Type" : "Temp + Humidity",
"TypeImg" : "temperature",
"Unit" : 2,
"Used" : 1,
"XOffset" : "0",
"YOffset" : "0",
"idx" : "70"
},
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 0.0,
"AddjValue2" : 0.0,
"BatteryLevel" : 100,
"CustomImage" : 0,
"Data" : "19.8 C",
"Description" : "",
"Favorite" : 0,
"HardwareID" : 2,
"HardwareName" : "Xiaomi Gateway",
"HardwareType" : "Xiaomi Gateway",
"HardwareTypeVal" : 95,
"HaveTimeout" : false,
"ID" : "3AAC",
"LastUpdate" : "2018-12-28 22:11:24",
"Name" : "Salle de bain enfants",
"Notifications" : "false",
"PlanID" : "0",
"PlanIDs" : [ 0 ],
"Protected" : false,
"ShowNotifications" : true,
"SignalLevel" : "-",
"SubType" : "LaCrosse TX3",
"Temp" : 19.800000000000001,
"Timers" : "false",
"Type" : "Temp",
"TypeImg" : "temperature",
"Unit" : 172,
"Used" : 1,
"XOffset" : "0",
"YOffset" : "0",
"idx" : "81"
},
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 0.0,
"AddjValue2" : 0.0,
"BatteryLevel" : 255,
"CustomImage" : 0,
"Data" : "Humidity 55 %",
"Description" : "",
"Favorite" : 0,
"HardwareID" : 2,
"HardwareName" : "Xiaomi Gateway",
"HardwareType" : "Xiaomi Gateway",
"HardwareTypeVal" : 95,
"HaveTimeout" : false,
"Humidity" : 55,
"HumidityStatus" : "Comfortable",
"ID" : "3AAC",
"LastUpdate" : "2018-12-28 22:11:24",
"Name" : "Salle de bain enfants - Humidité",
"Notifications" : "false",
"PlanID" : "0",
"PlanIDs" : [ 0 ],
"Protected" : false,
"ShowNotifications" : true,
"SignalLevel" : "-",
"SubType" : "LaCrosse TX3",
"Timers" : "false",
"Type" : "Humidity",
"TypeImg" : "temperature",
"Unit" : 1,
"Used" : 1,
"XOffset" : "0",
"YOffset" : "0",
"idx" : "82"
},
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 0.0,
"AddjValue2" : 0.0,
"BatteryLevel" : 100,
"CustomImage" : 0,
"Data" : "20.6 C",
"Description" : "",
"Favorite" : 0,
"HardwareID" : 2,
"HardwareName" : "Xiaomi Gateway",
"HardwareType" : "Xiaomi Gateway",
"HardwareTypeVal" : 95,
"HaveTimeout" : false,
"ID" : "8063",
"LastUpdate" : "2018-12-28 22:07:03",
"Name" : "Salle de bain parentale",
"Notifications" : "false",
"PlanID" : "0",
"PlanIDs" : [ 0 ],
"Protected" : false,
"ShowNotifications" : true,
"SignalLevel" : "-",
"SubType" : "LaCrosse TX3",
"Temp" : 20.600000000000001,
"Timers" : "false",
"Type" : "Temp",
"TypeImg" : "temperature",
"Unit" : 99,
"Used" : 1,
"XOffset" : "0",
"YOffset" : "0",
"idx" : "85"
},
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 0.0,
"AddjValue2" : 0.0,
"BatteryLevel" : 255,
"CustomImage" : 0,
"Data" : "Humidity 53 %",
"Description" : "",
"Favorite" : 0,
"HardwareID" : 2,
"HardwareName" : "Xiaomi Gateway",
"HardwareType" : "Xiaomi Gateway",
"HardwareTypeVal" : 95,
"HaveTimeout" : false,
"Humidity" : 53,
"HumidityStatus" : "Comfortable",
"ID" : "8063",
"LastUpdate" : "2018-12-28 22:07:03",
"Name" : "Salle de bain parentale - Humidité",
"Notifications" : "false",
"PlanID" : "0",
"PlanIDs" : [ 0 ],
"Protected" : false,
"ShowNotifications" : true,
"SignalLevel" : "-",
"SubType" : "LaCrosse TX3",
"Timers" : "false",
"Type" : "Humidity",
"TypeImg" : "temperature",
"Unit" : 1,
"Used" : 1,
"XOffset" : "0",
"YOffset" : "0",
"idx" : "86"
},
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 0.0,
"AddjValue2" : 0.0,
"BatteryLevel" : 255,
"CustomImage" : 0,
"Data" : "5.9 C, 93 %",
"Description" : "",
"DewPoint" : "4.85",
"Favorite" : 0,
"HardwareID" : 2,
"HardwareName" : "Xiaomi Gateway",
"HardwareType" : "Xiaomi Gateway",
"HardwareTypeVal" : 95,
"HaveTimeout" : false,
"Humidity" : 93,
"HumidityStatus" : "Wet",
"ID" : "3AF2",
"LastUpdate" : "2018-12-28 22:09:18",
"Name" : "VMC - entrant",
"Notifications" : "false",
"PlanID" : "0",
"PlanIDs" : [ 0 ],
"Protected" : false,
"ShowNotifications" : true,
"SignalLevel" : "-",
"SubType" : "LaCrosse TX3",
"Temp" : 5.9000000000000004,
"Timers" : "false",
"Type" : "Temp + Humidity",
"TypeImg" : "temperature",
"Unit" : 2,
"Used" : 1,
"XOffset" : "0",
"YOffset" : "0",
"idx" : "92"
},
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 0.0,
"AddjValue2" : 0.0,
"BatteryLevel" : 255,
"CustomImage" : 0,
"Data" : "12.4 C, 64 %",
"Description" : "",
"DewPoint" : "5.78",
"Favorite" : 0,
"HardwareID" : 2,
"HardwareName" : "Xiaomi Gateway",
"HardwareType" : "Xiaomi Gateway",
"HardwareTypeVal" : 95,
"HaveTimeout" : false,
"Humidity" : 64,
"HumidityStatus" : "Wet",
"ID" : "3AEA",
"LastUpdate" : "2018-12-28 22:08:37",
"Name" : "VMC - sortant",
"Notifications" : "false",
"PlanID" : "0",
"PlanIDs" : [ 0 ],
"Protected" : false,
"ShowNotifications" : true,
"SignalLevel" : "-",
"SubType" : "LaCrosse TX3",
"Temp" : 12.4,
"Timers" : "false",
"Type" : "Temp + Humidity",
"TypeImg" : "temperature",
"Unit" : 2,
"Used" : 1,
"XOffset" : "0",
"YOffset" : "0",
"idx" : "98"
},
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 1.0,
"AddjValue2" : 0.0,
"BatteryLevel" : 81,
"CustomImage" : 0,
"Data" : "20.8 C, 51 %",
"Description" : "",
"DewPoint" : "10.29",
"Favorite" : 0,
"HardwareID" : 2,
"HardwareName" : "Xiaomi Gateway",
"HardwareType" : "Xiaomi Gateway",
"HardwareTypeVal" : 95,
"HaveTimeout" : false,
"Humidity" : 51,
"HumidityStatus" : "Comfortable",
"ID" : "5614",
"LastUpdate" : "2018-12-28 22:05:38",
"Name" : "Chambre Noé",
"Notifications" : "false",
"PlanID" : "0",
"PlanIDs" : [ 0 ],
"Protected" : false,
"ShowNotifications" : true,
"SignalLevel" : "-",
"SubType" : "LaCrosse TX3",
"Temp" : 20.800000000000001,
"Timers" : "false",
"Type" : "Temp + Humidity",
"TypeImg" : "temperature",
"Unit" : 2,
"Used" : 1,
"XOffset" : "0",
"YOffset" : "0",
"idx" : "110"
},
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 0.0,
"AddjValue2" : 0.0,
"BatteryLevel" : 255,
"CustomImage" : 0,
"Data" : "20.8 C, 53 %",
"Description" : "",
"DewPoint" : "10.87",
"Favorite" : 0,
"HardwareID" : 2,
"HardwareName" : "Xiaomi Gateway",
"HardwareType" : "Xiaomi Gateway",
"HardwareTypeVal" : 95,
"HaveTimeout" : false,
"Humidity" : 53,
"HumidityStatus" : "Comfortable",
"ID" : "5FB0",
"LastUpdate" : "2018-12-28 21:47:35",
"Name" : "Séjour",
"Notifications" : "false",
"PlanID" : "0",
"PlanIDs" : [ 0 ],
"Protected" : false,
"ShowNotifications" : true,
"SignalLevel" : "-",
"SubType" : "LaCrosse TX3",
"Temp" : 20.800000000000001,
"Timers" : "false",
"Type" : "Temp + Humidity",
"TypeImg" : "temperature",
"Unit" : 2,
"Used" : 1,
"XOffset" : "0",
"YOffset" : "0",
"idx" : "114"
},
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 0.0,
"AddjValue2" : 0.0,
"BatteryLevel" : 255,
"CustomImage" : 0,
"Data" : "2 Lux",
"Description" : "",
"Favorite" : 0,
"HardwareID" : 2,
"HardwareName" : "Xiaomi Gateway",
"HardwareType" : "Xiaomi Gateway",
"HardwareTypeVal" : 95,
"HaveTimeout" : false,
"ID" : "00000B2",
"LastUpdate" : "2018-12-28 21:50:57",
"Name" : "Garage",
"Notifications" : "false",
"PlanID" : "0",
"PlanIDs" : [ 0 ],
"Protected" : false,
"ShowNotifications" : true,
"SignalLevel" : "-",
"SubType" : "Lux",
"Timers" : "false",
"Type" : "Lux",
"TypeImg" : "lux",
"Unit" : 178,
"Used" : 1,
"XOffset" : "0",
"YOffset" : "0",
"idx" : "117"
},
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 0.0,
"AddjValue2" : 0.0,
"BatteryLevel" : 255,
"CustomImage" : 0,
"Data" : "Off",
"Description" : "",
"DimmerType" : "none",
"Favorite" : 0,
"HardwareID" : 2,
"HardwareName" : "Xiaomi Gateway",
"HardwareType" : "Xiaomi Gateway",
"HardwareTypeVal" : 95,
"HaveDimmer" : true,
"HaveGroupCmd" : true,
"HaveTimeout" : false,
"ID" : "01A663B2",
"Image" : "Light",
"IsSubDevice" : false,
"LastUpdate" : "2018-12-28 21:52:57",
"Level" : 0,
"LevelInt" : 0,
"MaxDimLevel" : 100,
"Name" : "Garage",
"Notifications" : "false",
"PlanID" : "0",
"PlanIDs" : [ 0 ],
"Protected" : false,
"ShowNotifications" : true,
"SignalLevel" : "-",
"Status" : "Off",
"StrParam1" : "",
"StrParam2" : "",
"SubType" : "Switch",
"SwitchType" : "Motion Sensor",
"SwitchTypeVal" : 8,
"Timers" : "false",
"Type" : "Light/Switch",
"TypeImg" : "motion",
"Unit" : 1,
"Used" : 1,
"UsedByCamera" : false,
"XOffset" : "0",
"YOffset" : "0",
"idx" : "118"
},
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 0.0,
"AddjValue2" : 0.0,
"BatteryLevel" : 255,
"CustomImage" : 0,
"Data" : "14 Lux",
"Description" : "",
"Favorite" : 0,
"HardwareID" : 2,
"HardwareName" : "Xiaomi Gateway",
"HardwareType" : "Xiaomi Gateway",
"HardwareTypeVal" : 95,
"HaveTimeout" : false,
"ID" : "0000062",
"LastUpdate" : "2018-12-28 22:01:50",
"Name" : "Séjour",
"Notifications" : "false",
"PlanID" : "0",
"PlanIDs" : [ 0 ],
"Protected" : false,
"ShowNotifications" : true,
"SignalLevel" : "-",
"SubType" : "Lux",
"Timers" : "false",
"Type" : "Lux",
"TypeImg" : "lux",
"Unit" : 98,
"Used" : 1,
"XOffset" : "0",
"YOffset" : "0",
"idx" : "125"
},
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 0.0,
"AddjValue2" : 0.0,
"BatteryLevel" : 255,
"CustomImage" : 0,
"Data" : "Off",
"Description" : "",
"DimmerType" : "none",
"Favorite" : 0,
"HardwareID" : 2,
"HardwareName" : "Xiaomi Gateway",
"HardwareType" : "Xiaomi Gateway",
"HardwareTypeVal" : 95,
"HaveDimmer" : true,
"HaveGroupCmd" : true,
"HaveTimeout" : false,
"ID" : "01AD6062",
"Image" : "Light",
"IsSubDevice" : false,
"LastUpdate" : "2018-12-28 22:03:50",
"Level" : 0,
"LevelInt" : 0,
"MaxDimLevel" : 100,
"Name" : "Séjour",
"Notifications" : "false",
"PlanID" : "0",
"PlanIDs" : [ 0 ],
"Protected" : false,
"ShowNotifications" : true,
"SignalLevel" : "-",
"Status" : "Off",
"StrParam1" : "",
"StrParam2" : "",
"SubType" : "Switch",
"SwitchType" : "Motion Sensor",
"SwitchTypeVal" : 8,
"Timers" : "false",
"Type" : "Light/Switch",
"TypeImg" : "motion",
"Unit" : 1,
"Used" : 1,
"UsedByCamera" : false,
"XOffset" : "0",
"YOffset" : "0",
"idx" : "126"
},
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 0.0,
"AddjValue2" : 0.0,
"BatteryLevel" : 255,
"CustomImage" : 0,
"Data" : "On",
"Description" : "",
"DimmerType" : "none",
"Favorite" : 0,
"HardwareID" : 2,
"HardwareName" : "Xiaomi Gateway",
"HardwareType" : "Xiaomi Gateway",
"HardwareTypeVal" : 95,
"HaveDimmer" : true,
"HaveGroupCmd" : true,
"HaveTimeout" : false,
"ID" : "01E15D47",
"Image" : "Light",
"IsSubDevice" : false,
"LastUpdate" : "2018-12-28 22:11:15",
"Level" : 0,
"LevelInt" : 0,
"MaxDimLevel" : 100,
"Name" : "Salon",
"Notifications" : "false",
"PlanID" : "0",
"PlanIDs" : [ 0 ],
"Protected" : false,
"ShowNotifications" : true,
"SignalLevel" : "-",
"Status" : "On",
"StrParam1" : "",
"StrParam2" : "",
"SubType" : "Switch",
"SwitchType" : "Motion Sensor",
"SwitchTypeVal" : 8,
"Timers" : "false",
"Type" : "Light/Switch",
"TypeImg" : "motion",
"Unit" : 1,
"Used" : 1,
"UsedByCamera" : false,
"XOffset" : "0",
"YOffset" : "0",
"idx" : "130"
},
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 0.0,
"AddjValue2" : 0.0,
"BatteryLevel" : 255,
"CustomImage" : 0,
"Data" : "Off",
"Description" : "",
"DimmerType" : "none",
"Favorite" : 0,
"HardwareID" : 2,
"HardwareName" : "Xiaomi Gateway",
"HardwareType" : "Xiaomi Gateway",
"HardwareTypeVal" : 95,
"HaveDimmer" : true,
"HaveGroupCmd" : true,
"HaveTimeout" : false,
"ID" : "01AD5CBE",
"Image" : "Light",
"IsSubDevice" : false,
"LastUpdate" : "2018-12-28 22:04:23",
"Level" : 0,
"LevelInt" : 0,
"MaxDimLevel" : 100,
"Name" : "Entrée",
"Notifications" : "false",
"PlanID" : "0",
"PlanIDs" : [ 0 ],
"Protected" : false,
"ShowNotifications" : true,
"SignalLevel" : "-",
"Status" : "Off",
"StrParam1" : "",
"StrParam2" : "",
"SubType" : "Switch",
"SwitchType" : "Motion Sensor",
"SwitchTypeVal" : 8,
"Timers" : "false",
"Type" : "Light/Switch",
"TypeImg" : "motion",
"Unit" : 1,
"Used" : 1,
"UsedByCamera" : false,
"XOffset" : "0",
"YOffset" : "0",
"idx" : "132"
},
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 0.0,
"AddjValue2" : 0.0,
"BatteryLevel" : 255,
"CustomImage" : 0,
"Data" : "Closed",
"Description" : "",
"DimmerType" : "none",
"Favorite" : 0,
"HardwareID" : 5,
"HardwareName" : "Virtual switch 1",
"HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
"HardwareTypeVal" : 15,
"HaveDimmer" : true,
"HaveGroupCmd" : true,
"HaveTimeout" : false,
"ID" : "000140D5",
"Image" : "Light",
"IsSubDevice" : false,
"LastUpdate" : "2018-12-27 23:14:42",
"Level" : 0,
"LevelInt" : 0,
"MaxDimLevel" : 100,
"Name" : "Volets",
"Notifications" : "false",
"PlanID" : "0",
"PlanIDs" : [ 0 ],
"Protected" : false,
"ShowNotifications" : true,
"SignalLevel" : "-",
"Status" : "Closed",
"StrParam1" : "",
"StrParam2" : "",
"SubType" : "Switch",
"SwitchType" : "Blinds",
"SwitchTypeVal" : 3,
"Timers" : "false",
"Type" : "Light/Switch",
"TypeImg" : "blinds",
"Unit" : 1,
"Used" : 1,
"UsedByCamera" : false,
"XOffset" : "0",
"YOffset" : "0",
"idx" : "133"
}
],
"status" : "OK",
"title" : "Devices"
});