exports.DOMOTICZ_GET_DEVICES = JSON.stringify({
"ActTime" : 1574108585,
"AstrTwilightEnd" : "19:09",
"AstrTwilightStart" : "06:24",
"CivTwilightEnd" : "17:52",
"CivTwilightStart" : "07:41",
"DayLength" : "09:02",
"NautTwilightEnd" : "18:31",
"NautTwilightStart" : "07:02",
"ServerTime" : "2019-11-18 21:23:05",
"SunAtSouth" : "12:46",
"Sunrise" : "08:16",
"Sunset" : "17:17",
"app_version" : "4.11492",
"result" : [
{
"Data" : "On",
"Description" : "",
"Favorite" : 0,
"LastUpdate" : "2019-11-18 17:27:01",
"Name" : "Volets",
"PlanID" : "",
"PlanIDs" : [ 0 ],
"Protected" : false,
"Status" : "On",
"Type" : "Group",
"TypeImg" : "group",
"UsedByCamera" : false,
"XOffset" : 0,
"YOffset" : 0,
"idx" : "2"
},
{
"Data" : "Off",
"Description" : "",
"Favorite" : 0,
"LastUpdate" : "2018-11-15 21:00:02",
"Name" : "Lumiere cuisine",
"PlanID" : "",
"PlanIDs" : [ 0 ],
"Protected" : false,
"Status" : "Off",
"Type" : "Group",
"TypeImg" : "group",
"UsedByCamera" : false,
"XOffset" : 0,
"YOffset" : 0,
"idx" : "3"
},
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 0.0,
"AddjValue2" : 0.0,
"BatteryLevel" : 255,
"CounterToday" : "0.050 kWh",
"CustomImage" : 0,
"Data" : "19886.090 kWh",
"Description" : "",
"EnergyMeterMode" : "",
"Favorite" : 0,
"HardwareID" : 2,
"HardwareName" : "Clé USB Zwave",
"HardwareType" : "OpenZWave USB",
"HardwareTypeVal" : 21,
"HaveTimeout" : false,
"ID" : "00000701",
"LastUpdate" : "2019-11-18 21:22:54",
"Name" : "kWh Meter",
"Notifications" : "false",
"PlanID" : "0",
"PlanIDs" : [ 0 ],
"Protected" : false,
"ShowNotifications" : true,
"SignalLevel" : "-",
"SubType" : "kWh",
"SwitchTypeVal" : 0,
"Timers" : "false",
"Type" : "General",
"TypeImg" : "current",
"Unit" : 1,
"Usage" : "4.1 Watt",
"Used" : 1,
"XOffset" : "0",
"YOffset" : "0",
"idx" : "158"
},
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 0.0,
"AddjValue2" : 0.0,
"BatteryLevel" : 255,
"Counter" : "43132.877",
"CounterDeliv" : "0.000",
"CounterDelivToday" : "0.000 kWh",
"CounterToday" : "67.192 kWh",
"CustomImage" : 0,
"Data" : "27010895;16121982;0;0;1550;0",
"Description" : "",
"Favorite" : 1,
"HardwareID" : 14,
"HardwareName" : "Teleinfo",
"HardwareType" : "Teleinfo EDF",
"HardwareTypeVal" : 19,
"HaveTimeout" : false,
"ID" : "0001",
"LastUpdate" : "2019-11-18 21:22:43",
"Name" : "Compteur EDF",
"Notifications" : "false",
"PlanID" : "0",
"PlanIDs" : [ 0 ],
"Protected" : false,
"ShowNotifications" : true,
"SignalLevel" : "-",
"SubType" : "Energy",
"SwitchTypeVal" : 0,
"Timers" : "false",
"Type" : "P1 Smart Meter",
"TypeImg" : "counter",
"Unit" : 1,
"Usage" : "1550 Watt",
"UsageDeliv" : "0 Watt",
"Used" : 1,
"XOffset" : "0",
"YOffset" : "0",
"idx" : "178"
},
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 0.0,
"AddjValue2" : 0.0,
"BatteryLevel" : 255,
"CustomImage" : 0,
"Data" : "13.06%",
"Description" : "",
"Favorite" : 0,
"HardwareID" : 3,
"HardwareName" : "Motherboard",
"HardwareType" : "Motherboard sensors",
"HardwareTypeVal" : 23,
"HaveTimeout" : false,
"ID" : "0000044C",
"Image" : "Computer",
"LastUpdate" : "2019-11-18 21:22:02",
"Name" : "RAM Raspberry",
"Notifications" : "false",
"PlanID" : "0",
"PlanIDs" : [ 0 ],
"Protected" : false,
"ShowNotifications" : true,
"SignalLevel" : "-",
"SubType" : "Percentage",
"Timers" : "false",
"Type" : "General",
"TypeImg" : "hardware",
"Unit" : 1,
"Used" : 1,
"XOffset" : "0",
"YOffset" : "0",
"idx" : "14"
},
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 0.0,
"AddjValue2" : 0.0,
"BatteryLevel" : 255,
"CustomImage" : 0,
"Data" : "13.52%",
"Description" : "",
"Favorite" : 0,
"HardwareID" : 3,
"HardwareName" : "Motherboard",
"HardwareType" : "Motherboard sensors",
"HardwareTypeVal" : 23,
"HaveTimeout" : false,
"ID" : "0000044F",
"Image" : "Computer",
"LastUpdate" : "2019-11-18 21:21:32",
"Name" : "HDD Raspberry",
"Notifications" : "false",
"PlanID" : "0",
"PlanIDs" : [ 0 ],
"Protected" : false,
"ShowNotifications" : true,
"SignalLevel" : "-",
"SubType" : "Percentage",
"Timers" : "false",
"Type" : "General",
"TypeImg" : "hardware",
"Unit" : 1,
"Used" : 1,
"XOffset" : "0",
"YOffset" : "0",
"idx" : "16"
},
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 0.0,
"AddjValue2" : 0.0,
"BatteryLevel" : 255,
"CustomImage" : 0,
"Data" : "0.53%",
"Description" : "",
"Favorite" : 0,
"HardwareID" : 3,
"HardwareName" : "Motherboard",
"HardwareType" : "Motherboard sensors",
"HardwareTypeVal" : 23,
"HaveTimeout" : false,
"ID" : "0000044D",
"Image" : "Computer",
"LastUpdate" : "2019-11-18 21:22:42",
"Name" : "CPU Raspberry",
"Notifications" : "false",
"PlanID" : "0",
"PlanIDs" : [ 0 ],
"Protected" : false,
"ShowNotifications" : true,
"SignalLevel" : "-",
"SubType" : "Percentage",
"Timers" : "false",
"Type" : "General",
"TypeImg" : "hardware",
"Unit" : 1,
"Used" : 1,
"XOffset" : "0",
"YOffset" : "0",
"idx" : "18"
},
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 0.0,
"AddjValue2" : 0.0,
"BatteryLevel" : 255,
"CustomImage" : 2,
"Data" : "Set Level: 10 %",
"Description" : "",
"DimmerType" : "none",
"Favorite" : 1,
"HardwareID" : 5,
"HardwareName" : "Virtual HW",
"HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
"HardwareTypeVal" : 15,
"HaveDimmer" : true,
"HaveGroupCmd" : true,
"HaveTimeout" : false,
"ID" : "000140B5",
"Image" : "TV",
"IsSubDevice" : false,
"LastUpdate" : "2019-11-18 21:20:06",
"Level" : 10,
"LevelActions" : "fHx8fHx8",
"LevelInt" : 10,
"LevelNames" : "T2ZmfFRWfENhc3R8UFMzfEZNfEFpcnxLb2Rp",
"LevelOffHidden" : false,
"MaxDimLevel" : 100,
"Name" : "Ampli Pioneer",
"Notifications" : "false",
"PlanID" : "0",
"PlanIDs" : [ 0 ],
"Protected" : false,
"SelectorStyle" : 0,
"ShowNotifications" : true,
"SignalLevel" : "-",
"Status" : "Set Level: 10 %",
"StrParam1" : "",
"StrParam2" : "",
"SubType" : "Selector Switch",
"SwitchType" : "Selector",
"SwitchTypeVal" : 18,
"Timers" : "true",
"Type" : "Light/Switch",
"TypeImg" : "Light",
"Unit" : 1,
"Used" : 1,
"UsedByCamera" : false,
"XOffset" : "0",
"YOffset" : "0",
"idx" : "102"
},
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 0.0,
"AddjValue2" : 0.0,
"BatteryLevel" : 255,
"CustomImage" : 0,
"Data" : "Off",
"Description" : "",
"DimmerType" : "abs",
"Favorite" : 0,
"HardwareID" : 5,
"HardwareName" : "Virtual HW",
"HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
"HardwareTypeVal" : 15,
"HaveDimmer" : true,
"HaveGroupCmd" : true,
"HaveTimeout" : false,
"ID" : "000140BC",
"Image" : "Light",
"IsSubDevice" : false,
"LastUpdate" : "2019-11-18 21:00:08",
"Level" : 35,
"LevelInt" : 35,
"MaxDimLevel" : 100,
"Name" : "Volume",
"Notifications" : "false",
"PlanID" : "0",
"PlanIDs" : [ 0 ],
"Protected" : false,
"ShowNotifications" : true,
"SignalLevel" : "-",
"Status" : "Off",
"StrParam1" : "",
"StrParam2" : "",
"SubType" : "Switch",
"SwitchType" : "Dimmer",
"SwitchTypeVal" : 7,
"Timers" : "false",
"Type" : "Light/Switch",
"TypeImg" : "dimmer",
"Unit" : 1,
"Used" : 1,
"UsedByCamera" : false,
"XOffset" : "0",
"YOffset" : "0",
"idx" : "104"
},
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 0.0,
"AddjValue2" : 0.0,
"BatteryLevel" : 255,
"CustomImage" : 13,
"Data" : "Off",
"Description" : "",
"DimmerType" : "none",
"Favorite" : 1,
"HardwareID" : 5,
"HardwareName" : "Virtual HW",
"HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
"HardwareTypeVal" : 15,
"HaveDimmer" : true,
"HaveGroupCmd" : true,
"HaveTimeout" : false,
"ID" : "000141DC",
"Image" : "Alarm",
"IsSubDevice" : false,
"LastUpdate" : "2019-11-18 16:45:02",
"Level" : 0,
"LevelInt" : 0,
"MaxDimLevel" : 100,
"Name" : "Absence Virtuelle",
"Notifications" : "true",
"PlanID" : "0",
"PlanIDs" : [ 0 ],
"Protected" : false,
"ShowNotifications" : true,
"SignalLevel" : "-",
"Status" : "Off",
"StrParam1" : "",
"StrParam2" : "",
"SubType" : "Switch",
"SwitchType" : "On/Off",
"SwitchTypeVal" : 0,
"Timers" : "true",
"Type" : "Light/Switch",
"TypeImg" : "lightbulb",
"Unit" : 1,
"Used" : 1,
"UsedByCamera" : false,
"XOffset" : "0",
"YOffset" : "0",
"idx" : "396"
},
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 0.0,
"AddjValue2" : 0.0,
"BatteryLevel" : 255,
"CustomImage" : 0,
"Data" : "Closed",
"Description" : "",
"DimmerType" : "none",
"Favorite" : 1,
"HardwareID" : 10,
"HardwareName" : "Clé USB RFXCom",
"HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
"HardwareTypeVal" : 1,
"HaveDimmer" : false,
"HaveGroupCmd" : false,
"HaveTimeout" : false,
"ID" : "071406",
"Image" : "Light",
"IsSubDevice" : false,
"LastUpdate" : "2019-11-18 13:50:43",
"Level" : 0,
"LevelInt" : 0,
"MaxDimLevel" : 0,
"Name" : "Portail",
"Notifications" : "false",
"PlanID" : "0",
"PlanIDs" : [ 0 ],
"Protected" : false,
"ShowNotifications" : true,
"SignalLevel" : "-",
"Status" : "Closed",
"StrParam1" : "",
"StrParam2" : "",
"SubType" : "RFY",
"SwitchType" : "Blinds",
"SwitchTypeVal" : 3,
"Timers" : "false",
"Type" : "RFY",
"TypeImg" : "blinds",
"Unit" : 1,
"Used" : 1,
"UsedByCamera" : false,
"XOffset" : "0",
"YOffset" : "0",
"idx" : "395"
},
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 0.0,
"AddjValue2" : 0.0,
"BatteryLevel" : 255,
"CustomImage" : 0,
"Data" : "On",
"Description" : "",
"DimmerType" : "none",
"Favorite" : 1,
"HardwareID" : 10,
"HardwareName" : "Clé USB RFXCom",
"HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
"HardwareTypeVal" : 1,
"HaveDimmer" : true,
"HaveGroupCmd" : true,
"HaveTimeout" : false,
"ID" : "0120885",
"Image" : "Light",
"IsSubDevice" : false,
"LastUpdate" : "2019-11-18 07:00:04",
"Level" : 100,
"LevelInt" : 15,
"MaxDimLevel" : 15,
"Name" : "Home cinema",
"Notifications" : "false",
"PlanID" : "0",
"PlanIDs" : [ 0 ],
"Protected" : false,
"ShowNotifications" : true,
"SignalLevel" : "-",
"Status" : "On",
"StrParam1" : "",
"StrParam2" : "",
"SubType" : "AC",
"SwitchType" : "On/Off",
"SwitchTypeVal" : 0,
"Timers" : "true",
"Type" : "Lighting 2",
"TypeImg" : "lightbulb",
"Unit" : 1,
"Used" : 1,
"UsedByCamera" : false,
"XOffset" : "0",
"YOffset" : "0",
"idx" : "67"
},
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 0.0,
"AddjValue2" : 0.0,
"BatteryLevel" : 255,
"CustomImage" : 15,
"Data" : "Off",
"Description" : "",
"DimmerType" : "none",
"Favorite" : 0,
"HardwareID" : 2,
"HardwareName" : "Clé USB Zwave",
"HardwareType" : "OpenZWave USB",
"HardwareTypeVal" : 21,
"HaveDimmer" : true,
"HaveGroupCmd" : true,
"HaveTimeout" : false,
"ID" : "00000601",
"Image" : "Heating",
"IsSubDevice" : false,
"LastUpdate" : "2019-11-18 19:04:00",
"Level" : 0,
"LevelInt" : 0,
"MaxDimLevel" : 100,
"Name" : "Radiateur Emma",
"Notifications" : "false",
"PlanID" : "0",
"PlanIDs" : [ 0 ],
"Protected" : false,
"ShowNotifications" : true,
"SignalLevel" : "-",
"Status" : "Off",
"StrParam1" : "",
"StrParam2" : "",
"SubType" : "Switch",
"SwitchType" : "On/Off",
"SwitchTypeVal" : 0,
"Timers" : "false",
"Type" : "Light/Switch",
"TypeImg" : "lightbulb",
"Unit" : 1,
"Used" : 1,
"UsedByCamera" : false,
"XOffset" : "0",
"YOffset" : "0",
"idx" : "80"
},
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 0.0,
"AddjValue2" : 0.0,
"BatteryLevel" : 255,
"CustomImage" : 0,
"Data" : "0",
"Description" : "",
"Favorite" : 0,
"HardwareID" : 8,
"HardwareName" : "Météo Caen FIO",
"HardwareType" : "DarkSky (Weather Lookup)",
"HardwareTypeVal" : 25,
"HaveTimeout" : true,
"ID" : "0001",
"LastUpdate" : "2019-04-03 10:55:01",
"Name" : "Pluie Caen FIO",
"Notifications" : "false",
"PlanID" : "0",
"PlanIDs" : [ 0 ],
"Protected" : false,
"Rain" : "0",
"RainRate" : "0",
"ShowNotifications" : true,
"SignalLevel" : "-",
"SubType" : "WWW",
"Timers" : "false",
"Type" : "Rain",
"TypeImg" : "rain",
"Unit" : 0,
"Used" : 1,
"XOffset" : "0",
"YOffset" : "0",
"forecast_url" : "aHR0cHM6Ly9kYXJrc2t5Lm5ldC8jL2YvNDkuMTYyNjEwJTJDJTIwLTAuMzI4ODUx",
"idx" : "49"
},
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 0.0,
"AddjValue2" : 0.0,
"BatteryLevel" : 255,
"CustomImage" : 15,
"Data" : "Off",
"Description" : "",
"DimmerType" : "none",
"Favorite" : 0,
"HardwareID" : 2,
"HardwareName" : "Clé USB Zwave",
"HardwareType" : "OpenZWave USB",
"HardwareTypeVal" : 21,
"HaveDimmer" : true,
"HaveGroupCmd" : true,
"HaveTimeout" : false,
"ID" : "00000F01",
"Image" : "Heating",
"IsSubDevice" : false,
"LastUpdate" : "2019-11-18 20:50:05",
"Level" : 0,
"LevelInt" : 0,
"MaxDimLevel" : 100,
"Name" : "Radiateur Robin",
"Notifications" : "false",
"PlanID" : "0",
"PlanIDs" : [ 0 ],
"Protected" : false,
"ShowNotifications" : true,
"SignalLevel" : "-",
"Status" : "Off",
"StrParam1" : "",
"StrParam2" : "",
"SubType" : "Switch",
"SwitchType" : "On/Off",
"SwitchTypeVal" : 0,
"Timers" : "false",
"Type" : "Light/Switch",
"TypeImg" : "lightbulb",
"Unit" : 1,
"Used" : 1,
"UsedByCamera" : false,
"XOffset" : "0",
"YOffset" : "0",
"idx" : "410"
},
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 0.0,
"AddjValue2" : 0.0,
"BatteryLevel" : 255,
"CustomImage" : 0,
"Data" : "On",
"Description" : "",
"DimmerType" : "none",
"Favorite" : 0,
"HardwareID" : 10,
"HardwareName" : "Clé USB RFXCom",
"HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
"HardwareTypeVal" : 1,
"HaveDimmer" : true,
"HaveGroupCmd" : true,
"HaveTimeout" : false,
"ID" : "3010204",
"Image" : "Light",
"IsSubDevice" : false,
"LastUpdate" : "2019-11-18 17:32:01",
"Level" : 100,
"LevelInt" : 15,
"MaxDimLevel" : 15,
"Name" : "Lumière Escalier OLD",
"Notifications" : "false",
"PlanID" : "0",
"PlanIDs" : [ 0 ],
"Protected" : false,
"ShowNotifications" : true,
"SignalLevel" : "-",
"Status" : "On",
"StrParam1" : "",
"StrParam2" : "",
"SubType" : "AC",
"SwitchType" : "On/Off",
"SwitchTypeVal" : 0,
"Timers" : "true",
"Type" : "Lighting 2",
"TypeImg" : "lightbulb",
"Unit" : 1,
"Used" : 1,
"UsedByCamera" : false,
"XOffset" : "0",
"YOffset" : "0",
"idx" : "125"
},
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 0.0,
"AddjValue2" : 0.0,
"BatteryLevel" : 255,
"CustomImage" : 0,
"Data" : "Off",
"Description" : "",
"DimmerType" : "none",
"Favorite" : 1,
"HardwareID" : 10,
"HardwareName" : "Clé USB RFXCom",
"HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
"HardwareTypeVal" : 1,
"HaveDimmer" : true,
"HaveGroupCmd" : true,
"HaveTimeout" : false,
"ID" : "0FC7412",
"Image" : "Light",
"IsSubDevice" : false,
"LastUpdate" : "2019-10-30 18:13:32",
"Level" : 100,
"LevelInt" : 15,
"MaxDimLevel" : 15,
"Name" : "Prise amplificateur OLD",
"Notifications" : "false",
"PlanID" : "0",
"PlanIDs" : [ 0 ],
"Protected" : false,
"ShowNotifications" : true,
"SignalLevel" : "-",
"Status" : "Off",
"StrParam1" : "",
"StrParam2" : "",
"SubType" : "AC",
"SwitchType" : "On/Off",
"SwitchTypeVal" : 0,
"Timers" : "true",
"Type" : "Lighting 2",
"TypeImg" : "lightbulb",
"Unit" : 2,
"Used" : 1,
"UsedByCamera" : false,
"XOffset" : "0",
"YOffset" : "0",
"idx" : "356"
},
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 0.0,
"AddjValue2" : 0.0,
"BatteryLevel" : 255,
"CustomImage" : 0,
"Data" : "Closed",
"Description" : "",
"DimmerType" : "none",
"Favorite" : 1,
"HardwareID" : 10,
"HardwareName" : "Clé USB RFXCom",
"HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
"HardwareTypeVal" : 1,
"HaveDimmer" : false,
"HaveGroupCmd" : true,
"HaveTimeout" : false,
"ID" : "71",
"Image" : "Light",
"IsSubDevice" : false,
"LastUpdate" : "2019-11-18 17:27:01",
"Level" : 0,
"LevelInt" : 0,
"MaxDimLevel" : 0,
"Name" : "Volet voiture",
"Notifications" : "false",
"PlanID" : "0",
"PlanIDs" : [ 0 ],
"Protected" : false,
"ShowNotifications" : true,
"SignalLevel" : "-",
"Status" : "Closed",
"StrParam1" : "",
"StrParam2" : "",
"SubType" : "ARC",
"SwitchType" : "Blinds",
"SwitchTypeVal" : 3,
"Timers" : "false",
"Type" : "Lighting 1",
"TypeImg" : "blinds",
"Unit" : 2,
"Used" : 1,
"UsedByCamera" : false,
"XOffset" : "0",
"YOffset" : "0",
"idx" : "116"
},
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 0.0,
"AddjValue2" : 0.0,
"BatteryLevel" : 255,
"CustomImage" : 0,
"Data" : "47.2 C",
"Description" : "",
"Favorite" : 0,
"HardwareID" : 3,
"HardwareName" : "Motherboard",
"HardwareType" : "Motherboard sensors",
"HardwareTypeVal" : 23,
"HaveTimeout" : false,
"ID" : "0001",
"LastUpdate" : "2019-11-18 21:22:22",
"Name" : "Raspberry",
"Notifications" : "false",
"PlanID" : "0",
"PlanIDs" : [ 0 ],
"Protected" : false,
"ShowNotifications" : true,
"SignalLevel" : "-",
"SubType" : "LaCrosse TX3",
"Temp" : 47.200000000000003,
"Timers" : "false",
"Type" : "Temp",
"TypeImg" : "temperature",
"Unit" : 1,
"Used" : 1,
"XOffset" : "0",
"YOffset" : "0",
"idx" : "17",
"trend" : 3
},
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 0.0,
"AddjValue2" : 0.0,
"BatteryLevel" : 255,
"CustomImage" : 0,
"Data" : "Closed",
"Description" : "",
"DimmerType" : "none",
"Favorite" : 1,
"HardwareID" : 10,
"HardwareName" : "Clé USB RFXCom",
"HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
"HardwareTypeVal" : 1,
"HaveDimmer" : false,
"HaveGroupCmd" : true,
"HaveTimeout" : false,
"ID" : "71",
"Image" : "Light",
"IsSubDevice" : false,
"LastUpdate" : "2019-11-18 17:29:03",
"Level" : 0,
"LevelInt" : 0,
"MaxDimLevel" : 0,
"Name" : "Volet cuisine",
"Notifications" : "false",
"PlanID" : "0",
"PlanIDs" : [ 0 ],
"Protected" : false,
"ShowNotifications" : true,
"SignalLevel" : "-",
"Status" : "Closed",
"StrParam1" : "",
"StrParam2" : "",
"SubType" : "ARC",
"SwitchType" : "Blinds",
"SwitchTypeVal" : 3,
"Timers" : "false",
"Type" : "Lighting 1",
"TypeImg" : "blinds",
"Unit" : 1,
"Used" : 1,
"UsedByCamera" : false,
"XOffset" : "0",
"YOffset" : "0",
"idx" : "115"
},
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 0.0,
"AddjValue2" : 0.0,
"BatteryLevel" : 255,
"CustomImage" : 0,
"Data" : "Closed",
"Description" : "",
"DimmerType" : "none",
"Favorite" : 1,
"HardwareID" : 10,
"HardwareName" : "Clé USB RFXCom",
"HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
"HardwareTypeVal" : 1,
"HaveDimmer" : false,
"HaveGroupCmd" : true,
"HaveTimeout" : false,
"ID" : "71",
"Image" : "Light",
"IsSubDevice" : false,
"LastUpdate" : "2019-11-18 17:29:01",
"Level" : 0,
"LevelInt" : 0,
"MaxDimLevel" : 0,
"Name" : "Volet salon",
"Notifications" : "false",
"PlanID" : "0",
"PlanIDs" : [ 0 ],
"Protected" : false,
"ShowNotifications" : true,
"SignalLevel" : "-",
"Status" : "Closed",
"StrParam1" : "",
"StrParam2" : "",
"SubType" : "ARC",
"SwitchType" : "Blinds",
"SwitchTypeVal" : 3,
"Timers" : "false",
"Type" : "Lighting 1",
"TypeImg" : "blinds",
"Unit" : 3,
"Used" : 1,
"UsedByCamera" : false,
"XOffset" : "0",
"YOffset" : "0",
"idx" : "120"
},
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 0.0,
"AddjValue2" : 0.0,
"BatteryLevel" : 255,
"CustomImage" : 0,
"Data" : "Closed",
"Description" : "",
"DimmerType" : "none",
"Favorite" : 1,
"HardwareID" : 10,
"HardwareName" : "Clé USB RFXCom",
"HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
"HardwareTypeVal" : 1,
"HaveDimmer" : false,
"HaveGroupCmd" : true,
"HaveTimeout" : false,
"ID" : "71",
"Image" : "Light",
"IsSubDevice" : false,
"LastUpdate" : "2019-11-18 17:29:03",
"Level" : 0,
"LevelInt" : 0,
"MaxDimLevel" : 0,
"Name" : "Volet voisin",
"Notifications" : "false",
"PlanID" : "0",
"PlanIDs" : [ 0 ],
"Protected" : false,
"ShowNotifications" : true,
"SignalLevel" : "-",
"Status" : "Closed",
"StrParam1" : "",
"StrParam2" : "",
"SubType" : "ARC",
"SwitchType" : "Blinds",
"SwitchTypeVal" : 3,
"Timers" : "false",
"Type" : "Lighting 1",
"TypeImg" : "blinds",
"Unit" : 4,
"Used" : 1,
"UsedByCamera" : false,
"XOffset" : "0",
"YOffset" : "0",
"idx" : "121"
},
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 0.0,
"AddjValue2" : 0.0,
"BatteryLevel" : 255,
"CustomImage" : 0,
"Data" : "Closed",
"Description" : "",
"DimmerType" : "none",
"Favorite" : 1,
"HardwareID" : 10,
"HardwareName" : "Clé USB RFXCom",
"HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
"HardwareTypeVal" : 1,
"HaveDimmer" : true,
"HaveGroupCmd" : true,
"HaveTimeout" : false,
"ID" : "2060805",
"Image" : "Light",
"IsSubDevice" : false,
"LastUpdate" : "2019-11-18 17:27:01",
"Level" : 0,
"LevelInt" : 0,
"MaxDimLevel" : 15,
"Name" : "Volet chambre",
"Notifications" : "false",
"PlanID" : "0",
"PlanIDs" : [ 0 ],
"Protected" : false,
"ShowNotifications" : true,
"SignalLevel" : "-",
"Status" : "Closed",
"StrParam1" : "",
"StrParam2" : "",
"SubType" : "AC",
"SwitchType" : "Blinds Inverted",
"SwitchTypeVal" : 6,
"Timers" : "false",
"Type" : "Lighting 2",
"TypeImg" : "blinds",
"Unit" : 4,
"Used" : 1,
"UsedByCamera" : false,
"XOffset" : "0",
"YOffset" : "0",
"idx" : "298"
},
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 0.0,
"AddjValue2" : 0.0,
"BatteryLevel" : 255,
"CustomImage" : 0,
"Data" : "Closed",
"Description" : "",
"DimmerType" : "none",
"Favorite" : 1,
"HardwareID" : 10,
"HardwareName" : "Clé USB RFXCom",
"HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
"HardwareTypeVal" : 1,
"HaveDimmer" : true,
"HaveGroupCmd" : true,
"HaveTimeout" : false,
"ID" : "139D2D6",
"Image" : "Light",
"IsSubDevice" : false,
"LastUpdate" : "2019-11-18 17:29:03",
"Level" : 100,
"LevelInt" : 15,
"MaxDimLevel" : 15,
"Name" : "Volet bureau",
"Notifications" : "false",
"PlanID" : "0",
"PlanIDs" : [ 0 ],
"Protected" : false,
"ShowNotifications" : true,
"SignalLevel" : "-",
"Status" : "Closed",
"StrParam1" : "",
"StrParam2" : "",
"SubType" : "AC",
"SwitchType" : "Blinds",
"SwitchTypeVal" : 3,
"Timers" : "false",
"Type" : "Lighting 2",
"TypeImg" : "blinds",
"Unit" : 1,
"Used" : 1,
"UsedByCamera" : false,
"XOffset" : "0",
"YOffset" : "0",
"idx" : "173"
},
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 300.0,
"AddjValue2" : 0.0,
"BatteryLevel" : 255,
"CustomImage" : 0,
"Data" : "Off",
"Description" : "",
"DimmerType" : "none",
"Favorite" : 1,
"HardwareID" : 10,
"HardwareName" : "Clé USB RFXCom",
"HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
"HardwareTypeVal" : 1,
"HaveDimmer" : true,
"HaveGroupCmd" : true,
"HaveTimeout" : false,
"ID" : "0A1F932",
"Image" : "Light",
"IsSubDevice" : false,
"LastUpdate" : "2019-11-18 21:07:03",
"Level" : 0,
"LevelInt" : 0,
"MaxDimLevel" : 15,
"Name" : "Detecteur Salon",
"Notifications" : "false",
"PlanID" : "0",
"PlanIDs" : [ 0 ],
"Protected" : false,
"ShowNotifications" : true,
"SignalLevel" : 5,
"Status" : "Off",
"StrParam1" : "",
"StrParam2" : "",
"SubType" : "AC",
"SwitchType" : "Motion Sensor",
"SwitchTypeVal" : 8,
"Timers" : "false",
"Type" : "Lighting 2",
"TypeImg" : "motion",
"Unit" : 10,
"Used" : 1,
"UsedByCamera" : false,
"XOffset" : "0",
"YOffset" : "0",
"idx" : "111"
},
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 60.0,
"AddjValue2" : 0.0,
"BatteryLevel" : 255,
"CustomImage" : 0,
"Data" : "Off",
"Description" : "",
"DimmerType" : "none",
"Favorite" : 1,
"HardwareID" : 10,
"HardwareName" : "Clé USB RFXCom",
"HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
"HardwareTypeVal" : 1,
"HaveDimmer" : true,
"HaveGroupCmd" : true,
"HaveTimeout" : false,
"ID" : "0A3135A",
"Image" : "Light",
"IsSubDevice" : false,
"LastUpdate" : "2019-11-18 20:55:40",
"Level" : 0,
"LevelInt" : 0,
"MaxDimLevel" : 15,
"Name" : "Detecteur exterieur",
"Notifications" : "false",
"PlanID" : "0",
"PlanIDs" : [ 0 ],
"Protected" : false,
"ShowNotifications" : true,
"SignalLevel" : 6,
"Status" : "Off",
"StrParam1" : "",
"StrParam2" : "",
"SubType" : "AC",
"SwitchType" : "Motion Sensor",
"SwitchTypeVal" : 8,
"Timers" : "false",
"Type" : "Lighting 2",
"TypeImg" : "motion",
"Unit" : 10,
"Used" : 1,
"UsedByCamera" : false,
"XOffset" : "0",
"YOffset" : "0",
"idx" : "424"
},
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 0.0,
"AddjValue2" : 0.0,
"BatteryLevel" : 255,
"CustomImage" : 0,
"Data" : "Off",
"Description" : "",
"DimmerType" : "abs",
"Favorite" : 0,
"HardwareID" : 10,
"HardwareName" : "Clé USB RFXCom",
"HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
"HardwareTypeVal" : 1,
"HaveDimmer" : true,
"HaveGroupCmd" : true,
"HaveTimeout" : false,
"ID" : "208015E",
"Image" : "Light",
"IsSubDevice" : false,
"LastUpdate" : "2019-11-18 08:16:01",
"Level" : 86,
"LevelInt" : 13,
"MaxDimLevel" : 15,
"Name" : "Spot 1",
"Notifications" : "false",
"PlanID" : "2",
"PlanIDs" : [ 2 ],
"Protected" : false,
"ShowNotifications" : true,
"SignalLevel" : "-",
"Status" : "Off",
"StrParam1" : "",
"StrParam2" : "",
"SubType" : "AC",
"SwitchType" : "Dimmer",
"SwitchTypeVal" : 7,
"Timers" : "true",
"Type" : "Lighting 2",
"TypeImg" : "dimmer",
"Unit" : 8,
"Used" : 1,
"UsedByCamera" : false,
"XOffset" : "0",
"YOffset" : "0",
"idx" : "169"
},
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 0.0,
"AddjValue2" : 0.0,
"BatteryLevel" : 255,
"CustomImage" : 0,
"Data" : "Off",
"Description" : "",
"DimmerType" : "abs",
"Favorite" : 0,
"HardwareID" : 10,
"HardwareName" : "Clé USB RFXCom",
"HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
"HardwareTypeVal" : 1,
"HaveDimmer" : true,
"HaveGroupCmd" : true,
"HaveTimeout" : false,
"ID" : "215620B",
"Image" : "Light",
"IsSubDevice" : false,
"LastUpdate" : "2019-11-18 08:16:01",
"Level" : 86,
"LevelInt" : 13,
"MaxDimLevel" : 15,
"Name" : "Spot 2",
"Notifications" : "false",
"PlanID" : "2",
"PlanIDs" : [ 2 ],
"Protected" : false,
"ShowNotifications" : true,
"SignalLevel" : "-",
"Status" : "Off",
"StrParam1" : "",
"StrParam2" : "",
"SubType" : "AC",
"SwitchType" : "Dimmer",
"SwitchTypeVal" : 7,
"Timers" : "true",
"Type" : "Lighting 2",
"TypeImg" : "dimmer",
"Unit" : 2,
"Used" : 1,
"UsedByCamera" : false,
"XOffset" : "0",
"YOffset" : "0",
"idx" : "166"
},
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 0.0,
"AddjValue2" : 0.0,
"BatteryLevel" : 255,
"CustomImage" : 0,
"Data" : "Off",
"Description" : "",
"DimmerType" : "abs",
"Favorite" : 0,
"HardwareID" : 10,
"HardwareName" : "Clé USB RFXCom",
"HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
"HardwareTypeVal" : 1,
"HaveDimmer" : true,
"HaveGroupCmd" : true,
"HaveTimeout" : false,
"ID" : "20B4761",
"Image" : "Light",
"IsSubDevice" : false,
"LastUpdate" : "2019-11-18 08:16:01",
"Level" : 86,
"LevelInt" : 13,
"MaxDimLevel" : 15,
"Name" : "Spot 3",
"Notifications" : "false",
"PlanID" : "2",
"PlanIDs" : [ 2 ],
"Protected" : false,
"ShowNotifications" : true,
"SignalLevel" : "-",
"Status" : "Off",
"StrParam1" : "",
"StrParam2" : "",
"SubType" : "AC",
"SwitchType" : "Dimmer",
"SwitchTypeVal" : 7,
"Timers" : "true",
"Type" : "Lighting 2",
"TypeImg" : "dimmer",
"Unit" : 12,
"Used" : 1,
"UsedByCamera" : false,
"XOffset" : "0",
"YOffset" : "0",
"idx" : "168"
},
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 0.0,
"AddjValue2" : 0.0,
"BatteryLevel" : 255,
"CustomImage" : 0,
"Data" : "10%",
"Description" : "",
"Favorite" : 0,
"HardwareID" : 14,
"HardwareName" : "Teleinfo",
"HardwareType" : "Teleinfo EDF",
"HardwareTypeVal" : 19,
"HaveTimeout" : false,
"ID" : "00000001",
"Image" : "Computer",
"LastUpdate" : "2019-11-18 21:22:43",
"Name" : "Pourcentage de Charge",
"Notifications" : "false",
"PlanID" : "0",
"PlanIDs" : [ 0 ],
"Protected" : false,
"ShowNotifications" : true,
"SignalLevel" : "-",
"SubType" : "Percentage",
"Timers" : "false",
"Type" : "General",
"TypeImg" : "hardware",
"Unit" : 1,
"Used" : 1,
"XOffset" : "0",
"YOffset" : "0",
"idx" : "307"
},
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 0.0,
"AddjValue2" : 0.0,
"BatteryLevel" : 255,
"CustomImage" : 0,
"Data" : "Normal",
"Description" : "",
"Favorite" : 0,
"HardwareID" : 10,
"HardwareName" : "Clé USB RFXCom",
"HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
"HardwareTypeVal" : 1,
"HaveDimmer" : false,
"HaveGroupCmd" : false,
"HaveTimeout" : false,
"ID" : "D54300",
"LastUpdate" : "2019-11-13 12:45:50",
"MaxDimLevel" : 0,
"Name" : "Détecteur fumée salon",
"Notifications" : "true",
"PlanID" : "0",
"PlanIDs" : [ 0 ],
"Protected" : false,
"ShowNotifications" : true,
"SignalLevel" : 6,
"Status" : "Normal",
"StrParam1" : "",
"StrParam2" : "",
"SubType" : "KD101 smoke detector",
"SwitchType" : "Smoke Detector",
"SwitchTypeVal" : 5,
"Timers" : "false",
"Type" : "Security",
"TypeImg" : "smoke",
"Unit" : 0,
"Used" : 1,
"XOffset" : "0",
"YOffset" : "0",
"idx" : "372"
},
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 0.0,
"AddjValue2" : 0.0,
"BatteryLevel" : 255,
"CustomImage" : 0,
"Data" : "Normal",
"Description" : "",
"Favorite" : 0,
"HardwareID" : 10,
"HardwareName" : "Clé USB RFXCom",
"HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
"HardwareTypeVal" : 1,
"HaveDimmer" : false,
"HaveGroupCmd" : false,
"HaveTimeout" : false,
"ID" : "F24D00",
"LastUpdate" : "2019-07-27 10:30:40",
"MaxDimLevel" : 0,
"Name" : "Détecteur fumée escalier",
"Notifications" : "true",
"PlanID" : "0",
"PlanIDs" : [ 0 ],
"Protected" : false,
"ShowNotifications" : true,
"SignalLevel" : "-",
"Status" : "Normal",
"StrParam1" : "",
"StrParam2" : "",
"SubType" : "KD101 smoke detector",
"SwitchType" : "Smoke Detector",
"SwitchTypeVal" : 5,
"Timers" : "false",
"Type" : "Security",
"TypeImg" : "smoke",
"Unit" : 0,
"Used" : 1,
"XOffset" : "0",
"YOffset" : "0",
"idx" : "400"
},
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 0.0,
"AddjValue2" : 0.0,
"BatteryLevel" : 255,
"CustomImage" : 7,
"Data" : "Off",
"Description" : "",
"DimmerType" : "none",
"Favorite" : 0,
"HardwareID" : 10,
"HardwareName" : "Clé USB RFXCom",
"HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
"HardwareTypeVal" : 1,
"HaveDimmer" : true,
"HaveGroupCmd" : true,
"HaveTimeout" : false,
"ID" : "0FC7412",
"Image" : "Fan",
"IsSubDevice" : false,
"LastUpdate" : "2018-11-02 10:15:28",
"Level" : 0,
"LevelInt" : 0,
"MaxDimLevel" : 15,
"Name" : "Ventilateur Garage",
"Notifications" : "false",
"PlanID" : "0",
"PlanIDs" : [ 0 ],
"Protected" : false,
"ShowNotifications" : true,
"SignalLevel" : 6,
"Status" : "Off",
"StrParam1" : "",
"StrParam2" : "",
"SubType" : "AC",
"SwitchType" : "On/Off",
"SwitchTypeVal" : 0,
"Timers" : "false",
"Type" : "Lighting 2",
"TypeImg" : "lightbulb",
"Unit" : 1,
"Used" : 1,
"UsedByCamera" : false,
"XOffset" : "0",
"YOffset" : "0",
"idx" : "379"
},
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 0.0,
"AddjValue2" : 0.0,
"BatteryLevel" : 0,
"CustomImage" : 0,
"Data" : "7.7 C, 72 %",
"Description" : "",
"DewPoint" : "2.97",
"Favorite" : 1,
"HardwareID" : 10,
"HardwareName" : "Clé USB RFXCom",
"HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
"HardwareTypeVal" : 1,
"HaveTimeout" : false,
"Humidity" : 72,
"HumidityStatus" : "Wet",
"ID" : "A501",
"LastUpdate" : "2019-11-18 21:22:44",
"Name" : "Garage",
"Notifications" : "true",
"PlanID" : "0",
"PlanIDs" : [ 0 ],
"Protected" : false,
"ShowNotifications" : true,
"SignalLevel" : 6,
"SubType" : "THGN122/123/132, THGR122/228/238/268",
"Temp" : 7.7000000000000002,
"Timers" : "false",
"Type" : "Temp + Humidity",
"TypeImg" : "temperature",
"Unit" : 1,
"Used" : 1,
"XOffset" : "0",
"YOffset" : "0",
"idx" : "382",
"trend" : 3
},
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 0.5,
"AddjValue2" : 0.0,
"BatteryLevel" : 255,
"CustomImage" : 0,
"Data" : "19.1 C",
"Description" : "",
"Favorite" : 0,
"HardwareID" : 2,
"HardwareName" : "Clé USB Zwave",
"HardwareType" : "OpenZWave USB",
"HardwareTypeVal" : 21,
"HaveTimeout" : false,
"ID" : "0601",
"LastUpdate" : "2019-11-18 21:21:34",
"Name" : "Température radiateur Emma",
"Notifications" : "false",
"PlanID" : "0",
"PlanIDs" : [ 0 ],
"Protected" : false,
"ShowNotifications" : true,
"SignalLevel" : "-",
"SubType" : "LaCrosse TX3",
"Temp" : 19.100000000000001,
"Timers" : "false",
"Type" : "Temp",
"TypeImg" : "temperature",
"Unit" : 1,
"Used" : 1,
"XOffset" : "0",
"YOffset" : "0",
"idx" : "383",
"trend" : 3
},
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 0.0,
"AddjValue2" : 0.0,
"BatteryLevel" : 255,
"CustomImage" : 0,
"Data" : "Heat",
"Description" : "",
"Favorite" : 0,
"HardwareID" : 2,
"HardwareName" : "Clé USB Zwave",
"HardwareType" : "OpenZWave USB",
"HardwareTypeVal" : 21,
"HaveTimeout" : true,
"ID" : "00000C01",
"LastUpdate" : "2019-11-18 06:00:49",
"Mode" : 1,
"Modes" : "0;Off;1;Heat;",
"Name" : "Chauffage SDB",
"Notifications" : "false",
"PlanID" : "0",
"PlanIDs" : [ 0 ],
"Protected" : false,
"ShowNotifications" : true,
"SignalLevel" : "-",
"SubType" : "Thermostat Mode",
"Timers" : "false",
"Type" : "General",
"TypeImg" : "mode",
"Unit" : 1,
"Used" : 1,
"XOffset" : "0",
"YOffset" : "0",
"idx" : "386"
},
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 0.0,
"AddjValue2" : 0.0,
"BatteryLevel" : 255,
"CustomImage" : 0,
"Data" : "10.0",
"Description" : "",
"Favorite" : 0,
"HardwareID" : 2,
"HardwareName" : "Clé USB Zwave",
"HardwareType" : "OpenZWave USB",
"HardwareTypeVal" : 21,
"HaveTimeout" : false,
"ID" : "0000C01",
"LastUpdate" : "2019-11-18 21:23:00",
"Name" : "Radiateur SDB",
"Notifications" : "false",
"PlanID" : "0",
"PlanIDs" : [ 0 ],
"Protected" : false,
"SetPoint" : "10.0",
"ShowNotifications" : true,
"SignalLevel" : "-",
"SubType" : "SetPoint",
"Timers" : "true",
"Type" : "Thermostat",
"TypeImg" : "override_mini",
"Unit" : 1,
"Used" : 1,
"XOffset" : "0",
"YOffset" : "0",
"idx" : "387"
},
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 0.0,
"AddjValue2" : 0.0,
"BatteryLevel" : 255,
"CustomImage" : 0,
"Data" : "Off",
"Description" : "",
"DimmerType" : "none",
"Favorite" : 0,
"HardwareID" : 5,
"HardwareName" : "Virtual HW",
"HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
"HardwareTypeVal" : 15,
"HaveDimmer" : true,
"HaveGroupCmd" : true,
"HaveTimeout" : false,
"ID" : "000141DD",
"Image" : "Light",
"IsSubDevice" : false,
"LastUpdate" : "2019-11-04 07:12:21",
"Level" : 0,
"LevelInt" : 0,
"MaxDimLevel" : 100,
"Name" : "Vacances scolaires",
"Notifications" : "false",
"PlanID" : "0",
"PlanIDs" : [ 0 ],
"Protected" : false,
"ShowNotifications" : true,
"SignalLevel" : "-",
"Status" : "Off",
"StrParam1" : "",
"StrParam2" : "",
"SubType" : "Switch",
"SwitchType" : "On/Off",
"SwitchTypeVal" : 0,
"Timers" : "false",
"Type" : "Light/Switch",
"TypeImg" : "lightbulb",
"Unit" : 1,
"Used" : 1,
"UsedByCamera" : false,
"XOffset" : "0",
"YOffset" : "0",
"idx" : "397"
},
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 0.0,
"AddjValue2" : 0.0,
"BatteryLevel" : 255,
"CustomImage" : 0,
"Data" : "Off",
"Description" : "",
"DimmerType" : "none",
"Favorite" : 0,
"HardwareID" : 5,
"HardwareName" : "Virtual HW",
"HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
"HardwareTypeVal" : 15,
"HaveDimmer" : true,
"HaveGroupCmd" : true,
"HaveTimeout" : false,
"ID" : "000141DE",
"Image" : "Light",
"IsSubDevice" : false,
"LastUpdate" : "2019-10-31 15:15:03",
"Level" : 0,
"LevelInt" : 0,
"MaxDimLevel" : 100,
"Name" : "Vacances Famille",
"Notifications" : "false",
"PlanID" : "0",
"PlanIDs" : [ 0 ],
"Protected" : false,
"ShowNotifications" : true,
"SignalLevel" : "-",
"Status" : "Off",
"StrParam1" : "",
"StrParam2" : "",
"SubType" : "Switch",
"SwitchType" : "On/Off",
"SwitchTypeVal" : 0,
"Timers" : "false",
"Type" : "Light/Switch",
"TypeImg" : "lightbulb",
"Unit" : 1,
"Used" : 1,
"UsedByCamera" : false,
"XOffset" : "0",
"YOffset" : "0",
"idx" : "398"
},
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 0.0,
"AddjValue2" : 0.0,
"BatteryLevel" : 255,
"CustomImage" : 0,
"Data" : "On",
"Description" : "",
"DimmerType" : "none",
"Favorite" : 0,
"HardwareID" : 10,
"HardwareName" : "Clé USB RFXCom",
"HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
"HardwareTypeVal" : 1,
"HaveDimmer" : true,
"HaveGroupCmd" : true,
"HaveTimeout" : false,
"ID" : "1CC4DD2",
"Image" : "Light",
"IsSubDevice" : false,
"LastUpdate" : "2019-11-15 20:02:45",
"Level" : 0,
"LevelInt" : 0,
"MaxDimLevel" : 15,
"Name" : "Sonnette",
"Notifications" : "true",
"PlanID" : "0",
"PlanIDs" : [ 0 ],
"Protected" : false,
"ShowNotifications" : true,
"SignalLevel" : 7,
"Status" : "",
"StrParam1" : "",
"StrParam2" : "",
"SubType" : "AC",
"SwitchType" : "Doorbell",
"SwitchTypeVal" : 1,
"Timers" : "false",
"Type" : "Lighting 2",
"TypeImg" : "doorbell",
"Unit" : 1,
"Used" : 1,
"UsedByCamera" : false,
"XOffset" : "0",
"YOffset" : "0",
"idx" : "399"
},
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 0.0,
"AddjValue2" : 0.0,
"BatteryLevel" : 255,
"CustomImage" : 0,
"Data" : "On",
"Description" : "",
"DimmerType" : "none",
"Favorite" : 1,
"HardwareID" : 2,
"HardwareName" : "Clé USB Zwave",
"HardwareType" : "OpenZWave USB",
"HardwareTypeVal" : 21,
"HaveDimmer" : true,
"HaveGroupCmd" : true,
"HaveTimeout" : false,
"ID" : "00000701",
"Image" : "Light",
"IsSubDevice" : false,
"LastUpdate" : "2019-11-18 17:27:01",
"Level" : 100,
"LevelInt" : 100,
"MaxDimLevel" : 100,
"Name" : "Lumière escalier",
"Notifications" : "false",
"PlanID" : "0",
"PlanIDs" : [ 0 ],
"Protected" : false,
"ShowNotifications" : true,
"SignalLevel" : "-",
"Status" : "On",
"StrParam1" : "",
"StrParam2" : "",
"SubType" : "Switch",
"SwitchType" : "On/Off",
"SwitchTypeVal" : 0,
"Timers" : "true",
"Type" : "Light/Switch",
"TypeImg" : "lightbulb",
"Unit" : 1,
"Used" : 1,
"UsedByCamera" : false,
"XOffset" : "0",
"YOffset" : "0",
"idx" : "153"
},
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 0.0,
"AddjValue2" : 30.0,
"BatteryLevel" : 255,
"CustomImage" : 9,
"Data" : "On",
"Description" : "http://192.168.1.251/cgi-bin/tts?voice=julie&text=Allumage%20alarme%20&nocache=0\nhttp://192.168.1.251/cgi-bin/tts?voice=julie&text=Exctinction%20alarme%20&nocache=0",
"DimmerType" : "none",
"Favorite" : 0,
"HardwareID" : 10,
"HardwareName" : "Clé USB RFXCom",
"HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
"HardwareTypeVal" : 1,
"HaveDimmer" : true,
"HaveGroupCmd" : true,
"HaveTimeout" : false,
"ID" : "1149C4E",
"Image" : "Generic",
"IsSubDevice" : false,
"LastUpdate" : "2019-11-18 13:50:43",
"Level" : 100,
"LevelInt" : 15,
"MaxDimLevel" : 15,
"Name" : "Bouton Portail",
"Notifications" : "false",
"PlanID" : "0",
"PlanIDs" : [ 0 ],
"Protected" : false,
"ShowNotifications" : true,
"SignalLevel" : 7,
"Status" : "On",
"StrParam1" : "",
"StrParam2" : "",
"SubType" : "AC",
"SwitchType" : "On/Off",
"SwitchTypeVal" : 0,
"Timers" : "true",
"Type" : "Lighting 2",
"TypeImg" : "lightbulb",
"Unit" : 11,
"Used" : 1,
"UsedByCamera" : false,
"XOffset" : "0",
"YOffset" : "0",
"idx" : "113"
},
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 0.0,
"AddjValue2" : 0.0,
"BatteryLevel" : 255,
"CustomImage" : 0,
"Data" : "22.6 C",
"Description" : "",
"Favorite" : 0,
"HardwareID" : 2,
"HardwareName" : "Clé USB Zwave",
"HardwareType" : "OpenZWave USB",
"HardwareTypeVal" : 21,
"HaveTimeout" : true,
"ID" : "0C01",
"LastUpdate" : "2019-09-20 00:29:34",
"Name" : "Temperature SDB",
"Notifications" : "false",
"PlanID" : "0",
"PlanIDs" : [ 0 ],
"Protected" : false,
"ShowNotifications" : true,
"SignalLevel" : "-",
"SubType" : "LaCrosse TX3",
"Temp" : 22.600000000000001,
"Timers" : "false",
"Type" : "Temp",
"TypeImg" : "temperature",
"Unit" : 1,
"Used" : 1,
"XOffset" : "0",
"YOffset" : "0",
"idx" : "409",
"trend" : 0
},
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 0.0,
"AddjValue2" : 0.0,
"BatteryLevel" : 255,
"CustomImage" : 0,
"Data" : "Off",
"Description" : "",
"DimmerType" : "none",
"Favorite" : 0,
"HardwareID" : 5,
"HardwareName" : "Virtual HW",
"HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
"HardwareTypeVal" : 15,
"HaveDimmer" : true,
"HaveGroupCmd" : true,
"HaveTimeout" : false,
"ID" : "000141EE",
"Image" : "Light",
"IsSubDevice" : false,
"LastUpdate" : "2019-11-18 06:00:26",
"Level" : 0,
"LevelInt" : 0,
"MaxDimLevel" : 100,
"Name" : "Beacon Orange",
"Notifications" : "false",
"PlanID" : "0",
"PlanIDs" : [ 0 ],
"Protected" : false,
"ShowNotifications" : true,
"SignalLevel" : "-",
"Status" : "Off",
"StrParam1" : "",
"StrParam2" : "",
"SubType" : "Switch",
"SwitchType" : "On/Off",
"SwitchTypeVal" : 0,
"Timers" : "false",
"Type" : "Light/Switch",
"TypeImg" : "lightbulb",
"Unit" : 1,
"Used" : 1,
"UsedByCamera" : false,
"XOffset" : "0",
"YOffset" : "0",
"idx" : "414"
},
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 0.0,
"AddjValue2" : 0.0,
"BatteryLevel" : 255,
"CustomImage" : 0,
"Data" : "On",
"Description" : "",
"DimmerType" : "none",
"Favorite" : 0,
"HardwareID" : 5,
"HardwareName" : "Virtual HW",
"HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
"HardwareTypeVal" : 15,
"HaveDimmer" : true,
"HaveGroupCmd" : true,
"HaveTimeout" : false,
"ID" : "000141EF",
"Image" : "Light",
"IsSubDevice" : false,
"LastUpdate" : "2019-11-18 19:25:02",
"Level" : 0,
"LevelInt" : 0,
"MaxDimLevel" : 100,
"Name" : "Simon",
"Notifications" : "false",
"PlanID" : "0",
"PlanIDs" : [ 0 ],
"Protected" : false,
"ShowNotifications" : true,
"SignalLevel" : "-",
"Status" : "On",
"StrParam1" : "",
"StrParam2" : "",
"SubType" : "Switch",
"SwitchType" : "On/Off",
"SwitchTypeVal" : 0,
"Timers" : "false",
"Type" : "Light/Switch",
"TypeImg" : "lightbulb",
"Unit" : 1,
"Used" : 1,
"UsedByCamera" : false,
"XOffset" : "0",
"YOffset" : "0",
"idx" : "415"
},
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 0.0,
"AddjValue2" : 0.0,
"BatteryLevel" : 0,
"CustomImage" : 0,
"Data" : "22.9 C",
"Description" : "",
"Favorite" : 0,
"HardwareID" : 10,
"HardwareName" : "Clé USB RFXCom",
"HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
"HardwareTypeVal" : 1,
"HaveTimeout" : true,
"ID" : "4001",
"LastUpdate" : "2019-08-16 18:15:10",
"Name" : "Température chambre Robin",
"Notifications" : "false",
"PlanID" : "0",
"PlanIDs" : [ 0 ],
"Protected" : false,
"ShowNotifications" : true,
"SignalLevel" : 6,
"SubType" : "THC238/268, THN132, THWR288, THRN122, THN122, AW129/131",
"Temp" : 22.899999999999999,
"Timers" : "false",
"Type" : "Temp",
"TypeImg" : "temperature",
"Unit" : 1,
"Used" : 1,
"XOffset" : "0",
"YOffset" : "0",
"idx" : "420",
"trend" : 0
},
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 0.5,
"AddjValue2" : 0.0,
"BatteryLevel" : 255,
"CustomImage" : 0,
"Data" : "20.3 C",
"Description" : "",
"Favorite" : 0,
"HardwareID" : 2,
"HardwareName" : "Clé USB Zwave",
"HardwareType" : "OpenZWave USB",
"HardwareTypeVal" : 21,
"HaveTimeout" : false,
"ID" : "0F01",
"LastUpdate" : "2019-11-18 21:22:42",
"Name" : "Température radiateur Robin",
"Notifications" : "false",
"PlanID" : "0",
"PlanIDs" : [ 0 ],
"Protected" : false,
"ShowNotifications" : true,
"SignalLevel" : "-",
"SubType" : "LaCrosse TX3",
"Temp" : 20.300000000000001,
"Timers" : "false",
"Type" : "Temp",
"TypeImg" : "temperature",
"Unit" : 1,
"Used" : 1,
"XOffset" : "0",
"YOffset" : "0",
"idx" : "421",
"trend" : 2
},
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 0.0,
"AddjValue2" : 0.0,
"BatteryLevel" : 255,
"Color" : "{\"b\":0,\"cw\":98,\"g\":0,\"m\":2,\"r\":0,\"t\":157,\"ww\":157}",
"CustomImage" : 0,
"Data" : "Set Color",
"Description" : "",
"DimmerType" : "abs",
"Favorite" : 0,
"HardwareID" : 16,
"HardwareName" : "Hue Bridge",
"HardwareType" : "Philips Hue Bridge",
"HardwareTypeVal" : 38,
"HaveDimmer" : true,
"HaveGroupCmd" : false,
"HaveTimeout" : false,
"ID" : "1",
"Image" : "Light",
"IsSubDevice" : false,
"LastUpdate" : "2019-11-18 06:00:21",
"Level" : 100,
"LevelInt" : 100,
"MaxDimLevel" : 100,
"Name" : "Lumière télé",
"Notifications" : "false",
"PlanID" : "0",
"PlanIDs" : [ 0 ],
"Protected" : false,
"ShowNotifications" : true,
"SignalLevel" : "-",
"Status" : "Set Level: 100 %",
"StrParam1" : "",
"StrParam2" : "",
"SubType" : "RGBWW",
"SwitchType" : "Dimmer",
"SwitchTypeVal" : 7,
"Timers" : "false",
"Type" : "Color Switch",
"TypeImg" : "dimmer",
"Unit" : 1,
"Used" : 1,
"UsedByCamera" : false,
"XOffset" : "0",
"YOffset" : "0",
"idx" : "425"
},
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 0.0,
"AddjValue2" : 0.0,
"BatteryLevel" : 255,
"Color" : "{\"b\":0,\"cw\":98,\"g\":0,\"m\":2,\"r\":0,\"t\":157,\"ww\":157}",
"CustomImage" : 0,
"Data" : "Set Color",
"Description" : "",
"DimmerType" : "abs",
"Favorite" : 0,
"HardwareID" : 16,
"HardwareName" : "Hue Bridge",
"HardwareType" : "Philips Hue Bridge",
"HardwareTypeVal" : 38,
"HaveDimmer" : true,
"HaveGroupCmd" : false,
"HaveTimeout" : false,
"ID" : "00000002",
"Image" : "Light",
"IsSubDevice" : false,
"LastUpdate" : "2019-11-18 19:28:00",
"Level" : 100,
"LevelInt" : 100,
"MaxDimLevel" : 100,
"Name" : "Lumière canapé",
"Notifications" : "false",
"PlanID" : "0",
"PlanIDs" : [ 0 ],
"Protected" : false,
"ShowNotifications" : true,
"SignalLevel" : "-",
"Status" : "Set Level: 100 %",
"StrParam1" : "",
"StrParam2" : "",
"SubType" : "RGBWW",
"SwitchType" : "Dimmer",
"SwitchTypeVal" : 7,
"Timers" : "false",
"Type" : "Color Switch",
"TypeImg" : "dimmer",
"Unit" : 1,
"Used" : 1,
"UsedByCamera" : false,
"XOffset" : "0",
"YOffset" : "0",
"idx" : "426"
},
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 0.0,
"AddjValue2" : 0.0,
"BatteryLevel" : 255,
"Color" : "{\"b\":0,\"cw\":98,\"g\":0,\"m\":2,\"r\":0,\"t\":157,\"ww\":157}",
"CustomImage" : 0,
"Data" : "Set Color",
"Description" : "",
"DimmerType" : "abs",
"Favorite" : 0,
"HardwareID" : 16,
"HardwareName" : "Hue Bridge",
"HardwareType" : "Philips Hue Bridge",
"HardwareTypeVal" : 38,
"HaveDimmer" : true,
"HaveGroupCmd" : false,
"HaveTimeout" : false,
"ID" : "00000005",
"Image" : "Light",
"IsSubDevice" : false,
"LastUpdate" : "2019-11-18 06:00:21",
"Level" : 100,
"LevelInt" : 100,
"MaxDimLevel" : 100,
"Name" : "Spot bureau 1",
"Notifications" : "false",
"PlanID" : "0",
"PlanIDs" : [ 0 ],
"Protected" : false,
"ShowNotifications" : true,
"SignalLevel" : "-",
"Status" : "Set Level: 100 %",
"StrParam1" : "",
"StrParam2" : "",
"SubType" : "WW",
"SwitchType" : "Dimmer",
"SwitchTypeVal" : 7,
"Timers" : "false",
"Type" : "Color Switch",
"TypeImg" : "dimmer",
"Unit" : 1,
"Used" : 1,
"UsedByCamera" : false,
"XOffset" : "0",
"YOffset" : "0",
"idx" : "429"
},
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 0.0,
"AddjValue2" : 0.0,
"BatteryLevel" : 255,
"Color" : "{\"b\":0,\"cw\":98,\"g\":0,\"m\":2,\"r\":0,\"t\":157,\"ww\":157}",
"CustomImage" : 0,
"Data" : "Set Color",
"Description" : "",
"DimmerType" : "abs",
"Favorite" : 0,
"HardwareID" : 16,
"HardwareName" : "Hue Bridge",
"HardwareType" : "Philips Hue Bridge",
"HardwareTypeVal" : 38,
"HaveDimmer" : true,
"HaveGroupCmd" : false,
"HaveTimeout" : false,
"ID" : "00000006",
"Image" : "Light",
"IsSubDevice" : false,
"LastUpdate" : "2019-11-18 06:00:21",
"Level" : 100,
"LevelInt" : 100,
"MaxDimLevel" : 100,
"Name" : "Spot bureau 2",
"Notifications" : "false",
"PlanID" : "0",
"PlanIDs" : [ 0 ],
"Protected" : false,
"ShowNotifications" : true,
"SignalLevel" : "-",
"Status" : "Set Level: 100 %",
"StrParam1" : "",
"StrParam2" : "",
"SubType" : "WW",
"SwitchType" : "Dimmer",
"SwitchTypeVal" : 7,
"Timers" : "false",
"Type" : "Color Switch",
"TypeImg" : "dimmer",
"Unit" : 1,
"Used" : 1,
"UsedByCamera" : false,
"XOffset" : "0",
"YOffset" : "0",
"idx" : "430"
},
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 0.0,
"AddjValue2" : 0.0,
"BatteryLevel" : 255,
"Color" : "{\"b\":0,\"cw\":98,\"g\":0,\"m\":2,\"r\":0,\"t\":157,\"ww\":157}",
"CustomImage" : 0,
"Data" : "Set Color",
"Description" : "",
"DimmerType" : "abs",
"Favorite" : 0,
"HardwareID" : 16,
"HardwareName" : "Hue Bridge",
"HardwareType" : "Philips Hue Bridge",
"HardwareTypeVal" : 38,
"HaveDimmer" : true,
"HaveGroupCmd" : false,
"HaveTimeout" : false,
"ID" : "00000007",
"Image" : "Light",
"IsSubDevice" : false,
"LastUpdate" : "2019-11-18 06:00:21",
"Level" : 100,
"LevelInt" : 100,
"MaxDimLevel" : 100,
"Name" : "Spot bureau 3",
"Notifications" : "false",
"PlanID" : "0",
"PlanIDs" : [ 0 ],
"Protected" : false,
"ShowNotifications" : true,
"SignalLevel" : "-",
"Status" : "Set Level: 100 %",
"StrParam1" : "",
"StrParam2" : "",
"SubType" : "WW",
"SwitchType" : "Dimmer",
"SwitchTypeVal" : 7,
"Timers" : "false",
"Type" : "Color Switch",
"TypeImg" : "dimmer",
"Unit" : 1,
"Used" : 1,
"UsedByCamera" : false,
"XOffset" : "0",
"YOffset" : "0",
"idx" : "431"
},
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 0.0,
"AddjValue2" : 0.0,
"BatteryLevel" : 255,
"Color" : "{\"b\":0,\"cw\":98,\"g\":0,\"m\":2,\"r\":0,\"t\":157,\"ww\":157}",
"CustomImage" : 0,
"Data" : "Set Color",
"Description" : "",
"DimmerType" : "abs",
"Favorite" : 0,
"HardwareID" : 16,
"HardwareName" : "Hue Bridge",
"HardwareType" : "Philips Hue Bridge",
"HardwareTypeVal" : 38,
"HaveDimmer" : true,
"HaveGroupCmd" : false,
"HaveTimeout" : false,
"ID" : "00000008",
"Image" : "Light",
"IsSubDevice" : false,
"LastUpdate" : "2019-11-18 06:00:21",
"Level" : 100,
"LevelInt" : 100,
"MaxDimLevel" : 100,
"Name" : "Spot bureau 4",
"Notifications" : "false",
"PlanID" : "0",
"PlanIDs" : [ 0 ],
"Protected" : false,
"ShowNotifications" : true,
"SignalLevel" : "-",
"Status" : "Set Level: 100 %",
"StrParam1" : "",
"StrParam2" : "",
"SubType" : "WW",
"SwitchType" : "Dimmer",
"SwitchTypeVal" : 7,
"Timers" : "false",
"Type" : "Color Switch",
"TypeImg" : "dimmer",
"Unit" : 1,
"Used" : 1,
"UsedByCamera" : false,
"XOffset" : "0",
"YOffset" : "0",
"idx" : "432"
}
],
"status" : "OK",
"title" : "Devices"
});