exports.DOMOTICZ_GET_DEVICES = JSON.stringify({
   "ActTime" : 1673100763,
   "AstrTwilightEnd" : "19:05",
   "AstrTwilightStart" : "06:49",
   "CivTwilightEnd" : "17:46",
   "CivTwilightStart" : "08:07",
   "DayLength" : "08:26",
   "NautTwilightEnd" : "18:27",
   "NautTwilightStart" : "07:27",
   "ServerTime" : "2023-01-07 15:12:43",
   "SunAtSouth" : "12:57",
   "Sunrise" : "08:44",
   "Sunset" : "17:10",
   "app_version" : "2022.2",
   "result" : 
   [
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "Off",
         "Description" : "Lampe de chevet",
         "DimmerType" : "none",
         "Favorite" : 1,
         "HardwareDisabled" : false,
         "HardwareID" : 1,
         "HardwareName" : "RFXtrx USB via Lan",
         "HardwareType" : "RFXCOM - RFXtrx shared over LAN interface",
         "HardwareTypeVal" : 2,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "0875FB6",
         "Image" : "Light",
         "IsSubDevice" : false,
         "LastUpdate" : "2023-01-07 05:24:20",
         "Level" : 100,
         "LevelInt" : 15,
         "MaxDimLevel" : 15,
         "Name" : "Lampe de chevet",
         "Notifications" : "false",
         "PlanID" : "3",
         "PlanIDs" : 
         [
            3
         ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "AC",
         "SwitchType" : "On/Off",
         "SwitchTypeVal" : 0,
         "Timers" : "true",
         "Type" : "Lighting 2",
         "TypeImg" : "lightbulb",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "780",
         "YOffset" : "164",
         "idx" : "37"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "Off",
         "Description" : "Leds Dimmables",
         "DimmerType" : "abs",
         "Favorite" : 1,
         "HardwareDisabled" : false,
         "HardwareID" : 1,
         "HardwareName" : "RFXtrx USB via Lan",
         "HardwareType" : "RFXCOM - RFXtrx shared over LAN interface",
         "HardwareTypeVal" : 2,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "11A1111",
         "Image" : "Light",
         "IsSubDevice" : false,
         "LastUpdate" : "2023-01-07 01:00:01",
         "Level" : 100,
         "LevelInt" : 15,
         "MaxDimLevel" : 15,
         "Name" : "Lumiere cuisine",
         "Notifications" : "false",
         "PlanID" : "1",
         "PlanIDs" : 
         [
            1
         ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "AC",
         "SwitchType" : "Dimmer",
         "SwitchTypeVal" : 7,
         "Timers" : "true",
         "Type" : "Lighting 2",
         "TypeImg" : "dimmer",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "167",
         "YOffset" : "287",
         "idx" : "77"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "Open",
         "Description" : "none",
         "DimmerType" : "none",
         "Favorite" : 1,
         "HardwareDisabled" : false,
         "HardwareID" : 1,
         "HardwareName" : "RFXtrx USB via Lan",
         "HardwareType" : "RFXCOM - RFXtrx shared over LAN interface",
         "HardwareTypeVal" : 2,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "05C0886",
         "Image" : "blinds",
         "IsSubDevice" : false,
         "LastUpdate" : "2023-01-07 13:30:01",
         "Level" : 100,
         "LevelInt" : 15,
         "MaxDimLevel" : 15,
         "Name" : "Volet chambre enfants",
         "Notifications" : "false",
         "PlanID" : "4",
         "PlanIDs" : 
         [
            4
         ],
         "Protected" : false,
         "ReversePosition" : false,
         "ReverseState" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Open",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "AC",
         "SwitchType" : "Blinds",
         "SwitchTypeVal" : 3,
         "Timers" : "false",
         "Type" : "Lighting 2",
         "TypeImg" : "blinds",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "588",
         "YOffset" : "443",
         "idx" : "11"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "Open",
         "Description" : "none",
         "DimmerType" : "none",
         "Favorite" : 1,
         "HardwareDisabled" : false,
         "HardwareID" : 1,
         "HardwareName" : "RFXtrx USB via Lan",
         "HardwareType" : "RFXCOM - RFXtrx shared over LAN interface",
         "HardwareTypeVal" : 2,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "05C0886",
         "Image" : "blinds",
         "IsSubDevice" : false,
         "LastUpdate" : "2023-01-07 13:30:01",
         "Level" : 100,
         "LevelInt" : 15,
         "MaxDimLevel" : 15,
         "Name" : "Volet chambre parents",
         "Notifications" : "false",
         "PlanID" : "3",
         "PlanIDs" : 
         [
            3
         ],
         "Protected" : false,
         "ReversePosition" : false,
         "ReverseState" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Open",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "AC",
         "SwitchType" : "Blinds",
         "SwitchTypeVal" : 3,
         "Timers" : "false",
         "Type" : "Lighting 2",
         "TypeImg" : "blinds",
         "Unit" : 2,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "652",
         "YOffset" : "6",
         "idx" : "19"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "Open",
         "Description" : "none",
         "DimmerType" : "none",
         "Favorite" : 1,
         "HardwareDisabled" : false,
         "HardwareID" : 1,
         "HardwareName" : "RFXtrx USB via Lan",
         "HardwareType" : "RFXCOM - RFXtrx shared over LAN interface",
         "HardwareTypeVal" : 2,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "05C0886",
         "Image" : "blinds",
         "IsSubDevice" : false,
         "LastUpdate" : "2023-01-07 13:30:01",
         "Level" : 100,
         "LevelInt" : 15,
         "MaxDimLevel" : 15,
         "Name" : "Volet bar",
         "Notifications" : "false",
         "PlanID" : "1",
         "PlanIDs" : 
         [
            1
         ],
         "Protected" : false,
         "ReversePosition" : false,
         "ReverseState" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Open",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "AC",
         "SwitchType" : "Blinds",
         "SwitchTypeVal" : 3,
         "Timers" : "false",
         "Type" : "Lighting 2",
         "TypeImg" : "blinds",
         "Unit" : 3,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "485",
         "YOffset" : "25",
         "idx" : "20"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "Open",
         "Description" : "none",
         "DimmerType" : "none",
         "Favorite" : 1,
         "HardwareDisabled" : false,
         "HardwareID" : 1,
         "HardwareName" : "RFXtrx USB via Lan",
         "HardwareType" : "RFXCOM - RFXtrx shared over LAN interface",
         "HardwareTypeVal" : 2,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "05C0886",
         "Image" : "blinds",
         "IsSubDevice" : false,
         "LastUpdate" : "2023-01-07 13:30:02",
         "Level" : 100,
         "LevelInt" : 15,
         "MaxDimLevel" : 15,
         "Name" : "Volet cuisine",
         "Notifications" : "false",
         "PlanID" : "1",
         "PlanIDs" : 
         [
            1
         ],
         "Protected" : false,
         "ReversePosition" : false,
         "ReverseState" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Open",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "AC",
         "SwitchType" : "Blinds",
         "SwitchTypeVal" : 3,
         "Timers" : "false",
         "Type" : "Lighting 2",
         "TypeImg" : "blinds",
         "Unit" : 5,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "151",
         "YOffset" : "440",
         "idx" : "22"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "Counter" : "39966.781",
         "CounterDeliv" : "0.000",
         "CounterDelivToday" : "0.000 kWh",
         "CounterToday" : "0.000 kWh",
         "CustomImage" : 0,
         "Data" : "22245961;17720820;0;0;3560;0;",
         "Description" : "Compteur electrique P1 intelligent",
         "Favorite" : 1,
         "HardwareDisabled" : false,
         "HardwareID" : 4,
         "HardwareName" : "Virtuals Switchs",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveTimeout" : true,
         "ID" : "14146",
         "LastUpdate" : "2022-12-27 15:42:00",
         "Name" : "Compteur \u00e9lectrique",
         "Notifications" : "false",
         "PlanID" : "1",
         "PlanIDs" : 
         [
            1
         ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "Energy",
         "SwitchTypeVal" : 0,
         "Timers" : "false",
         "Type" : "P1 Smart Meter",
         "TypeImg" : "counter",
         "Unit" : 1,
         "Usage" : "0 Watt",
         "UsageDeliv" : "0 Watt",
         "Used" : 1,
         "XOffset" : "318",
         "YOffset" : "21",
         "idx" : "246"
      }
   ],
   "status" : "OK",
   "title" : "Devices"
});