exports.DOMOTICZ_GET_DEVICES = JSON.stringify(
{
   "ActTime" : 1557342262,
   "AstrTwilightEnd" : "23:13",
   "AstrTwilightStart" : "03:40",
   "CivTwilightEnd" : "21:30",
   "CivTwilightStart" : "05:23",
   "DayLength" : "14:54",
   "NautTwilightEnd" : "22:17",
   "NautTwilightStart" : "04:37",
   "ServerTime" : "2019-05-08 21:04:22",
   "SunAtSouth" : "13:05",
   "Sunrise" : "06:00",
   "Sunset" : "20:54",
   "app_version" : "4.9700",
   "result" : [
      {
         "Data" : "On",
         "Description" : "",
         "Favorite" : 0,
         "LastUpdate" : "2018-05-17 14:12:07",
         "Name" : "Eclairage lumières salon",
         "PlanID" : "",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "Status" : "On",
         "Type" : "Scene",
         "TypeImg" : "scene",
         "UsedByCamera" : false,
         "XOffset" : 0,
         "YOffset" : 0,
         "idx" : "1"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 100,
         "CustomImage" : 0,
         "Data" : "10.5 C, 74 %",
         "Description" : "Thermo-hygro exterieur (Est)",
         "DewPoint" : "6.06",
         "Favorite" : 1,
         "HardwareID" : 2,
         "HardwareName" : "RFXcom 433E",
         "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
         "HardwareTypeVal" : 1,
         "HaveTimeout" : false,
         "Humidity" : 74,
         "HumidityStatus" : "Wet",
         "ID" : "B301",
         "LastUpdate" : "2019-05-08 21:03:31",
         "Name" : "Exterieur Est",
         "Notifications" : "true",
         "PlanID" : "2",
         "PlanIDs" : [ 2 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : 7,
         "SubType" : "THGR810, THGN800",
         "Temp" : 10.5,
         "Timers" : "false",
         "Type" : "Temp + Humidity",
         "TypeImg" : "temperature",
         "Unit" : 1,
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "24"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 100,
         "CustomImage" : 0,
         "Data" : "18.7 C, 51 %",
         "Description" : "Thermo-hygro chambre",
         "DewPoint" : "8.36",
         "Favorite" : 1,
         "HardwareID" : 2,
         "HardwareName" : "RFXcom 433E",
         "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
         "HardwareTypeVal" : 1,
         "HaveTimeout" : false,
         "Humidity" : 51,
         "HumidityStatus" : "Normal",
         "ID" : "EA03",
         "LastUpdate" : "2019-05-08 21:04:04",
         "Name" : "Chambre",
         "Notifications" : "false",
         "PlanID" : "2",
         "PlanIDs" : [ 2 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : 7,
         "SubType" : "THGR810, THGN800",
         "Temp" : 18.699999999999999,
         "Timers" : "false",
         "Type" : "Temp + Humidity",
         "TypeImg" : "temperature",
         "Unit" : 3,
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "25"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 100,
         "CustomImage" : 0,
         "Data" : "20.8 C, 40 %",
         "Description" : "Capteur Oregon Scientific",
         "DewPoint" : "6.71",
         "Favorite" : 1,
         "HardwareID" : 2,
         "HardwareName" : "RFXcom 433E",
         "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
         "HardwareTypeVal" : 1,
         "HaveTimeout" : false,
         "Humidity" : 40,
         "HumidityStatus" : "Comfortable",
         "ID" : "C902",
         "LastUpdate" : "2019-05-08 21:04:04",
         "Name" : "Salle a manger",
         "Notifications" : "true",
         "PlanID" : "2",
         "PlanIDs" : [ 2 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : 8,
         "SubType" : "THGR810, THGN800",
         "Temp" : 20.800000000000001,
         "Timers" : "false",
         "Type" : "Temp + Humidity",
         "TypeImg" : "temperature",
         "Unit" : 2,
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "23"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 100,
         "CustomImage" : 0,
         "Data" : "11.5 C, 9 %",
         "Description" : "Thermomètre bassin a poissons",
         "DewPoint" : "-20.36",
         "Favorite" : 1,
         "HardwareID" : 2,
         "HardwareName" : "RFXcom 433E",
         "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
         "HardwareTypeVal" : 1,
         "HaveTimeout" : false,
         "Humidity" : 9,
         "HumidityStatus" : "Dry",
         "ID" : "9401",
         "LastUpdate" : "2019-05-08 21:03:30",
         "Name" : "T. Bassin",
         "Notifications" : "true",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : 6,
         "SubType" : "Rubicson/IW008T/TX95",
         "Temp" : 11.5,
         "Timers" : "false",
         "Type" : "Temp + Humidity",
         "TypeImg" : "temperature",
         "Unit" : 1,
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "63"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "46.2 C",
         "Description" : "",
         "Favorite" : 0,
         "HardwareID" : 3,
         "HardwareName" : "PI sensors",
         "HardwareType" : "Motherboard sensors",
         "HardwareTypeVal" : 23,
         "HaveTimeout" : false,
         "ID" : "0001",
         "LastUpdate" : "2019-05-08 21:03:34",
         "Name" : "Temp. interne PI3",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "LaCrosse TX3",
         "Temp" : 46.200000000000003,
         "Timers" : "false",
         "Type" : "Temp",
         "TypeImg" : "temperature",
         "Unit" : 1,
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "2"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "7.32%",
         "Description" : "",
         "Favorite" : 0,
         "HardwareID" : 3,
         "HardwareName" : "PI sensors",
         "HardwareType" : "Motherboard sensors",
         "HardwareTypeVal" : 23,
         "HaveTimeout" : false,
         "ID" : "0000044C",
         "Image" : "Computer",
         "LastUpdate" : "2019-05-08 21:03:44",
         "Name" : "Utilisation memoire",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "Percentage",
         "Timers" : "false",
         "Type" : "General",
         "TypeImg" : "hardware",
         "Unit" : 1,
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "3"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "On",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 1,
         "HardwareID" : 2,
         "HardwareName" : "RFXcom 433E",
         "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
         "HardwareTypeVal" : 1,
         "HaveDimmer" : false,
         "HaveGroupCmd" : false,
         "HaveTimeout" : false,
         "ID" : "151555",
         "Image" : "Light",
         "InternalState" : "On",
         "IsSubDevice" : false,
         "LastUpdate" : "2019-05-08 20:52:01",
         "Level" : 0,
         "LevelInt" : 433,
         "MaxDimLevel" : 0,
         "Name" : "Allumer Ambiance",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "PT2262",
         "SwitchType" : "Push On Button",
         "SwitchTypeVal" : 9,
         "Timers" : "true",
         "Type" : "Lighting 4",
         "TypeImg" : "push",
         "Unit" : 0,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "186"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "On",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 1,
         "HardwareID" : 2,
         "HardwareName" : "RFXcom 433E",
         "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
         "HardwareTypeVal" : 1,
         "HaveDimmer" : false,
         "HaveGroupCmd" : false,
         "HaveTimeout" : false,
         "ID" : "151554",
         "Image" : "Light",
         "IsSubDevice" : false,
         "LastUpdate" : "2019-05-07 23:00:59",
         "Level" : 0,
         "LevelInt" : 433,
         "MaxDimLevel" : 0,
         "Name" : "Eteindre Ambiance",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "PT2262",
         "SwitchType" : "Push Off Button",
         "SwitchTypeVal" : 10,
         "Timers" : "true",
         "Type" : "Lighting 4",
         "TypeImg" : "pushoff",
         "Unit" : 0,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "10"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "On",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 1,
         "HardwareID" : 2,
         "HardwareName" : "RFXcom 433E",
         "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
         "HardwareTypeVal" : 1,
         "HaveDimmer" : false,
         "HaveGroupCmd" : false,
         "HaveTimeout" : false,
         "ID" : "154555",
         "Image" : "Light",
         "InternalState" : "On",
         "IsSubDevice" : false,
         "LastUpdate" : "2019-05-06 20:49:20",
         "Level" : 0,
         "LevelInt" : 433,
         "MaxDimLevel" : 0,
         "Name" : "Allumer liseuse",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "PT2262",
         "SwitchType" : "Push On Button",
         "SwitchTypeVal" : 9,
         "Timers" : "true",
         "Type" : "Lighting 4",
         "TypeImg" : "push",
         "Unit" : 0,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "11"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "On",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 1,
         "HardwareID" : 2,
         "HardwareName" : "RFXcom 433E",
         "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
         "HardwareTypeVal" : 1,
         "HaveDimmer" : false,
         "HaveGroupCmd" : false,
         "HaveTimeout" : false,
         "ID" : "154554",
         "Image" : "Light",
         "IsSubDevice" : false,
         "LastUpdate" : "2019-05-07 22:57:59",
         "Level" : 0,
         "LevelInt" : 428,
         "MaxDimLevel" : 0,
         "Name" : "Eteindre liseuse",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "PT2262",
         "SwitchType" : "Push Off Button",
         "SwitchTypeVal" : 10,
         "Timers" : "true",
         "Type" : "Lighting 4",
         "TypeImg" : "pushoff",
         "Unit" : 0,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "12"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "On",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareID" : 2,
         "HardwareName" : "RFXcom 433E",
         "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
         "HardwareTypeVal" : 1,
         "HaveDimmer" : false,
         "HaveGroupCmd" : false,
         "HaveTimeout" : false,
         "ID" : "A81D04",
         "Image" : "Light",
         "InternalState" : "On",
         "IsSubDevice" : false,
         "LastUpdate" : "2019-01-24 17:18:29",
         "Level" : 0,
         "LevelInt" : 417,
         "MaxDimLevel" : 0,
         "Name" : "Allumer Kota",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "PT2262",
         "SwitchType" : "Push On Button",
         "SwitchTypeVal" : 9,
         "Timers" : "false",
         "Type" : "Lighting 4",
         "TypeImg" : "push",
         "Unit" : 0,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "177"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "On",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareID" : 2,
         "HardwareName" : "RFXcom 433E",
         "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
         "HardwareTypeVal" : 1,
         "HaveDimmer" : false,
         "HaveGroupCmd" : false,
         "HaveTimeout" : false,
         "ID" : "A81D06",
         "Image" : "Light",
         "IsSubDevice" : false,
         "LastUpdate" : "2019-01-24 17:18:46",
         "Level" : 0,
         "LevelInt" : 412,
         "MaxDimLevel" : 0,
         "Name" : "Eteindre Kota",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "PT2262",
         "SwitchType" : "Push Off Button",
         "SwitchTypeVal" : 10,
         "Timers" : "false",
         "Type" : "Lighting 4",
         "TypeImg" : "pushoff",
         "Unit" : 0,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "178"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "On",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareID" : 2,
         "HardwareName" : "RFXcom 433E",
         "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
         "HardwareTypeVal" : 1,
         "HaveDimmer" : false,
         "HaveGroupCmd" : false,
         "HaveTimeout" : false,
         "ID" : "A81D07",
         "Image" : "Light",
         "InternalState" : "On",
         "IsSubDevice" : false,
         "LastUpdate" : "2019-01-24 14:53:41",
         "Level" : 0,
         "LevelInt" : 415,
         "MaxDimLevel" : 0,
         "Name" : "Kota 100%",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "PT2262",
         "SwitchType" : "Push On Button",
         "SwitchTypeVal" : 9,
         "Timers" : "false",
         "Type" : "Lighting 4",
         "TypeImg" : "push",
         "Unit" : 0,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "179"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "On",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareID" : 2,
         "HardwareName" : "RFXcom 433E",
         "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
         "HardwareTypeVal" : 1,
         "HaveDimmer" : false,
         "HaveGroupCmd" : false,
         "HaveTimeout" : false,
         "ID" : "A81D0F",
         "Image" : "Light",
         "InternalState" : "On",
         "IsSubDevice" : false,
         "LastUpdate" : "2019-01-20 19:51:43",
         "Level" : 0,
         "LevelInt" : 412,
         "MaxDimLevel" : 0,
         "Name" : "Lumiere Kota 1mn",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : 5,
         "Status" : "",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "PT2262",
         "SwitchType" : "Push On Button",
         "SwitchTypeVal" : 9,
         "Timers" : "false",
         "Type" : "Lighting 4",
         "TypeImg" : "push",
         "Unit" : 0,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "182"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 10.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "Off",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareID" : 2,
         "HardwareName" : "RFXcom 433E",
         "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
         "HardwareTypeVal" : 1,
         "HaveDimmer" : false,
         "HaveGroupCmd" : false,
         "HaveTimeout" : false,
         "ID" : "EC96EE",
         "Image" : "Light",
         "IsSubDevice" : false,
         "LastUpdate" : "2019-05-08 20:48:12",
         "Level" : 0,
         "LevelInt" : 410,
         "MaxDimLevel" : 0,
         "Name" : "PIR_Entree",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : 8,
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "PT2262",
         "SwitchType" : "Motion Sensor",
         "SwitchTypeVal" : 8,
         "Timers" : "false",
         "Type" : "Lighting 4",
         "TypeImg" : "motion",
         "Unit" : 0,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "193"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 10.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "Off",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareID" : 2,
         "HardwareName" : "RFXcom 433E",
         "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
         "HardwareTypeVal" : 1,
         "HaveDimmer" : false,
         "HaveGroupCmd" : false,
         "HaveTimeout" : false,
         "ID" : "D3D15C",
         "Image" : "Light",
         "IsSubDevice" : false,
         "LastUpdate" : "2019-05-08 20:54:02",
         "Level" : 0,
         "LevelInt" : 359,
         "MaxDimLevel" : 0,
         "Name" : "PIR_Salon",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : 8,
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "PT2262",
         "SwitchType" : "Motion Sensor",
         "SwitchTypeVal" : 8,
         "Timers" : "false",
         "Type" : "Lighting 4",
         "TypeImg" : "motion",
         "Unit" : 0,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "54"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "On",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareID" : 2,
         "HardwareName" : "RFXcom 433E",
         "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
         "HardwareTypeVal" : 1,
         "HaveDimmer" : false,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "79",
         "Image" : "Light",
         "InternalState" : "On",
         "IsSubDevice" : false,
         "LastUpdate" : "2019-05-08 20:24:35",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 0,
         "Name" : "Allumer guirlande",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "ARC",
         "SwitchType" : "Push On Button",
         "SwitchTypeVal" : 9,
         "Timers" : "false",
         "Type" : "Lighting 1",
         "TypeImg" : "push",
         "Unit" : 8,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "13"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "On",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareID" : 2,
         "HardwareName" : "RFXcom 433E",
         "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
         "HardwareTypeVal" : 1,
         "HaveDimmer" : false,
         "HaveGroupCmd" : false,
         "HaveTimeout" : false,
         "ID" : "155454",
         "Image" : "Light",
         "IsSubDevice" : false,
         "LastUpdate" : "2019-05-07 22:57:59",
         "Level" : 0,
         "LevelInt" : 431,
         "MaxDimLevel" : 0,
         "Name" : "Eteindre guirlande",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "PT2262",
         "SwitchType" : "Push Off Button",
         "SwitchTypeVal" : 10,
         "Timers" : "false",
         "Type" : "Lighting 4",
         "TypeImg" : "pushoff",
         "Unit" : 0,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "14"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "On",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareID" : 2,
         "HardwareName" : "RFXcom 433E",
         "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
         "HardwareTypeVal" : 1,
         "HaveDimmer" : false,
         "HaveGroupCmd" : false,
         "HaveTimeout" : false,
         "ID" : "155155",
         "Image" : "Light",
         "InternalState" : "On",
         "IsSubDevice" : false,
         "LastUpdate" : "2019-05-08 20:07:27",
         "Level" : 0,
         "LevelInt" : 433,
         "MaxDimLevel" : 0,
         "Name" : "Allumer lampe sel et son TV",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : 7,
         "Status" : "",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "PT2262",
         "SwitchType" : "Push On Button",
         "SwitchTypeVal" : 9,
         "Timers" : "false",
         "Type" : "Lighting 4",
         "TypeImg" : "push",
         "Unit" : 0,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "15"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "On",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareID" : 2,
         "HardwareName" : "RFXcom 433E",
         "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
         "HardwareTypeVal" : 1,
         "HaveDimmer" : false,
         "HaveGroupCmd" : false,
         "HaveTimeout" : false,
         "ID" : "155154",
         "Image" : "Light",
         "IsSubDevice" : false,
         "LastUpdate" : "2019-05-07 22:57:59",
         "Level" : 0,
         "LevelInt" : 431,
         "MaxDimLevel" : 0,
         "Name" : "Eteindre lampe sel et son TV",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "PT2262",
         "SwitchType" : "Push Off Button",
         "SwitchTypeVal" : 10,
         "Timers" : "false",
         "Type" : "Lighting 4",
         "TypeImg" : "pushoff",
         "Unit" : 0,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "16"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "1.49%",
         "Description" : "",
         "Favorite" : 0,
         "HardwareID" : 3,
         "HardwareName" : "PI sensors",
         "HardwareType" : "Motherboard sensors",
         "HardwareTypeVal" : 23,
         "HaveTimeout" : false,
         "ID" : "0000044D",
         "Image" : "Computer",
         "LastUpdate" : "2019-05-08 21:04:04",
         "Name" : "CPU_Usage",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "Percentage",
         "Timers" : "false",
         "Type" : "General",
         "TypeImg" : "hardware",
         "Unit" : 1,
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "26"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "42.57 MB",
         "Description" : "",
         "Favorite" : 0,
         "HardwareID" : 3,
         "HardwareName" : "PI sensors",
         "HardwareType" : "Motherboard sensors",
         "HardwareTypeVal" : 23,
         "HaveTimeout" : false,
         "ID" : "000005DC",
         "Image" : "Custom",
         "LastUpdate" : "2019-05-08 21:03:44",
         "Name" : "Process Usage",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "SensorType" : 1,
         "SensorUnit" : "MB",
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "Custom Sensor",
         "Timers" : "false",
         "Type" : "General",
         "TypeImg" : "Custom",
         "Unit" : 1,
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "27"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "50.98%",
         "Description" : "",
         "Favorite" : 0,
         "HardwareID" : 3,
         "HardwareName" : "PI sensors",
         "HardwareType" : "Motherboard sensors",
         "HardwareTypeVal" : 23,
         "HaveTimeout" : false,
         "ID" : "0000044E",
         "Image" : "Computer",
         "LastUpdate" : "2019-05-08 21:01:54",
         "Name" : "HDD /boot",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "Percentage",
         "Timers" : "false",
         "Type" : "General",
         "TypeImg" : "hardware",
         "Unit" : 1,
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "28"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "8.63%",
         "Description" : "",
         "Favorite" : 0,
         "HardwareID" : 3,
         "HardwareName" : "PI sensors",
         "HardwareType" : "Motherboard sensors",
         "HardwareTypeVal" : 23,
         "HaveTimeout" : false,
         "ID" : "0000044F",
         "Image" : "Computer",
         "LastUpdate" : "2019-05-08 21:01:54",
         "Name" : "HDD /",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "Percentage",
         "Timers" : "false",
         "Type" : "General",
         "TypeImg" : "hardware",
         "Unit" : 1,
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "29"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CameraIdx" : "1",
         "CustomImage" : 0,
         "Data" : "On",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareID" : 2,
         "HardwareName" : "RFXcom 433E",
         "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
         "HardwareTypeVal" : 1,
         "HaveDimmer" : false,
         "HaveGroupCmd" : false,
         "HaveTimeout" : false,
         "ID" : "155557",
         "Image" : "Light",
         "InternalState" : "On",
         "IsSubDevice" : false,
         "LastUpdate" : "2019-05-07 15:43:36",
         "Level" : 0,
         "LevelInt" : 431,
         "MaxDimLevel" : 0,
         "Name" : "Camera Ouest",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : 7,
         "Status" : "",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "PT2262",
         "SwitchType" : "Push On Button",
         "SwitchTypeVal" : 9,
         "Timers" : "false",
         "Type" : "Lighting 4",
         "TypeImg" : "push",
         "Unit" : 0,
         "Used" : 1,
         "UsedByCamera" : true,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "30"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "Off",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareID" : 2,
         "HardwareName" : "RFXcom 433E",
         "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
         "HardwareTypeVal" : 1,
         "HaveDimmer" : false,
         "HaveGroupCmd" : false,
         "HaveTimeout" : false,
         "ID" : "5D5555",
         "Image" : "Light",
         "IsSubDevice" : false,
         "LastUpdate" : "2019-05-01 20:21:32",
         "Level" : 0,
         "LevelInt" : 461,
         "MaxDimLevel" : 0,
         "Name" : "Detecteur fumee - Salon",
         "Notifications" : "true",
         "PlanID" : "2",
         "PlanIDs" : [ 2 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "PT2262",
         "SwitchType" : "Smoke Detector",
         "SwitchTypeVal" : 5,
         "Timers" : "false",
         "Type" : "Lighting 4",
         "TypeImg" : "smoke",
         "Unit" : 0,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "31"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "Normal",
         "Description" : "",
         "Favorite" : 1,
         "HardwareID" : 1,
         "HardwareName" : "Domoticz Internal",
         "HardwareType" : "Domoticz Internal interface",
         "HardwareTypeVal" : 67,
         "HaveDimmer" : false,
         "HaveGroupCmd" : false,
         "HaveTimeout" : false,
         "ID" : "148702",
         "LastUpdate" : "2019-05-06 14:40:16",
         "MaxDimLevel" : 0,
         "Name" : "Clavier sécurité Domoticz",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Normal",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Security Panel",
         "SwitchType" : "Security",
         "SwitchTypeVal" : 0,
         "Timers" : "false",
         "Type" : "Security",
         "TypeImg" : "security",
         "Unit" : 0,
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "55"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 100,
         "CustomImage" : 0,
         "Data" : "45.00;NE;12;9;0.0;0.0",
         "Description" : "",
         "Direction" : 45.0,
         "DirectionStr" : "NE",
         "Favorite" : 1,
         "Gust" : "3.2",
         "HardwareID" : 2,
         "HardwareName" : "RFXcom 433E",
         "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
         "HardwareTypeVal" : 1,
         "HaveTimeout" : false,
         "ID" : "8600",
         "LastUpdate" : "2019-05-08 21:04:19",
         "Name" : "Anémomètre",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : 6,
         "Speed" : "4.3",
         "SubType" : "WGR800",
         "Timers" : "false",
         "Type" : "Wind",
         "TypeImg" : "wind",
         "Unit" : 0,
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "64"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "Barometer" : 1002,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "10.9 C, 77 %, 1002 hPa",
         "Description" : "",
         "DewPoint" : "7.03",
         "Favorite" : 0,
         "Forecast" : 4,
         "ForecastStr" : "Rain",
         "HardwareID" : 5,
         "HardwareName" : "DarkSky",
         "HardwareType" : "DarkSky (Weather Lookup)",
         "HardwareTypeVal" : 25,
         "HaveTimeout" : false,
         "Humidity" : 77,
         "HumidityStatus" : "Wet",
         "ID" : "0001",
         "LastUpdate" : "2019-05-08 21:01:05",
         "Name" : "Pression athmo",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "THB1 - BTHR918, BTHGN129",
         "Temp" : 10.9,
         "Timers" : "false",
         "Type" : "Temp + Humidity + Baro",
         "TypeImg" : "temperature",
         "Unit" : 1,
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "forecast_url" : "aHR0cHM6Ly9kYXJrc2t5Lm5ldC8jL2YvNDguNDk0MTg2JTJDNy40NTcxNjE=",
         "idx" : "80"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "Chill" : 10.9,
         "CustomImage" : 0,
         "Data" : "183.00;S;30;97;10.9;10.9",
         "Description" : "",
         "Direction" : 183.0,
         "DirectionStr" : "S",
         "Favorite" : 0,
         "Gust" : "34.9",
         "HardwareID" : 5,
         "HardwareName" : "DarkSky",
         "HardwareType" : "DarkSky (Weather Lookup)",
         "HardwareTypeVal" : 25,
         "HaveTimeout" : false,
         "ID" : "0001",
         "LastUpdate" : "2019-05-08 21:01:05",
         "Name" : "Vent",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Speed" : "10.8",
         "SubType" : "TFA",
         "Temp" : 10.9,
         "Timers" : "false",
         "Type" : "Wind",
         "TypeImg" : "wind",
         "Unit" : 0,
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "forecast_url" : "aHR0cHM6Ly9kYXJrc2t5Lm5ldC8jL2YvNDguNDk0MTg2JTJDNy40NTcxNjE=",
         "idx" : "81"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "0.0 UVI",
         "Description" : "",
         "Favorite" : 0,
         "HardwareID" : 5,
         "HardwareName" : "DarkSky",
         "HardwareType" : "DarkSky (Weather Lookup)",
         "HardwareTypeVal" : 25,
         "HaveTimeout" : false,
         "ID" : "0001",
         "LastUpdate" : "2019-05-08 21:01:05",
         "Name" : "UV Index",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "UVN128,UV138",
         "Timers" : "false",
         "Type" : "UV",
         "TypeImg" : "uv",
         "UVI" : "0.0",
         "Unit" : 0,
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "forecast_url" : "aHR0cHM6Ly9kYXJrc2t5Lm5ldC8jL2YvNDguNDk0MTg2JTJDNy40NTcxNjE=",
         "idx" : "82"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "0;0.2",
         "Description" : "",
         "Favorite" : 0,
         "HardwareID" : 5,
         "HardwareName" : "DarkSky",
         "HardwareType" : "DarkSky (Weather Lookup)",
         "HardwareTypeVal" : 25,
         "HaveTimeout" : false,
         "ID" : "0001",
         "LastUpdate" : "2019-05-08 21:01:05",
         "Name" : "Pluie",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "Rain" : "0.2",
         "RainRate" : "0",
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "WWW",
         "Timers" : "false",
         "Type" : "Rain",
         "TypeImg" : "rain",
         "Unit" : 0,
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "forecast_url" : "aHR0cHM6Ly9kYXJrc2t5Lm5ldC8jL2YvNDguNDk0MTg2JTJDNy40NTcxNjE=",
         "idx" : "83"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "12.8 km",
         "Description" : "",
         "Favorite" : 0,
         "HardwareID" : 5,
         "HardwareName" : "DarkSky",
         "HardwareType" : "DarkSky (Weather Lookup)",
         "HardwareTypeVal" : 25,
         "HaveTimeout" : false,
         "ID" : "0",
         "LastUpdate" : "2019-05-08 21:01:05",
         "Name" : "Visibilité",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "Visibility",
         "SwitchTypeVal" : 0,
         "Timers" : "false",
         "Type" : "General",
         "TypeImg" : "visibility",
         "Unit" : 1,
         "Used" : 1,
         "Visibility" : 12.800000000000001,
         "XOffset" : "0",
         "YOffset" : "0",
         "forecast_url" : "aHR0cHM6Ly9kYXJrc2t5Lm5ldC8jL2YvNDguNDk0MTg2JTJDNy40NTcxNjE=",
         "idx" : "84"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "400.55 DU",
         "Description" : "",
         "Favorite" : 1,
         "HardwareID" : 5,
         "HardwareName" : "DarkSky",
         "HardwareType" : "DarkSky (Weather Lookup)",
         "HardwareTypeVal" : 25,
         "HaveTimeout" : false,
         "ID" : "00000100",
         "Image" : "Custom",
         "LastUpdate" : "2019-05-08 21:01:05",
         "Name" : "Ozone Sensor",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "SensorType" : 1,
         "SensorUnit" : "DU",
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "Custom Sensor",
         "Timers" : "false",
         "Type" : "General",
         "TypeImg" : "Custom",
         "Unit" : 1,
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "forecast_url" : "aHR0cHM6Ly9kYXJrc2t5Lm5ldC8jL2YvNDguNDk0MTg2JTJDNy40NTcxNjE=",
         "idx" : "85"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "Open",
         "Description" : "Controle du store zip Est (1)",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareID" : 6,
         "HardwareName" : "Controle stores",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "000140BB",
         "Image" : "Light",
         "IsSubDevice" : false,
         "LastUpdate" : "2019-05-04 10:02:21",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 100,
         "Name" : "Store1",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Open",
         "StrParam1" : "aHR0cDovLzE5Mi4xNjguMS4zODo1MDAwL2V4ZWN1dGUvU3RvcmUlMjBFc3QlMjAoMSkvZG93bg==",
         "StrParam2" : "aHR0cDovLzE5Mi4xNjguMS4zODo1MDAwL2V4ZWN1dGUvU3RvcmUlMjBFc3QlMjAoMSkvdXA=",
         "SubType" : "Switch",
         "SwitchType" : "Blinds Percentage",
         "SwitchTypeVal" : 13,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "blinds",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "107"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "Open",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareID" : 6,
         "HardwareName" : "Controle stores",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "000140BD",
         "Image" : "Light",
         "IsSubDevice" : false,
         "LastUpdate" : "2019-05-01 13:47:55",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 100,
         "Name" : "Store2",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Open",
         "StrParam1" : "aHR0cDovLzE5Mi4xNjguMS4zODo1MDAwL2V4ZWN1dGUvU3RvcmUlMjBTdWQlMjAoMikvZG93bg==",
         "StrParam2" : "aHR0cDovLzE5Mi4xNjguMS4zODo1MDAwL2V4ZWN1dGUvU3RvcmUlMjBTdWQlMjAoMikvdXA=",
         "SubType" : "Switch",
         "SwitchType" : "Blinds Percentage",
         "SwitchTypeVal" : 13,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "blinds",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "109"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "Open",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareID" : 6,
         "HardwareName" : "Controle stores",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "000140BE",
         "Image" : "Light",
         "IsSubDevice" : false,
         "LastUpdate" : "2019-05-08 20:21:18",
         "Level" : 100,
         "LevelInt" : 100,
         "MaxDimLevel" : 100,
         "Name" : "Store3",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Open",
         "StrParam1" : "aHR0cDovLzE5Mi4xNjguMS4zODo1MDAwL2V4ZWN1dGUvU3RvcmUlMjBTdWQlMjAoMykvZG93bg==",
         "StrParam2" : "aHR0cDovLzE5Mi4xNjguMS4zODo1MDAwL2V4ZWN1dGUvU3RvcmUlMjBTdWQlMjAoMykvdXA=",
         "SubType" : "Switch",
         "SwitchType" : "Blinds Percentage",
         "SwitchTypeVal" : 13,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "blinds",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "110"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "Open",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareID" : 6,
         "HardwareName" : "Controle stores",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "000140BF",
         "Image" : "Light",
         "IsSubDevice" : false,
         "LastUpdate" : "2019-05-07 15:58:11",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 100,
         "Name" : "Store4",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Open",
         "StrParam1" : "aHR0cDovLzE5Mi4xNjguMS4zODo1MDAwL2V4ZWN1dGUvU3RvcmUlMjBPdWVzdCUyMCg0KS9kb3du",
         "StrParam2" : "aHR0cDovLzE5Mi4xNjguMS4zODo1MDAwL2V4ZWN1dGUvU3RvcmUlMjBPdWVzdCUyMCg0KS91cA==",
         "SubType" : "Switch",
         "SwitchType" : "Blinds Percentage",
         "SwitchTypeVal" : 13,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "blinds",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "111"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "Open",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareID" : 6,
         "HardwareName" : "Controle stores",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "000140C0",
         "Image" : "Light",
         "IsSubDevice" : false,
         "LastUpdate" : "2019-05-07 15:58:01",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 100,
         "Name" : "Store toiture",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Open",
         "StrParam1" : "aHR0cDovLzE5Mi4xNjguMS4zODo1MDAwL2V4ZWN1dGUvT21icmFnZSUyMHRvaXR1cmUvZG93bg==",
         "StrParam2" : "aHR0cDovLzE5Mi4xNjguMS4zODo1MDAwL2V4ZWN1dGUvT21icmFnZSUyMHRvaXR1cmUvdXA=",
         "SubType" : "Switch",
         "SwitchType" : "Blinds Percentage",
         "SwitchTypeVal" : 13,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "blinds",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "112"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "On",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareID" : 2,
         "HardwareName" : "RFXcom 433E",
         "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
         "HardwareTypeVal" : 1,
         "HaveDimmer" : false,
         "HaveGroupCmd" : false,
         "HaveTimeout" : false,
         "ID" : "A81D09",
         "Image" : "Light",
         "InternalState" : "On",
         "IsSubDevice" : false,
         "LastUpdate" : "2018-12-31 21:44:11",
         "Level" : 0,
         "LevelInt" : 417,
         "MaxDimLevel" : 0,
         "Name" : "Lumiere Kota +",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : 5,
         "Status" : "",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "PT2262",
         "SwitchType" : "Push On Button",
         "SwitchTypeVal" : 9,
         "Timers" : "false",
         "Type" : "Lighting 4",
         "TypeImg" : "push",
         "Unit" : 0,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "180"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "On",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareID" : 2,
         "HardwareName" : "RFXcom 433E",
         "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
         "HardwareTypeVal" : 1,
         "HaveDimmer" : false,
         "HaveGroupCmd" : false,
         "HaveTimeout" : false,
         "ID" : "A81D0C",
         "Image" : "Light",
         "InternalState" : "On",
         "IsSubDevice" : false,
         "LastUpdate" : "2019-01-06 17:28:38",
         "Level" : 0,
         "LevelInt" : 415,
         "MaxDimLevel" : 0,
         "Name" : "Lumiere Kota -",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : 6,
         "Status" : "",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "PT2262",
         "SwitchType" : "Push On Button",
         "SwitchTypeVal" : 9,
         "Timers" : "false",
         "Type" : "Lighting 4",
         "TypeImg" : "push",
         "Unit" : 0,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "181"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "Color" : "{\"b\":255,\"cw\":0,\"g\":255,\"m\":3,\"r\":255,\"t\":0,\"ww\":0}",
         "CustomImage" : 0,
         "Data" : "Set Level",
         "Description" : "",
         "DimmerType" : "abs",
         "Favorite" : 0,
         "HardwareID" : 7,
         "HardwareName" : "Dimmer Kota",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveDimmer" : true,
         "HaveGroupCmd" : false,
         "HaveTimeout" : false,
         "ID" : "00082185",
         "Image" : "Light",
         "IsSubDevice" : false,
         "LastUpdate" : "2019-05-01 12:10:39",
         "Level" : 68,
         "LevelInt" : 68,
         "MaxDimLevel" : 100,
         "Name" : "Dimmer kota",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Set Level: 68 %",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "RGBW",
         "SwitchType" : "Dimmer",
         "SwitchTypeVal" : 7,
         "Timers" : "false",
         "Type" : "Color Switch",
         "TypeImg" : "dimmer",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "185"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 9,
         "Data" : "Off",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareID" : 8,
         "HardwareName" : "SonOff",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "0001410B",
         "Image" : "Generic",
         "IsSubDevice" : false,
         "LastUpdate" : "2019-04-26 18:18:54",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 100,
         "Name" : "SonOff_basic_0",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "aHR0cDovLzE5Mi4xNjguMS4yMjAvY29udHJvbD9jbWQ9R1BJTywxMiwx",
         "StrParam2" : "aHR0cDovLzE5Mi4xNjguMS4yMjAvY29udHJvbD9jbWQ9R1BJTywxMiww",
         "SubType" : "Switch",
         "SwitchType" : "On/Off",
         "SwitchTypeVal" : 0,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "lightbulb",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "187"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "Off",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareID" : 7,
         "HardwareName" : "Dimmer Kota",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "0001410E",
         "Image" : "Light",
         "IsSubDevice" : false,
         "LastUpdate" : "2019-02-01 14:04:10",
         "Level" : 0,
         "LevelActions" : "fHx8",
         "LevelInt" : 0,
         "LevelNames" : "T2ZmfEtvdGEgMTAlfEtvdGEgNTAlfEtvdGEgMTAwJQ==",
         "LevelOffHidden" : false,
         "MaxDimLevel" : 100,
         "Name" : "Dimmer kota",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "SelectorStyle" : 0,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Selector Switch",
         "SwitchType" : "Selector",
         "SwitchTypeVal" : 18,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "Light",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "190"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "19.0 C, 47 %",
         "Description" : "",
         "DewPoint" : "7.43",
         "Favorite" : 1,
         "HardwareID" : 8,
         "HardwareName" : "SonOff",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveTimeout" : true,
         "Humidity" : 47,
         "HumidityStatus" : "Comfortable",
         "ID" : "1410F",
         "LastUpdate" : "2019-05-08 18:59:01",
         "Name" : "Station-F5UJA",
         "Notifications" : "false",
         "PlanID" : "3",
         "PlanIDs" : [ 3 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : 10,
         "SubType" : "THGN122/123/132, THGR122/228/238/268",
         "Temp" : 19.0,
         "Timers" : "false",
         "Type" : "Temp + Humidity",
         "TypeImg" : "temperature",
         "Unit" : 1,
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "191"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "Off",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareID" : 9,
         "HardwareName" : "Passerelle Xiaomi zigbee",
         "HardwareType" : "Xiaomi Gateway",
         "HardwareTypeVal" : 95,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "0233DA6B",
         "Image" : "Light",
         "IsSubDevice" : false,
         "LastUpdate" : "2019-05-08 20:55:03",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 100,
         "Name" : "PIR_Entree_Xiaomi",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Switch",
         "SwitchType" : "Motion Sensor",
         "SwitchTypeVal" : 8,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "motion",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "211"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 9,
         "Data" : "On",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 1,
         "HardwareID" : 8,
         "HardwareName" : "SonOff",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "00014112",
         "Image" : "Generic",
         "IsSubDevice" : false,
         "LastUpdate" : "2019-05-08 20:52:02",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 100,
         "Name" : "Lampe de sel entrée",
         "Notifications" : "false",
         "PlanID" : "2",
         "PlanIDs" : [ 2 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "On",
         "StrParam1" : "aHR0cDovLzE5Mi4xNjguMS4yMzAvY29udHJvbD9jbWQ9R1BJTywxMiwx",
         "StrParam2" : "aHR0cDovLzE5Mi4xNjguMS4yMzAvY29udHJvbD9jbWQ9R1BJTywxMiww",
         "SubType" : "Switch",
         "SwitchType" : "On/Off",
         "SwitchTypeVal" : 0,
         "Timers" : "true",
         "Type" : "Light/Switch",
         "TypeImg" : "lightbulb",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "194"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 9,
         "Data" : "Off",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 1,
         "HardwareID" : 8,
         "HardwareName" : "SonOff",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "00014113",
         "Image" : "Generic",
         "IsSubDevice" : false,
         "LastUpdate" : "2019-05-08 18:59:13",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 100,
         "Name" : "SonOff_basic_DTH22",
         "Notifications" : "false",
         "PlanID" : "3",
         "PlanIDs" : [ 3 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "aHR0cDovLzE5Mi4xNjguMS4yMjEvY29udHJvbD9jbWQ9R1BJTywxMiwx",
         "StrParam2" : "aHR0cDovLzE5Mi4xNjguMS4yMjEvY29udHJvbD9jbWQ9R1BJTywxMiww",
         "SubType" : "Switch",
         "SwitchType" : "On/Off",
         "SwitchTypeVal" : 0,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "lightbulb",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "195"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 100,
         "CustomImage" : 0,
         "Data" : "0;117.4",
         "Description" : "",
         "Favorite" : 1,
         "HardwareID" : 2,
         "HardwareName" : "RFXcom 433E",
         "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
         "HardwareTypeVal" : 1,
         "HaveTimeout" : false,
         "ID" : "1600",
         "LastUpdate" : "2019-05-08 21:04:10",
         "Name" : "Pluviometre Oregon",
         "Notifications" : "true",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "Rain" : "4.1",
         "RainRate" : "0",
         "ShowNotifications" : true,
         "SignalLevel" : 8,
         "SubType" : "PCR800",
         "Timers" : "false",
         "Type" : "Rain",
         "TypeImg" : "rain",
         "Unit" : 0,
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "196"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "Color" : "{\"b\":40,\"cw\":0,\"g\":159,\"m\":3,\"r\":255,\"t\":0,\"ww\":0}",
         "CustomImage" : 0,
         "Data" : "Off",
         "Description" : "",
         "DimmerType" : "abs",
         "Favorite" : 0,
         "HardwareID" : 9,
         "HardwareName" : "Passerelle Xiaomi zigbee",
         "HardwareType" : "Xiaomi Gateway",
         "HardwareTypeVal" : 95,
         "HaveDimmer" : true,
         "HaveGroupCmd" : false,
         "HaveTimeout" : false,
         "ID" : "8C97A39B",
         "Image" : "Light",
         "IsSubDevice" : false,
         "LastUpdate" : "2019-05-08 20:55:01",
         "Level" : 18,
         "LevelInt" : 18,
         "MaxDimLevel" : 100,
         "Name" : "Xiaomi RGB Gateway (192.168.1.246)",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "RGBW",
         "SwitchType" : "Dimmer",
         "SwitchTypeVal" : 7,
         "Timers" : "false",
         "Type" : "Color Switch",
         "TypeImg" : "dimmer",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "201"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 8,
         "Data" : "Off",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareID" : 9,
         "HardwareName" : "Passerelle Xiaomi zigbee",
         "HardwareType" : "Xiaomi Gateway",
         "HardwareTypeVal" : 95,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "8C97A39B",
         "Image" : "Speaker",
         "IsSubDevice" : false,
         "LastUpdate" : "2019-04-02 19:55:11",
         "Level" : 0,
         "LevelActions" : "",
         "LevelInt" : 0,
         "LevelNames" : "T2ZmfFBvbGljZSBzaXJlbiAxfFBvbGljZSBzaXJlbiAyfEFjY2lkZW50IHRvbmV8TWlzc2xlIGNvdW50ZG93bnxHaG9zdHxTbmlwZXJ8V2FyfEFpciBTdHJpa2V8QmFya2luZyBkb2dz",
         "LevelOffHidden" : false,
         "MaxDimLevel" : 100,
         "Name" : "Xiaomi Gateway Alarm Ringtone",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "SelectorStyle" : 1,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Selector Switch",
         "SwitchType" : "Selector",
         "SwitchTypeVal" : 18,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "Light",
         "Unit" : 3,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "202"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 8,
         "Data" : "Off",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareID" : 9,
         "HardwareName" : "Passerelle Xiaomi zigbee",
         "HardwareType" : "Xiaomi Gateway",
         "HardwareTypeVal" : 95,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "8C97A39B",
         "Image" : "Speaker",
         "IsSubDevice" : false,
         "LastUpdate" : "2019-05-08 20:21:46",
         "Level" : 10,
         "LevelActions" : "",
         "LevelInt" : 10,
         "LevelNames" : "T2ZmfE1pTWl4fEVudGh1c2lhc3RpY3xHdWl0YXJDbGFzc2ljfEljZVdvcmxkUGlhbm98TGVpc3VyZVRpbWV8Q2hpbGRob29kfE1vcm5pbmdTdHJlYW1sZXR8TXVzaWNCb3h8T3JhbmdlfFRoaW5rZXI=",
         "LevelOffHidden" : false,
         "MaxDimLevel" : 100,
         "Name" : "Xiaomi Gateway Alarm Clock",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "SelectorStyle" : 1,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Selector Switch",
         "SwitchType" : "Selector",
         "SwitchTypeVal" : 18,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "Light",
         "Unit" : 4,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "203"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 8,
         "Data" : "Off",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareID" : 9,
         "HardwareName" : "Passerelle Xiaomi zigbee",
         "HardwareType" : "Xiaomi Gateway",
         "HardwareTypeVal" : 95,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "8C97A39B",
         "Image" : "Speaker",
         "IsSubDevice" : false,
         "LastUpdate" : "2019-05-06 14:40:20",
         "Level" : 0,
         "LevelActions" : "",
         "LevelInt" : 0,
         "LevelNames" : "T2ZmfERvb3JiZWxsIHJpbmcgdG9uZXxLbm9jayBvbiBkb29yfEhpbGFyaW91c3xBbGFybSBjbG9jaw==",
         "LevelOffHidden" : false,
         "MaxDimLevel" : 100,
         "Name" : "Xiaomi Gateway Doorbell",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "SelectorStyle" : 1,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Selector Switch",
         "SwitchType" : "Selector",
         "SwitchTypeVal" : 18,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "Light",
         "Unit" : 5,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "204"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 8,
         "Data" : "Off",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareID" : 9,
         "HardwareName" : "Passerelle Xiaomi zigbee",
         "HardwareType" : "Xiaomi Gateway",
         "HardwareTypeVal" : 95,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "8C97A39B",
         "Image" : "Speaker",
         "IsSubDevice" : false,
         "LastUpdate" : "2019-04-02 19:52:47",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 100,
         "Name" : "Xiaomi Gateway MP3",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Switch",
         "SwitchType" : "On/Off",
         "SwitchTypeVal" : 0,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "lightbulb",
         "Unit" : 6,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "205"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 8,
         "Data" : "Off",
         "Description" : "",
         "DimmerType" : "abs",
         "Favorite" : 0,
         "HardwareID" : 9,
         "HardwareName" : "Passerelle Xiaomi zigbee",
         "HardwareType" : "Xiaomi Gateway",
         "HardwareTypeVal" : 95,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "8C97A39B",
         "Image" : "Speaker",
         "IsSubDevice" : false,
         "LastUpdate" : "2019-05-01 12:18:22",
         "Level" : 74,
         "LevelInt" : 74,
         "MaxDimLevel" : 100,
         "Name" : "Xiaomi Gateway Volume",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Switch",
         "SwitchType" : "Dimmer",
         "SwitchTypeVal" : 7,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "dimmer",
         "Unit" : 7,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "206"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 84,
         "CustomImage" : 9,
         "Data" : "On",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareID" : 9,
         "HardwareName" : "Passerelle Xiaomi zigbee",
         "HardwareType" : "Xiaomi Gateway",
         "HardwareTypeVal" : 95,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "020DCB23",
         "Image" : "Generic",
         "IsSubDevice" : false,
         "LastUpdate" : "2019-05-07 19:45:41",
         "Level" : 10,
         "LevelActions" : "fHx8fA==",
         "LevelInt" : 10,
         "LevelNames" : "T2ZmfENsaWNrfERvdWJsZSBDbGlja3xMb25nIENsaWNrfExvbmcgQ2xpY2sgUmVsZWFzZQ==",
         "LevelOffHidden" : false,
         "MaxDimLevel" : 100,
         "Name" : "Xiaomi Bouton 0",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "SelectorStyle" : 0,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "On",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Selector Switch",
         "SwitchType" : "Selector",
         "SwitchTypeVal" : 18,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "Light",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "207"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 9,
         "Data" : "On",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareID" : 8,
         "HardwareName" : "SonOff",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "00014122",
         "Image" : "Generic",
         "IsSubDevice" : false,
         "LastUpdate" : "2019-05-07 13:03:31",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 100,
         "Name" : "S20_station",
         "Notifications" : "false",
         "PlanID" : "3",
         "PlanIDs" : [ 3 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "On",
         "StrParam1" : "aHR0cDovLzE5Mi4xNjguMS4yMzEvY29udHJvbD9jbWQ9R1BJTywxMiwx",
         "StrParam2" : "aHR0cDovLzE5Mi4xNjguMS4yMzEvY29udHJvbD9jbWQ9R1BJTywxMiww",
         "SubType" : "Switch",
         "SwitchType" : "On/Off",
         "SwitchTypeVal" : 0,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "lightbulb",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "210"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "395 Lux",
         "Description" : "",
         "Favorite" : 1,
         "HardwareID" : 9,
         "HardwareName" : "Passerelle Xiaomi zigbee",
         "HardwareType" : "Xiaomi Gateway",
         "HardwareTypeVal" : 95,
         "HaveTimeout" : false,
         "ID" : "000009B",
         "LastUpdate" : "2019-05-08 20:55:01",
         "Name" : "Luxmetre couloir étage",
         "Notifications" : "false",
         "PlanID" : "2",
         "PlanIDs" : [ 2 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "Lux",
         "Timers" : "false",
         "Type" : "Lux",
         "TypeImg" : "lux",
         "Unit" : 155,
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "212"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 2.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 9,
         "Data" : "Off",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareID" : 2,
         "HardwareName" : "RFXcom 433E",
         "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
         "HardwareTypeVal" : 1,
         "HaveDimmer" : false,
         "HaveGroupCmd" : false,
         "HaveTimeout" : false,
         "ID" : "555503",
         "Image" : "Generic",
         "InternalState" : "Off",
         "IsSubDevice" : false,
         "LastUpdate" : "2019-05-07 22:45:12",
         "Level" : 0,
         "LevelInt" : 459,
         "MaxDimLevel" : 0,
         "Name" : "Telec Bouton A",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : 8,
         "Status" : "",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "PT2262",
         "SwitchType" : "Push On Button",
         "SwitchTypeVal" : 9,
         "Timers" : "false",
         "Type" : "Lighting 4",
         "TypeImg" : "push",
         "Unit" : 0,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "240"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 76,
         "CustomImage" : 0,
         "Data" : "Closed",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 1,
         "HardwareID" : 9,
         "HardwareName" : "Passerelle Xiaomi zigbee",
         "HardwareType" : "Xiaomi Gateway",
         "HardwareTypeVal" : 95,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "02C7DFC0",
         "Image" : "Light",
         "InternalState" : "Closed",
         "IsSubDevice" : false,
         "LastUpdate" : "2019-05-05 10:15:51",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 100,
         "Name" : "DO_Porte cellier",
         "Notifications" : "false",
         "PlanID" : "3",
         "PlanIDs" : [ 3 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Closed",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Switch",
         "SwitchType" : "Door Contact",
         "SwitchTypeVal" : 11,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "door",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "213"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 81,
         "CustomImage" : 0,
         "Data" : "Closed",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 1,
         "HardwareID" : 9,
         "HardwareName" : "Passerelle Xiaomi zigbee",
         "HardwareType" : "Xiaomi Gateway",
         "HardwareTypeVal" : 95,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "01E15663",
         "Image" : "Light",
         "InternalState" : "Closed",
         "IsSubDevice" : false,
         "LastUpdate" : "2019-05-05 11:05:11",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 100,
         "Name" : "DO_Fenetre station",
         "Notifications" : "false",
         "PlanID" : "2",
         "PlanIDs" : [ 2 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Closed",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Switch",
         "SwitchType" : "Door Contact",
         "SwitchTypeVal" : 11,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "door",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "208"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "Closed",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 1,
         "HardwareID" : 10,
         "HardwareName" : "Detecteurs portes  (virtuel)",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "00014145",
         "Image" : "Light",
         "InternalState" : "Closed",
         "IsSubDevice" : false,
         "LastUpdate" : "2019-05-08 19:33:57",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 100,
         "Name" : "DO_Porte de cuisine",
         "Notifications" : "false",
         "PlanID" : "2",
         "PlanIDs" : [ 2 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Closed",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Switch",
         "SwitchType" : "Door Contact",
         "SwitchTypeVal" : 11,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "door",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "245"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "Closed",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 1,
         "HardwareID" : 10,
         "HardwareName" : "Detecteurs portes  (virtuel)",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "00014148",
         "Image" : "Light",
         "InternalState" : "Closed",
         "IsSubDevice" : false,
         "LastUpdate" : "2019-05-01 18:22:39",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 100,
         "Name" : "DO_Porte Fenetre Sud",
         "Notifications" : "false",
         "PlanID" : "2",
         "PlanIDs" : [ 2 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Closed",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Switch",
         "SwitchType" : "Door Contact",
         "SwitchTypeVal" : 11,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "door",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "248"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 2.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 9,
         "Data" : "Off",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareID" : 2,
         "HardwareName" : "RFXcom 433E",
         "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
         "HardwareTypeVal" : 1,
         "HaveDimmer" : false,
         "HaveGroupCmd" : false,
         "HaveTimeout" : false,
         "ID" : "55550C",
         "Image" : "Generic",
         "InternalState" : "Off",
         "IsSubDevice" : false,
         "LastUpdate" : "2019-05-07 22:58:00",
         "Level" : 0,
         "LevelInt" : 452,
         "MaxDimLevel" : 0,
         "Name" : "Telec Bouton B",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : 8,
         "Status" : "",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "PT2262",
         "SwitchType" : "Push On Button",
         "SwitchTypeVal" : 9,
         "Timers" : "false",
         "Type" : "Lighting 4",
         "TypeImg" : "push",
         "Unit" : 0,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "241"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 10.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 9,
         "Data" : "Off",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareID" : 2,
         "HardwareName" : "RFXcom 433E",
         "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
         "HardwareTypeVal" : 1,
         "HaveDimmer" : false,
         "HaveGroupCmd" : false,
         "HaveTimeout" : false,
         "ID" : "029683",
         "Image" : "Generic",
         "IsSubDevice" : false,
         "LastUpdate" : "2019-05-08 19:33:35",
         "Level" : 0,
         "LevelInt" : 415,
         "MaxDimLevel" : 0,
         "Name" : "Porte cuisine Ouverte (event)",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : 6,
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "PT2262",
         "SwitchType" : "On/Off",
         "SwitchTypeVal" : 0,
         "Timers" : "false",
         "Type" : "Lighting 4",
         "TypeImg" : "lightbulb",
         "Unit" : 0,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "242"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 9,
         "Data" : "On",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareID" : 2,
         "HardwareName" : "RFXcom 433E",
         "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
         "HardwareTypeVal" : 1,
         "HaveDimmer" : false,
         "HaveGroupCmd" : false,
         "HaveTimeout" : false,
         "ID" : "029689",
         "Image" : "Generic",
         "IsSubDevice" : false,
         "LastUpdate" : "2019-05-08 19:33:57",
         "Level" : 0,
         "LevelInt" : 415,
         "MaxDimLevel" : 0,
         "Name" : "Porte cuisine Fermee (event)",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : 6,
         "Status" : "On",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "PT2262",
         "SwitchType" : "On/Off",
         "SwitchTypeVal" : 0,
         "Timers" : "false",
         "Type" : "Lighting 4",
         "TypeImg" : "lightbulb",
         "Unit" : 0,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "243"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 9,
         "Data" : "On",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareID" : 2,
         "HardwareName" : "RFXcom 433E",
         "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
         "HardwareTypeVal" : 1,
         "HaveDimmer" : false,
         "HaveGroupCmd" : false,
         "HaveTimeout" : false,
         "ID" : "048593",
         "Image" : "Generic",
         "IsSubDevice" : false,
         "LastUpdate" : "2019-05-01 18:21:17",
         "Level" : 0,
         "LevelInt" : 417,
         "MaxDimLevel" : 0,
         "Name" : "P/F sud Ouverte (event)",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : 8,
         "Status" : "On",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "PT2262",
         "SwitchType" : "On/Off",
         "SwitchTypeVal" : 0,
         "Timers" : "false",
         "Type" : "Lighting 4",
         "TypeImg" : "lightbulb",
         "Unit" : 0,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "246"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 9,
         "Data" : "On",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareID" : 2,
         "HardwareName" : "RFXcom 433E",
         "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
         "HardwareTypeVal" : 1,
         "HaveDimmer" : false,
         "HaveGroupCmd" : false,
         "HaveTimeout" : false,
         "ID" : "048599",
         "Image" : "Generic",
         "IsSubDevice" : false,
         "LastUpdate" : "2019-05-01 18:22:38",
         "Level" : 0,
         "LevelInt" : 417,
         "MaxDimLevel" : 0,
         "Name" : "P/F sud Fermee (event)",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : 8,
         "Status" : "On",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "PT2262",
         "SwitchType" : "On/Off",
         "SwitchTypeVal" : 0,
         "Timers" : "false",
         "Type" : "Lighting 4",
         "TypeImg" : "lightbulb",
         "Unit" : 0,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "247"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 5.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "Off",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareID" : 2,
         "HardwareName" : "RFXcom 433E",
         "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
         "HardwareTypeVal" : 1,
         "HaveDimmer" : false,
         "HaveGroupCmd" : false,
         "HaveTimeout" : false,
         "ID" : "EC090E",
         "Image" : "Light",
         "IsSubDevice" : false,
         "LastUpdate" : "2019-05-08 21:01:40",
         "Level" : 0,
         "LevelInt" : 410,
         "MaxDimLevel" : 0,
         "Name" : "PIR dégagement",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : 6,
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "PT2262",
         "SwitchType" : "Motion Sensor",
         "SwitchTypeVal" : 8,
         "Timers" : "false",
         "Type" : "Lighting 4",
         "TypeImg" : "motion",
         "Unit" : 0,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "249"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 9,
         "Data" : "On",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareID" : 9,
         "HardwareName" : "Passerelle Xiaomi zigbee",
         "HardwareType" : "Xiaomi Gateway",
         "HardwareTypeVal" : 95,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "029BBEC9",
         "Image" : "Generic",
         "IsSubDevice" : false,
         "LastUpdate" : "2019-05-07 22:57:06",
         "Level" : 70,
         "LevelActions" : "",
         "LevelInt" : 70,
         "LevelNames" : "T2ZmfGZsaXA5MHxmbGlwMTgwfG1vdmV8dGFwX3R3aWNlfHNoYWtlX2Fpcnxzd2luZ3xhbGVydHxmcmVlX2ZhbGx8cm90YXRl",
         "LevelOffHidden" : false,
         "MaxDimLevel" : 100,
         "Name" : "Aqara Cube",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "SelectorStyle" : 0,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "On",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Selector Switch",
         "SwitchType" : "Selector",
         "SwitchTypeVal" : 18,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "Light",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "250"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "4,500",
         "Description" : "",
         "Favorite" : 0,
         "HardwareID" : 9,
         "HardwareName" : "Passerelle Xiaomi zigbee",
         "HardwareType" : "Xiaomi Gateway",
         "HardwareTypeVal" : 95,
         "HaveTimeout" : false,
         "ID" : "9BBFFFC9",
         "LastUpdate" : "2019-05-05 17:22:03",
         "Name" : "Aqara Cube text",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : false,
         "SignalLevel" : "-",
         "SubType" : "Text",
         "Timers" : "false",
         "Type" : "General",
         "TypeImg" : "text",
         "Unit" : 1,
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "251"
      }
   ],
   "status" : "OK",
   "title" : "Devices"
});