exports.DOMOTICZ_GET_DEVICES = JSON.stringify({
   "ActTime" : 1540113093,
   "AstrTwilightEnd" : "20:34",
   "AstrTwilightStart" : "06:34",
   "CivTwilightEnd" : "19:22",
   "CivTwilightStart" : "07:45",
   "DayLength" : "10:34",
   "NautTwilightEnd" : "19:58",
   "NautTwilightStart" : "07:10",
   "ServerTime" : "2018-10-21 11:11:33",
   "SunAtSouth" : "13:05",
   "Sunrise" : "08:17",
   "Sunset" : "18:51",
   "app_version" : "4.10078",
   "result" : [
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "Off",
         "Description" : "",
         "DimmerType" : "abs",
         "Favorite" : 1,
         "HardwareID" : 3,
         "HardwareName" : "Hue Bridge",
         "HardwareType" : "Philips Hue Bridge",
         "HardwareTypeVal" : 38,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
      },
      {
         "HardwareID" : 4,
         "HardwareName" : "netatmo",
         "HardwareType" : "Netatmo",
         "HardwareTypeVal" : 54,
         "HaveTimeout" : false,
         "ID" : "000006A",
         "LastUpdate" : "2018-10-21 11:03:58",
         "Name" : "Consigne Thermostat",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "SetPoint" : "21.0",
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "SetPoint",
         "Timers" : "false",
         "Type" : "Thermostat",
         "TypeImg" : "override_mini",
         "Unit" : 1,
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "64"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "Open",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 1,
         "HardwareID" : 2,
         "HardwareName" : "RFX",
         "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
         "HardwareTypeVal" : 1,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "158ED3E",
         "Image" : "Light",
         "IsSubDevice" : false,
         "LastUpdate" : "2018-10-21 08:22:18",
         "Level" : 100,
         "LevelInt" : 15,
         "MaxDimLevel" : 15,
         "Name" : "Volet chambre",
         "Notifications" : "false",
         "PlanID" : "4",
         "PlanIDs" : [ 4 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : 6,
         "Status" : "Open",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "AC",
         "SwitchType" : "Blinds Inverted",
         "SwitchTypeVal" : 6,
         "Timers" : "true",
         "Type" : "Lighting 2",
         "TypeImg" : "blinds",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "1249",
         "YOffset" : "2568",
         "idx" : "185"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "Open",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 1,
         "HardwareID" : 2,
         "HardwareName" : "RFX",
         "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
         "HardwareTypeVal" : 1,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "158ED3E",
         "Image" : "Light",
         "IsSubDevice" : false,
         "LastUpdate" : "2018-10-21 08:15:01",
         "Level" : 100,
         "LevelInt" : 15,
         "MaxDimLevel" : 15,
         "Name" : "Volet salon",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Open",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "AC",
         "SwitchType" : "Blinds Inverted",
         "SwitchTypeVal" : 6,
         "Timers" : "true",
         "Type" : "Lighting 2",
         "TypeImg" : "blinds",
         "Unit" : 2,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "77"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "Off",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 1,
         "HardwareID" : 4,
         "HardwareName" : "netatmo",
         "HardwareType" : "Netatmo",
         "HardwareTypeVal" : 54,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "0000003",
         "Image" : "Light",
         "IsSubDevice" : false,
         "LastUpdate" : "2018-09-28 18:05:33",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 15,
         "Name" : "Thermostat mode absence",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : true,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "AC",
         "SwitchType" : "On/Off",
         "SwitchTypeVal" : 0,
         "Timers" : "false",
         "Type" : "Lighting 2",
         "TypeImg" : "lightbulb",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "65"
      }
   ],
   "status" : "OK",
   "title" : "Devices"
});
