exports.DOMOTICZ_GET_DEVICES = JSON.stringify({
ActTime: 1545084183,
AstrTwilightEnd: "18:49",
AstrTwilightStart: "06:48",
CivTwilightEnd: "17:26",
CivTwilightStart: "08:11",
DayLength: "07:57",
NautTwilightEnd: "18:09",
NautTwilightStart: "07:29",
ServerTime: "2018-12-17 23:03:03",
SunAtSouth: "12:05",
Sunrise: "08:51",
Sunset: "16:47",
app_version: "4.9700",
result: [
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 255,
Color: "",
CustomImage: 0,
Data: "Off",
Description: "",
DimmerType: "abs",
Favorite: 0,
HardwareID: 2,
HardwareName: "Passerelle Xiaomi",
HardwareType: "Xiaomi Gateway",
HardwareTypeVal: 95,
HaveDimmer: true,
HaveGroupCmd: false,
HaveTimeout: false,
ID: "EB17DC08",
Image: "Light",
IsSubDevice: false,
LastUpdate: "2018-12-17 22:47:24",
Level: 100,
LevelInt: 100,
MaxDimLevel: 100,
Name: "Xiaomi RGB Gateway",
Notifications: "false",
PlanID: "0",
PlanIDs: [
0
],
Protected: false,
ShowNotifications: true,
SignalLevel: "-",
Status: "Off",
StrParam1: "",
StrParam2: "",
SubType: "RGBW",
SwitchType: "Dimmer",
SwitchTypeVal: 7,
Timers: "false",
Type: "Color Switch",
TypeImg: "dimmer",
Unit: 1,
Used: 1,
UsedByCamera: false,
XOffset: "0",
YOffset: "0",
idx: "1"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 255,
CustomImage: 8,
Data: "Off",
Description: "",
DimmerType: "none",
Favorite: 0,
HardwareID: 2,
HardwareName: "Passerelle Xiaomi",
HardwareType: "Xiaomi Gateway",
HardwareTypeVal: 95,
HaveDimmer: true,
HaveGroupCmd: true,
HaveTimeout: false,
ID: "EB17DC08",
Image: "Speaker",
IsSubDevice: false,
LastUpdate: "2018-05-29 20:01:11",
Level: 0,
LevelActions: "",
LevelInt: 0,
LevelNames: "T2ZmfFBvbGljZSBzaXJlbiAxfFBvbGljZSBzaXJlbiAyfEFjY2lkZW50IHRvbmV8TWlzc2xlIGNvdW50ZG93bnxHaG9zdHxTbmlwZXJ8V2FyfEFpciBTdHJpa2V8QmFya2luZyBkb2dz",
LevelOffHidden: false,
MaxDimLevel: 100,
Name: "Xiaomi Gateway Alarm Ringtone",
Notifications: "false",
PlanID: "0",
PlanIDs: [
0
],
Protected: false,
SelectorStyle: 1,
ShowNotifications: true,
SignalLevel: "-",
Status: "Off",
StrParam1: "",
StrParam2: "",
SubType: "Selector Switch",
SwitchType: "Selector",
SwitchTypeVal: 18,
Timers: "false",
Type: "Light/Switch",
TypeImg: "Light",
Unit: 3,
Used: 1,
UsedByCamera: false,
XOffset: "0",
YOffset: "0",
idx: "2"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 255,
CustomImage: 8,
Data: "Off",
Description: "",
DimmerType: "none",
Favorite: 0,
HardwareID: 2,
HardwareName: "Passerelle Xiaomi",
HardwareType: "Xiaomi Gateway",
HardwareTypeVal: 95,
HaveDimmer: true,
HaveGroupCmd: true,
HaveTimeout: false,
ID: "EB17DC08",
Image: "Speaker",
IsSubDevice: false,
LastUpdate: "2018-06-11 21:26:59",
Level: 0,
LevelActions: "",
LevelInt: 0,
LevelNames: "T2ZmfE1pTWl4fEVudGh1c2lhc3RpY3xHdWl0YXJDbGFzc2ljfEljZVdvcmxkUGlhbm98TGVpc3VyZVRpbWV8Q2hpbGRob29kfE1vcm5pbmdTdHJlYW1sZXR8TXVzaWNCb3h8T3JhbmdlfFRoaW5rZXI=",
LevelOffHidden: false,
MaxDimLevel: 100,
Name: "Xiaomi Gateway Alarm Clock",
Notifications: "false",
PlanID: "0",
PlanIDs: [
0
],
Protected: false,
SelectorStyle: 1,
ShowNotifications: true,
SignalLevel: "-",
Status: "Off",
StrParam1: "",
StrParam2: "",
SubType: "Selector Switch",
SwitchType: "Selector",
SwitchTypeVal: 18,
Timers: "false",
Type: "Light/Switch",
TypeImg: "Light",
Unit: 4,
Used: 1,
UsedByCamera: false,
XOffset: "0",
YOffset: "0",
idx: "3"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 255,
CustomImage: 8,
Data: "Off",
Description: "",
DimmerType: "none",
Favorite: 0,
HardwareID: 2,
HardwareName: "Passerelle Xiaomi",
HardwareType: "Xiaomi Gateway",
HardwareTypeVal: 95,
HaveDimmer: true,
HaveGroupCmd: true,
HaveTimeout: false,
ID: "EB17DC08",
Image: "Speaker",
IsSubDevice: false,
LastUpdate: "2018-05-29 20:01:21",
Level: 0,
LevelActions: "",
LevelInt: 0,
LevelNames: "T2ZmfERvb3JiZWxsIHJpbmcgdG9uZXxLbm9jayBvbiBkb29yfEhpbGFyaW91c3xBbGFybSBjbG9jaw==",
LevelOffHidden: false,
MaxDimLevel: 100,
Name: "Xiaomi Gateway Doorbell",
Notifications: "false",
PlanID: "0",
PlanIDs: [
0
],
Protected: false,
SelectorStyle: 1,
ShowNotifications: true,
SignalLevel: "-",
Status: "Off",
StrParam1: "",
StrParam2: "",
SubType: "Selector Switch",
SwitchType: "Selector",
SwitchTypeVal: 18,
Timers: "false",
Type: "Light/Switch",
TypeImg: "Light",
Unit: 5,
Used: 1,
UsedByCamera: false,
XOffset: "0",
YOffset: "0",
idx: "4"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 255,
CustomImage: 8,
Data: "Off",
Description: "",
DimmerType: "none",
Favorite: 0,
HardwareID: 2,
HardwareName: "Passerelle Xiaomi",
HardwareType: "Xiaomi Gateway",
HardwareTypeVal: 95,
HaveDimmer: true,
HaveGroupCmd: true,
HaveTimeout: false,
ID: "EB17DC08",
Image: "Speaker",
IsSubDevice: false,
LastUpdate: "2018-05-22 19:27:41",
Level: 0,
LevelInt: 0,
MaxDimLevel: 100,
Name: "Xiaomi Gateway MP3",
Notifications: "false",
PlanID: "0",
PlanIDs: [
0
],
Protected: false,
ShowNotifications: true,
SignalLevel: "-",
Status: "Off",
StrParam1: "",
StrParam2: "",
SubType: "Switch",
SwitchType: "On/Off",
SwitchTypeVal: 0,
Timers: "false",
Type: "Light/Switch",
TypeImg: "lightbulb",
Unit: 6,
Used: 1,
UsedByCamera: false,
XOffset: "0",
YOffset: "0",
idx: "5"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 255,
CustomImage: 8,
Data: "Off",
Description: "",
DimmerType: "abs",
Favorite: 0,
HardwareID: 2,
HardwareName: "Passerelle Xiaomi",
HardwareType: "Xiaomi Gateway",
HardwareTypeVal: 95,
HaveDimmer: true,
HaveGroupCmd: true,
HaveTimeout: false,
ID: "EB17DC08",
Image: "Speaker",
IsSubDevice: false,
LastUpdate: "2018-06-11 21:26:37",
Level: 68,
LevelInt: 68,
MaxDimLevel: 100,
Name: "Xiaomi Gateway Volume",
Notifications: "false",
PlanID: "0",
PlanIDs: [
0
],
Protected: false,
ShowNotifications: true,
SignalLevel: "-",
Status: "Off",
StrParam1: "",
StrParam2: "",
SubType: "Switch",
SwitchType: "Dimmer",
SwitchTypeVal: 7,
Timers: "false",
Type: "Light/Switch",
TypeImg: "dimmer",
Unit: 7,
Used: 1,
UsedByCamera: false,
XOffset: "0",
YOffset: "0",
idx: "6"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 82,
CustomImage: 0,
Data: "3.025 V",
Description: "",
Favorite: 0,
HardwareID: 2,
HardwareName: "Passerelle Xiaomi",
HardwareType: "Xiaomi Gateway",
HardwareTypeVal: 95,
HaveTimeout: true,
ID: "4A4FDFDA",
LastUpdate: "2018-06-26 18:21:24",
Name: "Xiaomi Voltage",
Notifications: "false",
PlanID: "0",
PlanIDs: [
0
],
Protected: false,
ShowNotifications: true,
SignalLevel: "-",
SubType: "Voltage",
Timers: "false",
Type: "General",
TypeImg: "current",
Unit: 1,
Used: 1,
Voltage: 3.025,
XOffset: "0",
YOffset: "0",
idx: "8"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 84,
CustomImage: 9,
Data: "Off",
Description: "",
DimmerType: "none",
Favorite: 0,
HardwareID: 2,
HardwareName: "Passerelle Xiaomi",
HardwareType: "Xiaomi Gateway",
HardwareTypeVal: 95,
HaveDimmer: true,
HaveGroupCmd: true,
HaveTimeout: false,
ID: "0251EF4F",
Image: "Generic",
IsSubDevice: false,
LastUpdate: "2018-11-20 17:54:32",
Level: 0,
LevelActions: "",
LevelInt: 0,
LevelNames: "T2ZmfENsaWNrfERvdWJsZSBDbGlja3xMb25nIENsaWNrfExvbmcgQ2xpY2sgUmVsZWFzZQ==",
LevelOffHidden: false,
MaxDimLevel: 100,
Name: "Bunton 1",
Notifications: "false",
PlanID: "0",
PlanIDs: [
0
],
Protected: false,
SelectorStyle: 0,
ShowNotifications: true,
SignalLevel: "-",
Status: "Off",
StrParam1: "",
StrParam2: "",
SubType: "Selector Switch",
SwitchType: "Selector",
SwitchTypeVal: 18,
Timers: "false",
Type: "Light/Switch",
TypeImg: "Light",
Unit: 1,
Used: 1,
UsedByCamera: false,
XOffset: "0",
YOffset: "0",
idx: "9"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 87,
CustomImage: 0,
Data: "3.072 V",
Description: "",
Favorite: 0,
HardwareID: 2,
HardwareName: "Passerelle Xiaomi",
HardwareType: "Xiaomi Gateway",
HardwareTypeVal: 95,
HaveTimeout: true,
ID: "53FFEF4F",
LastUpdate: "2018-06-26 19:08:40",
Name: "Xiaomi Voltage",
Notifications: "false",
PlanID: "0",
PlanIDs: [
0
],
Protected: false,
ShowNotifications: true,
SignalLevel: "-",
SubType: "Voltage",
Timers: "false",
Type: "General",
TypeImg: "current",
Unit: 1,
Used: 1,
Voltage: 3.072,
XOffset: "0",
YOffset: "0",
idx: "10"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 255,
CustomImage: 13,
Data: "Off",
Description: "",
DimmerType: "none",
Favorite: 1,
HardwareID: 5,
HardwareName: "virtuel",
HardwareType: "Dummy (Does nothing, use for virtual switches only)",
HardwareTypeVal: 15,
HaveDimmer: true,
HaveGroupCmd: true,
HaveTimeout: false,
ID: "0001406F",
Image: "Alarm",
IsSubDevice: false,
LastUpdate: "2018-12-13 19:41:53",
Level: 0,
LevelInt: 0,
MaxDimLevel: 100,
Name: "Alarme",
Notifications: "true",
PlanID: "0",
PlanIDs: [
0
],
Protected: false,
ShowNotifications: true,
SignalLevel: "-",
Status: "Off",
StrParam1: "",
StrParam2: "",
SubType: "Switch",
SwitchType: "On/Off",
SwitchTypeVal: 0,
Timers: "false",
Type: "Light/Switch",
TypeImg: "lightbulb",
Unit: 1,
Used: 1,
UsedByCamera: false,
XOffset: "0",
YOffset: "0",
idx: "31"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 88,
CustomImage: 0,
Data: "Off",
Description: "",
DimmerType: "none",
Favorite: 0,
HardwareID: 2,
HardwareName: "Passerelle Xiaomi",
HardwareType: "Xiaomi Gateway",
HardwareTypeVal: 95,
HaveDimmer: true,
HaveGroupCmd: true,
HaveTimeout: false,
ID: "01E58DF0",
Image: "Light",
IsSubDevice: false,
LastUpdate: "2018-09-08 15:21:28",
Level: 0,
LevelInt: 0,
MaxDimLevel: 100,
Name: "Détecteur de fumée RDC",
Notifications: "true",
PlanID: "3",
PlanIDs: [
3
],
Protected: false,
ShowNotifications: true,
SignalLevel: "-",
Status: "Off",
StrParam1: "",
StrParam2: "",
SubType: "Switch",
SwitchType: "Smoke Detector",
SwitchTypeVal: 5,
Timers: "false",
Type: "Light/Switch",
TypeImg: "smoke",
Unit: 1,
Used: 1,
UsedByCamera: false,
XOffset: "1943",
YOffset: "912",
idx: "167"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 76,
CustomImage: 0,
Data: "Closed",
Description: "",
DimmerType: "none",
Favorite: 0,
HardwareID: 2,
HardwareName: "Passerelle Xiaomi",
HardwareType: "Xiaomi Gateway",
HardwareTypeVal: 95,
HaveDimmer: true,
HaveGroupCmd: true,
HaveTimeout: false,
ID: "022CFDBF",
Image: "Light",
IsSubDevice: false,
LastUpdate: "2018-12-17 19:04:21",
Level: 0,
LevelInt: 0,
MaxDimLevel: 100,
Name: "Porte d'entrée",
Notifications: "false",
PlanID: "7",
PlanIDs: [
7
],
Protected: false,
ShowNotifications: true,
SignalLevel: "-",
Status: "Closed",
StrParam1: "",
StrParam2: "",
SubType: "Switch",
SwitchType: "Contact",
SwitchTypeVal: 2,
Timers: "false",
Type: "Light/Switch",
TypeImg: "contact",
Unit: 1,
Used: 1,
UsedByCamera: false,
XOffset: "2371",
YOffset: "831",
idx: "11"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 255,
CustomImage: 1,
Data: "Off",
Description: "",
DimmerType: "none",
Favorite: 1,
HardwareID: 2,
HardwareName: "Passerelle Xiaomi",
HardwareType: "Xiaomi Gateway",
HardwareTypeVal: 95,
HaveDimmer: true,
HaveGroupCmd: true,
HaveTimeout: false,
ID: "0247F116",
Image: "WallSocket",
IsSubDevice: false,
LastUpdate: "2018-12-17 16:47:01",
Level: 100,
LevelInt: 100,
MaxDimLevel: 100,
Name: "Prise Tortue",
Notifications: "true",
PlanID: "2",
PlanIDs: [
2
],
Protected: false,
ShowNotifications: true,
SignalLevel: "-",
Status: "Off",
StrParam1: "",
StrParam2: "",
SubType: "Switch",
SwitchType: "On/Off",
SwitchTypeVal: 0,
Timers: "true",
Type: "Light/Switch",
TypeImg: "lightbulb",
Unit: 1,
Used: 1,
UsedByCamera: false,
XOffset: "475",
YOffset: "47",
idx: "7"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 78,
CustomImage: 0,
Data: "2.985 V",
Description: "",
Favorite: 0,
HardwareID: 2,
HardwareName: "Passerelle Xiaomi",
HardwareType: "Xiaomi Gateway",
HardwareTypeVal: 95,
HaveTimeout: true,
ID: "2EFDFFBF",
LastUpdate: "2018-06-26 18:25:51",
Name: "Xiaomi Voltage",
Notifications: "false",
PlanID: "0",
PlanIDs: [
0
],
Protected: false,
ShowNotifications: true,
SignalLevel: "-",
SubType: "Voltage",
Timers: "false",
Type: "General",
TypeImg: "current",
Unit: 1,
Used: 1,
Voltage: 2.985,
XOffset: "0",
YOffset: "0",
idx: "12"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 255,
CustomImage: 0,
Data: "Humidity 52 %",
Description: "",
Favorite: 0,
HardwareID: 2,
HardwareName: "Passerelle Xiaomi",
HardwareType: "Xiaomi Gateway",
HardwareTypeVal: 95,
HaveTimeout: false,
Humidity: 52,
HumidityStatus: "Comfortable",
ID: "ED18",
LastUpdate: "2018-12-17 23:02:15",
Name: "Humidité Salle à manger",
Notifications: "false",
PlanID: "2",
PlanIDs: [
2
],
Protected: false,
ShowNotifications: true,
SignalLevel: "-",
SubType: "LaCrosse TX3",
Timers: "false",
Type: "Humidity",
TypeImg: "temperature",
Unit: 1,
Used: 1,
XOffset: "764",
YOffset: "303",
idx: "14"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 255,
CustomImage: 0,
Data: "20.4 C, 52 %",
Description: "",
DewPoint: "10.21",
Favorite: 0,
HardwareID: 2,
HardwareName: "Passerelle Xiaomi",
HardwareType: "Xiaomi Gateway",
HardwareTypeVal: 95,
HaveTimeout: false,
Humidity: 52,
HumidityStatus: "Comfortable",
ID: "ED18",
LastUpdate: "2018-12-17 23:02:15",
Name: "Temp & Hu Salle à manger",
Notifications: "false",
PlanID: "2",
PlanIDs: [
2
],
Protected: false,
ShowNotifications: true,
SignalLevel: "-",
SubType: "LaCrosse TX3",
Temp: 20.4,
Timers: "false",
Type: "Temp + Humidity",
TypeImg: "temperature",
Unit: 2,
Used: 1,
XOffset: "824",
YOffset: "243",
idx: "25"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 100,
CustomImage: 0,
Data: "20.4 C",
Description: "",
Favorite: 0,
HardwareID: 2,
HardwareName: "Passerelle Xiaomi",
HardwareType: "Xiaomi Gateway",
HardwareTypeVal: 95,
HaveTimeout: false,
ID: "ED18",
LastUpdate: "2018-12-17 23:02:15",
Name: "Température Salle à manger",
Notifications: "false",
PlanID: "2",
PlanIDs: [
2
],
Protected: false,
ShowNotifications: true,
SignalLevel: "-",
SubType: "LaCrosse TX3",
Temp: 20.4,
Timers: "false",
Type: "Temp",
TypeImg: "temperature",
Unit: 24,
Used: 1,
XOffset: "762",
YOffset: "243",
idx: "13"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 255,
CounterToday: "1 kWh",
CustomImage: 0,
Data: "181 kWh",
Description: "",
Favorite: 0,
HardwareID: 2,
HardwareName: "Passerelle Xiaomi",
HardwareType: "Xiaomi Gateway",
HardwareTypeVal: 95,
HaveTimeout: false,
ID: "47F11601",
LastUpdate: "2018-12-17 23:01:44",
Name: "Conso Prise Tortue",
Notifications: "false",
Options: "",
PlanID: "0",
PlanIDs: [
0
],
Protected: false,
ShowNotifications: true,
SignalLevel: "-",
SubType: "kWh",
SwitchTypeVal: 0,
Timers: "false",
Type: "General",
TypeImg: "current",
Unit: 1,
Usage: "0 Watt",
Used: 1,
XOffset: "0",
YOffset: "0",
idx: "15"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 255,
CustomImage: 0,
Data: "21.0 C, (17.0 C), Auto",
Description: "",
Favorite: 0,
HardwareID: 3,
HardwareName: "Evohome",
HardwareType: "Evohome via Web API",
HardwareTypeVal: 75,
HaveTimeout: false,
ID: "3784453",
LastUpdate: "2018-12-17 23:02:32",
Name: "Salon",
Notifications: "false",
PlanID: "0",
PlanIDs: [
0
],
Protected: false,
SetPoint: 17,
ShowNotifications: true,
SignalLevel: 10,
Status: "Auto",
SubType: "Zone",
Temp: 21,
Timers: "false",
Type: "Heating",
TypeImg: "override_mini",
Unit: 1,
Used: 1,
XOffset: "0",
YOffset: "0",
idx: "17"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 255,
CustomImage: 0,
Data: "Auto",
Description: "",
Favorite: 1,
HardwareID: 3,
HardwareName: "Evohome",
HardwareType: "Evohome via Web API",
HardwareTypeVal: 75,
HaveDimmer: false,
HaveGroupCmd: false,
HaveTimeout: false,
ID: "3784460",
LastUpdate: "2018-11-28 09:48:57",
MaxDimLevel: 0,
Name: "EvoTouch",
Notifications: "false",
PlanID: "3",
PlanIDs: [
3
],
Protected: false,
ShowNotifications: true,
SignalLevel: "-",
Status: "Auto",
StrParam1: "",
StrParam2: "",
SubType: "Evohome",
SwitchType: "evohome",
SwitchTypeVal: 0,
Timers: "false",
Type: "Heating",
TypeImg: "override_mini",
Unit: 0,
Used: 1,
XOffset: "1754",
YOffset: "167",
idx: "18"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 255,
CustomImage: 0,
Data: "21.5 C, (16.0 C), Auto",
Description: "",
Favorite: 0,
HardwareID: 3,
HardwareName: "Evohome",
HardwareType: "Evohome via Web API",
HardwareTypeVal: 75,
HaveTimeout: false,
ID: "3784454",
LastUpdate: "2018-12-17 23:02:32",
Name: "Salle de bain",
Notifications: "false",
PlanID: "5",
PlanIDs: [
5
],
Protected: false,
SetPoint: 16,
ShowNotifications: true,
SignalLevel: 10,
Status: "Auto",
SubType: "Zone",
Temp: 21.5,
Timers: "false",
Type: "Heating",
TypeImg: "override_mini",
Unit: 2,
Used: 1,
XOffset: "1490",
YOffset: "778",
idx: "19"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 255,
CustomImage: 0,
Data: "19.0 C, (17.0 C), Auto",
Description: "",
Favorite: 0,
HardwareID: 3,
HardwareName: "Evohome",
HardwareType: "Evohome via Web API",
HardwareTypeVal: 75,
HaveTimeout: false,
ID: "3784455",
LastUpdate: "2018-12-17 23:02:32",
Name: "Parents",
Notifications: "false",
PlanID: "8",
PlanIDs: [
8
],
Protected: false,
SetPoint: 17,
ShowNotifications: true,
SignalLevel: 10,
Status: "Auto",
SubType: "Zone",
Temp: 19,
Timers: "false",
Type: "Heating",
TypeImg: "override_mini",
Unit: 3,
Used: 1,
XOffset: "631",
YOffset: "1243",
idx: "20"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 255,
CustomImage: 0,
Data: "19.0 C, (17.0 C), Auto",
Description: "",
Favorite: 0,
HardwareID: 3,
HardwareName: "Evohome",
HardwareType: "Evohome via Web API",
HardwareTypeVal: 75,
HaveTimeout: false,
ID: "3784456",
LastUpdate: "2018-12-17 23:02:32",
Name: "Lola",
Notifications: "false",
PlanID: "10",
PlanIDs: [
10
],
Protected: false,
SetPoint: 17,
ShowNotifications: true,
SignalLevel: 10,
Status: "Auto",
SubType: "Zone",
Temp: 19,
Timers: "false",
Type: "Heating",
TypeImg: "override_mini",
Unit: 4,
Used: 1,
XOffset: "1490",
YOffset: "512",
idx: "21"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 255,
CustomImage: 0,
Data: "17.5 C, (17.0 C), Auto",
Description: "",
Favorite: 0,
HardwareID: 3,
HardwareName: "Evohome",
HardwareType: "Evohome via Web API",
HardwareTypeVal: 75,
HaveTimeout: false,
ID: "3784457",
LastUpdate: "2018-12-17 23:02:32",
Name: "Lison",
Notifications: "false",
PlanID: "9",
PlanIDs: [
9
],
Protected: false,
SetPoint: 17,
ShowNotifications: true,
SignalLevel: 10,
Status: "Auto",
SubType: "Zone",
Temp: 17.5,
Timers: "false",
Type: "Heating",
TypeImg: "override_mini",
Unit: 5,
Used: 1,
XOffset: "886",
YOffset: "464",
idx: "22"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 255,
CustomImage: 0,
Data: "19.0 C, (17.0 C), Auto",
Description: "",
Favorite: 0,
HardwareID: 3,
HardwareName: "Evohome",
HardwareType: "Evohome via Web API",
HardwareTypeVal: 75,
HaveTimeout: false,
ID: "3784458",
LastUpdate: "2018-12-17 23:02:32",
Name: "Bureau",
Notifications: "false",
PlanID: "11",
PlanIDs: [
11
],
Protected: false,
SetPoint: 17,
ShowNotifications: true,
SignalLevel: 10,
Status: "Auto",
SubType: "Zone",
Temp: 19,
Timers: "false",
Type: "Heating",
TypeImg: "override_mini",
Unit: 6,
Used: 1,
XOffset: "1620",
YOffset: "1294",
idx: "23"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 255,
CustomImage: 0,
Data: "20.5 C, (12.5 C), PermanentOverride",
Description: "",
Favorite: 0,
HardwareID: 3,
HardwareName: "Evohome",
HardwareType: "Evohome via Web API",
HardwareTypeVal: 75,
HaveTimeout: false,
ID: "3784459",
LastUpdate: "2018-12-17 23:02:32",
Name: "Salle de jeux",
Notifications: "false",
PlanID: "13",
PlanIDs: [
13
],
Protected: false,
SetPoint: 12.5,
ShowNotifications: true,
SignalLevel: 10,
Status: "PermanentOverride",
SubType: "Zone",
Temp: 20.5,
Timers: "false",
Type: "Heating",
TypeImg: "override_mini",
Unit: 7,
Used: 1,
XOffset: "1210",
YOffset: "795",
idx: "24"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 255,
CustomImage: 0,
Data: "338 Lux",
Description: "",
Favorite: 0,
HardwareID: 2,
HardwareName: "Passerelle Xiaomi",
HardwareType: "Xiaomi Gateway",
HardwareTypeVal: 95,
HaveTimeout: false,
ID: "0000008",
LastUpdate: "2018-12-17 22:47:24",
Name: "Xiaomi Gateway Lux",
Notifications: "false",
PlanID: "0",
PlanIDs: [
0
],
Protected: false,
ShowNotifications: true,
SignalLevel: "-",
SubType: "Lux",
Timers: "false",
Type: "Lux",
TypeImg: "lux",
Unit: 8,
Used: 1,
XOffset: "0",
YOffset: "0",
idx: "30"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 255,
CustomImage: 0,
Data: "Off",
Description: "",
DimmerType: "none",
Favorite: 0,
HardwareID: 2,
HardwareName: "Passerelle Xiaomi",
HardwareType: "Xiaomi Gateway",
HardwareTypeVal: 95,
HaveDimmer: true,
HaveGroupCmd: true,
HaveTimeout: false,
ID: "024807DA",
Image: "Light",
IsSubDevice: false,
LastUpdate: "2018-12-17 22:21:28",
Level: 0,
LevelInt: 0,
MaxDimLevel: 100,
Name: "détecteur de mouvement",
Notifications: "false",
PlanID: "0",
PlanIDs: [
0
],
Protected: false,
ShowNotifications: true,
SignalLevel: "-",
Status: "Off",
StrParam1: "",
StrParam2: "",
SubType: "Switch",
SwitchType: "Motion Sensor",
SwitchTypeVal: 8,
Timers: "false",
Type: "Light/Switch",
TypeImg: "motion",
Unit: 1,
Used: 1,
UsedByCamera: false,
XOffset: "0",
YOffset: "0",
idx: "33"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 100,
CustomImage: 0,
Data: "21.6 C",
Description: "",
Favorite: 0,
HardwareID: 2,
HardwareName: "Passerelle Xiaomi",
HardwareType: "Xiaomi Gateway",
HardwareTypeVal: 95,
HaveTimeout: false,
ID: "C984",
LastUpdate: "2018-12-17 22:56:37",
Name: "Température Salle de Bain",
Notifications: "false",
PlanID: "5",
PlanIDs: [
5
],
Protected: false,
ShowNotifications: true,
SignalLevel: "-",
SubType: "LaCrosse TX3",
Temp: 21.6,
Timers: "false",
Type: "Temp",
TypeImg: "temperature",
Unit: 132,
Used: 1,
XOffset: "1351",
YOffset: "966",
idx: "34"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 255,
CustomImage: 0,
Data: "Humidity 49 %",
Description: "",
Favorite: 0,
HardwareID: 2,
HardwareName: "Passerelle Xiaomi",
HardwareType: "Xiaomi Gateway",
HardwareTypeVal: 95,
HaveTimeout: false,
Humidity: 49,
HumidityStatus: "Comfortable",
ID: "C984",
LastUpdate: "2018-12-17 22:56:37",
Name: "Humidité Salle de bain",
Notifications: "false",
PlanID: "5",
PlanIDs: [
5
],
Protected: false,
ShowNotifications: true,
SignalLevel: "-",
SubType: "LaCrosse TX3",
Timers: "false",
Type: "Humidity",
TypeImg: "temperature",
Unit: 1,
Used: 1,
XOffset: "1422",
YOffset: "961",
idx: "35"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 255,
CustomImage: 0,
Data: "1019.0 Bar",
Description: "",
Favorite: 0,
HardwareID: 2,
HardwareName: "Passerelle Xiaomi",
HardwareType: "Xiaomi Gateway",
HardwareTypeVal: 95,
HaveTimeout: false,
ID: "2CC98401",
LastUpdate: "2018-12-17 22:56:38",
Name: "Pression Salle de bain",
Notifications: "false",
PlanID: "5",
PlanIDs: [
5
],
Pressure: 1019,
Protected: false,
ShowNotifications: true,
SignalLevel: "-",
SubType: "Pressure",
Timers: "false",
Type: "General",
TypeImg: "gauge",
Unit: 1,
Used: 1,
XOffset: "1285",
YOffset: "963",
idx: "36"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 255,
CustomImage: 0,
Data: "21.6 C, 49 %",
Description: "",
DewPoint: "10.43",
Favorite: 0,
HardwareID: 2,
HardwareName: "Passerelle Xiaomi",
HardwareType: "Xiaomi Gateway",
HardwareTypeVal: 95,
HaveTimeout: false,
Humidity: 49,
HumidityStatus: "Comfortable",
ID: "C984",
LastUpdate: "2018-12-17 22:56:37",
Name: "Temp & Hu Salle de bain",
Notifications: "false",
PlanID: "5",
PlanIDs: [
5
],
Protected: false,
ShowNotifications: true,
SignalLevel: "-",
SubType: "LaCrosse TX3",
Temp: 21.6,
Timers: "false",
Type: "Temp + Humidity",
TypeImg: "temperature",
Unit: 2,
Used: 1,
XOffset: "1275",
YOffset: "1015",
idx: "37"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 75,
CustomImage: 0,
Data: "Closed",
Description: "",
DimmerType: "none",
Favorite: 0,
HardwareID: 2,
HardwareName: "Passerelle Xiaomi",
HardwareType: "Xiaomi Gateway",
HardwareTypeVal: 95,
HaveDimmer: true,
HaveGroupCmd: true,
HaveTimeout: false,
ID: "01F388B9",
Image: "Light",
IsSubDevice: false,
LastUpdate: "2018-10-22 18:45:56",
Level: 0,
LevelInt: 0,
MaxDimLevel: 100,
Name: "Fenêtre D Salon",
Notifications: "false",
PlanID: "3",
PlanIDs: [
3
],
Protected: false,
ShowNotifications: true,
SignalLevel: "-",
Status: "Closed",
StrParam1: "",
StrParam2: "",
SubType: "Switch",
SwitchType: "Contact",
SwitchTypeVal: 2,
Timers: "false",
Type: "Light/Switch",
TypeImg: "contact",
Unit: 1,
Used: 1,
UsedByCamera: false,
XOffset: "2356",
YOffset: "513",
idx: "38"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 77,
CustomImage: 0,
Data: "2.975 V",
Description: "",
Favorite: 0,
HardwareID: 2,
HardwareName: "Passerelle Xiaomi",
HardwareType: "Xiaomi Gateway",
HardwareTypeVal: 95,
HaveTimeout: true,
ID: "F3FBB9B9",
LastUpdate: "2018-06-26 18:45:44",
Name: "voltage fenetre salon",
Notifications: "false",
PlanID: "0",
PlanIDs: [
0
],
Protected: false,
ShowNotifications: true,
SignalLevel: "-",
SubType: "Voltage",
Timers: "false",
Type: "General",
TypeImg: "current",
Unit: 1,
Used: 1,
Voltage: 2.975,
XOffset: "0",
YOffset: "0",
idx: "39"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 78,
CustomImage: 0,
Data: "Closed",
Description: "",
DimmerType: "none",
Favorite: 0,
HardwareID: 2,
HardwareName: "Passerelle Xiaomi",
HardwareType: "Xiaomi Gateway",
HardwareTypeVal: 95,
HaveDimmer: true,
HaveGroupCmd: true,
HaveTimeout: false,
ID: "0253701E",
Image: "Light",
IsSubDevice: false,
LastUpdate: "2018-10-21 09:17:53",
Level: 0,
LevelInt: 0,
MaxDimLevel: 100,
Name: "Fenêtre G Salon",
Notifications: "false",
PlanID: "3",
PlanIDs: [
3
],
Protected: false,
ShowNotifications: true,
SignalLevel: "-",
Status: "Closed",
StrParam1: "",
StrParam2: "",
SubType: "Switch",
SwitchType: "Contact",
SwitchTypeVal: 2,
Timers: "false",
Type: "Light/Switch",
TypeImg: "contact",
Unit: 1,
Used: 1,
UsedByCamera: false,
XOffset: "2354",
YOffset: "199",
idx: "187"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 255,
CustomImage: 1,
Data: "Off",
Description: "",
DimmerType: "none",
Favorite: 0,
HardwareID: 6,
HardwareName: "rflink 433",
HardwareType: "RFLink Gateway USB",
HardwareTypeVal: 46,
HaveDimmer: false,
HaveGroupCmd: false,
HaveTimeout: false,
ID: "00000000",
Image: "WallSocket",
IsSubDevice: false,
LastUpdate: "2018-09-03 20:52:08",
Level: 0,
LevelInt: 0,
MaxDimLevel: 100,
Name: "prise carrefour 1",
Notifications: "false",
PlanID: "0",
PlanIDs: [
0
],
Protected: false,
ShowNotifications: true,
SignalLevel: "-",
Status: "Off",
StrParam1: "",
StrParam2: "",
SubType: "Powerfix",
SwitchType: "On/Off",
SwitchTypeVal: 0,
Timers: "false",
Type: "Light/Switch",
TypeImg: "lightbulb",
Unit: 0,
Used: 1,
UsedByCamera: false,
XOffset: "0",
YOffset: "0",
idx: "40"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 78,
CustomImage: 0,
Data: "Closed",
Description: "",
DimmerType: "none",
Favorite: 0,
HardwareID: 2,
HardwareName: "Passerelle Xiaomi",
HardwareType: "Xiaomi Gateway",
HardwareTypeVal: 95,
HaveDimmer: true,
HaveGroupCmd: true,
HaveTimeout: false,
ID: "01D83B4B",
Image: "Light",
IsSubDevice: false,
LastUpdate: "2018-12-09 13:53:30",
Level: 0,
LevelInt: 0,
MaxDimLevel: 100,
Name: "Porte fenêtre DD Salle à manger",
Notifications: "false",
PlanID: "2",
PlanIDs: [
2
],
Protected: false,
ShowNotifications: true,
SignalLevel: "-",
Status: "Closed",
StrParam1: "",
StrParam2: "",
SubType: "Switch",
SwitchType: "Contact",
SwitchTypeVal: 2,
Timers: "false",
Type: "Light/Switch",
TypeImg: "contact",
Unit: 1,
Used: 1,
UsedByCamera: false,
XOffset: "61",
YOffset: "94",
idx: "57"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 80,
CustomImage: 0,
Data: "3.005 V",
Description: "",
Favorite: 0,
HardwareID: 2,
HardwareName: "Passerelle Xiaomi",
HardwareType: "Xiaomi Gateway",
HardwareTypeVal: 95,
HaveTimeout: true,
ID: "D9FB7B4B",
LastUpdate: "2018-06-26 19:00:32",
Name: "salle porte fenêtre 1",
Notifications: "false",
PlanID: "0",
PlanIDs: [
0
],
Protected: false,
ShowNotifications: true,
SignalLevel: "-",
SubType: "Voltage",
Timers: "false",
Type: "General",
TypeImg: "current",
Unit: 1,
Used: 1,
Voltage: 3.005,
XOffset: "0",
YOffset: "0",
idx: "58"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 78,
CustomImage: 0,
Data: "Off",
Description: "",
DimmerType: "none",
Favorite: 0,
HardwareID: 2,
HardwareName: "Passerelle Xiaomi",
HardwareType: "Xiaomi Gateway",
HardwareTypeVal: 95,
HaveDimmer: true,
HaveGroupCmd: true,
HaveTimeout: false,
ID: "01C1B01E",
Image: "Light",
IsSubDevice: false,
LastUpdate: "2018-08-26 20:35:37",
Level: 0,
LevelInt: 0,
MaxDimLevel: 100,
Name: "détecteur d'eau Cave",
Notifications: "true",
PlanID: "12",
PlanIDs: [
12
],
Protected: false,
ShowNotifications: true,
SignalLevel: "-",
Status: "Off",
StrParam1: "",
StrParam2: "",
SubType: "Switch",
SwitchType: "Smoke Detector",
SwitchTypeVal: 5,
Timers: "false",
Type: "Light/Switch",
TypeImg: "smoke",
Unit: 1,
Used: 1,
UsedByCamera: false,
XOffset: "503",
YOffset: "1782",
idx: "59"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 82,
CustomImage: 0,
Data: "Closed",
Description: "",
DimmerType: "none",
Favorite: 0,
HardwareID: 2,
HardwareName: "Passerelle Xiaomi",
HardwareType: "Xiaomi Gateway",
HardwareTypeVal: 95,
HaveDimmer: true,
HaveGroupCmd: true,
HaveTimeout: false,
ID: "020B55AA",
Image: "Light",
IsSubDevice: false,
LastUpdate: "2018-11-11 13:45:49",
Level: 0,
LevelInt: 0,
MaxDimLevel: 100,
Name: "Porte fenêtre DG Salle à manger",
Notifications: "false",
PlanID: "2",
PlanIDs: [
2
],
Protected: false,
ShowNotifications: true,
SignalLevel: "-",
Status: "Closed",
StrParam1: "",
StrParam2: "",
SubType: "Switch",
SwitchType: "Contact",
SwitchTypeVal: 2,
Timers: "false",
Type: "Light/Switch",
TypeImg: "contact",
Unit: 1,
Used: 1,
UsedByCamera: false,
XOffset: "54",
YOffset: "491",
idx: "60"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 80,
CustomImage: 0,
Data: "Closed",
Description: "",
DimmerType: "none",
Favorite: 0,
HardwareID: 2,
HardwareName: "Passerelle Xiaomi",
HardwareType: "Xiaomi Gateway",
HardwareTypeVal: 95,
HaveDimmer: true,
HaveGroupCmd: true,
HaveTimeout: false,
ID: "020B7D37",
Image: "Light",
IsSubDevice: false,
LastUpdate: "2018-12-17 12:32:52",
Level: 0,
LevelInt: 0,
MaxDimLevel: 100,
Name: "Porte fenêtre GD Salle à manger",
Notifications: "false",
PlanID: "2",
PlanIDs: [
2
],
Protected: false,
ShowNotifications: true,
SignalLevel: "-",
Status: "Closed",
StrParam1: "",
StrParam2: "",
SubType: "Switch",
SwitchType: "Contact",
SwitchTypeVal: 2,
Timers: "false",
Type: "Light/Switch",
TypeImg: "contact",
Unit: 1,
Used: 1,
UsedByCamera: false,
XOffset: "546",
YOffset: "564",
idx: "91"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 80,
CustomImage: 0,
Data: "Closed",
Description: "",
DimmerType: "none",
Favorite: 0,
HardwareID: 2,
HardwareName: "Passerelle Xiaomi",
HardwareType: "Xiaomi Gateway",
HardwareTypeVal: 95,
HaveDimmer: true,
HaveGroupCmd: true,
HaveTimeout: false,
ID: "0204688E",
Image: "Light",
IsSubDevice: false,
LastUpdate: "2018-12-12 19:50:46",
Level: 0,
LevelInt: 0,
MaxDimLevel: 100,
Name: "Porte fenêtre GG Salle à manger",
Notifications: "false",
PlanID: "2",
PlanIDs: [
2
],
Protected: false,
ShowNotifications: true,
SignalLevel: "-",
Status: "Closed",
StrParam1: "",
StrParam2: "",
SubType: "Switch",
SwitchType: "Contact",
SwitchTypeVal: 2,
Timers: "false",
Type: "Light/Switch",
TypeImg: "contact",
Unit: 1,
Used: 1,
UsedByCamera: false,
XOffset: "879",
YOffset: "560",
idx: "92"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 79,
CustomImage: 0,
Data: "Closed",
Description: "",
DimmerType: "none",
Favorite: 0,
HardwareID: 2,
HardwareName: "Passerelle Xiaomi",
HardwareType: "Xiaomi Gateway",
HardwareTypeVal: 95,
HaveDimmer: true,
HaveGroupCmd: true,
HaveTimeout: false,
ID: "02436860",
Image: "Light",
IsSubDevice: false,
LastUpdate: "2018-12-17 06:11:17",
Level: 0,
LevelInt: 0,
MaxDimLevel: 100,
Name: "Fenêtre Chambre Parents",
Notifications: "false",
PlanID: "8",
PlanIDs: [
8
],
Protected: false,
ShowNotifications: true,
SignalLevel: "-",
Status: "Closed",
StrParam1: "",
StrParam2: "",
SubType: "Switch",
SwitchType: "Contact",
SwitchTypeVal: 2,
Timers: "false",
Type: "Light/Switch",
TypeImg: "contact",
Unit: 1,
Used: 1,
UsedByCamera: false,
XOffset: "163",
YOffset: "1513",
idx: "144"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 78,
CustomImage: 0,
Data: "Closed",
Description: "",
DimmerType: "none",
Favorite: 0,
HardwareID: 2,
HardwareName: "Passerelle Xiaomi",
HardwareType: "Xiaomi Gateway",
HardwareTypeVal: 95,
HaveDimmer: true,
HaveGroupCmd: true,
HaveTimeout: false,
ID: "023865F1",
Image: "Light",
IsSubDevice: false,
LastUpdate: "2018-11-28 10:03:37",
Level: 0,
LevelInt: 0,
MaxDimLevel: 100,
Name: "Fenêtre Bureau",
Notifications: "false",
PlanID: "11",
PlanIDs: [
11
],
Protected: false,
ShowNotifications: true,
SignalLevel: "-",
Status: "Closed",
StrParam1: "",
StrParam2: "",
SubType: "Switch",
SwitchType: "Contact",
SwitchTypeVal: 2,
Timers: "false",
Type: "Light/Switch",
TypeImg: "contact",
Unit: 1,
Used: 1,
UsedByCamera: false,
XOffset: "2265",
YOffset: "1499",
idx: "143"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 81,
CustomImage: 0,
Data: "Closed",
Description: "",
DimmerType: "none",
Favorite: 0,
HardwareID: 2,
HardwareName: "Passerelle Xiaomi",
HardwareType: "Xiaomi Gateway",
HardwareTypeVal: 95,
HaveDimmer: true,
HaveGroupCmd: true,
HaveTimeout: false,
ID: "022DA6DE",
Image: "Light",
IsSubDevice: false,
LastUpdate: "2018-12-17 06:15:10",
Level: 0,
LevelInt: 0,
MaxDimLevel: 100,
Name: "Fenêtre Chambre Lison",
Notifications: "false",
PlanID: "9",
PlanIDs: [
9
],
Protected: false,
ShowNotifications: true,
SignalLevel: "-",
Status: "Closed",
StrParam1: "",
StrParam2: "",
SubType: "Switch",
SwitchType: "Contact",
SwitchTypeVal: 2,
Timers: "false",
Type: "Light/Switch",
TypeImg: "contact",
Unit: 1,
Used: 1,
UsedByCamera: false,
XOffset: "149",
YOffset: "490",
idx: "145"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 78,
CustomImage: 0,
Data: "Closed",
Description: "",
DimmerType: "none",
Favorite: 0,
HardwareID: 2,
HardwareName: "Passerelle Xiaomi",
HardwareType: "Xiaomi Gateway",
HardwareTypeVal: 95,
HaveDimmer: true,
HaveGroupCmd: true,
HaveTimeout: false,
ID: "02386391",
Image: "Light",
IsSubDevice: false,
LastUpdate: "2018-12-16 09:38:40",
Level: 0,
LevelInt: 0,
MaxDimLevel: 100,
Name: "Fenêtre Chambre Lola",
Notifications: "false",
PlanID: "10",
PlanIDs: [
10
],
Protected: false,
ShowNotifications: true,
SignalLevel: "-",
Status: "Closed",
StrParam1: "",
StrParam2: "",
SubType: "Switch",
SwitchType: "Contact",
SwitchTypeVal: 2,
Timers: "false",
Type: "Light/Switch",
TypeImg: "contact",
Unit: 1,
Used: 1,
UsedByCamera: false,
XOffset: "2259",
YOffset: "493",
idx: "146"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 255,
CustomImage: 0,
Data: "On",
Description: "",
DimmerType: "none",
Favorite: 1,
HardwareID: 5,
HardwareName: "virtuel",
HardwareType: "Dummy (Does nothing, use for virtual switches only)",
HardwareTypeVal: 15,
HaveDimmer: true,
HaveGroupCmd: true,
HaveTimeout: false,
ID: "000140CD",
Image: "Light",
InternalState: "On",
IsSubDevice: false,
LastUpdate: "2018-12-17 08:51:01",
Level: 0,
LevelInt: 0,
MaxDimLevel: 100,
Name: "Ouvrir tous les volets",
Notifications: "true",
PlanID: "6",
PlanIDs: [
6
],
Protected: false,
ShowNotifications: true,
SignalLevel: "-",
Status: "",
StrParam1: "",
StrParam2: "",
SubType: "Selector Switch",
SwitchType: "Push On Button",
SwitchTypeVal: 9,
Timers: "true",
Type: "Light/Switch",
TypeImg: "push",
Unit: 1,
Used: 1,
UsedByCamera: false,
XOffset: "1188",
YOffset: "256",
idx: "125"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 255,
CustomImage: 0,
Data: "On",
Description: "",
DimmerType: "none",
Favorite: 1,
HardwareID: 5,
HardwareName: "virtuel",
HardwareType: "Dummy (Does nothing, use for virtual switches only)",
HardwareTypeVal: 15,
HaveDimmer: true,
HaveGroupCmd: true,
HaveTimeout: false,
ID: "000140CE",
Image: "Light",
InternalState: "On",
IsSubDevice: false,
LastUpdate: "2018-12-17 16:48:01",
Level: 0,
LevelInt: 0,
MaxDimLevel: 100,
Name: "Fermeture tous les volets",
Notifications: "true",
PlanID: "6",
PlanIDs: [
6
],
Protected: false,
ShowNotifications: true,
SignalLevel: "-",
Status: "",
StrParam1: "",
StrParam2: "",
SubType: "Switch",
SwitchType: "Push On Button",
SwitchTypeVal: 9,
Timers: "true",
Type: "Light/Switch",
TypeImg: "push",
Unit: 1,
Used: 1,
UsedByCamera: false,
XOffset: "1190",
YOffset: "322",
idx: "126"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 255,
CustomImage: 0,
Data: "Off",
Description: "",
DimmerType: "none",
Favorite: 0,
HardwareID: 6,
HardwareName: "rflink 433",
HardwareType: "RFLink Gateway USB",
HardwareTypeVal: 46,
HaveDimmer: false,
HaveGroupCmd: false,
HaveTimeout: false,
ID: "00000945",
Image: "Light",
IsSubDevice: false,
LastUpdate: "2018-11-11 14:16:42",
Level: 0,
LevelInt: 0,
MaxDimLevel: 100,
Name: "télécommande 1",
Notifications: "false",
PlanID: "0",
PlanIDs: [
0
],
Protected: false,
ShowNotifications: true,
SignalLevel: "-",
Status: "Off",
StrParam1: "",
StrParam2: "",
SubType: "Powerfix",
SwitchType: "On/Off",
SwitchTypeVal: 0,
Timers: "false",
Type: "Light/Switch",
TypeImg: "lightbulb",
Unit: 0,
Used: 1,
UsedByCamera: false,
XOffset: "0",
YOffset: "0",
idx: "152"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 255,
CustomImage: 0,
Data: "Off",
Description: "",
DimmerType: "none",
Favorite: 0,
HardwareID: 6,
HardwareName: "rflink 433",
HardwareType: "RFLink Gateway USB",
HardwareTypeVal: 46,
HaveDimmer: false,
HaveGroupCmd: false,
HaveTimeout: false,
ID: "00000945",
Image: "Light",
IsSubDevice: false,
LastUpdate: "2018-11-11 14:16:48",
Level: 0,
LevelInt: 0,
MaxDimLevel: 100,
Name: "télécommande 2",
Notifications: "false",
PlanID: "0",
PlanIDs: [
0
],
Protected: false,
ShowNotifications: true,
SignalLevel: "-",
Status: "Off",
StrParam1: "",
StrParam2: "",
SubType: "Powerfix",
SwitchType: "On/Off",
SwitchTypeVal: 0,
Timers: "false",
Type: "Light/Switch",
TypeImg: "lightbulb",
Unit: 1,
Used: 1,
UsedByCamera: false,
XOffset: "0",
YOffset: "0",
idx: "153"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 255,
CustomImage: 0,
Data: "Off",
Description: "",
DimmerType: "none",
Favorite: 0,
HardwareID: 6,
HardwareName: "rflink 433",
HardwareType: "RFLink Gateway USB",
HardwareTypeVal: 46,
HaveDimmer: false,
HaveGroupCmd: false,
HaveTimeout: false,
ID: "00000945",
Image: "Light",
IsSubDevice: false,
LastUpdate: "2018-11-11 14:16:52",
Level: 0,
LevelInt: 0,
MaxDimLevel: 100,
Name: "télécommande 3",
Notifications: "false",
PlanID: "0",
PlanIDs: [
0
],
Protected: false,
ShowNotifications: true,
SignalLevel: "-",
Status: "Off",
StrParam1: "",
StrParam2: "",
SubType: "Powerfix",
SwitchType: "On/Off",
SwitchTypeVal: 0,
Timers: "false",
Type: "Light/Switch",
TypeImg: "lightbulb",
Unit: 3,
Used: 1,
UsedByCamera: false,
XOffset: "0",
YOffset: "0",
idx: "154"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 255,
CustomImage: 0,
Data: "On",
Description: "",
DimmerType: "none",
Favorite: 0,
HardwareID: 6,
HardwareName: "rflink 433",
HardwareType: "RFLink Gateway USB",
HardwareTypeVal: 46,
HaveDimmer: false,
HaveGroupCmd: false,
HaveTimeout: false,
ID: "00000945",
Image: "Light",
IsSubDevice: false,
LastUpdate: "2018-11-11 14:16:51",
Level: 0,
LevelInt: 0,
MaxDimLevel: 100,
Name: "télécommande 4",
Notifications: "false",
PlanID: "0",
PlanIDs: [
0
],
Protected: false,
ShowNotifications: true,
SignalLevel: "-",
Status: "On",
StrParam1: "",
StrParam2: "",
SubType: "Powerfix",
SwitchType: "On/Off",
SwitchTypeVal: 0,
Timers: "false",
Type: "Light/Switch",
TypeImg: "lightbulb",
Unit: 2,
Used: 1,
UsedByCamera: false,
XOffset: "0",
YOffset: "0",
idx: "155"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 255,
CustomImage: 0,
Data: "Normal",
Description: "",
Favorite: 0,
HardwareID: 1,
HardwareName: "Domoticz Internal",
HardwareType: "Domoticz Internal interface",
HardwareTypeVal: 67,
HaveDimmer: false,
HaveGroupCmd: false,
HaveTimeout: false,
ID: "148702",
LastUpdate: "2018-10-22 19:01:34",
MaxDimLevel: 0,
Name: "Domoticz Security Panel",
Notifications: "false",
PlanID: "0",
PlanIDs: [
0
],
Protected: false,
ShowNotifications: true,
SignalLevel: "-",
Status: "Normal",
StrParam1: "",
StrParam2: "",
SubType: "Security Panel",
SwitchType: "Security",
SwitchTypeVal: 0,
Timers: "false",
Type: "Security",
TypeImg: "security",
Unit: 0,
Used: 1,
XOffset: "0",
YOffset: "0",
idx: "158"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 255,
CustomImage: 0,
Data: "Closed",
Description: "",
DimmerType: "none",
Favorite: 1,
HardwareID: 7,
HardwareName: "zwave",
HardwareType: "OpenZWave USB",
HardwareTypeVal: 21,
HaveDimmer: true,
HaveGroupCmd: true,
HaveTimeout: false,
ID: "00000401",
Image: "Light",
IsSubDevice: false,
LastUpdate: "2018-12-17 16:48:31",
Level: 100,
LevelInt: 100,
MaxDimLevel: 100,
Name: "Volet Salle à manger Gauche",
Notifications: "false",
PlanID: "2",
PlanIDs: [
2
],
Protected: false,
ShowNotifications: true,
SignalLevel: "-",
Status: "Closed",
StrParam1: "",
StrParam2: "",
SubType: "Switch",
SwitchType: "Blinds Percentage",
SwitchTypeVal: 13,
Timers: "false",
Type: "Light/Switch",
TypeImg: "blinds",
Unit: 1,
Used: 1,
UsedByCamera: false,
XOffset: "721",
YOffset: "570",
idx: "188"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 255,
CustomImage: 0,
Data: "Closed",
Description: "",
DimmerType: "none",
Favorite: 1,
HardwareID: 7,
HardwareName: "zwave",
HardwareType: "OpenZWave USB",
HardwareTypeVal: 21,
HaveDimmer: true,
HaveGroupCmd: true,
HaveTimeout: false,
ID: "00000501",
Image: "Light",
IsSubDevice: false,
LastUpdate: "2018-12-17 16:48:30",
Level: 100,
LevelInt: 100,
MaxDimLevel: 100,
Name: "Volet Salle à manger Droite",
Notifications: "false",
PlanID: "2",
PlanIDs: [
2
],
Protected: false,
ShowNotifications: true,
SignalLevel: "-",
Status: "Closed",
StrParam1: "",
StrParam2: "",
SubType: "Switch",
SwitchType: "Blinds Percentage",
SwitchTypeVal: 13,
Timers: "false",
Type: "Light/Switch",
TypeImg: "blinds",
Unit: 1,
Used: 1,
UsedByCamera: false,
XOffset: "54",
YOffset: "278",
idx: "189"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 255,
CustomImage: 0,
Data: "0.7 Watt",
Description: "",
Favorite: 0,
HardwareID: 7,
HardwareName: "zwave",
HardwareType: "OpenZWave USB",
HardwareTypeVal: 21,
HaveTimeout: false,
ID: "0000404",
LastUpdate: "2018-12-17 22:48:30",
Name: "Volet Salle à manger Gauche",
Notifications: "false",
PlanID: "0",
PlanIDs: [
0
],
Protected: false,
ShowNotifications: true,
SignalLevel: "-",
SubType: "Electric",
Timers: "false",
Type: "Usage",
TypeImg: "current",
Unit: 2,
Used: 1,
XOffset: "0",
YOffset: "0",
idx: "193"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 255,
CounterToday: "0 kWh",
CustomImage: 0,
Data: "0.3 kWh",
Description: "",
Favorite: 0,
HardwareID: 7,
HardwareName: "zwave",
HardwareType: "OpenZWave USB",
HardwareTypeVal: 21,
HaveTimeout: false,
ID: "00000401",
LastUpdate: "2018-12-17 22:48:30",
Name: "Volet Salle à manger Gauche",
Notifications: "false",
Options: "",
PlanID: "0",
PlanIDs: [
0
],
Protected: false,
ShowNotifications: true,
SignalLevel: "-",
SubType: "kWh",
SwitchTypeVal: 0,
Timers: "false",
Type: "General",
TypeImg: "current",
Unit: 1,
Usage: "0.7 Watt",
Used: 1,
XOffset: "0",
YOffset: "0",
idx: "194"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 255,
CustomImage: 0,
Data: "0 Watt",
Description: "",
Favorite: 0,
HardwareID: 7,
HardwareName: "zwave",
HardwareType: "OpenZWave USB",
HardwareTypeVal: 21,
HaveTimeout: true,
ID: "0000401",
LastUpdate: "2018-12-17 08:51:01",
Name: "Volet Salle à manger Gauche",
Notifications: "false",
PlanID: "0",
PlanIDs: [
0
],
Protected: false,
ShowNotifications: true,
SignalLevel: "-",
SubType: "Electric",
Timers: "false",
Type: "Usage",
TypeImg: "current",
Unit: 2,
Used: 1,
XOffset: "0",
YOffset: "0",
idx: "195"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 255,
CustomImage: 0,
Data: "0 Watt",
Description: "",
Favorite: 0,
HardwareID: 7,
HardwareName: "zwave",
HardwareType: "OpenZWave USB",
HardwareTypeVal: 21,
HaveTimeout: false,
ID: "0000504",
LastUpdate: "2018-12-17 22:48:29",
Name: "Volet Salle à manger Droite",
Notifications: "false",
PlanID: "0",
PlanIDs: [
0
],
Protected: false,
ShowNotifications: true,
SignalLevel: "-",
SubType: "Electric",
Timers: "false",
Type: "Usage",
TypeImg: "current",
Unit: 2,
Used: 1,
XOffset: "0",
YOffset: "0",
idx: "196"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 255,
CounterToday: "0 kWh",
CustomImage: 0,
Data: "0.29 kWh",
Description: "",
Favorite: 0,
HardwareID: 7,
HardwareName: "zwave",
HardwareType: "OpenZWave USB",
HardwareTypeVal: 21,
HaveTimeout: false,
ID: "00000501",
LastUpdate: "2018-12-17 22:48:29",
Name: "Volet Salle à manger Droite",
Notifications: "false",
Options: "",
PlanID: "0",
PlanIDs: [
0
],
Protected: false,
ShowNotifications: true,
SignalLevel: "-",
SubType: "kWh",
SwitchTypeVal: 0,
Timers: "false",
Type: "General",
TypeImg: "current",
Unit: 1,
Usage: "0 Watt",
Used: 1,
XOffset: "0",
YOffset: "0",
idx: "197"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 255,
CustomImage: 0,
Data: "0 Watt",
Description: "",
Favorite: 0,
HardwareID: 7,
HardwareName: "zwave",
HardwareType: "OpenZWave USB",
HardwareTypeVal: 21,
HaveTimeout: true,
ID: "0000501",
LastUpdate: "2018-12-17 08:51:01",
Name: "Volet Salle à manger Droite",
Notifications: "false",
PlanID: "0",
PlanIDs: [
0
],
Protected: false,
ShowNotifications: true,
SignalLevel: "-",
SubType: "Electric",
Timers: "false",
Type: "Usage",
TypeImg: "current",
Unit: 2,
Used: 1,
XOffset: "0",
YOffset: "0",
idx: "198"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 255,
CustomImage: 0,
Data: "0 Watt",
Description: "",
Favorite: 0,
HardwareID: 7,
HardwareName: "zwave",
HardwareType: "OpenZWave USB",
HardwareTypeVal: 21,
HaveTimeout: false,
ID: "0000604",
LastUpdate: "2018-12-17 22:48:22",
Name: "Volet Salle à manger Millieu",
Notifications: "false",
PlanID: "0",
PlanIDs: [
0
],
Protected: false,
ShowNotifications: true,
SignalLevel: "-",
SubType: "Electric",
Timers: "false",
Type: "Usage",
TypeImg: "current",
Unit: 2,
Used: 1,
XOffset: "0",
YOffset: "0",
idx: "199"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 255,
CounterToday: "0 kWh",
CustomImage: 0,
Data: "0.17 kWh",
Description: "",
Favorite: 0,
HardwareID: 7,
HardwareName: "zwave",
HardwareType: "OpenZWave USB",
HardwareTypeVal: 21,
HaveTimeout: false,
ID: "00000601",
LastUpdate: "2018-12-17 22:48:22",
Name: "Volet Salle à manger Millieu",
Notifications: "false",
Options: "",
PlanID: "0",
PlanIDs: [
0
],
Protected: false,
ShowNotifications: true,
SignalLevel: "-",
SubType: "kWh",
SwitchTypeVal: 0,
Timers: "false",
Type: "General",
TypeImg: "current",
Unit: 1,
Usage: "0 Watt",
Used: 1,
XOffset: "0",
YOffset: "0",
idx: "200"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 255,
CustomImage: 0,
Data: "Closed",
Description: "",
DimmerType: "none",
Favorite: 1,
HardwareID: 7,
HardwareName: "zwave",
HardwareType: "OpenZWave USB",
HardwareTypeVal: 21,
HaveDimmer: true,
HaveGroupCmd: true,
HaveTimeout: false,
ID: "00000601",
Image: "Light",
IsSubDevice: false,
LastUpdate: "2018-12-17 16:48:23",
Level: 100,
LevelInt: 100,
MaxDimLevel: 100,
Name: "\tVolet Salle à manger Millieu",
Notifications: "false",
PlanID: "2",
PlanIDs: [
2
],
Protected: false,
ShowNotifications: true,
SignalLevel: "-",
Status: "Closed",
StrParam1: "",
StrParam2: "",
SubType: "Switch",
SwitchType: "Blinds Percentage",
SwitchTypeVal: 13,
Timers: "false",
Type: "Light/Switch",
TypeImg: "blinds",
Unit: 1,
Used: 1,
UsedByCamera: false,
XOffset: "247",
YOffset: "568",
idx: "201"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 255,
CustomImage: 0,
Data: "Closed",
Description: "",
DimmerType: "none",
Favorite: 1,
HardwareID: 7,
HardwareName: "zwave",
HardwareType: "OpenZWave USB",
HardwareTypeVal: 21,
HaveDimmer: true,
HaveGroupCmd: true,
HaveTimeout: false,
ID: "00000701",
Image: "Light",
IsSubDevice: false,
LastUpdate: "2018-12-17 16:48:32",
Level: 100,
LevelInt: 100,
MaxDimLevel: 100,
Name: "Volet Salle de bain",
Notifications: "false",
PlanID: "5",
PlanIDs: [
5
],
Protected: false,
ShowNotifications: true,
SignalLevel: "-",
Status: "Closed",
StrParam1: "",
StrParam2: "",
SubType: "Switch",
SwitchType: "Blinds Percentage",
SwitchTypeVal: 13,
Timers: "false",
Type: "Light/Switch",
TypeImg: "blinds",
Unit: 1,
Used: 1,
UsedByCamera: false,
XOffset: "1121",
YOffset: "919",
idx: "202"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 255,
CustomImage: 0,
Data: "Closed",
Description: "",
DimmerType: "none",
Favorite: 1,
HardwareID: 7,
HardwareName: "zwave",
HardwareType: "OpenZWave USB",
HardwareTypeVal: 21,
HaveDimmer: true,
HaveGroupCmd: true,
HaveTimeout: false,
ID: "00000801",
Image: "Light",
IsSubDevice: false,
LastUpdate: "2018-12-17 23:01:25",
Level: 100,
LevelInt: 100,
MaxDimLevel: 100,
Name: "Volet Salon",
Notifications: "false",
PlanID: "3",
PlanIDs: [
3
],
Protected: false,
ShowNotifications: true,
SignalLevel: "-",
Status: "Closed",
StrParam1: "",
StrParam2: "",
SubType: "Switch",
SwitchType: "Blinds Percentage",
SwitchTypeVal: 13,
Timers: "false",
Type: "Light/Switch",
TypeImg: "blinds",
Unit: 1,
Used: 1,
UsedByCamera: false,
XOffset: "0",
YOffset: "0",
idx: "203"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 255,
CustomImage: 0,
Data: "0 Watt",
Description: "",
Favorite: 0,
HardwareID: 7,
HardwareName: "zwave",
HardwareType: "OpenZWave USB",
HardwareTypeVal: 21,
HaveTimeout: true,
ID: "0000601",
LastUpdate: "2018-12-17 08:51:02",
Name: "Volet Salle à manger Millieu",
Notifications: "false",
PlanID: "0",
PlanIDs: [
0
],
Protected: false,
ShowNotifications: true,
SignalLevel: "-",
SubType: "Electric",
Timers: "false",
Type: "Usage",
TypeImg: "current",
Unit: 2,
Used: 1,
XOffset: "0",
YOffset: "0",
idx: "204"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 255,
CustomImage: 0,
Data: "0 Watt",
Description: "",
Favorite: 0,
HardwareID: 7,
HardwareName: "zwave",
HardwareType: "OpenZWave USB",
HardwareTypeVal: 21,
HaveTimeout: false,
ID: "0000704",
LastUpdate: "2018-12-17 22:48:30",
Name: "Volet Salle de bain",
Notifications: "false",
PlanID: "0",
PlanIDs: [
0
],
Protected: false,
ShowNotifications: true,
SignalLevel: "-",
SubType: "Electric",
Timers: "false",
Type: "Usage",
TypeImg: "current",
Unit: 2,
Used: 1,
XOffset: "0",
YOffset: "0",
idx: "205"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 255,
CounterToday: "0 kWh",
CustomImage: 0,
Data: "0.39 kWh",
Description: "",
Favorite: 0,
HardwareID: 7,
HardwareName: "zwave",
HardwareType: "OpenZWave USB",
HardwareTypeVal: 21,
HaveTimeout: false,
ID: "00000701",
LastUpdate: "2018-12-17 22:48:30",
Name: "Volet Salle de bain",
Notifications: "false",
Options: "",
PlanID: "0",
PlanIDs: [
0
],
Protected: false,
ShowNotifications: true,
SignalLevel: "-",
SubType: "kWh",
SwitchTypeVal: 0,
Timers: "false",
Type: "General",
TypeImg: "current",
Unit: 1,
Usage: "0 Watt",
Used: 1,
XOffset: "0",
YOffset: "0",
idx: "206"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 255,
CustomImage: 0,
Data: "0 Watt",
Description: "",
Favorite: 0,
HardwareID: 7,
HardwareName: "zwave",
HardwareType: "OpenZWave USB",
HardwareTypeVal: 21,
HaveTimeout: true,
ID: "0000701",
LastUpdate: "2018-12-17 08:51:01",
Name: "Volet Salle de bain",
Notifications: "false",
PlanID: "0",
PlanIDs: [
0
],
Protected: false,
ShowNotifications: true,
SignalLevel: "-",
SubType: "Electric",
Timers: "false",
Type: "Usage",
TypeImg: "current",
Unit: 2,
Used: 1,
XOffset: "0",
YOffset: "0",
idx: "207"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 255,
CustomImage: 0,
Data: "0.7 Watt",
Description: "",
Favorite: 0,
HardwareID: 7,
HardwareName: "zwave",
HardwareType: "OpenZWave USB",
HardwareTypeVal: 21,
HaveTimeout: false,
ID: "0000804",
LastUpdate: "2018-12-17 23:01:27",
Name: "Volet Salon",
Notifications: "false",
PlanID: "0",
PlanIDs: [
0
],
Protected: false,
ShowNotifications: true,
SignalLevel: "-",
SubType: "Electric",
Timers: "false",
Type: "Usage",
TypeImg: "current",
Unit: 2,
Used: 1,
XOffset: "0",
YOffset: "0",
idx: "208"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 255,
CounterToday: "0 kWh",
CustomImage: 0,
Data: "0.28 kWh",
Description: "",
Favorite: 0,
HardwareID: 7,
HardwareName: "zwave",
HardwareType: "OpenZWave USB",
HardwareTypeVal: 21,
HaveTimeout: false,
ID: "00000801",
LastUpdate: "2018-12-17 23:01:27",
Name: "Volet Salon",
Notifications: "false",
Options: "",
PlanID: "0",
PlanIDs: [
0
],
Protected: false,
ShowNotifications: true,
SignalLevel: "-",
SubType: "kWh",
SwitchTypeVal: 0,
Timers: "false",
Type: "General",
TypeImg: "current",
Unit: 1,
Usage: "0.7 Watt",
Used: 1,
XOffset: "0",
YOffset: "0",
idx: "209"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 255,
CustomImage: 0,
Data: "0 Watt",
Description: "",
Favorite: 0,
HardwareID: 7,
HardwareName: "zwave",
HardwareType: "OpenZWave USB",
HardwareTypeVal: 21,
HaveTimeout: true,
ID: "0000801",
LastUpdate: "2018-12-17 08:51:02",
Name: "Volet Salon",
Notifications: "false",
PlanID: "0",
PlanIDs: [
0
],
Protected: false,
ShowNotifications: true,
SignalLevel: "-",
SubType: "Electric",
Timers: "false",
Type: "Usage",
TypeImg: "current",
Unit: 2,
Used: 1,
XOffset: "0",
YOffset: "0",
idx: "210"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 255,
CustomImage: 0,
Data: "0.7 Watt",
Description: "",
Favorite: 0,
HardwareID: 7,
HardwareName: "zwave",
HardwareType: "OpenZWave USB",
HardwareTypeVal: 21,
HaveTimeout: true,
ID: "0000008",
LastUpdate: "2018-10-21 10:30:49",
Name: "Volet Salon",
Notifications: "false",
PlanID: "0",
PlanIDs: [
0
],
Protected: false,
ShowNotifications: true,
SignalLevel: "-",
SubType: "Electric",
Timers: "false",
Type: "Usage",
TypeImg: "current",
Unit: 4,
Used: 1,
XOffset: "0",
YOffset: "0",
idx: "220"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
Barometer: 1021,
BatteryLevel: 255,
CustomImage: 0,
Data: "6.7 C, 94 %, 1021 hPa",
Description: "",
DewPoint: "5.80",
Favorite: 0,
Forecast: 2,
ForecastStr: "Partly Cloudy",
HardwareID: 8,
HardwareName: "meteo",
HardwareType: "DarkSky (Weather Lookup)",
HardwareTypeVal: 25,
HaveTimeout: false,
Humidity: 94,
HumidityStatus: "Wet",
ID: "0001",
LastUpdate: "2018-12-17 23:02:58",
Name: "Barométre",
Notifications: "false",
PlanID: "0",
PlanIDs: [
0
],
Protected: false,
ShowNotifications: true,
SignalLevel: "-",
SubType: "THB1 - BTHR918, BTHGN129",
Temp: 6.7,
Timers: "false",
Type: "Temp + Humidity + Baro",
TypeImg: "temperature",
Unit: 1,
Used: 1,
XOffset: "0",
YOffset: "0",
forecast_url: "aHR0cHM6Ly9kYXJrc2t5Lm5ldC8jL2YvNTAuOTQ0OTc1JTJDMS44MjAzMTMz",
idx: "221"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 255,
Chill: 4.4,
CustomImage: 0,
Data: "164.00;SSE;32;113;6.7;4.4",
Description: "",
Direction: 164,
DirectionStr: "SSE",
Favorite: 1,
Gust: "11.3",
HardwareID: 8,
HardwareName: "meteo",
HardwareType: "DarkSky (Weather Lookup)",
HardwareTypeVal: 25,
HaveTimeout: false,
ID: "0001",
LastUpdate: "2018-12-17 23:02:58",
Name: "Metéo",
Notifications: "false",
PlanID: "0",
PlanIDs: [
0
],
Protected: false,
ShowNotifications: true,
SignalLevel: "-",
Speed: "3.2",
SubType: "TFA",
Temp: 6.7,
Timers: "false",
Type: "Wind",
TypeImg: "wind",
Unit: 0,
Used: 1,
XOffset: "0",
YOffset: "0",
forecast_url: "aHR0cHM6Ly9kYXJrc2t5Lm5ldC8jL2YvNTAuOTQ0OTc1JTJDMS44MjAzMTMz",
idx: "222"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 255,
CustomImage: 0,
Data: "0.0 UVI",
Description: "",
Favorite: 0,
HardwareID: 8,
HardwareName: "meteo",
HardwareType: "DarkSky (Weather Lookup)",
HardwareTypeVal: 25,
HaveTimeout: false,
ID: "0001",
LastUpdate: "2018-12-17 23:02:58",
Name: "Indice d'UV",
Notifications: "false",
PlanID: "0",
PlanIDs: [
0
],
Protected: false,
ShowNotifications: true,
SignalLevel: "-",
SubType: "UVN128,UV138",
Timers: "false",
Type: "UV",
TypeImg: "uv",
UVI: "0.0",
Unit: 0,
Used: 1,
XOffset: "0",
YOffset: "0",
forecast_url: "aHR0cHM6Ly9kYXJrc2t5Lm5ldC8jL2YvNTAuOTQ0OTc1JTJDMS44MjAzMTMz",
idx: "223"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 255,
CustomImage: 0,
Data: "0;0.0",
Description: "",
Favorite: 0,
HardwareID: 8,
HardwareName: "meteo",
HardwareType: "DarkSky (Weather Lookup)",
HardwareTypeVal: 25,
HaveTimeout: false,
ID: "0001",
LastUpdate: "2018-12-17 23:02:58",
Name: "Pluie",
Notifications: "false",
PlanID: "0",
PlanIDs: [
0
],
Protected: false,
Rain: "0",
RainRate: "0",
ShowNotifications: true,
SignalLevel: "-",
SubType: "WWW",
Timers: "false",
Type: "Rain",
TypeImg: "rain",
Unit: 0,
Used: 1,
XOffset: "0",
YOffset: "0",
forecast_url: "aHR0cHM6Ly9kYXJrc2t5Lm5ldC8jL2YvNTAuOTQ0OTc1JTJDMS44MjAzMTMz",
idx: "224"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 255,
CustomImage: 0,
Data: "12.8 km",
Description: "",
Favorite: 0,
HardwareID: 8,
HardwareName: "meteo",
HardwareType: "DarkSky (Weather Lookup)",
HardwareTypeVal: 25,
HaveTimeout: false,
ID: "0",
LastUpdate: "2018-12-17 23:02:58",
Name: "Visibilité",
Notifications: "false",
PlanID: "0",
PlanIDs: [
0
],
Protected: false,
ShowNotifications: true,
SignalLevel: "-",
SubType: "Visibility",
SwitchTypeVal: 0,
Timers: "false",
Type: "General",
TypeImg: "visibility",
Unit: 1,
Used: 1,
Visibility: 12.8,
XOffset: "0",
YOffset: "0",
forecast_url: "aHR0cHM6Ly9kYXJrc2t5Lm5ldC8jL2YvNTAuOTQ0OTc1JTJDMS44MjAzMTMz",
idx: "225"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 255,
CustomImage: 0,
Data: "290.08 DU",
Description: "",
Favorite: 0,
HardwareID: 8,
HardwareName: "meteo",
HardwareType: "DarkSky (Weather Lookup)",
HardwareTypeVal: 25,
HaveTimeout: false,
ID: "00000100",
Image: "Custom",
LastUpdate: "2018-12-17 23:02:58",
Name: "Ozone Sensor",
Notifications: "false",
PlanID: "0",
PlanIDs: [
0
],
Protected: false,
SensorType: 1,
SensorUnit: "DU",
ShowNotifications: true,
SignalLevel: "-",
SubType: "Custom Sensor",
Timers: "false",
Type: "General",
TypeImg: "Custom",
Unit: 1,
Used: 1,
XOffset: "0",
YOffset: "0",
forecast_url: "aHR0cHM6Ly9kYXJrc2t5Lm5ldC8jL2YvNTAuOTQ0OTc1JTJDMS44MjAzMTMz",
idx: "226"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 255,
CustomImage: 0,
Data: "On",
Description: "",
DimmerType: "none",
Favorite: 0,
HardwareID: 7,
HardwareName: "zwave",
HardwareType: "OpenZWave USB",
HardwareTypeVal: 21,
HaveDimmer: true,
HaveGroupCmd: true,
HaveTimeout: false,
ID: "00170700",
Image: "Light",
IsSubDevice: false,
LastUpdate: "2018-10-29 09:23:35",
Level: 255,
LevelInt: 255,
MaxDimLevel: 100,
Name: "Volet Salle de bain",
Notifications: "false",
PlanID: "0",
PlanIDs: [
0
],
Protected: false,
ShowNotifications: true,
SignalLevel: "-",
Status: "On",
StrParam1: "",
StrParam2: "",
SubType: "Switch",
SwitchType: "On/Off",
SwitchTypeVal: 0,
Timers: "false",
Type: "Light/Switch",
TypeImg: "lightbulb",
Unit: 1,
Used: 1,
UsedByCamera: false,
XOffset: "0",
YOffset: "0",
idx: "234"
},
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 255,
CustomImage: 0,
Data: "4.6 C, 97 %",
Description: "",
DewPoint: "4.16",
Favorite: 0,
HardwareID: 6,
HardwareName: "rflink 433",
HardwareType: "RFLink Gateway USB",
HardwareTypeVal: 46,
HaveTimeout: true,
Humidity: 97,
HumidityStatus: "Wet",
ID: "FA01",
LastUpdate: "2018-12-16 19:26:40",
Name: "Auriol V3",
Notifications: "false",
PlanID: "0",
PlanIDs: [
0
],
Protected: false,
ShowNotifications: true,
SignalLevel: "-",
SubType: "WTGR800",
Temp: 4.6,
Timers: "false",
Type: "Temp + Humidity",
TypeImg: "temperature",
Unit: 0,
Used: 1,
XOffset: "0",
YOffset: "0",
idx: "269"
}
],
status: "OK",
title: "Devices"
});