exports.DOMOTICZ_GET_DEVICES = JSON.stringify(
{
   "ActTime" : 1539762187,
   "AstrTwilightEnd" : "20:59",
   "AstrTwilightStart" : "06:47",
   "CivTwilightEnd" : "19:48",
   "CivTwilightStart" : "07:58",
   "DayLength" : "10:48",
   "NautTwilightEnd" : "20:23",
   "NautTwilightStart" : "07:22",
   "ServerTime" : "2018-10-17 09:43:07",
   "SunAtSouth" : "13:05",
   "Sunrise" : "08:29",
   "Sunset" : "19:17",
   "app_version" : "4.9796",
   "result" : [
      {
         "AddjMulti":   1,
         "AddjMulti2":  1,
         "AddjValue":   0,
         "AddjValue2":  0,
         "BatteryLevel":   255,
         "CustomImage": 2,
         "Data":  "Off",
         "Description": "",
         "DimmerType":  "none",
         "Favorite": 1,
         "HardwareID":  10,
         "HardwareName":   "temp / Hub  + harmony",
         "HardwareType":   "temp Harmony Hub",
         "HardwareTypeVal":   36,
         "HaveDimmer":  true,
         "HaveGroupCmd":   true,
         "HaveTimeout": false,
         "ID": "1CDDD6E",
         "Image ":"TV",
         "IsSubDevice": false,
         "LastUpdate":  "2018-10-14 19:40:21",
         "Level": 0,
         "LevelInt": 0,
         "MaxDimLevel": 15,
         "Name ": "Regarder la TV",
         "Notifications":  "false",
         "PlanID" : "4",
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" :   "Off",
         "StrParam1" :   "",
         "StrParam2" :   "",
         "SubType" :  "AC",
         "SwitchType" :  "On/Off",
         "SwitchTypeVal" :  0,
         "Timers" :   "false",
         "Type" :  "Temp + Humidity",
         "Name" : 'robot.mi naomi/27+',
         "TypeImg" :  "lightbulb",
         "Unit" :  1,
         "Used" :  1,
         "UsedByCamera" :   false,
         "XOffset" :  "237",
         "YOffset" :  "185",
         "idx" : 155
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "Open",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 1,
         "HardwareID" : 3,
         "HardwareName" : "zwave",
         "HardwareType" : "OpenZWave USB",
         "HardwareTypeVal" : 21,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "00001201",
         "Image" : "Light",
         "IsSubDevice" : false,
         "LastUpdate" : "2018-10-17 09:00:40",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 100,
         "Name" : "volet_salon",
         "Notifications" : "false",
         "PlanID" : "2",
         "PlanIDs" : [ 2 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Open",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Switch",
         "SwitchType" : "Blinds Percentage",
         "SwitchTypeVal" : 13,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "blinds",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "312",
         "YOffset" : "377",
         "idx" : "146"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "Open",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 1,
         "HardwareID" : 3,
         "HardwareName" : "zwave",
         "HardwareType" : "OpenZWave USB",
         "HardwareTypeVal" : 21,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "00000301",
         "Image" : "Light",
         "IsSubDevice" : false,
         "LastUpdate" : "2018-10-17 09:00:28",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 100,
         "Name" : "volet_Gbaie",
         "Notifications" : "false",
         "PlanID" : "2",
         "PlanIDs" : [ 2 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Open",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Switch",
         "SwitchType" : "Blinds Percentage",
         "SwitchTypeVal" : 13,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "blinds",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "195",
         "YOffset" : "89",
         "idx" : "18"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "Open",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 1,
         "HardwareID" : 3,
         "HardwareName" : "zwave",
         "HardwareType" : "OpenZWave USB",
         "HardwareTypeVal" : 21,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "00001401",
         "Image" : "Light",
         "IsSubDevice" : false,
         "LastUpdate" : "2018-10-17 09:00:26",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 100,
         "Name" : "volet_Pbaie",
         "Notifications" : "false",
         "PlanID" : "2",
         "PlanIDs" : [ 2 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Open",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Switch",
         "SwitchType" : "Blinds Percentage",
         "SwitchTypeVal" : 13,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "blinds",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "327",
         "YOffset" : "73",
         "idx" : "151"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "Open",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 1,
         "HardwareID" : 3,
         "HardwareName" : "zwave",
         "HardwareType" : "OpenZWave USB",
         "HardwareTypeVal" : 21,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "00001501",
         "Image" : "Light",
         "IsSubDevice" : false,
         "LastUpdate" : "2018-10-17 09:01:01",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 100,
         "Name" : "volet_couloir",
         "Notifications" : "false",
         "PlanID" : "2",
         "PlanIDs" : [ 2 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Open",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Switch",
         "SwitchType" : "Blinds Percentage",
         "SwitchTypeVal" : 13,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "blinds",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "422",
         "YOffset" : "118",
         "idx" : "159"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "Open",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 1,
         "HardwareID" : 3,
         "HardwareName" : "zwave",
         "HardwareType" : "OpenZWave USB",
         "HardwareTypeVal" : 21,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "00001601",
         "Image" : "Light",
         "IsSubDevice" : false,
         "LastUpdate" : "2018-10-17 09:00:51",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 100,
         "Name" : "volet_cellier",
         "Notifications" : "false",
         "PlanID" : "2",
         "PlanIDs" : [ 2 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Open",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Switch",
         "SwitchType" : "Blinds Percentage",
         "SwitchTypeVal" : 13,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "blinds",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "147",
         "YOffset" : "423",
         "idx" : "164"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 101,
         "Data" : "Off",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 1,
         "HardwareID" : 7,
         "HardwareName" : "mi.robot",
         "HardwareType" : "Xiaomi Mi Robot Vacuum",
         "HardwareTypeVal" : 94,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "00070002",
         "Image" : "xiaomi-mi-robot-vacuum-icon",
         "IsSubDevice" : false,
         "LastUpdate" : "2018-02-06 18:18:46",
         "Level" : 0,
         "LevelActions" : "fHx8fHx8",
         "LevelInt" : 0,
         "LevelNames" : "T2ZmfENsZWFufEhvbWV8U3BvdHxQYXVzZXxTdG9wfEZpbmQ=",
         "LevelOffHidden" : true,
         "MaxDimLevel" : 100,
         "Name" : "mi.robot - Control",
         "Notifications" : "false",
         "PlanID" : "2",
         "PlanIDs" : [ 2 ],
         "Protected" : false,
         "SelectorStyle" : 0,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Selector Switch",
         "SwitchType" : "Selector",
         "SwitchTypeVal" : 18,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "Light",
         "Unit" : 2,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "170"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "20.1 C",
         "Description" : "",
         "Favorite" : 1,
         "HardwareID" : 3,
         "HardwareName" : "zwave",
         "HardwareType" : "OpenZWave USB",
         "HardwareTypeVal" : 21,
         "HaveTimeout" : false,
         "ID" : "1C01",
         "LastUpdate" : "2018-10-17 09:42:59",
         "Name" : "TemperatureSejour",
         "Notifications" : "false",
         "PlanID" : "2",
         "PlanIDs" : [ 2 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "LaCrosse TX3",
         "Temp" : 20.100000000000001,
         "Timers" : "false",
         "Type" : "Temp",
         "TypeImg" : "temperature",
         "Unit" : 1,
         "Used" : 1,
         "XOffset" : "220",
         "YOffset" : "222",
         "idx" : "206"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "18.1 C",
         "Description" : "",
         "Favorite" : 1,
         "HardwareID" : 3,
         "HardwareName" : "zwave",
         "HardwareType" : "OpenZWave USB",
         "HardwareTypeVal" : 21,
         "HaveTimeout" : false,
         "ID" : "1A01",
         "LastUpdate" : "2018-10-17 09:33:32",
         "Name" : "TemperatureNuit",
         "Notifications" : "false",
         "PlanID" : "2",
         "PlanIDs" : [ 2 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "LaCrosse TX3",
         "Temp" : 18.100000000000001,
         "Timers" : "false",
         "Type" : "Temp",
         "TypeImg" : "temperature",
         "Unit" : 1,
         "Used" : 1,
         "XOffset" : "571",
         "YOffset" : "321",
         "idx" : "200"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.69999999999999996,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "19.6 C",
         "Description" : "",
         "Favorite" : 1,
         "HardwareID" : 2,
         "HardwareName" : "dummy dev",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveTimeout" : true,
         "ID" : "14121",
         "LastUpdate" : "2018-10-16 16:17:49",
         "Name" : "Temperature Piscine",
         "Notifications" : "false",
         "PlanID" : "2",
         "PlanIDs" : [ 2 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "LaCrosse TX3",
         "Temp" : 19.600000000000001,
         "Timers" : "false",
         "Type" : "Temp",
         "TypeImg" : "temperature",
         "Unit" : 1,
         "Used" : 1,
         "XOffset" : "587",
         "YOffset" : "17",
         "idx" : "209"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 100,
         "CustomImage" : 0,
         "Data" : "7.5 C",
         "Description" : "",
         "Favorite" : 1,
         "HardwareID" : 9,
         "HardwareName" : "RF player",
         "HardwareType" : "RFplayer",
         "HardwareTypeVal" : 94,
         "HaveTimeout" : false,
         "ID" : "00090001",
         "LastUpdate" : "2018-10-17 09:35:49",
         "Name" : "temperature exterieur",
         "Notifications" : "false",
         "PlanID" : "2",
         "PlanIDs" : [ 2 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : 2,
         "SubType" : "Unknown",
         "Temp" : 7.5,
         "Timers" : "false",
         "Type" : "Temp",
         "TypeImg" : "temperature",
         "Unit" : 1,
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "256"
      }
   ],
   "status" : "OK",
   "title" : "Devices"
});
