exports.DOMOTICZ_GET_DEVICES = JSON.stringify({
	ActTime: 1577716544,
	AstrTwilightEnd: "18:53",
	AstrTwilightStart: "06:34",
	CivTwilightEnd: "17:38",
	CivTwilightStart: "07:48",
	DayLength: "08:41",
	NautTwilightEnd: "18:16",
	NautTwilightStart: "07:10",
	ServerTime: "2019-12-30 15:35:44",
	SunAtSouth: "12:43",
	Sunrise: "08:23",
	Sunset: "17:04",
	app_version: "4.10717",
	result: [
		{
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 20,
         "Data" : "Off",
         "Description" : "Alexa_Name: lampe bleue",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareID" : 11,
         "HardwareName" : "BlitzWolf",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "00014105",
         "Image" : "BW-SHP6",
         "IsSubDevice" : false,
         "LastUpdate" : "2020-08-03 22:45:29",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 100,
         "Name" : "BlitzWolf",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" :
         [
         0
         ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Switch",
         "SwitchType" : "On/Off",
         "SwitchTypeVal" : 0,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "lightbulb",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "181"
      }
	],
	status: "OK",
	title: "Devices"
});
