exports.DOMOTICZ_GET_DEVICES = JSON.stringify({
	ActTime: 1577716544,
	AstrTwilightEnd: "18:53",
	AstrTwilightStart: "06:34",
	CivTwilightEnd: "17:38",
	CivTwilightStart: "07:48",
	DayLength: "08:41",
	NautTwilightEnd: "18:16",
	NautTwilightStart: "07:10",
	ServerTime: "2019-12-30 15:35:44",
	SunAtSouth: "12:43",
	Sunrise: "08:23",
	Sunset: "17:04",
	app_version: "4.10717",
	result: [
		{
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "Stopped",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 0,
         "HardwareID" : 10,
         "HardwareName" : "RFX",
         "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
         "HardwareTypeVal" : 1,
         "HaveDimmer" : false,
         "HaveGroupCmd" : false,
         "HaveTimeout" : false,
         "ID" : "002810",
         "Image" : "Light",
         "IsSubDevice" : false,
         "LastUpdate" : "2020-02-14 14:32:17",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 0,
         "Name" : "Garage",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Stopped",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "RFY",
         "SwitchType" : "Blinds",
         "SwitchTypeVal" : 3,
         "Timers" : "false",
         "Type" : "RFY",
         "TypeImg" : "blinds",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "37"
      }
	],
	status: "OK",
	title: "Devices"
});
